// Most Likely To, clean: city life, tech, health, shopping and hobbies.
export default [
  "know every metro station by heart", "fall asleep on the metro and miss their stop", "get the last seat on a crowded bus", "stand in the bus and still read a book", "know every auto driver in their area",
  "argue with an auto driver about the meter", "use the meter every time", "take a cycle rickshaw for short distances", "cycle to work", "get stuck in traffic every day and stay calm",
  "honk the least", "drive the most carefully", "drive too slow on the highway", "be the best at parking", "know the cheapest petrol pump",
  "keep their car spotless", "name their car", "talk to their car", "have a car full of snacks", "buy the latest gadget on launch day",
  "stand in line for a new phone", "use the same phone for seven years", "know everything about phones", "fix their own laptop", "build their own computer",
  "have the fastest internet", "know every wifi password at every cafe", "have the most apps on their phone", "organise their apps by colour", "have zero unread emails",
  "reply to emails in a minute", "use dark mode on everything", "type faster than they talk", "use voice notes for everything", "learn coding for fun",
  "make their own app", "make their own website", "fix the family's wifi", "set up the smart TV for everyone", "go to the gym every morning",
  "run five kilometres every day", "do yoga on the terrace", "do push-ups during ads", "take the stairs instead of the lift", "drink a green smoothie every morning",
  "eat healthy all week", "count their protein", "bring a salad to work", "sleep eight hours every night", "meditate every day",
  "do breathing exercises when stressed", "go for long walks to think", "go to bed at 10 pm", "shop at the local market", "love window shopping",
  "shop online every week", "wait for a sale to buy anything", "buy things they never use", "own the most shoes", "own the most watches",
  "own the most sunglasses", "have a perfume collection", "have a hat collection", "have the best sense of style", "wear only black",
  "wear bright colours every day", "match their outfit with their shoes every time", "iron their clothes perfectly", "know every fashion trend", "make their own clothes",
  "get their clothes stitched by a tailor", "know the best tailor in the city", "bargain the best at street markets", "paint as a hobby", "draw portraits of their friends",
  "keep a sketchbook", "do calligraphy", "learn an instrument", "learn to dance", "learn pottery",
  "learn photography", "learn a martial art", "knit a sweater", "make jewellery", "do woodwork",
  "fix old radios", "build model airplanes", "collect stamps", "collect coins", "collect vinyl records",
  "collect old cameras", "garden on their balcony", "grow tomatoes at home", "keep a fish tank", "keep a rabbit",
  "go to the library every week", "read the newspaper cover to cover", "do the crossword every morning", "listen to the radio in the car", "write letters to friends",
  "learn a new skill every year", "take up a new hobby every month", "teach themselves something from YouTube", "get really good at something unusual", "turn a hobby into a business",
  "spend Sunday morning reading in bed", "spend Sunday cleaning the house", "spend Sunday with family", "spend Sunday playing cricket", "spend Sunday sleeping",
  "go to the movies alone", "go to a cafe alone with a book", "enjoy their own company", "travel alone happily", "eat at a restaurant alone happily",
  "know the best cafe in the city", "work from a cafe every day", "know the barista's name", "order the same coffee every day", "try a new drink every time",
  "visit every museum in the city", "visit every art gallery", "go to every food festival", "go to every music festival", "join a running club",
  "join a cycling club", "join a photography walk", "join a heritage walk", "join a trekking group",
]
