// Most Likely To, clean: home, habits and everyday life.
export default [
  "wake up before the alarm every day", "wake up at 5 am for fun", "sleep through an earthquake", "fall asleep on the sofa every night", "nap at every chance",
  "take a nap and wake up confused", "sleep with three pillows", "hug a pillow to sleep", "sleep with socks on", "sleep in a cold room with a blanket",
  "fight for the blanket", "hog the bed", "sleep sideways on a bed", "fall off the bed in their sleep", "keep their room perfectly clean",
  "organise their cupboard by colour", "label every box at home", "know where everything is in the house", "keep their keys in the fridge by mistake", "put things in a 'safe place' and forget the place",
  "find a lost thing a year later", "kill every plant they own", "have more plants than furniture", "redecorate their room every year", "move the furniture around every month",
  "buy cushions they do not need", "fill their home with fairy lights", "decorate for every festival", "keep the Diwali lights up all year", "put up a Christmas tree in India",
  "make rangoli at every festival", "light the most diyas at Diwali", "do the dishes right after eating", "leave the dishes for tomorrow", "fold clothes perfectly",
  "iron everything including socks", "never iron anything", "do laundry once a month", "do laundry every day", "mix whites with colours",
  "turn white clothes pink", "shrink a sweater in the wash", "cook every day", "order food every day", "make a grocery list and follow it",
  "go to the store for one thing and come back with ten", "forget the one thing they went to buy", "carry a cloth bag to the market", "bargain with the sabzi wala", "get free coriander every time",
  "know every shopkeeper in their area", "get credit at the local shop", "fix things at home with tape", "fix things themselves and break them more", "call a plumber for everything",
  "know how to fix a fuse", "know how to change a bulb safely", "be scared of the mixer grinder", "be scared of the pressure cooker whistle", "count the cooker whistles",
  "forget the cooker on the stove", "burn milk while boiling it", "boil milk and watch it like a hawk", "make the best filter coffee at home", "own every kitchen gadget",
  "own an air fryer and use it for everything", "own a microwave and only heat water in it", "keep the house cold like a fridge", "keep the house warm all year", "fight with family over the AC",
  "switch off every light in the house", "leave the TV on all day", "watch TV while working", "watch the news all day", "watch the same film every Sunday",
  "watch cartoons as an adult", "watch old serials on YouTube", "listen to the radio every morning", "sing while cooking", "dance while cleaning",
  "clean the house when stressed", "cook when sad", "have a strict daily routine", "never have the same day twice", "do yoga every morning",
  "go for a walk after every meal", "count steps every day", "drink eight glasses of water a day", "carry a big water bottle everywhere", "drink warm water with lemon every morning",
  "drink haldi milk every night", "trust home remedies over medicine", "have a remedy for every illness", "suggest ginger tea for every problem", "take vitamins every day",
  "never take medicine", "visit the doctor for a small cold", "never go to the doctor", "google every symptom", "be scared of injections",
  "be very good with kids", "be very good with old people", "be good with animals", "be the favourite of every pet they meet", "have a pet that likes them more than its owner",
  "talk to their pet all day", "dress their pet in clothes", "make their pet a birthday cake", "have a pet that sleeps on their bed", "have the most spoiled pet",
  "know the names of all the birds outside their window", "keep a bird feeder", "watch the sunset every evening", "watch the stars on the terrace", "own a telescope",
  "know the names of the constellations", "wake up early to watch the sunrise", "love the rain", "go out to dance in the rain", "love winter",
  "love summer", "complain about the cold every winter", "never feel cold", "always feel cold", "carry a jacket everywhere",
  "wear a sweater in the office AC", "carry an umbrella every day", "never carry an umbrella and always get wet", "know the weather forecast for the week", "predict the rain by looking at the sky",
  "smell the rain before it comes", "check the weather app ten times a day", "trust the weather app and get wet", "have the most organised wallet", "keep every receipt",
  "keep every warranty card", "know the expiry date of everything at home", "keep spare batteries for everything", "have a drawer full of chargers", "keep a torch ready for power cuts",
  "have a candle stash for power cuts", "have the inverter details memorised", "know the electricity bill by heart", "pay every bill on the first day", "forget to pay a bill",
  "set reminders for everything", "never forget a birthday", "have a calendar for every family event", "write a diary every night", "keep a gratitude journal",
  "make lists for everything", "have sticky notes everywhere", "write notes on their hand",
]
