// Most Likely To, clean: who is best (or first) at something.
export default [
  "be the best at keeping secrets", "be the best at giving advice", "be the best at planning parties", "be the best at saving money", "be the best at finding deals",
  "be the best at packing a suitcase", "be the best at reading maps", "be the best at remembering names", "be the best at remembering faces", "be the best at remembering birthdays",
  "be the best at making people laugh", "be the best at telling stories", "be the best at writing cards", "be the best at choosing gifts", "be the best at wrapping gifts",
  "be the best at taking photos", "be the best at editing videos", "be the best at drawing", "be the best at handwriting", "be the best at spelling",
  "be the best at mental maths", "be the best at puzzles", "be the best at riddles", "be the best at quizzes", "be the best at general knowledge",
  "be the best at cooking under pressure", "be the best at making chai", "be the best at making coffee", "be the best at baking", "be the best at making Maggi",
  "be the best at dancing", "be the best at singing", "be the best at playing an instrument", "be the best at acting", "be the best at mimicry",
  "be the best at sports", "be the best at cricket", "be the best at football", "be the best at badminton", "be the best at swimming",
  "be the best at video games", "be the best at board games", "be the best at card games", "be the best at chess", "be the best at carrom",
  "be the best at fixing things", "be the best at technology", "be the best at cleaning", "be the best at organising", "be the best at decorating",
  "be the best at keeping plants alive", "be the best with animals", "be the best with kids", "be the best with old people", "be the best listener",
  "be the best at saying sorry", "be the best at making up after a fight", "be the best at staying calm", "be the best in an emergency", "be the best at first aid",
  "be the best at bargaining", "be the best at negotiating", "be the best at public speaking", "be the best at interviews", "be the best at selling anything",
  "be the best at languages", "be the best at accents", "be the best at learning new things", "be the best at teaching", "be the best at explaining things simply",
  "be the first to reply in the group chat", "be the first to wish everyone on birthdays", "be the first to arrive at a party", "be the first on the dance floor", "be the first to try a new restaurant",
  "be the first to know the news", "be the first to share a meme", "be the first to finish an exam", "be the first to finish a book", "be the first to finish a series",
  "be the first to buy a new phone", "be the first to learn to drive", "be the first to travel abroad", "be the first to live alone", "be the first to own a pet",
  "be the first to help when someone is in trouble", "be the first to say sorry", "be the first to forgive", "be the first to laugh", "be the first to cry at a film",
  "be the first awake on a trip", "be the first asleep on a trip", "be the first in the pool", "be the first to the top of a hill", "be the first to the buffet",
  "be the last to finish dinner", "be the last to reply to a message", "be the last to get ready", "be the last to know the news", "be the last to give up",
  "be the last one standing in a game", "be the last to fall asleep at a sleepover", "be the last to leave the office", "be the last to buy a smartphone", "win every argument",
  "win every race", "win every bet", "win every game of rock-paper-scissors", "win a lucky draw", "win a contest on the radio",
  "win a car in a lottery", "win a cooking competition", "win a dance competition", "win an award at work", "win a scholarship",
  "win a medal in sports", "win a photography contest", "make the best first impression", "be remembered by everyone they meet", "make friends anywhere",
  "make friends with strangers on a trip", "make a friend in a lift ride", "talk to anyone about anything", "start a conversation with a stranger", "keep a conversation going for hours",
  "never run out of things to say", "know a little about everything",
]
