// Most Likely To, clean: sports, fitness and outdoor play.
export default [
  "wake up at 5 am to play badminton", "play cricket every Sunday morning", "play football in the rain", "play volleyball on the beach", "play kabaddi at a family function",
  "be the captain of every team", "be picked first for every team", "be picked last and still win the game", "be the best fielder", "drop the easiest catch",
  "hit a six in their first game", "get out on the first ball every time", "bowl a perfect yorker", "keep wicket with no gloves", "argue with the umpire in a friendly match",
  "run the fastest in the group", "win the hundred-metre race", "finish a marathon", "finish a half marathon in a costume", "walk a marathon and finish last proudly",
  "go cycling every weekend", "cycle up a mountain", "go on a long cycle ride with friends", "fix their own bicycle", "teach a child to ride a bicycle",
  "swim every morning", "swim in the sea", "swim in a cold river", "teach a friend to swim", "dive off the high board",
  "do yoga every day", "touch their toes easily", "stand on their head", "hold a plank for five minutes", "do a hundred push-ups",
  "go to the gym every single day", "lift the heaviest weight in the gym", "help a stranger at the gym", "know every exercise", "make their own workout plan",
  "play tennis like a pro", "play table tennis every lunch break", "play squash", "play golf someday", "learn to surf",
  "learn to skate", "learn to ski", "learn to ride a horse", "learn archery", "learn fencing",
  "go rock climbing", "go bouldering", "climb a frozen waterfall", "climb a sand dune", "climb every staircase two steps at a time",
  "win a medal for their state", "play a sport for their country", "become a sports coach", "become a fitness instructor", "become a referee",
  "know every rule of cricket", "explain the offside rule to anyone", "know every Olympic sport", "watch every Olympic event", "know every Indian Olympic medal winner",
  "stay up to watch a tennis final", "watch every Formula 1 race", "know every football club's anthem", "have a favourite kabaddi team", "go to every IPL match in their city",
  "paint their face for a match", "wear the team jersey to the office on match day", "shout the loudest in a stadium", "do the Mexican wave in a stadium", "catch a ball in the stands",
  "meet a cricketer at the airport", "get an autograph from a sports star", "take a selfie with an athlete", "collect signed jerseys", "own a bat signed by a team",
  "play chess in the park with old men", "play carrom all night in the holidays", "win the colony badminton tournament", "organise a cricket tournament in their colony", "make trophies for a colony tournament",
  "be the best at gully cricket", "make the gully cricket rules", "own the only good bat in the colony", "keep the cricket ball when the game ends", "lose the ball in a drain",
  "play hockey in school", "play throwball in school", "play kho-kho in school", "win the tug of war", "win the three-legged race",
  "do a cartwheel at thirty", "do a backflip", "walk on their hands", "do the splits", "jump over a fence",
  "go on a morning walk with their parents", "go jogging in the park", "join a laughter club", "join a walking group", "join a dance fitness class",
]
