// Most Likely To, clean: hobbies, games and pastimes.
export default [
  "finish a 2,000-piece puzzle", "solve a crossword in ten minutes", "solve every sudoku on the hardest level", "build a huge Lego set", "build a model ship in a bottle",
  "play chess every day online", "teach chess to a child", "win a chess tournament", "beat their grandfather at chess", "lose to their grandfather at chess every time",
  "play carrom every Diwali holiday", "pocket the queen in one shot", "play Ludo with their grandparents", "play Snakes and Ladders with kids and lose", "play Monopoly for six hours",
  "play Scrabble and use a big word", "play Scrabble and argue about a word", "play Pictionary and draw badly", "play dumb charades and act brilliantly", "play cards every evening with family",
  "collect stamps from every country", "collect coins from old times", "collect postcards", "collect magnets", "collect key chains",
  "collect old film posters", "collect cricket memorabilia", "collect model cars", "collect comics", "collect board games",
  "grow vegetables on the terrace", "grow roses that win prizes", "grow herbs on the windowsill", "grow a bonsai", "grow a garden that butterflies visit",
  "keep fish in a big aquarium", "keep birds as pets", "keep a rabbit in the garden", "keep a tortoise for years", "keep a cat that rules the house",
  "go fishing on weekends", "go bird watching with binoculars", "go stargazing with a telescope", "go cycling in the countryside", "go hiking in the hills",
  "take photographs of birds", "take photographs of old buildings", "take photographs of street food", "take photographs of strangers' pets", "take photographs of the moon",
  "learn magic tricks", "learn to juggle", "learn to yo-yo", "learn to whistle with fingers", "learn to solve a Rubik's cube",
  "learn calligraphy", "learn origami", "learn to sketch faces", "learn watercolours", "learn to make clay pots",
  "learn to bake bread", "learn to make pasta from scratch", "learn to make sushi", "learn to make momos", "learn to make biryani like their grandmother",
  "learn to play the dhol", "learn to play the sitar", "learn to play the mouth organ", "learn to play the ukulele", "learn to DJ",
  "learn a new language for fun", "learn sign language", "learn to read old scripts", "learn Sanskrit", "start a blog about their hobby",
  "start a YouTube channel about their hobby", "start a club for their hobby", "teach their hobby to kids", "make money from their hobby", "spend every weekend on their hobby",
  "spend all their money on their hobby", "travel for their hobby", "make friends through their hobby", "turn their hobby into a job", "read a book every week",
  "read poetry before bed", "read the same favourite book every year", "read books in two languages", "read comics as an adult proudly", "write a novel in their free time",
  "write short stories for children", "write song lyrics in a notebook", "write a blog about food", "write film reviews for fun", "watch old films on weekends",
  "watch documentaries about space", "watch nature films with their family", "watch cooking shows to learn", "watch every cricket highlight", "go to every book fair",
  "go to every science exhibition", "go to every craft fair", "go to every comic convention", "go to every gaming event",
]
