// Most Likely To, clean: work, careers and money.
export default [
  "become the CEO of a big company", "start their own company", "work from a beach someday", "never work a day in their life", "love their job the most",
  "change careers three times", "become an engineer and then a chef", "become a pilot", "become a scientist who discovers something", "become a famous author",
  "become a journalist", "become a news anchor", "become a photographer", "become a designer", "become an architect",
  "become a famous artist", "become a film director", "become a music producer", "become a famous dancer", "become a sportsperson",
  "play for India", "become a cricket coach", "become a gym trainer", "become a yoga teacher", "become a farmer",
  "open a farm stay", "become a vet", "work at a zoo", "work with wildlife", "join the army",
  "join the navy", "join the air force", "join the police", "become an IAS officer", "crack UPSC",
  "become a diplomat", "work at the UN", "become a minister", "become the Prime Minister", "be the first to get a job",
  "be the first to buy a car", "be the first to buy a house", "be the first to become a manager", "be the first to retire", "make a five-year plan",
  "make a ten-year plan and stick to it", "have a backup career", "have a side business", "have three side hustles", "save half their salary",
  "spend their whole salary in a week", "keep an expense sheet", "know exactly how much money they have", "never check their bank balance", "invest in mutual funds",
  "invest in gold", "invest in real estate", "start an SIP on their first salary", "give their first salary to their parents", "buy something big with their first salary",
  "treat everyone with their first salary", "buy their parents a gift with their first bonus", "take their parents on a trip abroad", "build their parents a house", "be the most organised at work",
  "have the cleanest desk", "have the messiest desk", "have plants on their desk", "decorate their desk for every festival", "be the office's tech helper",
  "fix the printer every time", "know the office wifi password", "be the first in the office every day", "be the most loved person in the office", "be the office's party planner",
  "organise every birthday cake in the office", "remember every colleague's birthday", "bring sweets to the office every Monday", "be the best at presentations", "make the best PowerPoint slides",
  "make slides with too many animations", "speak confidently in every meeting", "be nervous in every presentation", "ask the most questions in a meeting", "take notes in every meeting",
  "be the one everyone asks for help", "train every new joiner", "be everyone's mentor", "win employee of the month", "get promoted every year",
  "get the biggest raise", "negotiate the best salary", "get headhunted by a big company", "work in five countries", "work in a startup",
  "work at Google", "work at ISRO", "work at a newspaper", "write a book about their career", "give a TED talk",
  "speak at a big conference", "teach at a university", "be invited as a chief guest", "become famous on LinkedIn", "have a perfect LinkedIn profile",
  "have the most connections on LinkedIn", "post motivational quotes at work", "share a book recommendation at work", "work best at night", "work best in the morning",
  "work with music on", "work in total silence", "take short breaks every hour", "take a lunch walk every day", "eat lunch at their desk",
  "know every office gossip but share none", "keep everyone's secrets at work", "stay at one job for twenty years", "switch jobs for a better canteen", "choose a job for the work-life balance",
  "choose a job for the money", "choose a job for the travel", "take a sabbatical", "take a gap year to travel", "volunteer for a year",
  "work for a charity", "start a charity", "become rich and give it all away", "fund a school in their village", "help a friend start a business",
  "lend money to a friend in need", "pay for a stranger's meal",
]
