// Most Likely To, clean: funny, quirky and random.
export default [
  "laugh at their own jokes the loudest", "tell the worst jokes with a straight face", "tell a joke and forget the punchline", "make up a song about anything", "sing every word in a song wrong",
  "dance when nobody is watching", "dance in the kitchen", "dance in the lift", "talk to animals in a funny voice", "give every pet a human name",
  "name their car and bike", "name their plants", "name their wifi something funny", "have the funniest ringtone", "have the funniest profile picture",
  "have the funniest nickname", "have the funniest laugh", "have the funniest sneeze", "do the funniest impressions", "pull the funniest faces in photos",
  "photobomb every photo", "pose the same way in every photo", "close their eyes in every photo", "trip on nothing", "walk into a pole while texting",
  "push a door that says pull", "wave at someone who was not waving at them", "get stuck in a revolving door", "spill tea on themselves every day", "drop food on their shirt",
  "lose a slipper in the rain", "get their umbrella flipped by the wind", "get splashed by a car in the rain", "look for something they are holding", "put their phone in the fridge",
  "put the milk in the cupboard", "wear their glasses on their head and look for them", "laugh in their sleep", "sleepwalk to the kitchen", "wake up and say something weird",
  "dream in other languages", "believe every fun fact they read", "share a fun fact at every dinner", "know useless facts about everything", "win a trivia game with a weird fact",
  "start a sentence with 'did you know'", "have a weird talent", "touch their nose with their tongue", "wiggle their ears", "whistle a whole song",
  "juggle three oranges", "make animal sounds perfectly", "do a perfect crow call", "bark back at dogs", "meow back at cats",
  "talk to birds", "be scared of a harmless spider", "jump at their own shadow", "scream at a balloon popping", "be startled by the pressure cooker",
  "fall off a chair from laughing", "eat weird food combinations", "put chips in their sandwich", "eat mango with salt", "drink tea with biscuits dunked too long",
  "eat ice cream with a fork", "argue with a vending machine", "talk back to Google Maps", "say thank you to Alexa", "ask a voice assistant silly questions",
  "get into an argument with autocorrect", "make a list of their top 10 everything", "rank every biryani they ever ate", "rate every chai out of ten", "keep a list of the best naps",
  "have a favourite cloud", "collect funny signboards", "take photos of funny shop names", "read every signboard aloud", "correct spelling mistakes on menus",
  "notice every typo", "make up words", "use their own made-up words every day", "speak in a cartoon voice", "talk like a pirate for a day",
  "talk like a robot for fun", "have an imaginary friend as a child", "still talk to their soft toys", "sleep with a soft toy", "give their soft toy a birthday",
  "have a soft toy older than them", "be the most dramatic about a small cut", "act like a cold is the end of the world", "need a hug when they have a fever", "sneeze in a funny way",
  "hiccup at the worst moment", "get the giggles in a serious place", "get the giggles in a temple", "get the giggles in a library", "get the giggles during a photo",
  "get the giggles during a prayer", "start a dance party in the kitchen", "start a pillow fight", "start a water fight in summer", "start a snowball fight in Manali",
  "start a tickle fight", "make a fort out of blankets", "build a fort out of sofa cushions", "slide down the stairs on a mattress", "roll down a grassy hill",
  "climb a tree at thirty", "play pranks on April Fools' Day", "believe every April Fools' prank", "plan an April Fools' prank for a month", "fall for the same prank twice",
  "prank their parents", "wear mismatched socks on purpose", "wear a funny hat for no reason", "wear a costume to a party that is not a costume party", "dress up their pet for Halloween",
  "carve a pumpkin in India",
]
