// Most Likely To, clean: everyday moments and small habits.
export default [
  "hold the lift for everyone", "press the lift button ten times", "take the stairs to avoid a crowded lift", "say hello to everyone in the lift", "stand awkwardly in silence in the lift",
  "say 'bless you' to every sneeze", "say 'sorry' when someone bumps into them", "say 'thank you' to the ATM", "say 'good morning' to everyone in the office", "wave at every child they see",
  "be the first to pick up a fallen pen for someone", "hold the door for a long line of people", "let everyone go first", "give way to every car", "stop for every pedestrian",
  "make small talk with taxi drivers", "learn the life story of their cab driver", "give a five-star rating to every driver", "tip every driver", "share snacks with the driver on a long trip",
  "make a friend in a hospital waiting room", "make a friend in a bank queue", "make a friend at a bus stop", "make a friend at a wedding they did not want to go to", "remember the names of everyone's kids",
  "remember the names of everyone's pets", "remember what everyone ordered last time", "remember every friend's favourite colour", "remember every friend's allergy", "carry tissues for everyone",
  "carry a safety pin for emergencies", "carry hand sanitiser everywhere", "carry a spare phone charger", "carry an umbrella for two people", "keep a first-aid kit in their car",
  "keep snacks in the car", "keep a blanket in the car", "keep a phone stand in the car", "keep the car smelling nice", "be on time for everything",
  "arrive ten minutes early everywhere", "set their watch five minutes fast", "plan the route before leaving home", "check the traffic before every trip", "write things down so they never forget",
  "use sticky notes on the fridge", "make a shopping list for everything", "keep a planner", "use a calendar app for their whole life", "fold their clothes the same way every time",
  "have a place for everything in their room", "keep their phone on the same table every night", "keep their keys on the same hook", "never lose their keys", "clean the house every Sunday",
  "wash their car every weekend", "water the plants every evening", "feed the birds every morning", "take a walk every evening", "drink tea at exactly 5 pm",
  "read the newspaper with their morning tea", "listen to the same radio station every morning", "watch the same news channel every night", "fall asleep at the same time every night", "open the windows every morning",
  "light a diya every evening", "say a prayer before every exam", "say a prayer before every journey", "know every shop in their market", "have a favourite vegetable seller",
  "know the best fruit shop in the area", "know which shop has fresh bread", "know the medical store open at night", "know the bus timings by heart", "know the train schedule by heart",
  "know every traffic signal timing", "know the best time to beat traffic", "know every road in the city", "be good at giving directions", "draw a map on a napkin for a stranger",
  "walk someone to the right place instead of explaining", "help a tourist buy a train ticket", "translate for a confused tourist", "pick up litter even when nobody is watching", "separate wet and dry waste perfectly",
  "switch off the lights in an empty room", "turn off the tap while brushing", "reuse every plastic bag", "repair things instead of buying new ones", "sew a button themselves",
  "fix a leaking tap themselves", "fix the wifi by restarting it", "fix a chair with a book under the leg", "send birthday wishes at midnight", "call instead of texting on birthdays",
  "send a handwritten card on birthdays", "bake a cake for every friend's birthday", "remember every anniversary of their friends", "keep every greeting card they ever got", "keep every wedding invitation",
  "keep every ticket from every film", "keep every photo from every trip", "print photos to put in an album",
]
