// Most Likely To, clean: family, relatives, festivals and growing up in India.
export default [
  "be their grandmother's favourite", "call their parents after every meal", "video call their family every night", "still ask their mom what to wear", "touch their elders' feet without being told",
  "know every relative's name", "know every cousin's birthday", "organise every family reunion", "make the family WhatsApp group", "send the most good morning messages to the family group",
  "reply to every forward in the family group", "teach their grandparents to use WhatsApp", "help their parents with their phone every week", "set up the TV for their parents", "be the family's photographer",
  "be the family's tech support", "be the family's peacemaker", "be the family's comedian", "be the family's travel planner", "be the one relatives ask for advice",
  "be the one cousins tell their secrets to", "be the cool cousin", "be the elder cousin everyone looks up to", "be the youngest cousin who gets away with everything", "fight with their siblings every day",
  "be best friends with their siblings", "share clothes with their siblings", "blame their siblings for everything", "cover for their siblings", "get the bigger piece of cake as the youngest",
  "be compared with their siblings", "have the loudest family", "have the biggest joint family", "have the most relatives in one city", "have relatives in every country",
  "know their family tree", "know their family history for five generations", "keep old family photos safe", "cook their grandmother's recipes", "learn a family recipe",
  "keep the family traditions alive", "tell family stories at every dinner", "know every old family story by heart", "make the most rangoli at Diwali", "burst the most crackers",
  "be scared of crackers", "eat the most sweets at Diwali", "visit every relative at Diwali", "play the most at Holi", "hide from Holi colours",
  "make thandai at Holi", "be the first to put colour on everyone", "come home green after Holi", "dance the most at Navratri", "do garba every night of Navratri",
  "fast during Navratri and eat the most", "go pandal hopping all night at Durga Puja", "know the best pandals in the city", "fly the most kites at Makar Sankranti", "cut the most kites",
  "get their kite cut first", "climb onto the roof for kites", "have the strongest manja", "tie the most rakhis", "give the best Raksha Bandhan gifts",
  "forget to buy a rakhi gift", "celebrate every festival of every religion", "invite friends home for every festival", "make the best sewaiyan at Eid", "make the best plum cake at Christmas",
  "decorate the most for Christmas", "go to midnight mass with friends", "make modaks for Ganesh Chaturthi", "carry the Ganpati idol home dancing", "dance the most at the Ganpati visarjan",
  "make an eco-friendly Ganpati", "celebrate Onam with a giant sadya", "make the biggest pookalam", "celebrate Pongal with sugarcane", "celebrate Baisakhi with bhangra",
  "light the bonfire at Lohri", "go to every mela in town", "win prizes at every mela", "ride the giant wheel at every mela", "eat cotton candy at every fair",
  "buy a toy at every fair", "know all the festival dates by heart", "remind everyone of every festival", "cry at every family wedding", "dance at every family wedding",
  "help plan every family wedding", "get the best seat at every family wedding", "know who is getting married next in the family", "give the funniest speech at a family function", "sing old songs at family gatherings",
  "start antakshari at family dinners", "play cards with the uncles", "play carrom with the cousins all night", "fall asleep at every family gathering", "stay up the latest at family gatherings",
  "sleep on the floor with all the cousins", "have midnight snacks with cousins", "tell ghost stories to the younger cousins", "take the kids to the park", "babysit the younger cousins",
  "teach the younger cousins to ride a bicycle", "help the younger cousins with homework", "spoil the younger cousins with chocolates", "go to their native village every summer", "love village life",
  "milk a cow in their village", "climb a mango tree in the village", "swim in the village pond", "spend summer holidays at their nani's house", "eat mangoes all summer",
  "play in the afternoon heat while the elders sleep", "sleep on the terrace in summer", "count stars on the terrace", "remember their childhood games", "still play stapu",
  "still play gilli-danda", "still play hide-and-seek", "still play pittu", "keep their childhood toys", "keep their school bag from class one",
  "keep their first drawing", "frame their first certificate", "keep a box of childhood memories", "have the most childhood photos", "have the cutest baby photos",
  "have the most embarrassing childhood nickname", "still be called by their childhood nickname", "have a nickname only their family uses", "look exactly like their dad", "look exactly like their mom",
  "laugh like their dad", "talk like their mom", "become their parents one day", "take care of their parents in old age", "live with their parents forever",
  "build a house for the whole family", "buy their parents a car", "take their grandparents on a trip", "listen to their grandparents' stories for hours", "record their grandparents' stories",
  "learn their grandparents' language", "write a book about their family", "make a family tree poster",
]
