// Most Likely To, clean: school, exams, college and studying.
export default [
  "top the class without studying", "study for twelve hours and still panic", "make colourful notes and never read them", "highlight the whole textbook", "finish the syllabus a month early",
  "start studying the night before every exam", "ask 'is this in the syllabus?' in every class", "ask the teacher a question at the end of class when everyone wants to leave", "remind the teacher about a test", "sit in the front row every day",
  "sit in the last bench forever", "sleep in class with their eyes open", "draw cartoons in the margins of their notebook", "write their name in fancy letters on every notebook", "cover their books with newspaper",
  "have the neatest handwriting", "have handwriting nobody can read", "lose a pen every day", "have the best pencil box in class", "carry an extra pen for everyone",
  "borrow a pen and never return it", "always forget their geometry box", "use a calculator for two plus two", "love maths the most", "hate maths the most",
  "get full marks in maths and fail in Hindi", "love history and know every date", "remember every capital city", "win every quiz competition", "win the school spelling bee",
  "win the school science fair with a volcano", "make the best project with their parents' help", "make a project the night before with chart paper", "glue their fingers together making a project", "be the class monitor",
  "be the teacher's favourite", "be the teacher's least favourite", "make the teacher laugh in class", "get the teacher's name wrong for a whole year", "be picked to read out loud every time",
  "volunteer for every school event", "host the school annual day", "dance in every annual day performance", "forget their lines in the school play", "play a tree in the school play",
  "play the lead in the school play", "be the school band's drummer", "sing the school prayer the loudest", "faint in the morning assembly", "be punished for talking in the assembly",
  "be sent to the principal's office", "be friends with the principal's child", "have a parent who is a teacher in the same school", "get the most stars in their notebook", "collect every badge at school",
  "be the house captain", "win the 100-metre race on sports day", "fall in the sack race", "win the lemon-and-spoon race by cheating", "be the best at kho-kho",
  "bring the best lunch to school", "share their tiffin with everyone", "eat their tiffin before the first break", "trade tiffins every day", "bring the same lunch every day for years",
  "forget their tiffin at home", "fall asleep on the school bus", "be the last to be picked up from school", "miss the school bus every week", "walk to school in the rain on purpose",
  "jump in every puddle on the way home", "keep a secret stash of chocolates in their school bag", "carry the heaviest school bag", "have a school bag with wheels", "keep every old notebook from school",
  "keep their school ID card forever", "remember their roll number from class five", "remember every teacher's name", "still dream about school exams", "have a recurring dream about missing an exam",
  "wake up thinking they are late for school years after leaving", "go back to visit their old school", "be invited to speak at their old school", "become a teacher at their old school", "write the best essays",
  "win an essay competition", "write the longest answers in exams", "fill extra answer sheets every exam", "draw diagrams for every answer", "finish an exam in half the time",
  "use every minute of the exam and then ask for more", "check their answers three times", "leave the exam hall first", "be the last to leave the exam hall", "compare answers after every exam",
  "refuse to discuss the exam after it ends", "know their marks before the results", "calculate their percentage to two decimals", "frame their report card", "cry when they get 98",
  "celebrate passing like they topped", "say 'the paper was easy' and fail", "say 'I will fail' and top", "get a perfect score in a board exam", "be on the merit list",
  "get a scholarship", "win an Olympiad", "get into the best college in the country", "crack an entrance exam on the first try", "go to coaching classes for everything",
  "spend more time in coaching than in school", "make friends for life at coaching classes", "become a coaching teacher", "start an online tuition channel", "teach their younger cousins for free",
  "explain things better than the teacher", "help the whole class before exams", "make a group study a party", "turn every group study into a gossip session", "fall asleep during group study",
  "eat all the snacks at group study", "study with music on", "need total silence to study", "study best in a cafe", "study best at 3 am",
  "study best on the terrace", "make a study timetable and follow it", "make a study timetable and never follow it", "spend the whole day making a study plan", "buy new stationery before every exam",
  "believe a new pen helps them score more", "have a lucky pen for exams", "eat curd and sugar before every exam", "pray at every temple before results", "do a degree they never use",
  "do three degrees", "keep studying forever", "do a PhD", "be called 'doctor' and not be a doctor", "change their major three times",
  "pick a college for the canteen food", "pick a college because their crush went there", "pick a course because their friends picked it", "stay friends with their school bench partner forever", "be in touch with every school friend",
  "organise the school reunion", "make the school WhatsApp group", "share old school photos in the group", "remember every embarrassing thing from school", "still know the school song by heart",
  "still know their multiplication tables up to twenty", "still remember the periodic table", "still remember a poem from class two", "still have their school uniform", "get a job at the school canteen just for fun",
  "go back to their school as the chief guest", "donate a library to their school", "start a school someday", "be the principal of a school one day", "write a textbook",
  "write a guidebook that students actually like", "make a study app", "teach a class on YouTube", "become a famous professor", "learn to code at forty",
  "take an online course and actually finish it", "collect online certificates", "sign up for ten courses and finish none", "read a book a week", "read the last page of a book first",
  "fall asleep reading", "carry a book everywhere and never open it", "have a library at home", "re-read the same book every year", "have a favourite book they recommend to everyone",
  "join a book club", "start a book club", "argue about books at a book club",
]
