// Most Likely To, clean: childhood memories and growing up.
export default [
  "have been the naughtiest child in their colony", "have been the quietest child in class", "have broken the most things as a child", "have hidden their report card as a child", "have cried on the first day of school the longest",
  "have had an imaginary friend", "have had a secret hideout as a child", "have built a fort in the living room", "have played house with their cousins", "have played teacher-teacher with their dolls",
  "have collected cricket cards", "have collected WWE cards", "have collected Pokemon cards", "have collected stickers in a notebook", "have collected bottle caps",
  "have saved money in a piggy bank", "have broken their piggy bank for a toy", "have spent all their pocket money on chips", "have bought candy from the school canteen every day", "have traded tiffin for chocolates",
  "have watched cartoons all summer", "have watched Shaktimaan every Sunday", "have watched Doordarshan with the whole family", "have watched Ramayana on TV with the family", "have danced to every song on Chitrahaar",
  "have played outside until it got dark", "have come home with scraped knees every day", "have climbed every tree in the colony", "have fallen off a bicycle the most", "have learned to ride a cycle with a parent holding on",
  "have played cricket on the street", "have broken a neighbour's window with a ball", "have rung a doorbell and run away", "have stolen mangoes from a neighbour's tree", "have chased a kite across the colony",
  "have played video games at a friend's house", "have played on a family computer", "have played Mario on a video game console", "have played Road Rash at a cyber cafe", "have spent pocket money at a cyber cafe",
  "have had the coolest school bag", "have had the best pencil box", "have had a water bottle with a cartoon", "have had a lunch box that smelled of every meal", "have lost a water bottle every week",
  "have been scared of their school principal", "have been scolded for talking in class", "have stood outside the classroom as punishment", "have done 'murga' punishment", "have been the class monitor who wrote names",
  "have written names of talking students on the board", "have been the teacher's helper", "have carried the teacher's books", "have cleaned the blackboard every day", "have brought flowers for the teacher",
  "have made a card for Teachers' Day", "have dressed as a teacher on Teachers' Day", "have won a fancy dress competition", "have dressed as a freedom fighter for fancy dress", "have dressed as a vegetable for fancy dress",
  "have been in every school play", "have recited a poem on stage", "have forgotten a poem on stage", "have sung the national anthem the loudest", "have taken part in the march past",
  "have gone on a school picnic and got lost", "have been sick on the school bus", "have sat at the back of the school bus singing", "have been friends with the bus driver", "have saved a seat for a friend on the bus",
  "have had a best friend forever from class one", "have fought with their best friend over a pencil", "have made up with their best friend over chocolate", "have had a secret code with a friend", "have passed chits in class",
  "have had summer holidays at their grandparents' house", "have slept on the terrace in summer", "have made a mud house in the rain", "have sailed paper boats in the rain", "have caught fireflies at night",
  "have eaten ice candy every summer day", "have drunk Rasna every summer", "have eaten Maggi at midnight as a kid", "have eaten raw mango with salt in summer", "have stolen pickle from a jar on the terrace",
  "have hidden under the bed during hide-and-seek", "have fallen asleep while hiding", "have won every game of chor-police", "have played lock-and-key every evening", "have played antakshari on long train trips",
  "have written a diary as a child", "have had a pen friend", "have sent letters to a pen friend abroad", "have written to Santa", "have believed in the tooth fairy",
  "have been scared of the dark as a child", "have been scared of a ghost story told by a cousin", "have been scared of a Ramsay horror film", "have slept with the lights on after a scary story", "have checked under the bed every night",
  "have wanted to be a pilot as a child", "have wanted to be a cricketer as a child", "have wanted to be a doctor as a child", "have wanted to be a film star as a child", "have wanted to be an astronaut as a child",
  "have had the same haircut since class one", "have had a bowl haircut as a child", "have worn the same school shoes for three years", "have had oiled hair every school day", "have had two plaits with ribbons",
  "have cried at the end of every summer holiday", "have finished summer homework the night before school", "have copied summer homework from a cousin", "have done a holiday project with glitter everywhere", "have stuck leaves in a scrapbook",
  "have had a birthday party with a magician", "have had a birthday party with musical chairs", "have cut a cake shaped like a cartoon", "have got return gifts at every party", "have distributed toffees in class on their birthday",
]
