// Most Likely To, clean: films, TV, music, sport and games.
export default [
  "know every dialogue of Sholay", "quote a Bollywood film in every conversation", "watch the first-day-first-show of every big film", "whistle in the cinema hall when the hero enters", "throw coins at the screen in a single-screen theatre",
  "cry at every Karan Johar film", "watch DDLJ every time it is on TV", "know all the songs of the 90s", "do the signature step of every famous song", "copy a film hero's hairstyle",
  "dress like a film character for a party", "have a favourite film villain", "root for the villain", "guess the twist in the first ten minutes", "never guess the twist",
  "watch a film three times in the theatre", "binge a whole series in one night", "watch a series with subtitles even in Hindi", "rewatch Friends every year", "rewatch The Office every year",
  "watch every Marvel film in order", "know every Harry Potter spell", "take a Hogwarts house quiz seriously", "wait for a Game of Thrones season with a countdown", "start a series and never finish it",
  "watch only the first episode of everything", "watch the last episode first", "fall asleep in every film", "talk to the characters on screen", "shout 'don't go in there' at a horror film",
  "watch horror films alone at night", "hide behind a cushion during a horror film", "love cartoons more than films", "watch Doraemon as an adult", "know every Tom and Jerry episode",
  "still watch Shaktimaan clips", "know the title song of every 90s TV show", "watch old Doordarshan shows on YouTube", "know every Taarak Mehta character", "watch CID for the comedy",
  "watch every season of Bigg Boss", "vote on reality shows", "audition for Indian Idol", "know every Shark Tank deal", "pitch an idea on Shark Tank one day",
  "be on KBC someday", "answer every KBC question from the sofa", "shout the answer at the TV before the contestant", "follow every award show", "predict the Oscar winners correctly",
  "cry at the Olympics", "watch the whole cricket World Cup", "take leave for an India-Pakistan match", "know the score of every match without watching", "check the score in a meeting",
  "be the most superstitious cricket fan", "sit in the same seat for every match", "pray during the last over", "switch off the TV when India is losing", "dance when India wins",
  "play gully cricket every Sunday", "be the one-tip-one-hand rule maker in gully cricket", "own the bat so they always bat first", "hit the ball into the neighbour's house", "be the best bowler in the colony",
  "be out first ball and ask for a trial ball", "argue every LBW in gully cricket", "play cricket in the rain", "play cricket in a narrow corridor", "follow football more than cricket",
  "stay up all night for a football match", "support a European club fiercely", "know every player in the IPL", "make a fantasy team every day", "win a fantasy league",
  "play badminton every evening", "play table tennis in the office", "be the carrom champion of the house", "be unbeatable at chess", "play chess online at 2 am",
  "watch chess streams", "play video games all weekend", "finish every game they start", "have a gaming setup with lights", "play the same game for ten years",
  "still play Super Mario", "still have their old video game console", "play Snake on an old Nokia", "beat everyone at Temple Run", "know the lyrics of every Arijit Singh song",
  "sing Kishore Kumar songs in the shower", "play old songs on a radio", "make a playlist for every mood", "share music recommendations every day", "discover a band before it gets famous",
  "go to every concert in the city", "get front-row tickets to a concert", "learn guitar from YouTube", "play the harmonium at every family gathering", "play the tabla on the dinner table",
  "drum on every surface", "sing in a choir", "win an antakshari", "remember an old song for every word", "start antakshari on every road trip",
  "be the best at dumb charades", "act out film names perfectly", "guess a film in two seconds in dumb charades", "pick the hardest film in dumb charades", "love board games more than films",
  "own fifty board games", "bring a board game to every party", "explain the rules of a board game for an hour", "win Monopoly by owning everything", "go to a stand-up comedy show and get picked on",
  "know every stand-up comedian's jokes", "quote comedians all day", "do impressions of film stars", "do a perfect Amitabh voice", "imitate a teacher perfectly",
  "imitate their parents to their face", "do every accent perfectly", "dub a film scene with friends", "make their own short film", "act in a web series",
  "become a film critic", "write film reviews online", "review every film with a star rating", "rate every film three stars", "watch only documentaries",
  "watch nature shows to fall asleep", "love cooking shows", "watch travel shows and plan trips", "watch the news like a hobby", "listen to podcasts at double speed",
  "start their own podcast", "listen to audiobooks on the way to work", "fall asleep listening to a podcast", "quote a podcast in every conversation",
]
