// Most Likely To, clean: food.
export default [
  "eat biryani for breakfast", "eat pani puri until they cry", "ask the pani puri bhaiya for one more free one", "know the best momos in the city", "drive an hour for a good dosa",
  "know the best chole bhature place in Delhi", "argue that their mom's food is the best", "rate every restaurant out of ten", "order the same thing at every restaurant", "try every new restaurant in the city",
  "eat at a five-star hotel and miss street food", "eat Maggi at every hill station", "eat ice cream in winter", "drink hot chai in summer", "drink five cups of chai a day",
  "drink coffee like water", "make their own cold coffee", "be a coffee snob", "be a tea snob", "put extra sugar in everything",
  "eat sweets after every meal", "keep a box of sweets at their desk", "eat gulab jamun cold from the fridge", "eat rasgulla in one bite", "finish a whole box of laddoos",
  "eat the most at a wedding", "go for a third round at a buffet", "eat only dessert at a buffet", "skip the main course for the starters", "love spicy food the most",
  "cry eating spicy food and keep eating", "ask for 'no spice' and still find it spicy", "add green chillies to everything", "carry hot sauce in their bag", "eat everything with curd",
  "eat rice with every meal", "need roti with every meal", "make the softest rotis", "make round rotis on the first try", "make Maggi the best",
  "invent a new Maggi recipe", "eat Maggi straight from the pan", "add cheese to everything", "put ketchup on Maggi", "cook a three-course meal for friends",
  "cook only when nobody is watching", "watch cooking shows and never cook", "follow a recipe exactly", "never follow a recipe", "taste food while cooking until half is gone",
  "burn the toast every morning", "make perfect chai", "make chai too strong for everyone", "eat the same breakfast every day", "skip breakfast and eat a big lunch",
  "eat dinner at 11 pm", "have a midnight snack every night", "raid the fridge at 3 am", "keep chocolate hidden from family", "have a secret chocolate stash",
  "eat the cream from biscuits first", "dip every biscuit in tea", "eat Parle-G with chai forever", "love karela", "hate karela with all their heart",
  "pick out the onions from everything", "pick out the cardamom from biryani", "eat the lemon slice in the water", "eat food in the right order", "eat one thing at a time on the plate",
  "mix everything on the plate", "eat with their hands even at a fancy restaurant", "eat pizza with a fork", "eat fruit with salt and chilli", "eat raw mango with masala",
  "eat ice golas in every colour", "know the best kulfi shop", "eat jalebi with rabri at midnight", "know every food stall on their street", "have a favourite thela wala",
  "be best friends with the momo uncle", "get extra chutney everywhere", "ask for extra papad", "eat South Indian food every day", "eat North Indian food every day",
  "learn to cook a dish from every state", "eat in every state of India", "know the difference between every kind of dosa", "love food from Bengal", "love Gujarati thalis",
  "love Kerala parottas", "love Hyderabadi biryani over everything", "love Lucknowi kebabs over everything", "take a cooking class abroad", "eat sushi and pretend to like it",
  "try every cuisine at least once", "order a pizza with paneer on everything", "hate eating out", "love trying weird food", "eat food from a vending machine for lunch",
  "carry a lunch box to work every day", "share their lunch with the whole office", "be the best at making sandwiches", "make the best pakoras when it rains", "make tea and pakoras the moment it rains",
  "say 'it is raining, let's have bhutta'", "know where to get the best roasted corn", "bake a cake for every birthday", "make a cake that sinks in the middle", "decorate a cake beautifully",
  "eat cake batter before baking", "eat the cake frosting first", "organise a potluck", "bring the most popular dish to a potluck", "bring the same dish to every potluck",
  "bring only chips to a potluck", "eat leftovers for three days", "love leftover food more than fresh", "eat dal chawal every day happily", "call dal chawal comfort food",
  "eat khichdi when sad", "eat ice cream when sad", "eat when bored", "forget to eat when busy", "remember every meal they ate on a holiday",
  "plan a trip around food", "pick a hotel because of the breakfast buffet", "take photos of every meal on a trip", "write food reviews", "become a food blogger",
  "open their own food stall", "start a cloud kitchen", "run a chai cafe", "make their own pickles", "make their own masala at home",
  "grow their own vegetables", "keep a herb garden on the windowsill", "eat healthy for a week and then eat a whole pizza", "count calories on everything", "eat salad and order fries",
  "say 'last bite' five times", "finish everyone's leftovers", "never waste food", "pack leftovers from restaurants every time", "ask for a doggy bag at a wedding",
  "save the last piece for someone else", "always offer food to guests ten times", "force guests to eat more", "never let anyone leave hungry", "feed every stray dog on the street",
  "carry biscuits for street dogs", "keep a bowl of water outside for birds", "know the best place for late-night food", "know the best breakfast place in the city", "know the best sweet shop in every city",
  "remember every food place from childhood", "go back to their childhood food spot",
]
