// Most Likely To, clean: little quirks everyone has.
export default [
  "eat the crust of the bread first", "eat around the edges of a pizza", "save the best bite for last", "eat the best bite first", "eat one food at a time from the plate",
  "never let foods touch on their plate", "eat cereal without milk", "pour milk before cereal", "dip fries in ice cream", "eat pineapple on pizza proudly",
  "fold their pizza slice in half", "eat a burger with a fork", "cut a sandwich diagonally only", "peel an orange in one piece", "peel a banana from the bottom",
  "squeeze the toothpaste from the middle", "roll the toothpaste tube neatly", "hang the toilet roll the 'wrong' way", "fold the towel a special way", "make the bed with hotel corners",
  "line up their shoes perfectly", "arrange books by colour", "arrange books by height", "arrange spices alphabetically", "keep their desk perfectly symmetrical",
  "count steps while climbing stairs", "avoid stepping on cracks", "touch every lamp post on a walk", "check the door lock three times", "check the gas knob three times before leaving",
  "keep the volume on an even number", "keep the TV volume on a round number", "keep their phone brightness on full", "keep their phone on low power mode always", "never let their phone battery go below 50",
  "keep their phone at 100 percent all day", "charge their phone every hour", "keep two phone chargers in every bag", "carry an earphone splitter", "carry a pen in every pocket",
  "sleep on the same side of the bed always", "sleep with one foot out of the blanket", "sleep with a fan on in winter", "sleep with white noise", "sleep with the window open",
  "need a glass of water by the bed", "need a night light", "need total silence to sleep", "fall asleep to rain sounds", "fall asleep to a podcast",
  "hum while eating", "hum while working", "whistle while cooking", "sing while walking", "tap a rhythm on every table",
  "click their pen while thinking", "twirl their hair while thinking", "chew on a pencil while thinking", "pace up and down while on calls", "doodle while on calls",
  "talk with their hands", "use their hands to explain everything", "raise their eyebrows at everything", "make faces while concentrating", "stick their tongue out while concentrating",
  "say 'basically' in every sentence", "say 'actually' in every sentence", "say 'literally' in every sentence", "say 'you know' after every line", "say 'na' at the end of every sentence",
  "repeat the last word of every sentence", "laugh before the end of their own joke", "snort when they laugh", "clap when they laugh", "fall over when they laugh",
  "always sit in the same seat", "always order the same dish", "always take the same route home", "always wear the same watch", "always carry the same bag",
  "have a lucky number", "have a lucky colour", "have a lucky shirt", "have a lucky pen", "have a lucky chair",
  "name every object they own", "talk to their car before a long drive", "say thank you to their laptop", "apologise to a door they slammed", "say good night to their plants",
  "smell every book before reading it", "smell every new notebook", "love the smell of petrol", "love the smell of rain on hot ground", "love the smell of a new phone",
  "keep every fortune cookie message", "keep every ticket stub", "keep every bottle cap", "keep every shell from every beach", "keep every key they ever had",
  "remember every phone number from childhood", "remember every number plate of family cars", "remember the date of every big event", "remember what they wore on every big day", "remember every meal on every trip",
  "wake up one minute before the alarm", "wake up at exactly the same time every day", "wake up hungry every night", "wake up and check the weather first", "wake up and make tea before thinking",
  "need music to do anything", "need silence to do anything", "need a snack to do anything", "need a deadline to do anything", "need a nap to do anything",
  "cut their nails at night against all advice", "never whistle at night because of superstition", "never cut hair on Tuesday", "never buy shoes on Saturday", "never start anything new on a Friday",
  "cross their fingers for luck", "knock on wood for luck", "wear their watch on the right hand", "wear two watches", "wear their sunglasses on their head all day",
  "carry a handkerchief every day", "carry a comb in their pocket", "carry a mint everywhere", "carry a book everywhere", "carry a notebook for ideas",
  "take a photo of their parking spot", "take a photo of every menu", "take a photo of every bill", "take a photo of every sunset", "take a photo of every dog they meet",
  "drink water only from their own bottle", "drink water at room temperature always", "drink only cold water even in winter", "drink tea with no sugar", "drink tea with three spoons of sugar",
  "eat dessert first at every buffet", "eat salad last at every buffet", "eat the same breakfast for years", "eat dinner exactly at eight", "eat lunch at their desk every day",
]
