// Most Likely To, clean: animals, nature and the seasons.
export default [
  "be followed home by a stray dog", "have every dog on the street love them", "stop to pet every dog they see", "stop to pet every cat they see", "carry dog biscuits in their bag",
  "rescue a kitten from a drain", "rescue a bird with a broken wing", "rescue a turtle on a road", "foster a puppy", "volunteer at a zoo",
  "know the name of every bird", "know the name of every tree in their colony", "know which flowers bloom in which season", "know every constellation", "know when the next eclipse is",
  "watch an eclipse with special glasses", "wake up at 4 am to see a meteor shower", "make a wish on a shooting star", "lie on the grass and watch clouds", "find shapes in the clouds",
  "love the smell of the first rain", "run outside when it starts to rain", "make paper boats in the monsoon", "jump in puddles", "love thunderstorms",
  "be scared of thunder", "count the seconds between lightning and thunder", "love winter mornings", "love foggy days", "love sitting by a bonfire",
  "drink hot chocolate in winter", "wear three sweaters in Delhi winter", "wear a monkey cap in winter", "sit in the sun on a winter afternoon", "eat peanuts in the winter sun",
  "love summer holidays", "eat mangoes every day in summer", "drink nimbu pani every day in summer", "sleep under a cooler", "love the beach in summer",
  "love spring flowers", "visit a flower show every year", "visit the tulip garden in Srinagar", "visit the Valley of Flowers", "grow sunflowers on their balcony",
  "love the mountains more than the sea", "love the sea more than the mountains", "love the desert at night", "love forests", "love waterfalls",
  "go on a nature walk every weekend", "go bird watching at dawn", "go on a butterfly walk", "go on a night safari", "go on a whale-watching trip",
  "see a snow leopard", "see a red panda", "see a one-horned rhino", "see a blue whale", "see dolphins in Goa",
  "feed the fish in a temple pond", "feed the ducks in a park", "feed the pigeons every morning", "feed the squirrels", "feed the cows on the road",
  "be scared of cows", "be scared of crows", "be scared of pigeons", "be scared of geese", "be scared of goats",
  "talk to cows", "talk to crows", "talk to squirrels", "talk to their goldfish", "talk to the moon",
  "have a pet parrot that talks", "have a pet tortoise that is older than them", "have a pet cat that ignores them", "have a dog that steals socks", "have a dog that eats their homework",
  "dress their dog in a sweater", "take their dog to a dog café", "throw a birthday party for their dog", "take their pet on holiday", "have a pet with an Instagram account",
  "plant a tree in their garden for every birthday", "grow a mango tree from a seed", "grow a tulsi plant", "grow a money plant in a bottle", "keep a bonsai alive for years",
  "hug a tree", "climb a tree to read a book", "build a birdhouse", "put up a bird feeder", "keep water for birds in summer",
  "collect leaves in a book", "collect feathers", "collect stones from every river", "collect sand from every beach", "collect pine cones from every hill station",
  "know the weather by looking at the sky", "smell rain before it comes", "know when the monsoon will arrive", "track cyclones on the news", "love storm-watching from a window",
]
