// Most Likely To, clean: travel and adventure.
export default [
  "visit every continent", "travel to fifty countries", "go on a world tour", "take a trip every month", "plan a trip a year in advance",
  "plan a trip the night before", "go on a trip without a plan", "always book the window seat", "sleep on every journey", "love long train journeys",
  "love road trips", "love flying", "be scared of flying", "get motion sickness on every bus", "pack the lightest bag",
  "pack the heaviest bag", "roll their clothes to save space", "carry a neck pillow everywhere", "carry home food on a plane", "be the first at the airport",
  "arrive at the station two hours early", "make friends with co-passengers", "share snacks with strangers on a train", "play cards on a train", "buy chai at every station",
  "buy samosas at every station", "know the famous food at every station", "know the train timings by heart", "know the platform numbers by heart", "climb the highest peak they can",
  "go trekking every winter", "camp under the stars", "sleep in a tent in the snow", "go river rafting", "go paragliding",
  "go snorkelling", "ride a cable car and close their eyes", "ride a camel in Jaisalmer", "ride a houseboat in Kerala", "ride a toy train in Darjeeling",
  "ride a bike to Ladakh", "see the Northern Lights", "see the pyramids", "see the Eiffel Tower", "see the Great Wall of China",
  "see the Taj Mahal at sunrise", "visit every UNESCO site in India", "visit every fort in Rajasthan", "visit every beach in Goa", "visit every hill station",
  "visit the Andaman Islands", "go to Kashmir in winter", "go to Kerala in the monsoon", "go to Meghalaya to see the living root bridges", "go to Spiti Valley",
  "go to Rann of Kutch on a full moon", "take the best travel photos", "make a travel scrapbook", "collect fridge magnets from every city", "collect coins from every country",
  "send postcards from every trip", "learn a few words of the local language on every trip", "talk to every local they meet", "find the best local food on every trip", "find hidden places nobody knows",
  "get the best deals on hotels", "travel solo", "travel with family every year", "travel with friends every year", "travel with their pet",
  "travel for work and love it", "move to another city for an adventure", "move abroad", "live in a different country every year", "become a travel blogger",
  "write a travel book", "be a tour guide in their own city", "show visitors around their city proudly", "know the history of every monument", "know every shortcut in the city",
  "never get lost", "get lost in every new city", "ask for directions instead of using maps", "trust Google Maps over locals", "read a paper map",
  "know how to use a compass", "go on a pilgrimage", "walk to a temple on a hill", "take a dip in the Ganga", "attend the Ganga aarti in Varanasi",
  "go to the Kumbh Mela", "go on a road trip across India", "drive across the country", "take the longest train route in India", "take the Palace on Wheels",
  "take a cruise", "visit a new place every weekend", "know the best weekend getaways", "find a hidden waterfall", "swim in a waterfall",
  "watch the sunrise from a mountain top", "watch the sunset at the beach every evening on holiday", "build a sandcastle on every beach trip", "collect shells on every beach", "write their name in the sand",
  "fall asleep on the beach", "go on a safari", "spot a tiger in the wild", "spot an elephant herd", "go bird watching",
  "take photos of wild animals", "stay in a treehouse", "stay in a homestay", "stay in a palace hotel", "stay in a desert camp",
  "stay in a hostel and make friends from ten countries",
]
