// Most Likely To, clean: what-ifs, superpowers and silly scenarios.
export default [
  "survive on a desert island the longest", "be the leader on a desert island", "eat the coconut and forget to share", "build a raft from nothing", "make friends with the island's monkeys",
  "survive in the jungle for a month", "survive in space", "be the first person on Mars", "become friends with an alien", "be abducted by aliens and sent back",
  "be chosen by aliens to speak for humans", "explain cricket to an alien", "teach an alien to make chai", "find a treasure map", "find a real treasure",
  "dig up something old in their garden", "find a secret room in their house", "find a hidden door in an old building", "solve a mystery like a detective", "catch a thief with their own clever plan",
  "be the hero in a disaster film", "be the first one eaten in a horror film", "survive till the end of a horror film", "be the one who says 'let's split up'", "go into the dark basement alone",
  "be the funny sidekick in a film", "be the villain in a film", "be the mentor in a film", "be the hero who saves the day at the last second", "be the one who knew it all along",
  "have a superpower and use it to skip traffic", "use invisibility to eat free food", "use mind reading to win arguments", "use super speed to never be late", "use flying to avoid the metro crowd",
  "pick teleportation as their superpower", "pick time travel as their superpower", "go back in time to fix one embarrassing moment", "go back in time to buy Bitcoin", "go back in time to meet their younger self",
  "go to the future to see who they marry", "live in the 1970s happily", "live in a medieval castle", "be a king or queen in another life", "have been a cat in their last life",
  "come back as a dog in their next life", "talk to animals if they could", "understand what babies say", "know what their pet is thinking", "be friends with a talking parrot",
  "win a dance reality show", "win a singing reality show", "win a cooking reality show", "win KBC", "become a millionaire on a quiz show",
  "use all lifelines on the first question", "phone a friend and get the wrong answer", "answer the 7-crore question correctly", "freeze on national TV", "win a hot-dog eating contest",
  "win a dance-off against a child", "win a pillow fight", "win a water-gun fight", "win a game of musical chairs", "win at carrom every time",
  "win at Ludo with a lucky six", "build the tallest card tower", "solve a Rubik's cube in a minute", "finish a 1,000-piece jigsaw puzzle", "finish the newspaper crossword every day",
  "do sudoku in pen", "win a chess game against a computer", "beat everyone at video games", "become a professional gamer", "set a world record",
  "hold the record for the most selfies in a day", "hold the record for the longest nap", "hold the record for eating the most golgappas", "be in the Guinness Book of World Records", "be in the Limca Book of Records",
  "be on a stamp someday", "have their face on a billboard", "be in a TV advertisement", "be a model for a biscuit advertisement", "be the voice of a cartoon character",
  "be a dubbing artist for a Hollywood film", "voice a famous video game character", "sing a jingle that everyone remembers", "invent a new dance move", "invent a new sport",
  "invent a new festival", "invent a new snack", "invent a new word that everyone uses", "write a song that becomes a hit", "make a film that wins an award",
  "make a short film with friends", "act in a school play and get a standing ovation", "direct a Bollywood film", "build a time machine in their garage", "build a treehouse",
  "build a sandcastle bigger than a car", "build a snowman in Manali", "swim across the English Channel", "run across India", "cycle from Kashmir to Kanyakumari",
  "walk 100 kilometres for charity", "fly a plane", "drive a race car", "sail across an ocean", "ride a camel across the desert",
  "ride an elephant in a parade", "live on a houseboat", "live in a castle", "live in a treehouse", "live on a farm",
  "live in a lighthouse", "own a zoo", "own a candy shop", "own a toy shop", "own a bookshop with a cat",
  "own an ice-cream factory", "run away to join the circus", "be a magician", "pull a rabbit out of a hat", "do a card trick that fools everyone",
  "make a coin disappear", "be a superhero in disguise", "have a secret identity", "wear a cape to work", "save a cat from a tree",
  "help an old lady cross the road every day", "find a lost wallet and return it", "find a lost child and find their parents", "rescue a puppy from the rain", "stop a fight with a joke",
  "make a crying baby laugh", "make friends with a ghost", "be the only one to see a ghost", "talk a ghost into leaving", "live in a haunted house happily",
  "throw a party for the ghosts", "win a hide-and-seek game against a whole school", "win a race against a horse", "outrun a dog", "catch a fish with their hands",
  "catch a butterfly without hurting it", "hug a panda", "pet a lion cub", "swim with dolphins", "ride a giant tortoise",
  "make friends with a whale",
]
