// Most Likely To, clean: kind, wholesome and lovely.
export default [
  "help a stranger without being asked", "give their seat to an elderly person", "carry an old lady's bags", "help a lost tourist", "return extra change to a shopkeeper",
  "tip the delivery person well", "thank the bus driver", "remember the watchman's name", "bring tea for the security guard", "share their lunch with a colleague who forgot theirs",
  "donate blood regularly", "volunteer at an animal shelter", "feed stray cats every day", "rescue an injured bird", "plant a tree every birthday",
  "clean up a beach", "pick up litter on a walk", "save water in every way", "carry their own bottle to avoid plastic", "teach poor children for free",
  "donate books to a library", "donate clothes every year", "give food to the homeless", "run a charity drive", "write a thank-you note",
  "send a handwritten letter", "remember everyone's favourite things", "plan the perfect surprise for a friend", "make a gift by hand", "call a friend just to check on them",
  "notice when a friend is sad", "listen without giving advice", "give the best hugs", "make everyone feel included", "invite the new person to sit with them",
  "befriend the shy person at a party", "talk to the lonely uncle at a wedding", "dance with the grandparents at a wedding", "make a child's day with a small gift", "cheer the loudest for their friends",
  "go to every friend's event", "show up when someone needs help", "drive a friend to the hospital at night", "stay up all night with a sick friend", "remember a friend's exam date and wish them luck",
  "send a voice note to cheer someone up", "make a playlist for a sad friend", "bring soup to a sick friend", "cook for a friend who just moved", "help a friend move house",
  "help a friend study", "help a friend find a job", "lend their notes to the whole class", "share their knowledge freely", "forgive easily",
  "never hold a grudge", "see the good in everyone", "stay calm in every situation", "make everyone laugh when things are bad", "be the most positive person in the room",
  "never say a bad word about anyone", "compliment strangers", "smile at everyone", "be loved by every child", "be loved by every dog",
  "be loved by every grandmother", "be the favourite of every teacher", "be the favourite neighbour", "help the neighbours with their groceries", "water the neighbours' plants when they are away",
  "look after the neighbours' pet", "bring sweets for the neighbours", "know everyone in the building", "organise a cleanliness drive in their colony", "start a community garden",
  "organise a blood donation camp", "organise a food drive", "start an NGO", "be a mentor to younger people", "help a junior with their career",
  "write recommendation letters for everyone", "share job openings with friends", "help someone learn English", "teach their parents something new", "teach their grandparents to video call",
  "spend a day with their grandparents every week", "write down their grandparents' recipes", "make their parents proud", "buy a gift for their mom for no reason", "cook a meal for their parents",
  "take their parents to a film", "take their parents on their first flight", "plan a surprise party for their parents' anniversary", "keep every promise", "keep every secret safe",
  "be honest even when it is hard", "stand up for someone being bullied", "speak up when something is wrong", "be the friend who never changes", "stay humble after success",
  "remember where they came from", "give credit to others", "celebrate others' success like their own",
]
