// Most Likely To, spicy: about the people in this room.
export default [
  "secretly fancy someone in this room", "date someone in this room in the next five years", "marry someone in this room", "have already kissed someone in this room", "have a crush on this room's best dancer",
  "have a crush on this room's best cook", "be the best kisser in this room", "be the worst kisser in this room", "be the best flirt in this room", "be the worst flirt in this room",
  "get married first out of this room", "have kids first out of this room", "get divorced first out of this room", "be single the longest out of this room", "stay single forever out of this room",
  "be the richest in this room in ten years", "be the most famous in this room in ten years", "move abroad first out of this room", "lose touch with this room first", "still be friends with this whole room at sixty",
  "be the one this room calls at 3 am", "be the one this room never trusts with a secret", "be the one this room trusts with every secret", "know the most about everyone in this room", "know the least about everyone in this room",
  "be the biggest gossip in this room", "be the biggest liar in this room", "be the most honest in this room", "be the most dramatic in this room", "be the calmest in this room",
  "be the funniest in this room", "think they are the funniest in this room", "laugh at everyone else's jokes in this room", "be the best storyteller in this room", "tell the longest stories in this room",
  "be the best dressed in this room", "spend the most on clothes in this room", "take the longest to get ready in this room", "be the most likely to be late tonight", "leave this party first",
  "stay at this party the longest", "eat the most food tonight", "drink the most tonight", "cry before the night ends", "start a dance party tonight",
  "have the best phone gallery in this room", "have the most embarrassing phone gallery in this room", "have the most unread messages in this room", "have the most screen time in this room", "never let anyone in this room touch their phone",
  "have the worst search history in this room", "have the best Spotify Wrapped in this room", "have the most embarrassing Spotify Wrapped in this room", "have the most Instagram followers in this room", "post about tonight first",
  "be the best driver in this room", "be the worst driver in this room", "be the best cook in this room", "be the worst cook in this room", "be the best singer in this room",
  "be the worst singer in this room", "be the best dancer in this room", "be the worst dancer in this room", "be the best at this game", "lose this game",
  "win this game by voting for themselves", "be voted the most tonight", "be secretly happy to be voted", "be secretly angry about a vote tonight", "remember tonight's votes for years",
  "be the bravest in this room", "be the biggest scaredy-cat in this room", "survive a horror film night best in this room", "scream first in a haunted house", "be the one this room hides behind",
  "be the smartest in this room", "think they are the smartest in this room", "know the answer to every quiz in this room", "be the best at maths in this room", "be the worst at directions in this room",
  "be the most romantic in this room", "be the least romantic in this room", "plan the best date in this room", "give the best gifts in this room", "forget everyone's birthday in this room",
  "be the most stubborn in this room", "be the most patient in this room", "be the least patient in this room", "be the most competitive in this room", "be the sorest loser in this room",
  "be the most adventurous in this room", "be the most careful in this room", "try anything once in this room", "say no to everything in this room", "say yes to every plan in this room",
  "be the best parent one day out of this room", "be the strictest parent out of this room", "be the coolest parent out of this room", "have the most pets out of this room", "live the longest out of this room",
  "be the first in this room to go bald", "be the first in this room to get grey hair", "age the best in this room", "look the same in twenty years", "still act like a teenager at fifty",
  "be the boss of someone in this room one day", "borrow money from someone in this room", "owe money to everyone in this room", "lend money to everyone in this room", "pay for everyone in this room tonight",
  "be the reason this group exists", "bring a new friend into this group", "have introduced two people in this room", "have fought with everyone in this room at least once", "be the first to say sorry in this room",
  "have the best memory of this group's history", "have the most photos of this group", "write this group's story someday", "plan this group's next trip", "cancel this group's next trip",
]
