// Most Likely To, spicy: crushes, dating, flirting and relationships. Each line finishes "Who is most likely to …".
export default [
  "Who is most likely to …", "fall for someone they met on a delayed flight", "date two people with the same name", "slide into a celebrity's DMs", "have a crush on their best friend's sibling",
  "get caught checking out someone at a wedding", "go on a date just for the free food", "flirt with the waiter to get a discount", "fall in love on a group trip", "match with their boss on a dating app",
  "propose on the third date", "kiss someone at midnight on New Year's Eve", "have a secret relationship for a year", "get set up by their mom and actually like the person", "ghost someone after a perfect first date",
  "fall for their gym trainer", "have a crush on a teacher", "write a love poem and send it at 3 am", "date someone ten years older", "date someone ten years younger",
  "fall in love with a foreigner on holiday", "get married in Vegas by mistake", "date someone just to make their ex jealous", "have a celebrity crush they would leave everyone for", "cry on a first date",
  "bring their mom to a date", "take a date to a family function", "forget their date's name halfway through dinner", "get stood up and stay for dessert anyway", "flirt with someone who turns out to be married",
  "fall for the person who rejected them", "have the longest talking stage ever", "date someone from their office", "date a friend's ex", "secretly stalk their crush's Instagram for hours",
  "accidentally like a crush's photo from three years ago", "send a risky text to the wrong person", "fall for someone because of their playlist", "date someone who is a terrible dancer", "marry their school sweetheart",
  "have a crush on a fictional character", "fall in love with a voice on the phone", "move to another city for love", "have three dates in one weekend", "use the same pickup line on everyone",
  "get a love letter in school and never reply", "be the third wheel on every date", "agree to an arranged marriage meeting just for the snacks", "go on a blind date and run away", "kiss on the first date",
  "make the first move", "never make the first move", "confess feelings in a voice note", "confess feelings by mistake in the family group", "fall for someone at a coaching class",
  "have a crush on the bus conductor's son", "date someone they met in a game lobby", "marry the first person they date", "date someone their parents hate", "date someone their parents love more than them",
  "take relationship advice from Instagram reels", "get dumped over text", "dump someone over text", "write their crush's name in a notebook", "plan their wedding in their head on the first date",
  "fall in love with a barista", "flirt with the delivery guy", "flirt their way out of a traffic fine", "pretend to like cricket to impress a date", "pretend to like a band to impress a crush",
  "pretend to be single at a party", "pretend to be taken to avoid someone", "have a fake boyfriend or girlfriend for a family event", "fall for a stranger on the metro", "send a good morning text to three people",
  "keep a backup crush", "date someone with the same name as their sibling", "date their dentist", "lie about their age on a dating app", "use a ten-year-old photo on their dating profile",
  "match with a cousin on a dating app", "swipe right on everyone", "swipe left on everyone and complain about being single", "go on a date with someone they met at a funeral", "fall in love at a wedding sangeet",
  "get proposed to in a mall", "propose with a ring pop", "propose in front of a stadium crowd", "say I love you on the second date", "never say I love you",
  "have a secret crush on someone in this room", "have dated someone in this room's family", "spend their whole salary on a date", "split the bill to the last rupee on a date", "ask for a second date during the first date",
  "fall for someone's handwriting", "fall for someone because they are good at maths", "date someone who is always late", "date someone who never replies", "have a long-distance relationship across time zones",
  "fly to another country for a date", "get back with someone after five years", "date a famous person in secret", "fall for a doctor while being treated", "fall for someone during a power cut",
  "have a holiday romance in Goa", "fall for their neighbour", "fall for their landlord's child", "date someone they met in a lift", "get engaged after one month",
  "get engaged and call it off the next week", "date someone with a very jealous mom", "be the jealous one in a relationship", "check their partner's phone", "change their password for a partner",
  "share their Netflix with an ex for years", "keep an ex's hoodie forever", "get a tattoo of a partner's name", "cover up a partner's name tattoo", "send flowers to themselves to make someone jealous",
  "write a song about a crush", "sing a romantic song at karaoke to a crush", "dedicate a song on the radio", "fall for a contestant on a reality show", "go on a reality dating show",
  "propose on Instagram live", "post a couple photo after one date", "hide a relationship from their parents for years", "get caught with a partner by their parents", "sneak out to meet someone",
  "make out in a movie theatre", "fall asleep on a date", "eat off their date's plate", "order for their date without asking", "bring a friend to a first date",
  "bring a pet to a first date", "have a crush on someone just because they have a dog", "talk about their ex on a first date", "show their date baby photos", "cry about their ex to their new date",
  "fall for the bride's brother at a wedding", "fall for the groom's sister at a wedding", "dance with a stranger at a baraat", "exchange numbers at a wedding buffet", "date someone who is engaged",
  "be someone's rebound", "have a rebound within a week", "rate their dates on a spreadsheet", "keep a list of all their crushes", "have dated someone in every city they lived in",
  "find a partner on LinkedIn", "flirt in the comments of a news post", "send a reel instead of saying how they feel", "fall in love over voice notes", "fall in love over a cricket argument",
  "get married in a temple without telling anyone", "elope", "get married at a court on a Tuesday", "have two weddings with the same person", "fall for their tuition teacher",
  "fall for their child's teacher", "fall in love in a hospital waiting room", "flirt with an air hostess", "flirt with the pilot announcement", "fall for someone at a cricket stadium",
  "get on the kiss cam", "kiss someone on a dare", "date someone just for their car", "date someone just for their house", "fall for someone's mom's cooking",
  "love someone's family more than the person", "get a promise ring at nineteen", "plan a surprise date that goes horribly wrong", "plan a candlelight dinner and set something on fire", "make a scrapbook for a partner",
  "forget an anniversary", "remember every anniversary including the first chat", "celebrate a monthiversary", "get jealous of a partner's pet", "fight with a partner over a Netflix show",
  "break up over food", "break up over a cricket team", "break up over a political argument", "break up on a birthday", "get back together on a birthday",
  "ask their ex for relationship advice", "set their ex up with someone", "attend their ex's wedding", "cry at their ex's wedding", "be invited to their ex's wedding and dance the most",
  "become best friends with their partner's ex", "date their partner's best friend after a breakup", "date twins one after the other", "go on fifty first dates", "never go on a second date",
  "have an online relationship for years without meeting", "be catfished", "catfish someone", "pretend to be rich on a date", "pretend to be a doctor on a dating app",
  "say they are a pilot to impress someone", "fall in love on a train journey", "write their number on a train seat", "pass a chit in class to a crush", "send a crush a Valentine's card anonymously",
  "receive ten Valentine's cards", "spend Valentine's Day eating alone happily", "hate Valentine's Day loudly every year", "go on a date on Valentine's Day with a friend", "take a date to a pani puri stall",
  "take a date to a five-star hotel and order chai", "take a date to their office party", "take a date to a cricket match", "date someone who supports the rival IPL team", "change their IPL team for love",
  "date a gym rat", "date someone who has never cooked", "date a chef", "marry for money", "marry for a green card",
  "marry someone they met online", "marry someone their grandmother chose", "marry their best friend", "fall for someone because they look like a film star", "fall for someone because they smell nice",
  "fall for someone over a shared umbrella", "fall for someone who saved them from a dog", "flirt using memes", "flirt using song lyrics", "flirt using shayari",
  "flirt in Hindi to sound romantic", "flirt in English to sound cool", "write a long paragraph on a partner's birthday", "post a partner's photo every Sunday", "make their partner their lock screen",
  "make their partner their contact name with emojis", "call their partner babu", "call their partner by their surname", "give everyone they date the same nickname", "save a crush's number under a fake name",
  "hide a crush's chat in archive", "delete chats with a crush every night", "screenshot a crush's messages to discuss with friends", "ask friends to decode a crush's text", "take three hours to reply to look busy",
  "reply in three seconds and regret it", "double text", "triple text", "send a paragraph and get a 'k' back", "see a crush's story within a minute every time",
  "post a story only for one person to see", "make a close friends list for one person", "change their DP after a breakup", "post sad songs after a breakup", "post gym photos after a breakup",
  "start a podcast after a breakup", "move to a new city after a breakup", "cut their hair after a breakup", "get a pet after a breakup", "become a poet after a breakup",
  "go to the mountains to find themselves after a breakup", "cry in an Uber after a date", "fall for an Uber driver", "fall for their bank relationship manager", "fall for the customer care agent",
  "fall for someone who sold them a phone", "kiss someone under the mistletoe", "kiss someone at a Holi party", "dance with their crush at Garba", "find love at Navratri",
  "find a partner at a college fest", "make out in a college library", "have a crush on the college topper", "date the college president", "date the hostel warden's child",
  "get caught sneaking into the girls' hostel", "get caught sneaking into the boys' hostel", "run a matchmaking service for friends", "set up two friends who then get married", "set up two friends who then hate each other",
  "be the friend who always knows who likes whom", "spread a rumour about two people dating", "be the subject of a dating rumour", "date someone just to end a rumour", "have a crush on a cricket player",
  "have a crush on a news anchor", "have a crush on a cartoon character", "have a crush on a voice assistant", "fall in love with a pen pal", "write love letters on paper in this century",
  "send a love letter by post", "keep every love letter they ever got", "fall for their crush's sibling instead", "accidentally flirt with a crush's parent", "call a crush's dad 'bro'",
  "meet the parents in shorts", "meet the parents and touch everyone's feet twice", "meet the parents and talk about money", "impress the parents and not the partner", "get approved by the parents in five minutes",
  "be rejected by a partner's dog", "be loved by a partner's grandmother", "bring a gift for the whole family on a first visit", "show up to meet the parents empty-handed", "date someone who lives with eight roommates",
  "date someone who still lives with their parents at forty", "date someone who calls their mom ten times a day", "plan a date with a spreadsheet", "plan a date that is just a walk and chai", "take a date to see their favourite sunset spot",
  "take every date to the same restaurant", "fall for a person they argued with on Twitter", "fall for a person who corrected their grammar", "fall for a person who beat them at chess", "fall for a person who beat them at Ludo",
  "get a crush on someone who is bad at everything", "date someone who is too good at everything", "be intimidated by their partner's job", "be jealous of their partner's salary", "date someone who is a famous Instagram creator",
  "become famous because of who they date", "go viral for a proposal", "go viral for a rejected proposal", "say no to a public proposal", "say yes to a proposal just to avoid embarrassment",
  "propose to the wrong twin", "propose while drunk", "propose at a funeral by accident", "plan a proposal for months and forget the ring", "drop the ring in the sea",
  "hide the ring in food and someone else eats it", "propose with a song they wrote", "fall in love on a trek", "kiss someone at the top of a mountain", "fall for a stranger at the airport",
  "miss a flight for a crush", "change their travel plans for a stranger", "spend a whole night talking to someone they just met", "watch the sunrise with a stranger", "share an auto with a stranger and swap numbers",
  "fall for someone during a fire drill", "go on a date in matching outfits", "make a couple reel", "start a couple YouTube channel", "break up and keep the couple YouTube channel",
  "write a book about their exes", "name a pet after an ex", "name a child after an ex", "dream about their crush every night", "dream about someone in this room",
  "blush when a crush says hi", "freeze when a crush says hi", "say 'you too' when a waiter says enjoy your meal, on a date", "trip and fall in front of their crush", "spill coffee on their crush",
  "sing badly to impress someone", "dance badly to impress someone", "play guitar badly to impress someone", "cook badly to impress someone", "lie about cooking skills to impress someone",
  "learn a new language for a partner", "learn a partner's family's recipes", "convert to a partner's football club", "pretend to love a partner's terrible jokes", "date someone who is a terrible singer and say they are amazing",
  "fight over who said I love you first", "have a fake fight to get attention", "make a partner jealous on purpose", "flirt with a partner's friend by mistake", "send a flirty text to their boss by mistake",
  "send a flirty text to their mom by mistake", "send a breakup text to the family group", "use a dating app while in a relationship", "keep a dating app 'just to see'", "delete the dating app and reinstall it the same night",
  "pay for a premium dating app plan", "get rejected by an AI dating coach", "use AI to write messages to a crush", "use AI to write a breakup text", "ask AI if their crush likes them",
  "have a crush on a co-passenger in the lift every day", "make eye contact with a crush for a year without talking", "finally talk to a crush and say something weird", "fall in love at a book fair", "fall in love at a protest",
  "fall in love at a hospital canteen", "fall in love at a laundromat", "fall in love at a petrol pump", "fall for someone who looks like their ex", "date the same type of person every time",
  "date the exact opposite of their ex", "date someone just because they are tall", "make a partner hold their bag all day", "make a partner take a hundred photos", "be the Instagram partner who takes all the photos",
  "never post their partner", "post their partner but hide their face", "have a secret couple account", "write a partner's name in the sand", "carve a name on a tree",
  "lock a love lock on a bridge", "carry a partner's photo in their wallet", "keep a partner's voice note as an alarm", "sleep on a video call", "talk on the phone all night and sleep at work",
  "spend all their data on video calls with a partner", "pay a partner's phone bill", "buy a partner's Netflix", "buy a partner a phone on the first month", "date someone who never pays",
  "always pay and complain later", "go Dutch on every date", "take a date to a buffet and eat more than them",
]
