// Most Likely To, spicy: wild, risky and chaotic.
export default [
  "get arrested for something silly", "get arrested on holiday", "be bailed out by their best friend", "spend a night in a police station chatting with the cops", "get a court summons for a parking ticket",
  "talk their way out of a challan", "bribe a watchman with samosas", "sneak into a five-star hotel pool", "sneak into a wedding in another city", "sneak backstage at a concert",
  "sneak into a cricket stadium", "run onto a cricket field to hug a player", "get on TV in the crowd at a match", "be on the news for something weird", "be interviewed by a news channel on the street",
  "go skinny dipping", "go to a nude beach by mistake", "jump off a cliff into the sea", "go bungee jumping and scream the whole time", "skydive and pass out",
  "ride a bike at 150 km an hour", "race a stranger at a traffic signal", "get a speeding ticket on a cycle", "drive to another state at midnight for food", "take a sudden trip to Ladakh on a bike",
  "quit their job and travel the world", "sell everything and move to Goa", "move to the mountains and open a cafe", "live in a van", "live on a boat",
  "go on a trip with strangers they met online", "hitchhike across the country", "say yes to every invitation for a month", "say yes to a stranger's wild plan", "follow a stranger's advice blindly",
  "get a tattoo on a dare", "get a tattoo of a meme", "get their crush's initials tattooed", "pierce something at a friend's house", "shave their head on a bet",
  "dye their hair a crazy colour on a whim", "cut their own hair at 2 am", "cut a friend's hair and ruin it", "wax their eyebrows off by mistake", "get a bad haircut before a wedding",
  "make a huge bet and lose", "bet their salary on a cricket match", "win a fortune in a fantasy league", "lose money in fantasy cricket every week", "go to a casino and win big",
  "go to a casino and lose everything", "play poker with real money and lose", "invest in a meme coin", "lose money on a stock tip from a friend", "start a business with a friend and fight",
  "lend money to a friend and lose the friend", "throw a party they cannot afford", "max out their credit card on a holiday", "buy something huge on impulse", "buy a car on a whim",
  "adopt three dogs on the same day", "bring a stray animal home every week", "rescue a cow from the road", "fight a monkey for a banana", "get chased by a goose",
  "get bitten by a monkey at a temple", "feed a wild animal and regret it", "try to pet a wild elephant", "swim with sharks", "go camping and get lost",
  "survive alone in a jungle", "win a reality survival show", "eat a bug on a dare", "eat the spiciest chilli in the world", "enter an eating competition",
  "drink a bottle of hot sauce", "eat food from every street stall in one night", "get food poisoning on every trip", "eat a dish without knowing what it was", "try every weird food abroad",
  "go on a road trip without a plan", "go somewhere without telling anyone", "switch off their phone for a week", "disappear for a weekend and come back with a story", "turn a short trip into a month",
  "miss a flight because they were shopping", "run through an airport for a flight", "board the wrong train", "fall asleep and miss their stop by 300 km", "end up in another country by mistake",
  "lose their passport abroad", "get stuck at an airport for two days", "sleep on an airport floor", "make friends with immigration officers", "get stopped at security for pickles in the bag",
  "carry home-made food through customs", "carry a pressure cooker on an international trip", "bring a full suitcase of maggi abroad", "get detained for carrying too many sweets", "smuggle laddoos into a cinema",
  "take food into a movie hall in their handbag", "watch three movies in a row in a theatre", "sneak into a second movie with one ticket", "fall asleep in a cinema and wake up after it closed", "get locked in a mall",
  "get stuck in a lift and make it a party", "climb onto a roof to watch fireworks", "light fireworks in their hand", "set something on fire while cooking", "start a kitchen fire making Maggi",
  "break a bone doing something stupid", "break a bone dancing", "get stitches from a party accident", "end up in the hospital on their birthday", "make friends in the hospital ward",
  "stand up to a bully in public", "fight a stranger for a parking spot", "shout at a rude driver", "chase a pickpocket", "catch a thief",
  "become a local hero for a day", "save someone from drowning", "be the first to help in an accident", "lead a protest", "start a petition about something silly",
  "run for local elections", "become a sarpanch", "become a minister someday", "start a political party with friends", "go viral for a speech",
  "say something outrageous at a family dinner", "drop a big announcement at a family dinner", "announce they are moving abroad at a wedding", "announce an engagement at someone else's party", "quit their job by email at 2 am",
  "tell their boss what they really think", "walk out of an exam", "walk out of a meeting", "walk out of their own wedding", "walk into the wrong wedding and stay",
  "do something legendary that the group still talks about", "be banned from a restaurant", "be banned from a friend's house", "be banned from a WhatsApp group for life", "be banned from karaoke",
  "make the group lose a security deposit", "break the hotel bed on a trip", "flood a bathroom in a hotel", "set off the hotel fire alarm", "get the whole group kicked out of a hotel",
  "get the group into a VIP party by luck", "befriend a celebrity on a flight", "end up at a celebrity's house party", "date a celebrity's assistant", "get a selfie with a cricketer at the airport",
  "say yes to a shady job offer abroad", "join a cult by accident", "join a pyramid scheme", "recruit their friends into a pyramid scheme", "sell protein powder to their friends",
  "start a gang in school", "be a gang leader in college", "have a bike gang", "own a leather jacket and act tough", "challenge someone twice their size to a fight",
  "arm wrestle a stranger at a bar", "do push-ups to win a bet", "run a marathon without training", "go to a jungle safari and get out of the jeep", "try to take a selfie with a tiger",
  "play with fire at a bonfire", "stay in a haunted hotel for fun", "do a ouija board at midnight", "call a ghost on a ouija board and run", "go into an abandoned building at night",
  "spend a night in a graveyard on a dare", "take a dare that ends badly", "always say 'what's the worst that could happen'",
]
