// Most Likely To, spicy: trips gone wrong (and right).
export default [
  "lose the group on the first day of a trip", "wander off and come back with a local friend", "get into a fight with a hotel manager", "talk their way into a free room upgrade", "book the wrong hotel in the wrong city",
  "book a hotel that looks nothing like the photos", "book a hostel and complain about everything", "sleep in the train corridor", "travel without a ticket and get caught", "argue with the TT in the train",
  "make friends with the whole train compartment", "share food with strangers on the train", "play cards with strangers on a train", "find their soulmate on a train", "get off at the wrong station to buy samosas",
  "miss the train because of the chai stall", "run after a moving train", "climb onto the train from the wrong side", "sleep through their station", "end up in Kanyakumari instead of Kochi",
  "go to Goa and only see the hotel pool", "go to Manali and only see the inside of a cafe", "go to the beach and refuse to get wet", "go to the mountains in flip-flops", "go trekking with a suitcase",
  "pack a party outfit for a trek", "pack ten outfits for a two-day trip", "forget their underwear on a trip", "forget their charger on every trip", "forget their ID at the airport",
  "argue at airport security about a water bottle", "set off the metal detector every time", "carry a knife in their bag by mistake", "get their bag searched at every airport", "try to carry a whole jar of pickle in hand luggage",
  "fall asleep at the gate and miss the boarding", "hear their name on the final boarding call", "run barefoot through the airport", "board the wrong flight", "make friends with the flight crew",
  "stand up as soon as the plane lands", "ask for extra food on the flight", "steal the airline blanket", "be the person who reclines the seat all the way", "take off their shoes on the flight",
  "talk to the passenger next to them for the whole flight", "pretend to sleep to avoid talking on a flight", "get upgraded to business class", "fly business class once and never shut up about it", "get food poisoning on holiday",
  "eat street food abroad and regret it", "find Indian food in every country", "carry their own Maggi to Europe", "complain that the food abroad has no spice", "get lost in a foreign city at night",
  "use Google Translate to flirt", "learn only rude words in a new language", "bargain in a mall abroad", "get scammed by a taxi abroad", "rent a scooter abroad without a licence",
  "drive on the wrong side of the road abroad", "get a parking ticket abroad", "get stopped by police abroad and talk their way out", "lose their passport and cry at the embassy", "overstay their visa by a day",
  "travel to ten countries in ten days", "do a solo trip and call home every hour", "do a solo trip and come back changed", "go on a pilgrimage and party after", "go on a meditation retreat and talk the whole time",
  "go on a detox retreat and sneak in chips", "go on a yoga retreat and sleep through every class", "go on a wellness trip and come back tired", "take a road trip without checking the car", "run out of petrol in the middle of nowhere",
  "get a flat tyre in the ghats", "take a shortcut that adds four hours", "follow Google Maps into a field", "argue about directions the whole trip", "control the music on every road trip",
  "sleep through the whole road trip", "eat all the road trip snacks in the first hour", "stop at every dhaba on a road trip", "want to stop for photos every ten minutes", "make the group wait for the perfect sunset photo",
  "drop a phone off a viewpoint", "climb on a monument for a photo", "get scolded by a guard for a photo", "fall into a river taking a selfie", "get splashed by a wave at the beach",
  "get stung by a jellyfish", "get chased by monkeys in Shimla", "get their glasses stolen by a monkey", "get their food stolen by a seagull", "feed the street dogs on every trip",
  "adopt a dog on a trip", "bring home a stray cat from a trip", "make friends with a cow on the beach in Goa", "spend all their money on the first day of the trip", "come back from a trip with no money and a new tattoo",
  "come back with ten fridge magnets", "buy souvenirs for everyone and forget themselves", "forget to buy souvenirs and buy them at the airport", "write a travel blog nobody reads", "make a travel reel for every trip",
  "post trip photos for three months after the trip", "say 'when I was in Paris' in every conversation", "plan the next trip on the way back",
]
