// Most Likely To, spicy: personality roasts.
export default [
  "think they are always the main character", "narrate their life like a film", "have a villain origin story", "have a redemption arc", "turn every conversation back to themselves",
  "one-up every story", "say 'that's nothing, listen to this'", "humble-brag in every conversation", "mention their salary casually", "mention their foreign trip casually",
  "drop famous names they barely know", "say they know a celebrity because they saw them once", "pretend to be busy all the time", "say 'I'm so busy' and post reels all day", "say 'I don't care' and care the most",
  "act cool and be nervous inside", "act tough and cry at a puppy video", "act sweet and be savage", "be savage and say 'just kidding'", "give compliments that are secretly insults",
  "say 'with all due respect' and then insult someone", "say 'I'm just being honest' to be rude", "be brutally honest without being asked", "be too nice to say no", "say yes to everything and do nothing",
  "overthink a two-word text", "overthink what they said at a party for a week", "replay an awkward moment at 3 am", "worry about things that never happen", "panic and then be perfectly fine",
  "plan everything and still be late", "plan nothing and have the best time", "be the most indecisive in the group", "take thirty minutes to order food", "order the same thing after reading the whole menu",
  "change their mind five times in an hour", "regret every decision", "never regret anything", "make decisions by flipping a coin", "make decisions by asking the group chat",
  "have an opinion on everything", "have no opinion on anything", "agree with whoever spoke last", "start a debate and leave", "be the loudest in a debate and the least informed",
  "read the headline and argue about the whole article", "become an expert in every topic overnight", "explain things to experts", "explain someone's own job to them", "correct people who are right",
  "be a know-it-all about films", "be a know-it-all about cricket", "be a know-it-all about food", "be a know-it-all about the stock market", "be a know-it-all about relationships while single",
  "give dating advice while being single for ten years", "give money advice while being broke", "give fitness advice and eat junk", "give parenting advice with no kids", "give career advice and hate their job",
  "be a different person in front of their parents", "be a different person at work", "be a different person after two drinks", "be a different person on Instagram", "be the same person everywhere",
  "be the nicest to strangers and rude to family", "be rude to waiters and lose friends for it", "be extra polite to waiters", "say thank you too many times", "apologise to furniture",
  "have a dramatic reaction to small news", "have no reaction to big news", "laugh at bad news out of nervousness", "cry at good news", "scream at surprises",
  "hate surprises", "love being the centre of attention", "hate being the centre of attention", "pretend to hate attention and love it", "fish for compliments",
  "need constant reassurance", "need nobody's approval", "change their look for every new partner", "change their music taste for every new partner", "change their personality for every new partner",
  "be a completely different person in a new relationship", "copy their partner's way of talking", "start saying their partner's words", "pick up their best friend's habits", "pick up every accent they hear",
  "be a terrible winner", "be a gracious loser", "be a terrible loser", "blame the phone when they lose a game", "blame the dice when they lose at Ludo",
  "hold everyone to high standards except themselves", "be stricter with themselves than anyone", "never take a compliment", "take every compliment and ask for more", "remember every compliment they ever got",
  "remember every insult they ever got", "keep score in friendships", "never keep score", "be the first to text after a fight", "never text first after a fight",
]
