// Most Likely To, spicy: more friend-group truths.
export default [
  "be the friend who always brings drama to the group trip", "be the friend who always has a crisis on the group trip", "be the friend who always needs money on the group trip", "be the friend who always gets lost on the group trip", "be the friend who always falls sick on the group trip",
  "be the friend who books everything and gets no credit", "be the friend who arrives with no bag", "be the friend who brings a speaker everywhere", "be the friend who knows the best photo spots", "be the friend who wakes everyone for sunrise",
  "be the friend who cries at every goodbye", "be the friend who never says goodbye", "be the friend who leaves the party without telling anyone", "be the friend who calls to say they reached home", "be the friend who forgets to text when they reach",
  "be the friend who always defends everyone", "be the friend who always takes the other side", "be the friend who sides with your partner", "be the friend who sides with you even when you are wrong", "be the friend who tells you when you are wrong",
  "be the friend who remembers every embarrassing story", "be the friend who brings up embarrassing stories at weddings", "be the friend who has a photo for every embarrassing story", "be the friend who swears they will never tell and tells", "be the friend who actually never tells",
  "be the friend who sends the most memes", "be the friend who replies to memes with 'lol'", "be the friend who never watches the reels you send", "be the friend who watches every reel and replies with an essay", "be the friend who sends the same reel back",
  "be the friend who plans birthdays", "be the friend who forgets birthdays", "be the friend who gives the most thoughtful gifts", "be the friend who gives gift cards to everyone", "be the friend who gives gifts that are secretly for themselves",
  "be the friend who always picks the restaurant", "be the friend who says 'anything is fine' and rejects everything", "be the friend who always orders for the table", "be the friend who always asks for the bill", "be the friend who disappears when the bill comes",
  "be the friend who knows everyone's parents", "be the friend who is invited to every family event", "be the friend who is called 'beta' by everyone's mom", "be the friend whose house is the hangout spot", "be the friend whose fridge everyone raids",
  "be the friend who gives the most honest outfit advice", "be the friend who lies and says everything looks great", "be the friend who does everyone's makeup", "be the friend who cuts everyone's hair", "be the friend who chooses everyone's DP",
  "be the friend who writes everyone's captions", "be the friend who edits everyone's photos", "be the friend who makes everyone's birthday video", "be the friend who makes the group's yearly recap", "be the friend who knows the group's history best",
  "be the friend everyone tells their problems to", "be the friend who gives advice nobody follows", "be the friend who always says 'I told you so'", "be the friend who never says 'I told you so'", "be the friend who saw it coming",
  "be the friend who moves away and visits every year", "be the friend who moves away and never visits", "be the friend who visits only for weddings", "be the friend who flies in for every birthday", "be the friend who sends gifts from abroad",
  "be the friend whose partner the group loves", "be the friend whose partner the group hates", "be the friend who brings a new partner every reunion", "be the friend who brings no partner ever", "be the friend who marries a friend from the group",
  "be the friend who makes the group laugh at a funeral", "be the friend who makes the group cry at a wedding", "be the friend who makes the group fight over a game", "be the friend who makes the group make up after a fight", "be the friend who makes the group stay together",
  "be the friend who knows the group's secrets and never uses them", "be the friend who threatens to use the group's secrets", "be the friend who wrote the group's unwritten rules", "be the friend who breaks every group rule", "be the friend who made this game night happen",
]
