// Most Likely To, spicy: secrets, lies, guilty pleasures and confessions.
export default [
  "have a secret Instagram account", "secretly write fan fiction", "secretly watch K-dramas all night", "secretly love saas-bahu serials", "secretly cry at reality shows",
  "secretly listen to Justin Bieber", "secretly know every word of a cringe song", "have a secret talent nobody knows", "have a secret savings account", "have a secret credit card bill",
  "hide a big purchase from their family", "hide a tattoo from their parents", "hide a piercing from their parents", "hide a relationship from their best friend", "hide their real marks from everyone",
  "lie on their CV", "lie about their salary to friends", "lie about their age at a club", "lie about their height on a dating app", "lie about being busy to avoid a friend",
  "lie about being sick to skip work", "lie about having read a book", "lie about having watched a film everyone loves", "pretend to understand a joke", "pretend to understand wine",
  "pretend to understand the stock market", "pretend to be on a diet to look disciplined", "pretend to be a morning person", "pretend to have plans on a Friday night", "say they are an introvert and talk the most",
  "say they hate drama and cause the most", "say 'I don't gossip' before gossiping", "know everyone's secrets in the friend group", "keep a secret for ten years", "tell a secret within ten minutes",
  "tell a secret and say 'don't tell anyone' to everyone", "start a rumour by accident", "be the source of every rumour", "be the last to know a big secret", "read someone's diary",
  "read messages over someone's shoulder", "look through a friend's photo gallery when handed the phone", "listen to someone's phone call from the next room", "eavesdrop in a restaurant", "have a fake name for coffee orders",
  "use a fake name at every restaurant", "have a fake email for spam that is now their main one", "have an embarrassing old email ID still in use", "have an embarrassing old username they still love", "have cringe old Facebook posts that still exist",
  "delete old posts before a job interview", "have a childhood video that would ruin them", "have embarrassing baby photos their mom shows everyone", "have a secret celebrity crush they deny", "have a crush on a friend's partner",
  "have a crush on a friend's sibling", "have had a crush on someone in this room", "still have a crush from school", "have dreamt about a friend romantically", "have kissed someone in this friend group",
  "have dated two people in this group", "have a secret second family WhatsApp group", "be in a group chat that talks about the rest of us", "screenshot everything people say", "keep receipts of every argument",
  "keep a list of people who wronged them", "hold a grudge for twenty years", "forgive everyone too easily", "pretend to forgive and remember forever", "stalk a new colleague on LinkedIn",
  "stalk their partner's ex", "stalk their teacher on Instagram", "find everyone's old school photos online", "know someone's whole life from their profile before meeting them", "google themselves",
  "google their crush", "google their own symptoms and panic", "have a weird search history", "clear their search history every night", "have the worst browser history",
  "accidentally share their search history on a projector", "have a playlist they would never let anyone see", "have a 'guilty pleasure' playlist with 500 songs", "have a song that makes them cry every time", "talk to their pet like a baby",
  "talk about their pet like it is their child", "have a pet with its own Instagram", "spend more on their pet than on themselves", "celebrate their pet's birthday with a cake", "eat their roommate's food and deny it",
  "drink from the milk carton", "use the same towel for a month", "wear socks two days in a row", "wear the same jeans for two weeks", "sniff clothes to check if they are clean",
  "re-gift a gift", "re-gift a gift to the person who gave it", "keep the gift card for themselves", "return a gift for cash", "pick the last-minute gift from the airport",
  "buy gifts from the petrol pump shop", "forget a birthday and post a long wish the next day", "use Facebook reminders for every birthday", "wish someone a happy birthday on the wrong day", "secretly be very competitive",
  "secretly practise a game before game night", "secretly google answers during a quiz", "cheat at a pub quiz", "cheat in a pub quiz and still lose", "secretly enjoy their friends' fights",
  "secretly start fights in the group", "be the friend who stirs the pot", "act innocent after stirring the pot", "keep popcorn ready for drama", "secretly want to be famous",
  "secretly want to be a singer", "secretly practise acceptance speeches", "secretly rehearse their Oscar speech in the mirror", "secretly believe they are the main character", "secretly love being the centre of attention",
  "secretly hate surprise parties", "secretly hate their own birthday", "secretly love small talk", "secretly not like dogs", "secretly not like biryani",
  "secretly hate cricket", "secretly enjoy doing taxes", "secretly enjoy Excel", "secretly enjoy cleaning", "secretly be the richest in the group",
  "secretly be broke while acting rich", "secretly own a lot of property", "secretly have invested in crypto and lost it all", "secretly have a side business", "have a second job nobody knows about",
  "have a hidden skill like juggling", "secretly speak four languages", "secretly be a great cook", "secretly be terrible at their job", "secretly be the boss's favourite",
  "secretly be looking for a new job", "secretly have resigned already", "secretly applied to the job of a friend", "secretly take credit for others' work", "secretly read their partner's chats",
  "secretly check who viewed their story", "secretly watch the same reel fifty times", "secretly cry at old photos", "secretly keep every ticket stub", "keep an ex's hoodie and still wear it",
  "keep screenshots of every compliment", "save every voice note from their mom", "save every love letter", "keep a diary since class five", "write a diary entry about this game",
  "have a secret poem collection", "have a book draft they never finished", "have a startup idea they never tell anyone", "have a business plan in their notes app", "have a plan for a zombie attack",
  "have a plan to escape if aliens come", "have a code word with their best friend", "have a secret handshake", "have an inside joke nobody else gets", "confess something huge at 2 am",
  "confess a crush on a voice note and delete it", "confess to breaking something years later", "confess they never liked a gift", "confess they lied about their age", "admit they were wrong after five years",
  "apologise for something from school", "admit they still sleep with a soft toy", "admit they are scared of the dark", "admit they still ask their mom what to wear", "admit they cannot ride a bicycle",
  "admit they cannot swim", "admit they have never seen Sholay", "admit they have never been on a plane", "admit they still cannot tie their shoelaces properly", "have lied in this game already",
  "be lying about one of their answers tonight", "have voted for themselves in this game", "be the one everyone suspects in Imposter", "be the best liar in the group", "be the worst liar in the group",
  "get caught lying because they smile", "lie so well they believe it themselves", "keep a lie going for years", "build a whole fake life story for fun", "tell a stranger a completely fake life story",
  "pretend to be a tourist in their own city", "pretend to be from another country for a day", "fake an accent for a whole trip", "pretend to be a celebrity's cousin", "have been mistaken for a celebrity",
  "have taken credit for a friend's joke", "have read a friend's message and pretended not to", "have unfriended someone over politics", "have muted their own family group", "have left a family group dramatically",
  "have been removed from a group chat", "have a group chat with only themselves for notes", "have sent a message about someone to that person", "have gossiped about someone who was standing right behind them", "have been caught gossiping on a speakerphone",
  "have accidentally butt-dialled during a rant", "have called someone by mistake while talking about them", "have liked a post while stalking and frozen", "have unsent a message just in time",
]
