// Most Likely To, spicy: shaadi season, rishtas, in-laws and aunties.
export default [
  "get a rishta at a cousin's wedding", "be pointed at by aunties at every wedding", "be told 'next number tera' at every wedding", "be asked their 'biodata' at a funeral", "have their photo shown to a stranger's family at a wedding",
  "have their mom ask a stranger's mom about their child's job", "have their parents send their kundli without asking", "have a kundli that matches with nobody", "have thirty-six gunas matched and still say no", "reject a rishta over a kundli dosh",
  "meet a rishta over chai and samosa and talk for three hours", "meet a rishta and both secretly want to say no", "meet a rishta and find out they went to the same school", "meet a rishta who is their ex's cousin", "meet a rishta and discuss only cricket",
  "go to a rishta meeting in a T-shirt", "go to a rishta meeting with sunglasses", "be asked if they can cook at a rishta meeting", "be asked about their salary in the first five minutes", "ask the rishta about their Netflix password first",
  "have a love marriage after a fake arranged one", "convince their parents for a love marriage with a PowerPoint", "bring their partner home disguised as a friend", "have their partner charm their dadi first", "have a secret engagement",
  "get married in three outfits in one day", "change five outfits at their own wedding", "spend more on the wedding than on a house", "have a destination wedding in Udaipur", "have a wedding with a theme",
  "have the longest baraat", "make the baraat dance for two hours before entering", "arrive at their wedding on a horse that runs away", "arrive at their wedding on a bike", "arrive at their wedding on a helicopter",
  "have a wedding with a thousand guests they do not know", "have a small wedding with only ten people", "have a court marriage and a big party later", "invite their ex to their wedding", "have their ex show up uninvited",
  "fight with the caterer at their own wedding", "fight with the photographer at their own wedding", "make the photographer take a thousand photos", "do a pre-wedding shoot in five locations", "do a pre-wedding shoot with a drone",
  "have the most dramatic pre-wedding video", "have a pre-wedding video that goes viral", "make a wedding hashtag", "have a wedding website", "have a wedding planner on speed dial",
  "cry at their haldi", "get haldi on their best friend on purpose", "have the darkest mehendi", "hide their partner's name in the mehendi", "take hours to find the name in the mehendi",
  "practise the sangeet dance for two months", "do a surprise dance for their partner", "make their parents dance at the sangeet", "make the in-laws dance at the sangeet", "do a Bollywood couple dance with their partner",
  "fight over the jaimala height", "have their friends lift them during the jaimala", "fall during the jaimala", "laugh during the pheras", "forget which way to walk in the pheras",
  "get the most shagun at their wedding", "count the shagun the same night", "give the shoe-stealing gang a big amount", "refuse to pay the shoe-stealing gang", "hide the shoes so well nobody finds them",
  "be the bride or groom who dances at their own vidaai", "be the bride who does not cry at the vidaai", "be the groom who cries at the vidaai", "take the whole family on the honeymoon", "go on a honeymoon to Manali",
  "be scolded by their mother-in-law on day one", "become their mother-in-law's favourite", "become their father-in-law's chess partner", "have their in-laws on their side in every fight", "call their in-laws 'mummy ji' and 'papa ji' from day one",
  "move in with their in-laws happily", "move out of their in-laws' house in a month", "have a fight about whose parents to visit at Diwali", "visit both families on the same day", "split festivals between families with a spreadsheet",
  "be asked 'good news?' at every family function", "answer 'good news' with 'I got a promotion'", "announce a pregnancy with a reel", "have a baby shower with a theme", "name their baby after a cricketer",
  "name their baby after a film character", "let their parents name their baby", "fight over the baby's name for a year", "have an astrologer pick the baby's name", "have a baby name that nobody can spell",
  "become the cousin everyone asks for wedding advice", "become a professional wedding planner", "start a wedding photography business", "become a wedding DJ", "become a sangeet choreographer",
  "get married twice to the same person for two families", "renew their vows in Bali", "have a silver jubilee party bigger than their wedding", "dance with their partner at their child's wedding", "cry at their child's wedding",
  "be the aunty who asks everyone when they are getting married", "be the uncle who gives speeches at every wedding", "be the relative who complains about the food at every wedding", "be the relative who arrives only for the food", "be the relative who leaves before the pheras",
]
