// Most Likely To, spicy: the friend group, loyalty and betrayal.
export default [
  "ditch the group for a new partner", "disappear when they get into a relationship", "come back to the group only after a breakup", "have a new best friend every year", "call everyone their best friend",
  "keep friends in separate groups so they never meet", "have a friend group nobody else knows about", "replace this friend group", "be replaced in this friend group", "be in a fight with someone in this room right now",
  "hold a grudge against someone in this room", "have talked about someone in this room behind their back", "have shared a secret of someone in this room", "be the glue of this group", "be the one who leaves the group first",
  "move abroad and forget everyone", "promise to stay in touch and never call", "call only when they need something", "call only on birthdays", "send a long message once a year",
  "plan every reunion", "never come to a reunion", "come to a reunion with a new personality", "come to a reunion with a new accent", "show up to a reunion rich",
  "be the friend who changed the most", "be the one whose parents everyone loves", "be the one everyone's parents warn about", "be the bad influence in the group", "be the responsible one who gets blamed anyway",
  "be the friend who always says 'I'm in' and never comes", "be the friend who brings a plus-one nobody invited", "be the one who finishes the food at gatherings", "be the one who washes the dishes after", "start drama in the group chat",
  "screenshot the group chat for another group", "get kicked out of the group chat", "make a new group without one person", "leave the group chat after an argument", "fight over who pays for dinner",
  "fight over the window seat", "fight over the front seat in the car", "call 'shotgun' a day in advance", "be stuck in the middle seat every time", "borrow a friend's car and return it empty",
  "borrow a friend's clothes and stretch them", "borrow a friend's charger and never return it", "borrow a friend's book and lose it", "borrow a friend's notes and score more", "copy a friend's assignment and change two words",
  "copy a friend's outfit to a party", "copy a friend's Instagram caption", "copy a friend's trip itinerary", "start dating a friend's crush", "steal a friend's date at a party",
  "tell a friend's crush about the crush", "set up a friend on a terrible date", "pick a terrible gift for a friend on purpose", "plan a prank that goes too far", "prank call a friend's parents",
  "change a friend's phone language to Chinese", "post on a friend's account while they are away", "change a friend's contact name to something rude", "put salt in a friend's tea", "hide a friend's shoes before they leave",
  "lock a friend out of the room", "eat a friend's birthday cake before they cut it", "forget a friend's birthday and blame the time zone", "throw a friend a surprise party they hate", "be the friend who cries at every farewell",
  "be the friend who gives the best hugs", "be the friend who gives the worst advice", "be the friend who gives brutally honest advice", "be the friend who says what everyone is thinking", "be the friend who agrees with everyone",
  "be the friend who has an opinion on everything", "be the friend who knows a guy for everything", "be the friend who knows the best doctor, lawyer and mechanic", "be the friend who always has painkillers", "be the friend with a first-aid kit in their bag",
  "be the friend who always has snacks", "be the friend who always has a pen", "be the friend who always has cash", "be the friend who never has cash", "be the friend who takes everyone's photos and is in none",
  "be the friend who ruins every group photo", "be the friend who closes their eyes in photos", "be the friend who is always looking at their phone in photos", "be the friend who knows their best angle", "drive the group to the airport at 4 am",
  "pick up a friend from a party at 3 am with no questions", "lie to a friend's parents to save them", "hide a friend from their angry parents", "take the blame for a friend", "keep a friend's secret even under pressure",
  "crack the moment someone asks about a secret", "defend a friend in public and scold them in private", "tell a friend their partner is bad news", "be right about a friend's partner", "be the friend everyone calls when something goes wrong",
  "be the friend who panics in an emergency", "be the calm one in a crisis", "make a crisis worse by trying to help", "fix a problem nobody knew existed", "plan the group trip and do all the work",
  "plan the group trip and cancel it", "make an Excel sheet for a group trip", "make everyone wake up at 5 am on a holiday", "sleep through the whole group trip", "get the best room on every trip",
  "take the bed and leave everyone the floor", "snore so loud nobody sleeps on the trip", "use all the hot water on a trip", "leave the hotel room in a mess", "forget something important on every trip",
  "pack for a week for a two-day trip", "pack nothing and borrow everything", "carry a full medicine box on every trip", "carry snacks for the whole group", "befriend locals on every trip",
  "befriend other tourists and leave the group", "fall in love on every trip", "come back from a trip with a new hobby", "come back from a trip with a new nickname", "be the one with the most stories about this group",
  "write a book about this friend group", "make a documentary about this friend group", "remember every inside joke from ten years ago", "forget every inside joke and ask for context", "give a speech at a friend's wedding that makes everyone cry",
  "give a speech at a friend's wedding that gets them in trouble", "reveal a secret in a wedding speech", "be the best man or maid of honour for five weddings", "be the friend who helps plan every wedding", "be godparent to all the group's kids",
  "be the cool uncle or aunt to everyone's kids", "babysit a friend's kids and lose one for a minute", "teach a friend's child a bad word", "spoil a friend's kids with sugar", "stay best friends with someone for fifty years",
  "stay friends with their school friends forever", "drift away from the group slowly", "be the one who brings the group back together", "be at the centre of every group photo in thirty years",
]
