// Most Likely To, spicy: parties, drinking and nights out.
export default [
  "say 'just one drink' and stay till 4 am", "dance on a table at a party", "lose their shoes at a party", "lose their phone at a club", "lose their friends at a club and find new ones",
  "cry in the bathroom at a party", "make a best friend in the club washroom", "give a speech at a party nobody asked for", "take over the music at someone else's party", "play only Punjabi songs at a party",
  "start a dance-off at a wedding", "do the naagin dance at every wedding", "be the last one on the dance floor", "be the first one asleep at the party", "fall asleep in the cab after a party",
  "throw up in a cab", "pay a cleaning fee to an Uber driver", "sing loudly in the cab at 3 am", "call their parents by mistake while drunk", "drunk-text their boss",
  "drunk-call their ex", "drunk-order food worth 3,000 rupees", "drunk-shop online and forget till the parcel comes", "wake up with a new tattoo", "wake up in a different city",
  "wake up at a friend's place with no memory", "wake up hugging the toilet", "pretend to be sober in front of their parents", "chew five mints before going home", "use perfume to hide the smell",
  "get caught coming home drunk by their dad", "get scolded by the building watchman", "climb the gate because the building was locked", "sleep in the car outside their house", "get locked out of their own house at night",
  "host a house party when their parents are away", "clean the house perfectly before parents return", "forget one empty bottle and get caught", "blame a friend for the bottles", "say the alcohol was for 'guests'",
  "mix five different drinks", "make the worst cocktail at a house party", "become a bartender for one night", "order the most expensive drink to show off", "drink only Coke at every party and still dance the most",
  "act drunk without drinking anything", "get drunk on one beer", "hold their drink the best", "be the designated driver every time", "be the friend who takes care of everyone at the end of the night",
  "be the friend who needs taking care of", "start a fight at a party", "stop a fight at a party", "flirt with the DJ", "request the same song five times",
  "get thrown out of a club", "get into a club with a fake name on the list", "talk their way into a VIP area", "make friends with the bouncer", "get stamped and lose the stamp",
  "go clubbing in chappals", "wear sunglasses inside a club", "take a hundred selfies at a party", "post a party story and forget it is visible to their parents", "get tagged in a party photo by their aunt",
  "post party photos from a fake account", "throw a theme party", "come in costume to a party that was not a theme party", "turn every birthday into a three-day event", "have the most surprise parties thrown for them",
  "ruin a surprise party by arriving early", "plan a surprise party and tell the person by mistake", "cry at their own surprise party", "forget their own birthday party", "get cake smashed on their face every birthday",
  "get bumps on their birthday and limp for a week", "play truth or dare and pick dare every time", "pick truth and lie", "take a dare to call their crush", "take a dare to text their boss",
  "take a dare to dance in public", "do a shot of hot sauce on a dare", "eat something gross on a dare", "go swimming at night on a dare", "jump into a pool with clothes on",
  "jump into a pool with their phone in their pocket", "get pushed into the pool at a party", "push someone into the pool", "start a water balloon fight indoors", "play Holi with paint that never comes off",
  "drink bhang at Holi and laugh for six hours", "cry from laughing at Holi", "dance on the road during Ganpati", "take over a wedding baraat as a stranger", "gatecrash a wedding for food",
  "gatecrash a wedding and get caught", "dance in a stranger's baraat on the road", "give a shagun envelope with ten rupees", "steal the groom's shoes and bargain hard", "make the most money from joota chupai",
  "be the loudest at a sangeet", "choreograph the whole family's sangeet", "forget the steps at the sangeet", "sing at the sangeet and clear the room", "dance with the bride's grandmother",
  "end up in the bride's family group chat", "make a speech at a wedding and roast the groom", "make the groom cry with a speech", "drink with the uncles at a wedding", "out-drink the uncles at a wedding",
  "get advice from a drunk uncle", "get a marriage proposal at a wedding", "fall asleep on the wedding chairs", "eat four rounds at a wedding buffet", "take wedding sweets home in their bag",
  "go to three weddings in one night", "attend a wedding without knowing the couple", "wear the same outfit to every wedding", "show up overdressed to a house party", "show up in pyjamas to a fancy party",
  "leave a party without saying bye", "say bye for forty-five minutes", "hug everyone twice before leaving", "stay over at the host's house after every party", "bring nothing to a potluck",
  "bring store-bought food and say they made it", "eat all the snacks before guests arrive", "cook Maggi at 3 am for everyone", "order biryani after every party", "find the best late-night food spot",
  "go for a 4 am drive to Marine Drive", "go to a dhaba at 3 am", "watch the sunrise after an all-nighter", "go straight to office from a party", "go to an exam straight from a party",
  "start a party in a hostel room", "get the hostel warden to join the party", "get caught by the warden with bottles", "throw a party on a train", "turn a long road trip into a party",
  "play antakshari loudly at 2 am", "argue about song lyrics at 2 am", "start singing old Hindi songs when drunk", "start speaking English with an accent when drunk", "start speaking their mother tongue when drunk",
  "get emotional and say 'I love you guys' at every party", "call everyone 'bhai' after two drinks", "tell everyone their secrets when drunk", "tell their deepest secret at a party and forget", "remember everything everyone said when drunk",
  "record videos of drunk friends for blackmail", "post a drunk friend's video in the group", "make a drunk friend a meme", "have the most embarrassing party video", "win every drinking game",
  "lose every drinking game", "invent a drinking game", "cheat at drinking games", "play never-have-I-ever and drink at every one", "lie during never-have-I-ever",
  "learn shocking things about friends in never-have-I-ever", "end a game of never-have-I-ever in a fight", "turn a game night into a party", "turn a party into a deep conversation", "have a deep talk about life at 3 am on the terrace",
  "cry about their career at a party", "decide to quit their job at a party", "plan a startup at a party", "plan a Goa trip at a party that never happens", "plan a Goa trip that actually happens",
  "go to Goa and stay in the room the whole time", "go to Goa and never sleep", "lose their wallet in Goa", "come back from Goa with a new friend group", "rent a scooter in Goa and crash it",
  "have a beach party and get sunburnt", "party in Kasol for a week", "go to a hill station and party in the hotel room", "go to a music festival and not see a single band", "lose their friends at a concert",
  "cry at a concert", "get on someone's shoulders at a concert", "get on the big screen at a concert", "sneak into a concert without a ticket", "buy a concert ticket for 20,000 rupees",
  "throw the best house party in the group", "have neighbours complain about every party", "have the police come to their party", "talk the police into letting the party go on", "become friends with the neighbours who complained",
  "invite the whole building to a party", "throw a party for their dog", "celebrate a half birthday", "celebrate the promotion they did not get", "throw a breakup party",
  "throw a divorce party", "throw a party when they quit their job", "throw a party for passing an exam with grace marks", "throw a party for no reason on a Tuesday", "bring a speaker everywhere",
  "start dancing as soon as music plays anywhere", "dance at a funeral by accident", "dance in the office lift", "dance in a mall when their song comes on", "have a signature dance move",
  "do the same dance move to every song", "do the bhangra to a slow song", "slow dance to a fast song", "challenge strangers to dance battles", "teach strangers to dance at a wedding",
  "learn a full dance from a reel for one party", "perform a TikTok dance at a family function", "make the aunties dance", "make the uncles do the twist", "be the karaoke star",
  "hog the karaoke mic", "sing a romantic song to their best friend at karaoke", "cry singing a sad song at karaoke", "sing in a fake accent at karaoke", "pick the hardest song at karaoke and fail",
  "start an open mic set at a party", "do stand-up comedy for friends who did not ask", "roast everyone at the party", "get roasted the most at every party", "laugh the loudest at their own jokes",
  "laugh so hard they snort", "spill a drink on the host", "break something at a party and hide it", "break the host's glass and replace it secretly", "set off the fire alarm at a party",
  "burn the food at a barbecue", "become the barbecue master for the night", "drink straight from the bottle", "pour drinks too strong for everyone", "measure every drink with a measuring cup",
  "invent a new cocktail and name it after themselves", "start a party tradition", "keep a party diary", "remember every party from college", "still go to parties like they are 20",
  "leave parties at 10 pm because they are tired", "fall asleep sitting up at a party", "be the 'one more round' person", "be the 'let's go home' person", "convince everyone to stay out longer",
  "convince everyone to go to a second location", "find an after-party at 3 am", "end the night at a stranger's after-party", "make five new friends in one night and never see them again",
]
