// Most Likely To, spicy: phones, social media, texting and the internet.
export default [
  "check their phone within ten seconds of waking up", "use their phone in the shower", "drop their phone in the toilet", "have 10 hours of screen time a day", "lie about their screen time",
  "delete Instagram for a week and come back in a day", "announce a social media break and post the next day", "post a story and check who saw it every five minutes", "post a story just for one person", "hide their story from their family",
  "hide their story from their boss", "forget to hide a story from their boss", "post a 'sick day' story from the beach", "get caught skipping work because of a story", "post a cryptic quote after every fight",
  "post a sad song to make someone ask what happened", "post a thirst trap and say it was random", "post a photo with an ex cropped out", "post a photo where only they look good", "post a group photo where everyone else has their eyes closed",
  "untag themselves from every bad photo", "beg to delete a photo before it goes up", "approve tags before anyone sees", "have a Finsta with ten followers", "follow celebrities and comment on every post",
  "argue with a celebrity in the comments", "get replied to by a celebrity", "get blocked by a celebrity", "get a blue tick someday", "become an influencer with 500 followers",
  "call themselves a content creator", "make a reel about their breakfast", "make a 'day in my life' video of a boring day", "do a 'get ready with me' for a trip to the market", "start a podcast with their best friend",
  "start a YouTube channel and post one video", "have a vlog that only their mom watches", "make a reel at every tourist spot", "make everyone redo a group photo ten times", "spend a trip filming instead of enjoying",
  "pick the hotel for the Instagram value", "order food for the photo and not eat it", "take a photo of every meal", "make a carousel of a normal weekend", "write a caption longer than the post",
  "use twenty hashtags", "use hashtags in WhatsApp", "write 'link in bio' with nothing in the bio", "add a song to every story", "watch reels until 4 am",
  "send fifty reels a day to one friend", "react to every reel with laughing emojis without watching", "say 'I saw this and thought of you' every day", "forward a reel to the person in the reel", "send memes in the family group by mistake",
  "send a personal message in the office group", "send a screenshot of a chat to the person it was about", "send a voice note complaining about someone to that person", "send 'I love you' to their boss instead of their partner", "send a 'call me' message and not pick up",
  "call without texting first", "text 'can I call?' and then call before an answer", "never pick up calls but reply on WhatsApp instantly", "pick up every call even in a movie", "keep their phone on silent forever",
  "keep their phone on full volume in a meeting", "have their ringtone go off during a funeral", "have their ringtone go off during an exam", "have an alarm go off in a quiet library", "have the most notifications",
  "have 99+ unread chats", "have every group muted", "be in 80 WhatsApp groups", "be the admin of 20 groups", "remove people from groups for sending good morning messages",
  "create a group for every small plan", "create a group without the person being discussed", "accidentally add the person to the group about them", "leave a group and get re-added by their mom", "have the longest 'about' on WhatsApp",
  "still have 'Hey there! I am using WhatsApp'", "change their DP every day", "use a cartoon as their DP for years", "use a photo with sunglasses as their DP forever", "hide their last seen and check everyone's",
  "turn off blue ticks and get angry at others", "keep online status hidden but always be online", "come online and go offline when their crush is online", "type and stop typing ten times", "write a message and delete it before sending",
  "take an hour to write a two-line text", "proofread a text five times", "send a text with a typo to their crush", "autocorrect something embarrassing to their boss", "use voice typing and send nonsense",
  "use 'k' as a full reply", "use 'hmm' to end conversations", "reply only with stickers", "have a sticker for every situation", "make stickers of their friends' faces",
  "send a sticker of a friend in the family group", "use the 'seen' feature as a weapon", "screenshot a story and get caught", "accidentally video call someone", "accidentally video call their ex",
  "accidentally call someone at 3 am", "pocket-dial their boss", "accidentally like a stranger's post from 2015", "accidentally follow someone while stalking", "unfollow a friend after a fight",
  "block a friend for one day", "mute a friend's stories", "know every friend's screen time", "check their partner's followers list", "get into an Instagram fight over cricket",
  "get into a Twitter fight with a stranger", "get trolled online", "create a meme that goes viral", "post an unpopular opinion and get destroyed", "post a political opinion in the family group",
  "fight with an uncle in the family group", "write long essays in the comments", "comment 'first' on YouTube", "leave a one-star review over a small thing", "write a five-star review to get free dessert",
  "write a review of every Zomato order", "rate their Uber driver five stars out of fear", "argue with customer care on Twitter", "get a refund just by complaining online", "order from five apps and compare",
  "check delivery tracking every minute", "chat with the delivery person like a friend", "order online and not be home", "buy something from an Instagram ad", "buy a useless gadget at 2 am",
  "add to cart and never buy", "have 300 items in their wishlist", "wait for a sale to buy something they do not need", "have every app's premium plan", "share one Netflix with ten people",
  "use someone else's Spotify for years", "know everyone's passwords", "use the same password everywhere", "forget their password every time", "lock themselves out of their own phone",
  "have the most complicated phone pattern", "let their friend unlock their phone with their face", "keep a password on their gallery", "have a hidden folder in their gallery", "have 30,000 photos in their gallery",
  "have 500 screenshots they never look at", "keep every meme in their gallery", "fill their phone storage every week", "delete photos to install one app", "pay for cloud storage for memes",
  "have a phone older than their younger cousin", "always have the latest iPhone", "upgrade their phone every year", "use a phone with a cracked camera", "carry two phones",
  "have a tablet they never use", "have a smartwatch that is always dead", "use their phone as a mirror", "take selfies in every lift", "take mirror selfies at the gym",
  "take a selfie at a funeral", "take a selfie with a celebrity's lookalike", "use a dating app abroad to find Indians", "match with everyone and talk to no one", "have the funniest dating profile",
  "have a dating profile written by friends", "screenshot dating profiles to show the group", "use AI for everything including texts to their mom", "ask AI to settle an argument", "trust AI over their doctor",
  "have AI write their wedding speech", "fall in love with an AI chatbot", "be addicted to a mobile game", "spend money on mobile game skins", "play mobile games in meetings",
  "stay up all night for a game event", "get angry at a ten-year-old in an online game", "have the most online friends they never met", "meet an online friend in real life", "have an online best friend in another country",
  "be in a Discord server at 3 am", "be the mod of an online community", "go viral on Reddit", "read Reddit stories instead of sleeping", "share a Reddit story as their own",
  "lurk on every forum and never post", "have a secret Twitter account for rants", "post a voice note on their story", "post their exam result on Instagram", "post their salary slip",
  "post their new car with a long thank-you caption", "post their engagement with a ring close-up", "post a cryptic 'some people' story", "post a 'thank you for nothing' story", "post an 'I am done' story and stay",
  "post a 'miss you' story without saying who", "post a photo of their hand holding a hand",
]
