// Most Likely To, spicy: roasts and embarrassing moments. Never about bodies, religion or caste.
export default [
  "laugh at their own joke before finishing it", "tell the same story at every party", "start every story with 'so basically'", "take ten minutes to tell a two-minute story", "forget the ending of their own joke",
  "explain a joke until it is not funny", "say 'no offence' and then offend everyone", "say 'I am not like other people'", "say 'trust me' right before a bad idea", "give advice they never follow",
  "act like an expert after watching one YouTube video", "argue with Google Maps", "argue with a waiter about the menu", "argue with a referee on TV", "argue in a comment section for hours",
  "lose an argument and keep going", "win an argument and bring it up for years", "correct everyone's grammar in the group chat", "send a voice note that is five minutes long", "send twenty messages instead of one",
  "leave people on read for days", "see a message, forget it, and reply a month later", "reply to a group message three days late", "type 'haha' with a straight face", "use too many emojis in a work email",
  "use 'Dear Sir' in a WhatsApp message", "send 'good morning' flowers to the group", "forward fake news to the family group", "believe every forward on WhatsApp", "fall for a 'you won a lottery' message",
  "click on a scam link", "give their OTP to a stranger", "lose money to an online scam and blame the bank", "buy a fake branded item and wear it proudly", "bargain at a mall",
  "bargain for ten rupees and feel proud", "pay full price at a street market", "get ripped off by an auto driver", "pretend to know the way and get everyone lost", "show up an hour late and say 'five minutes'",
  "say 'on my way' while still in bed", "say 'almost there' from home", "be the reason the group is late", "leave home last and arrive first somehow", "forget a friend's name in front of them",
  "call a friend by their sibling's name", "wave back at someone who was waving at someone else", "say 'you too' when the waiter says enjoy your food", "hold the door for someone very far away", "fall off a chair while laughing",
  "snore in a movie theatre", "fall asleep at a concert", "talk in their sleep about their crush", "sleepwalk into the kitchen", "wake up and not know what day it is",
  "take a nap and wake up the next morning", "miss an alarm because they set it for PM", "set ten alarms and sleep through all", "come to class in their slippers", "wear their shirt inside out all day",
  "wear two different shoes to work", "go out with toothpaste on their face", "forget to remove the price tag from new clothes", "wear the same jacket in every photo", "take forty photos to post one",
  "edit a photo so much they look different", "use the same filter on every photo", "post a selfie with a quote that makes no sense", "post a gym selfie after one workout", "post their food before eating it",
  "make everyone wait for a photo before eating", "post 'blessed' captions all the time", "write captions in five languages", "post a sunset with a deep quote", "go live on Instagram with three viewers",
  "beg friends to like their reels", "buy followers", "dance in a reel in a public place", "film a reel in a temple queue", "make a reel at a funeral by mistake",
  "have their reel go viral for the wrong reason", "get recognised from an embarrassing video", "call a teacher 'mummy' by mistake", "call their boss 'bro'", "reply-all to a company email",
  "share their screen with something embarrassing open", "forget to mute on a call and say something rude", "be on camera without knowing on a video call", "join a work call from the toilet", "join a call in their pyjamas and stand up by mistake",
  "show their messy room on a video call", "have a cat walk across the keyboard during a meeting", "cry at an advertisement", "cry at a cartoon", "cry at a wedding of someone they barely know",
  "cry when their phone breaks", "cry over a lost cricket match", "throw a tantrum when they are hungry", "get angry at a video game and throw the controller", "rage quit a board game",
  "flip the Monopoly board", "cheat at Ludo and deny it", "cheat at UNO and get caught", "be a sore loser", "be a sore winner",
  "celebrate a win like they won the World Cup", "keep score in a friendly game", "be afraid of a lizard", "scream at a cockroach", "run away from a dog that is wagging its tail",
  "be scared of horror films but watch them anyway", "sleep with the lights on after a horror film", "believe in ghosts the most", "check under the bed every night", "get scared of their own reflection",
  "pretend not to be scared and scream the loudest", "hide behind a friend at a haunted house", "get lost in a mall", "get lost in their own building", "forget where they parked",
  "lock their keys inside the car", "look for their phone while talking on it", "look for their glasses while wearing them", "leave the gas on", "forget their wallet when it is their treat",
  "always 'forget' their wallet", "borrow money and forget", "remember every rupee others owe them", "split the bill to the last paisa", "ask for the bill to be split by item",
  "order the cheapest thing and split equally anyway", "order the most expensive thing and split equally", "take food from everyone's plate", "say 'I'm not hungry' and eat half your food", "eat the last piece without asking",
  "hide snacks from roommates", "label their food in the fridge", "drink someone else's milk from the fridge", "use a roommate's shampoo", "borrow clothes and never return them",
  "wear a friend's clothes on a date", "take the longest showers", "have a full concert in the bathroom", "be scared of the dark bathroom at night", "fall asleep in the bathroom",
  "spend thirty minutes in the bathroom with their phone", "use a friend's toothbrush by mistake", "forget to flush at someone's house", "clog the toilet at a party", "leave the bathroom without a word after clogging it",
  "fart in the lift and blame someone else", "fart in a quiet room and laugh", "burp at the dinner table", "snore so loud the neighbours hear", "talk loudly on the phone in public",
  "play videos without earphones in the train", "watch reels at full volume in a waiting room", "call people on speaker in public", "have the weirdest ringtone", "have their mom's photo as their wallpaper",
  "have a selfie as their wallpaper", "name their wifi something rude", "name their phone after themselves", "have 20,000 unread emails", "have 300 tabs open",
  "never close any app", "have one percent battery all the time", "ask everyone for a charger", "carry three power banks", "have the cracked phone screen for years",
  "use a phone with a broken back", "drop their phone on their face while lying down", "take a selfie and accidentally record a video", "send a screenshot of the chat to the same person", "complain about the weather in every season",
  "complain about being busy while doing nothing", "say 'I am on a diet' while eating pizza", "start a diet every Monday", "buy gym clothes and never go", "pay for a gym membership and never use it",
  "go to the gym only to take selfies", "talk about their workout more than they work out", "do one push-up and post it", "brag about steps on their smartwatch", "fake a cough to get out of plans",
  "cancel plans at the last minute every time", "make plans and forget", "be the one who makes plans and gets left out", "be invited only because they have a car", "be the friend with the car who does all the driving",
  "be the worst driver in the group", "parallel park in ten moves", "honk at a red light", "talk to other drivers through the window", "fail their driving test twice",
  "get a challan for not wearing a seatbelt", "get a challan and argue with the cop", "get caught by a speed camera at 3 am", "lose their licence and use a photo of it", "sing along to songs and get all the words wrong",
  "make up lyrics confidently", "hum the same song for a week", "get a jingle stuck in everyone's head", "play the same song on repeat for a month", "think they can sing",
  "think they can dance", "think they can cook", "think they are funny", "think they are always right", "say 'I told you so' the most",
  "never admit they are wrong", "apologise for everything", "say sorry to a chair after bumping into it", "thank the ATM", "talk to themselves in the mirror",
  "practise arguments in the shower", "rehearse a phone call before making it", "hang up before the call is answered", "pretend to be on a call to avoid someone", "hide from a neighbour in their own building",
  "take the stairs to avoid small talk in the lift", "cross the road to avoid an old classmate", "pretend not to see someone they know", "be terrible at keeping a straight face", "laugh at a serious moment",
  "laugh at a funeral", "giggle during a wedding pheras", "laugh during a work presentation", "have the loudest laugh in the room", "laugh like a villain",
  "have a laugh that makes everyone else laugh", "cry and laugh at the same time", "get the hiccups when they laugh", "get a song request wrong as a DJ", "mispronounce a fancy dish at a restaurant",
  "order 'one bruschetta' with a hard 'ch'", "ask for ketchup at a fine dining restaurant", "eat the decorative garnish", "drink from the finger bowl", "use the wrong fork and not care",
  "put chilli on fruit", "eat pizza with a fork and knife", "get food on their shirt every meal", "drop food on the floor and eat it anyway", "eat food straight from the pan",
  "eat cereal for dinner", "eat cake for breakfast", "lie about their marks to their parents", "forge a parent's signature", "bunk class and get caught at the cinema",
  "get caught copying in an exam", "write answers on their hand", "go blank in an exam they studied for", "study the wrong chapter for an exam", "sleep through an exam",
  "come to an exam on the wrong day", "argue with the teacher for half a mark", "be the teacher's pet", "be the class clown", "be sent out of the class the most",
  "make the whole class laugh at the wrong time", "get the whole class punished",
]
