// Most Likely To, spicy: internet slang, trends and very online behaviour.
export default [
  "say 'no cap' in a serious meeting", "say 'it's giving' about everything", "call everything 'mid'", "say 'slay' to their grandmother", "use 'bestie' for people they just met",
  "say 'I'm literally dead' about a mild joke", "say 'main character energy' about themselves", "say 'touch grass' in every argument", "say 'rent free' about their ex", "say 'delulu is the solulu'",
  "call their partner 'my person'", "call every bad day 'not the vibe'", "rate everything as 'vibes'", "describe their mood with a song", "have a 'core' aesthetic for every season",
  "try every viral trend", "do every viral dance", "try every viral recipe", "buy every viral product", "fall for every viral hack",
  "make a 'get ready with me' for a dentist visit", "make a 'what I eat in a day' with Maggi", "film themselves crying for a reel", "post a photo dump of a normal week", "post a blurry photo dump on purpose",
  "have a different aesthetic for every account", "have a Pinterest board for their whole life", "plan their life on a vision board", "manifest a new phone", "manifest their crush texting back",
  "believe in manifesting more than working", "say 'the universe will provide'", "say 'it's Mercury in retrograde' for every problem", "pick friends by their zodiac sign", "refuse to date a Gemini",
  "ask someone's MBTI type before their name", "blame being an introvert for skipping plans", "call themselves an ambivert to get the best of both", "know their love language", "say 'my love language is food'",
  "take every online personality quiz", "share every personality quiz result", "know which Hogwarts house they are", "know which Friends character they are", "argue about which Friends character they are",
  "send screenshots of their screen time as a flex", "flex their Spotify Wrapped", "flex their Duolingo streak", "flex their step count", "flex their sleep score",
  "keep a Duolingo streak and learn nothing", "panic when they break a streak", "keep a Snapchat streak with someone they never talk to", "have a hundred Snapchat streaks", "send streak photos of the ceiling",
  "go viral for a bad take", "get ratioed on Twitter", "start a trend by accident", "have a comment with more likes than the post", "argue with a bot online",
  "spend hours making the perfect Instagram grid", "archive old posts to look cooler", "delete posts with few likes", "post at the 'best time' for likes", "post and then go offline to wait",
  "use their whole salary on a concert ticket", "fly to another country for a concert", "camp outside a stadium for a concert", "cry when their favourite band breaks up", "know every member of a K-pop band",
  "have an ultimate bias in a K-pop group", "learn Korean from K-dramas", "use Korean words in Hindi", "make Korean ramen every night", "cry over a K-drama ending",
  "have a fan account", "run a fan page with a thousand followers", "get noticed by a celebrity on Instagram", "make a fan edit that goes viral", "know every celebrity's dating history",
  "know every influencer drama", "watch drama videos about people they do not know", "pick sides in influencer fights", "unfollow an influencer after a scandal", "follow an influencer just to hate them",
  "buy something because an influencer said so", "use an influencer discount code", "become an influencer with a discount code", "get free products for posting", "review free products honestly",
  "say 'link in bio' in real life", "talk in hashtags", "speak in memes", "reply to everything with a GIF", "have a meme for every situation",
  "communicate with their best friend only through reels", "send a reel that ends a friendship", "send a reel to say sorry", "send a reel instead of a birthday wish", "send a reel and wait for a reaction",
  "make a voice note longer than a podcast", "listen to voice notes at 2x speed", "never listen to voice notes", "reply to a voice note with a voice note", "fall asleep listening to a friend's voice note",
]
