// Most Likely To, spicy: everything else that starts arguments in a friend group.
export default [
  "be the most dramatic person in this room", "turn a small problem into a big fight", "cry to win an argument", "storm out and come back for their phone", "slam a door and then hold it for someone",
  "send an angry text and then 'sorry, wrong chat'", "say 'I'm fine' when they are clearly not", "say 'whatever' and mean war", "give the silent treatment for a week", "forgive everyone after one samosa",
  "be the most stubborn person in the group", "refuse to say sorry for a decade", "be the first to apologise always", "argue just for fun", "play devil's advocate in every conversation",
  "change sides in an argument halfway", "win an argument with fake facts", "make up statistics confidently", "say 'research shows' without any research", "quote a WhatsApp forward as proof",
  "say 'I am not jealous' while clearly jealous", "get jealous of a friend's new friend", "get jealous of a friend's promotion", "get jealous of a friend's holiday photos", "be secretly happy when a rival fails",
  "be the most competitive at a family game", "be the most competitive at a kids' game", "cheat at a game against a child", "let a child win and then brag", "throw a game to make someone happy",
  "be the person who knows everyone's zodiac sign", "blame everything on their zodiac sign", "blame Mercury in retrograde", "believe in every superstition", "not leave the house if a cat crosses the road",
  "carry a lemon and chillies for luck", "wear a lucky shirt for every match", "refuse to wash their lucky jersey", "sit in the same spot every match for luck", "blame a loss on someone moving from their seat",
  "be the loudest cricket fan in the room", "cry when India loses a match", "throw the remote at the TV during a match", "know every cricket stat ever", "call a cricket match like a commentator",
  "start a fight about the best cricketer ever", "start a fight about the best actor ever", "start a fight about biryani", "start a fight about which city is best", "start a fight about pineapple on pizza",
  "start a fight about the AC temperature", "start a fight about whether a hot dog is a sandwich", "start a fight about whose turn it is to pay", "start a fight about the TV show ending", "start a fight about the rules of a board game",
  "make up rules in the middle of a game", "change the rules when they are losing", "quit the game when losing", "accuse everyone of cheating", "be caught cheating and say it was a strategy",
  "be the reason the group was thrown out of a restaurant", "be the reason the group had to leave a wedding early", "be the reason the group missed a train", "be the reason the group got lost", "be the reason the group laughs at every trip",
  "be the most likely to start a food fight", "throw cake at a party", "hide in a cupboard during hide-and-seek for two hours", "win hide-and-seek because everyone forgot them", "fall asleep during hide-and-seek",
  "say something wildly inappropriate at dinner", "make an awkward silence worse with a joke", "laugh when someone falls", "help someone up while laughing", "fall while laughing at someone falling",
  "be the one who makes the worst puns", "be the one who groans loudest at puns", "explain the plot of every film before it starts", "spoil a film's ending", "spoil a series finale on purpose",
  "talk through an entire film", "ask 'who is that?' every five minutes in a film", "fall asleep in the first ten minutes of a film", "cry at the sad scene and deny it", "watch the ending first",
  "have the strangest food combination", "eat Maggi with ketchup and curd", "put sugar on their rice", "eat chips with chopsticks", "dip biscuits in chai for too long",
  "make the best chai in the group", "make the worst chai in the group", "set off the smoke alarm making toast", "call their mom for every recipe", "order food every single day",
  "know every delivery person by name", "be the delivery app's top customer", "get a thank-you card from a restaurant", "have their own table at a restaurant", "be a regular at a bar",
  "have a bartender who knows their drink", "be a regular at a chai stall for ten years", "be on first-name terms with the security guard", "know the life story of their auto driver", "get a discount everywhere because of their smile",
  "get a discount because they bargained for an hour", "never pay full price for anything", "know every sale date by heart", "wait for Big Billion Days to buy anything",
]
