// Most Likely To, spicy: what they would do for money, on a bet, or just because.
export default [
  "shave their eyebrows for 10,000 rupees", "eat a raw onion like an apple for 5,000 rupees", "wear a wedding outfit to the office for a bet", "sing in the metro for a bet", "propose to a stranger for a bet",
  "dance at a traffic signal for 1,000 rupees", "call their boss and sing for 50,000 rupees", "text their ex 'I miss you' for 20,000 rupees", "post an embarrassing photo for a week for money", "give their phone to the group for an hour for money",
  "let the group post one story from their account", "let their mom read their chats for 1 lakh", "go a month without their phone for 1 lakh", "go a week without coffee for 5,000 rupees", "eat only khichdi for a month for money",
  "live in a tent for a month for money", "spend a night alone in a forest for money", "do a stand-up set on a dare", "go on a date chosen by the group", "let the group pick their haircut",
  "let the group choose their outfit for a week", "let the group write their dating profile", "let the group reply to their crush", "let the group plan their whole holiday", "wear a saree or a sherwani to the gym",
  "jump into the Arabian Sea in winter", "take a cold bucket bath in Shimla in January", "eat ten golgappas in one breath", "eat the spiciest chicken wings and not cry", "drink a glass of pickle oil",
  "eat a spoonful of ghee straight", "eat a whole jar of Nutella in one sitting", "finish a family pizza alone", "win a samosa-eating contest", "drink five cans of energy drink",
  "stay awake for 48 hours", "walk 30 kilometres in one day", "cycle to another city", "climb a hill at midnight", "swim across a lake",
  "say yes to everything for a day", "say no to everything for a day", "speak only in Hindi film dialogues for a day", "speak only in rhymes for an hour", "talk like a news anchor for a whole dinner",
  "act like a tourist in their own city", "pretend to be a famous singer in a mall", "sign autographs as a fake celebrity", "take on a fake accent for a whole party", "pretend to be married to a friend for a day",
  "go to a job interview as a joke", "apply for a reality show as a joke and get in", "audition for a film as a dare", "enter a beauty pageant as a joke", "run a marathon in a costume",
  "dress as a superhero to a wedding", "wear pyjamas to a fancy restaurant", "wear sunglasses everywhere for a week", "wear a cape to class", "wear the same outfit for a week on a bet",
  "keep a straight face through any joke", "laugh at nothing for a full minute in public", "cry on demand", "start a fake argument in public as a prank", "fake a proposal in a mall as a prank",
  "prank call a pizza place", "order a pizza to a friend's office as a prank", "fill a friend's car with balloons", "cover a friend's room in sticky notes", "swap a friend's sugar for salt",
  "hide in a friend's cupboard to scare them", "dress as a ghost to scare the hostel", "set ten alarms in a friend's room", "change every clock in the house", "rename the wifi to something scary for the neighbours",
  "take a dare and back out at the last second", "take every dare and never back out", "make up a dare nobody can do", "turn a dare into a business idea", "make money from a dare video",
  "get famous from a dare", "go viral eating something terrible", "start a challenge that everyone copies", "invent a new party game", "win a bet they had no chance of winning",
  "bet on something stupid and win big", "bet their bike and lose it", "bet their phone and keep it somehow", "bet a month of chores and lose", "bet on a cricket match against their own team",
  "agree to a crazy bet while drunk and actually do it", "make a bet and forget about it", "be reminded of a bet ten years later", "keep a list of bets they have won", "never pay up after losing a bet",
  "make every argument into a bet", "bet on how long a friend's relationship will last", "bet on who will get married first", "bet on who will cry at a farewell", "bet on what the boss will say in a meeting",
  "go skydiving for a free ticket", "sleep in an airport for a cheaper flight", "take a 30-hour bus ride to save money", "stand in line overnight for a phone", "stand in line for hours for a free T-shirt",
  "do something embarrassing for free food", "sing at a restaurant for a free dessert", "dance for a discount", "act sick to skip a queue", "pretend to have a sprained ankle for a seat",
  "pretend to be a doctor to get in somewhere", "pretend to be a journalist to get a free pass", "say they are the bride's cousin to eat at a wedding", "join a tour group they did not pay for", "attend a free seminar just for lunch",
  "fill out a survey for a free coffee", "sign up for a credit card for a free bag", "test-drive a car they cannot afford", "try on clothes they will never buy", "go to open houses for the snacks",
]
