// Most Likely To, spicy: office life, bosses, colleagues and money.
export default [
  "date someone from their office and hide it", "have an office crush on someone married", "flirt during a performance review", "flirt with HR to get leave approved", "get a promotion by being the boss's favourite",
  "be the office gossip", "know everyone's salary in the office", "leak the salary sheet by mistake", "complain about the boss in a group the boss is in", "send a rant about work to their manager",
  "say 'per my last email' with anger", "write passive-aggressive emails", "CC the boss to win an argument", "reply-all with a joke", "accidentally forward a private email to the whole company",
  "fake being busy by typing loudly", "keep an Excel sheet open to look busy", "move the mouse to stay 'green' on Teams", "attend a meeting from bed", "attend a meeting while driving",
  "fall asleep on a work call with the camera on", "join a meeting and forget to turn off the filter", "join a call with a potato filter", "be the reason a meeting overruns", "schedule a meeting that could have been an email",
  "say 'let's take this offline' to end every discussion", "use 'synergy' in a sentence", "say 'circle back' ten times a day", "speak only in corporate jargon", "make a PowerPoint for a friend's birthday plan",
  "steal the office stationery", "take office snacks home", "eat a colleague's lunch from the fridge", "microwave fish in the office", "take the last coffee and not make more",
  "take two-hour lunch breaks", "go for a 'chai break' every hour", "smoke-break gossip with the security guard", "know the canteen staff better than their team", "get free food from every office event",
  "attend every office party only for the drinks", "get drunk at the office party", "dance with the CEO at the office party", "say something wild to their boss at the office party", "be the main topic after the office party",
  "skip the office party and still be the main topic", "hook up at an offsite", "start an office romance on a team outing", "be caught with a colleague in a conference room", "use the conference room to nap",
  "lie about a dead grandparent to get leave", "take sick leave and post from a beach", "take leave for a cricket match", "call in sick on the day after Diwali", "take leave on their birthday every year",
  "be on 'work from home' while on holiday", "work from a mountain cafe and say the wifi is bad", "pretend their internet is down to skip a call", "use 'my power went out' as an excuse", "have a different excuse every Monday",
  "quit dramatically", "rage-quit in an email", "come back to the same company after quitting", "get fired and celebrate", "be the boss's spy",
  "pretend to work late to impress the boss", "leave at exactly 6 every day", "never take a single leave", "lose all their leaves because they never take them", "work on a Sunday and post about it on LinkedIn",
  "post humble-brags on LinkedIn", "write a LinkedIn post about a sad story and a sales lesson", "write 'I am thrilled to announce' for a tiny thing", "share an inspiring post about their maid", "make a LinkedIn post about this game",
  "lie in a job interview and get the job", "say 'my weakness is that I work too hard'", "ask for a salary double what they deserve", "negotiate a salary and win big", "accept the first offer without asking",
  "take a job just for the free food", "take a job just for the office location", "take a job because the HR person was cute", "change jobs every six months", "stay at one company for 25 years",
  "become the boss of their old boss", "become a CEO by forty", "start a company and become a unicorn", "start a company and shut it in six months", "start a company with their friends and fight",
  "get rich from stocks and act humble", "get rich and become unbearable", "lose all their savings and act fine", "brag about crypto profits and hide losses", "invest in their friend's startup and lose it",
  "be asked for money by everyone after a promotion", "pay for everyone's dinner after a salary hike", "spend their whole bonus in one weekend", "save every rupee of their bonus", "buy a house before thirty",
  "take a loan for a wedding", "take a loan for an iPhone", "pay EMIs for five things at once", "have more EMIs than income", "use Buy Now Pay Later for groceries",
  "borrow money for a trip and post it everywhere", "never return borrowed money", "keep a ledger of who owes what", "send payment reminders with a smile emoji", "split a ten-rupee chai on UPI",
  "request money for a group gift and add a fee", "manage the group's money and lose track", "be trusted with the trip budget and overspend", "find the cheapest flights for everyone", "know every credit card offer",
  "get free lounge access everywhere", "use every coupon and cashback", "get money back from every refund", "fight a bank for a 20-rupee charge", "win a fight with an airline",
  "sell their old stuff on OLX and get scammed", "buy from OLX and get scammed", "flip things online for profit", "run a side hustle from their bedroom", "earn more from the side hustle than the job",
  "become a stockbroker from YouTube videos", "give financial advice they never follow", "be the friend people ask about money", "be the friend who is always broke on the 20th", "survive the month on Maggi",
]
