// Most Likely To, spicy: hostel, college nights and roommates.
export default [
  "sneak into the hostel after curfew through a window", "bribe the hostel guard with Maggi", "keep a secret kettle in the hostel room", "cook biryani in a hostel room", "set off the hostel smoke alarm with Maggi",
  "get caught with a heater in the hostel", "hide a pet in the hostel", "hide a friend from another hostel in their cupboard", "have a party in the hostel corridor", "start a pillow fight that breaks a bulb",
  "steal food from the mess for the whole floor", "know every mess menu by heart", "complain about the mess and eat four plates", "sneak food out of the mess in their pocket", "eat at the mess of another hostel",
  "survive a semester on instant noodles", "order food at 3 am in the hostel", "go out for parathas at 4 am", "know every late-night dhaba near campus", "have a tab at the canteen",
  "never pay their canteen tab", "borrow money from the canteen owner", "be best friends with the canteen bhaiya", "get special treatment at the canteen", "have a chai named after them at the canteen",
  "use a roommate's things without asking", "wear a roommate's clothes to class", "eat a roommate's home food in one night", "finish a roommate's snacks from home", "hide their snacks from the roommate in their shoes",
  "never clean their side of the room", "have the messiest room on the floor", "have a perfectly clean room and judge everyone", "keep a dustbin full for a month", "have something growing in their room",
  "sleep through every morning class", "mark a friend's attendance with a fake voice", "get caught giving proxy attendance", "ask for proxy every single day", "have 'detained' written next to their name",
  "beg professors for attendance", "cry in front of a professor to pass", "argue with a professor and win", "become the professor's favourite with jokes", "date a teaching assistant",
  "study the night before and top the exam", "study all semester and fail", "make the best notes and lend them to everyone", "sell their notes to juniors", "photocopy someone else's notes and score more",
  "pull an all-nighter with ten cups of coffee", "fall asleep on their books before an exam", "start studying at 2 am", "watch a series 'for a break' and finish it", "decide to drop out every semester",
  "change their branch after one semester", "say 'I'll start studying tomorrow' every day", "write an exam with a hangover", "go to an exam in their nightclothes", "forget their admit card on exam day",
  "convince the whole class to bunk", "plan a mass bunk that goes wrong", "be the only one who attends a mass bunk", "be the class representative who never represents", "run for college elections",
  "win college elections with free samosas", "lose college elections by one vote", "start a college club that dies in a month", "organise the college fest", "spend the fest budget on the after-party",
  "get backstage at the fest with a fake pass", "perform at the fest and forget the lyrics", "win a dance competition at the fest", "have the best fest outfit", "fall in love at the fest every year",
  "still be scared of their seniors from college", "be the senior juniors love", "be the senior juniors are scared of", "give juniors fake advice for fun", "make juniors do their assignments",
  "date a junior", "date a senior", "date someone from another college", "date someone from the rival college", "leave college with a partner",
  "leave college with nothing but memories and debts", "get placed in the first company that comes", "get the highest package in the batch", "fail placements and start a startup", "go for higher studies to avoid a job",
  "go abroad for a master's and never come back", "come back from abroad and complain about everything", "become a professor in the same college", "come back to campus every year", "cry on the last day of college",
  "steal a souvenir from college", "carve their name in the hostel room", "leave a message for the next person in the room", "keep their hostel ID card forever", "visit their old hostel room and get emotional",
  "write a book about hostel life", "have the craziest hostel story", "have a hostel story that involves the police", "have a hostel story that involves a monkey", "have a hostel story they cannot tell in front of parents",
  "go on a trip with the hostel gang and lose someone", "go to Goa with the hostel gang and come back broke", "rent a bike with the hostel gang and crash it", "climb the water tank at night", "go to the terrace at night with a guitar",
  "sing old songs on the terrace at 2 am", "play cricket in the hostel corridor and break a window", "play Counter-Strike all night", "start a LAN party in the hostel", "play FIFA tournaments for money",
  "lose money in a hostel card game", "run a betting pool on cricket matches", "run a tuck shop from their room", "charge others to use their iron", "rent out their bike to juniors",
  "have a secret room for parties", "know a way into the closed library", "sleep in the library", "sneak food into the library", "get caught kissing in the library",
  "be the one who knows all the campus gossip", "know who is dating whom on campus", "spread a campus rumour that becomes legend", "become a campus legend", "be remembered by the security guards years later",
]
