// Most Likely To, spicy: predictions about where everyone ends up.
export default [
  "become famous for something embarrassing", "end up on a reality show", "win Bigg Boss", "be the villain on a reality show", "get eliminated first from a reality show",
  "become a viral meme template", "become a famous YouTuber by accident", "become a politician and forget their friends", "become a godman with followers", "start a cult around a diet",
  "become a billionaire and still split bills", "become rich and buy back their school", "win the lottery and lose it in a year", "go bankrupt twice and bounce back", "retire at thirty-five",
  "never retire", "work until ninety", "run a company their friends work for", "fire one of their friends", "hire all their friends and regret it",
  "marry a celebrity", "marry a foreigner and move away", "marry rich and act like they earned it", "marry three times", "marry their high school crush at fifty",
  "get divorced and throw a party", "have a scandal in the newspaper", "be on the front page for the wrong reason", "be sued by a famous person", "sue their neighbour over a tree",
  "move to the US and say 'back home' about India", "come back from abroad with a fake accent", "become a crazy cat person", "have twelve dogs", "live on a farm with goats",
  "become a priest", "open an ashram", "become a yoga teacher in Bali", "become a life coach with no life experience", "write a self-help book",
  "write a tell-all book about this group", "become a famous novelist", "write a film script based on their love life", "have their life made into a web series", "get roasted on a comedy show",
  "host a talk show", "become a famous chef", "open a restaurant that fails", "open a restaurant that becomes famous", "open a bar with friends",
  "open a cafe in the hills", "run a homestay in Himachal", "become a tour guide", "become a Bollywood villain", "play a doctor on a TV serial",
  "become a cricketer's agent", "become a sports commentator", "become a referee who gets booed", "own an IPL team", "invest in a startup that becomes huge",
  "become a crypto millionaire", "lose everything in crypto", "become a stock market guru on YouTube", "get rich selling something silly", "invent something everyone uses",
  "get a patent for a useless invention", "win a Nobel Prize", "win an Oscar", "win a Filmfare award", "win a Grammy",
  "go to jail for a white-collar crime", "become a lawyer who defends criminals", "become a judge", "become the police commissioner", "become a spy",
  "work for the intelligence agency and never tell anyone", "have a second family nobody knows about", "fake their own death", "disappear and reappear in ten years", "become the head of a big family",
  "have ten children", "never have children", "spoil their grandchildren", "become the strict parent they hated", "become exactly like their mom",
  "become exactly like their dad", "end up living with their parents at forty", "build a house next to their parents", "move as far away from family as possible", "become a grumpy old person who shouts at kids",
  "become a cool grandparent who plays video games", "be on Instagram at eighty", "still go clubbing at sixty", "have a midlife crisis with a motorbike", "learn to dance at seventy",
  "run a marathon at seventy", "go back to college at fifty", "start a new career at fifty", "fall in love again at seventy", "live to a hundred",
  "outlive everyone in this room", "be the last one standing at every reunion", "plan their own funeral playlist", "write their own funeral speech", "come back as a ghost to haunt this group",
  "have a statue made of themselves", "have a road named after them", "have a holiday named after them", "be remembered for a single meme",
]
