// Most Likely To, spicy: crushes, flirting and dating apps.
export default [
  "blush when their crush's name comes up", "change the topic when their crush is mentioned", "practise what to say to a crush in the mirror", "plan an accidental meeting with a crush", "take a longer route to pass a crush's house",
  "wait for a crush at the bus stop", "join a club just because their crush is in it", "learn a sport to impress a crush", "start going to the gym for a crush", "buy a new outfit to bump into a crush",
  "find out a crush's timetable", "know a crush's favourite song", "know a crush's coffee order", "know a crush's birthday before their own friends do", "know a crush's zodiac sign and check compatibility",
  "write a crush's name with their surname", "imagine their wedding with a crush", "name their future kids with a crush", "dream about a crush and act weird the next day", "tell everyone except the crush",
  "send a crush a song instead of saying anything", "post a story hoping a crush sees it", "react to every story of a crush", "reply to a crush's story with a long message", "wait an hour to reply to a crush on purpose",
  "type 'hehe' to a crush", "send a crush a meme every day", "use a meme to confess feelings", "confess on their crush's birthday", "confess and then say 'just kidding'",
  "confess at the end of the school year", "confess on the last day of college", "confess at a farewell party", "confess on a trip", "confess while drunk",
  "confess by mistake in a game of truth or dare", "have a crush who confesses first", "turn down a confession kindly", "turn down a confession and regret it", "have a secret admirer",
  "be someone's secret admirer", "leave a chocolate on a crush's desk", "leave an anonymous note for a crush", "send flowers anonymously", "ask a friend to find out if a crush likes them",
  "be the friend who carries messages between two crushes", "make two friends date each other", "get a crush on their friend's date", "get a crush on a friend's sibling at a wedding", "get a crush on a stranger every week",
  "fall for anyone who is nice to them", "fall for someone in five minutes", "fall out of love in five minutes", "have a crush on a celebrity for twenty years", "have a crush on a cartoon character as an adult",
  "flirt without knowing they are flirting", "be told they were flirting and deny it", "flirt with everyone at a party", "flirt with the bartender for free drinks", "flirt with the shopkeeper for a discount",
  "use a cheesy pickup line", "use a pickup line that actually works", "use a pickup line from a film", "use a maths pickup line", "use a food pickup line",
  "wink and fail", "smile at a stranger and get a smile back", "make eye contact across a room for an hour", "ask someone out in the metro", "ask someone out in a queue",
  "ask for a number and get a fake one", "give a fake number to get away", "give out their number on a napkin", "write their number on someone's hand", "get a number and never call",
  "make a dating profile with friends' help", "write a funny dating bio", "write a long dating bio nobody reads", "use photos with their dog to get matches", "use a photo with a borrowed car",
  "use a group photo where nobody knows who they are", "post a photo of a mountain as their main photo", "lie about liking travel on a dating app", "say they love reading and have read one book", "say they love dogs and are scared of them",
  "match with someone from their school", "match with a teacher", "match with a colleague and pretend not to", "match with a friend's sibling", "match with someone in this room",
  "go on a date from an app every weekend", "go on a date from an app and bring a friend", "have a safety call ready for every date", "fake an emergency to leave a date", "fake an emergency and get caught",
  "go on a date with a person who looks nothing like their photos", "be the person who looks nothing like their photos", "go on a great date and never hear back", "send a 'thank you for the date' text", "plan the second date on the first",
  "talk to five people on apps at once", "mix up two matches' names", "send the same message to everyone", "forget who they were talking to", "go on two dates in one evening",
  "delete the app after a bad date", "reinstall the app after a week", "pay for the app and still get no matches", "get a match after a year and panic", "match and never say hi",
  "use AI to write dating app messages", "use AI to plan a date", "ask the group chat what to reply", "screenshot a match's message for the group", "let friends swipe for them",
]
