// Most Likely To, spicy: lazy, weird and slightly gross habits.
export default [
  "wear the same T-shirt three days in a row", "skip a bath on Sunday", "skip a bath in winter for three days", "smell their socks to check", "use deodorant instead of a bath",
  "sleep in their jeans", "sleep in their shoes", "sleep on a pile of clothes", "use a chair as a cupboard", "have a mountain of laundry in their room",
  "make their bed only when guests come", "hide mess in the cupboard before guests arrive", "shove everything under the bed", "have a 'clean' room that is clean only on the outside", "eat in bed every night",
  "have crumbs in their bed", "keep a plate under their bed for days", "leave half-drunk cups everywhere", "have five water bottles by their bed", "put their lips on the shared water bottle",
  "drink straight from the jug", "eat ice cream from the tub with a spoon and put it back", "double-dip in the chutney", "lick their fingers at a restaurant", "eat with their mouth open",
  "talk with food in their mouth", "chew ice loudly", "eat chips loudly in a quiet room", "slurp tea like it is a sport", "pick their nose when they think nobody is looking",
  "bite their nails", "crack their knuckles all day", "crack their neck loudly", "click a pen until everyone goes mad", "tap their foot all the time",
  "shake their leg under the table", "whistle in an office", "talk to themselves on the street", "wear headphones without music to avoid people", "pretend to be asleep to avoid chores",
  "pretend to be on a call to avoid chores", "do chores only when their mom shouts", "do a chore badly so they are never asked again", "leave the tap running", "leave every light on",
  "leave the fridge door open", "leave the gas cylinder knob on", "forget to lock the door", "put an empty carton back in the fridge", "put the empty cereal box back",
  "leave one sheet of toilet paper", "never change the toilet roll", "leave the toilet seat up", "use the last of the hot water", "take a phone into the bathroom for an hour",
  "fall asleep on the toilet", "sing loudly on the toilet", "take calls on the toilet", "wear socks with sandals", "wear crocs everywhere",
  "wear chappals to a wedding", "wear a hoodie in summer", "wear shorts in winter", "own fifty pairs of shoes and wear one", "own one pair of shoes for everything",
  "never buy new clothes until the old ones tear", "buy new clothes every week", "keep clothes with tags for a year", "cut their own hair in the bathroom", "use their roommate's razor",
  "use dish soap as shampoo", "use shampoo as body wash", "own twenty skincare products and use none", "have a ten-step skincare routine", "spend an hour getting ready for the market",
  "get ready in two minutes for a wedding", "never iron their clothes", "iron their clothes while wearing them", "sleep twelve hours on weekends", "nap three times a day",
  "fall asleep anywhere in seconds", "need complete darkness to sleep", "sleep with the TV on", "keep their phone under their pillow", "wake up at noon and call it morning",
  "have breakfast at 4 pm", "eat dinner at midnight", "snack all night", "drink coffee at 11 pm and wonder why they cannot sleep", "eat Maggi three times a day",
  "eat everything with achaar", "never wash a dish until there are none left", "use paper plates to avoid washing", "eat from the pressure cooker", "eat straight from the fridge",
  "eat food that fell on the floor", "check expiry dates and eat it anyway", "smell milk before every use", "order the same food every day", "eat the same breakfast for ten years",
  "keep every plastic bag", "keep every takeaway container", "keep every cable they ever owned", "keep a drawer of random keys", "keep old phones in a drawer",
  "never throw away anything", "throw away everything and regret it", "hoard hotel shampoos", "take hotel slippers home", "take sugar sachets from cafes",
  "have a car full of junk", "eat in the car and leave wrappers", "use the car as a cupboard", "never clean the car", "wash the car every day",
  "count steps obsessively", "track everything in an app", "have a to-do list they never finish", "make a to-do list with 'make a to-do list'", "set goals every January and forget by February",
  "start a hobby every month", "buy all the gear for a hobby and quit", "own a guitar they cannot play", "own a yoga mat that has never been unrolled", "have an unused cycle on the balcony",
]
