// Dictionary Bluff words: real but rare English words, each with its meaning in plain English.

export interface BluffWord { w: string; d: string }

export const BLUFF_WORDS: BluffWord[] = [
  { w: 'petrichor', d: 'The pleasant smell of the earth after rain' },
  { w: 'defenestrate', d: 'To throw someone out of a window' },
  { w: 'borborygmus', d: 'The rumbling sound your stomach makes' },
  { w: 'sesquipedalian', d: 'Fond of using very long words' },
  { w: 'snollygoster', d: 'A clever but dishonest person, especially a politician' },
  { w: 'quidnunc', d: 'A person who always wants to know the latest gossip' },
  { w: 'lollygag', d: 'To waste time doing nothing useful' },
  { w: 'cattywampus', d: 'Crooked; not lined up properly' },
  { w: 'bumfuzzle', d: 'To confuse someone' },
  { w: 'widdershins', d: 'In the anticlockwise direction' },
  { w: 'kerfuffle', d: 'A noisy fuss or argument' },
  { w: 'flibbertigibbet', d: 'A silly person who talks too much' },
  { w: 'gongoozler', d: 'A person who likes to watch boats on a canal' },
  { w: 'absquatulate', d: 'To leave suddenly without telling anyone' },
  { w: 'taradiddle', d: 'A small lie; silly nonsense' },
  { w: 'hornswoggle', d: 'To cheat or trick someone' },
  { w: 'ultracrepidarian', d: 'A person who gives opinions on things they know nothing about' },
  { w: 'bibliopole', d: 'A person who buys and sells rare books' },
  { w: 'apricity', d: 'The warmth of the sun on a winter day' },
  { w: 'phosphene', d: 'The lights and colours you see when you rub your closed eyes' },
  { w: 'tmesis', d: 'Breaking a word into two by putting another word in the middle, as in "abso-very-lutely"' },
  { w: 'zugzwang', d: 'In chess, a position where every possible move makes things worse' },
  { w: 'yarborough', d: 'A hand of cards with no card higher than a nine' },
  { w: 'pandiculation', d: 'Stretching your body while yawning, usually after waking up' },
  { w: 'philtrum', d: 'The small groove between your nose and your upper lip' },
  { w: 'glabella', d: 'The smooth part of the forehead between the eyebrows' },
  { w: 'lunule', d: 'The white half-moon shape at the bottom of a fingernail' },
  { w: 'aglet', d: 'The plastic or metal tip at the end of a shoelace' },
  { w: 'ferrule', d: 'The metal band that holds the eraser on a pencil' },
  { w: 'tittle', d: 'The dot over a small letter i or j' },
  { w: 'zarf', d: 'A holder for a hot cup that has no handle' },
  { w: 'muntin', d: 'A strip of wood that separates the glass panes of a window' },
  { w: 'obelus', d: 'The ÷ sign used for division' },
  { w: 'octothorpe', d: 'The # symbol, also called the hash' },
  { w: 'interrobang', d: 'A punctuation mark that combines a question mark and an exclamation mark' },
  { w: 'jentacular', d: 'To do with breakfast' },
  { w: 'deipnosophist', d: 'A person who is good at conversation over dinner' },
  { w: 'nudiustertian', d: 'Of the day before yesterday' },
  { w: 'crepuscular', d: 'Active at dawn and dusk, like some animals' },
  { w: 'vespertine', d: 'Active or blooming in the evening' },
  { w: 'susurrus', d: 'A soft whispering or rustling sound' },
  { w: 'tintinnabulation', d: 'The ringing sound of bells' },
  { w: 'mumpsimus', d: 'A person who sticks to a mistake even after being shown it is wrong' },
  { w: 'logomachy', d: 'An argument about the meaning of words' },
  { w: 'floccinaucinihilipilification', d: 'The habit of thinking that something is worthless' },
  { w: 'bloviate', d: 'To talk for a long time in a show-off way' },
  { w: 'collywobbles', d: 'A nervous, uneasy feeling in the stomach' },
  { w: 'erinaceous', d: 'Like a hedgehog' },
  { w: 'vulpine', d: 'Like a fox; sly and clever' },
  { w: 'lucubration', d: 'Hard study or writing done late at night' },
  { w: 'omphalos', d: 'The belly button; also, the centre of something' },
  { w: 'uxorious', d: 'Too fond of, or too obedient to, one\'s wife' },
  { w: 'ninnyhammer', d: 'A foolish person' },
  { w: 'slubberdegullion', d: 'A dirty, lazy, good-for-nothing person' },
  { w: 'cachinnate', d: 'To laugh very loudly' },
  { w: 'tergiversate', d: 'To keep changing your opinion or side' },
  { w: 'perendinate', d: 'To put something off until the day after tomorrow' },
  { w: 'snickersnee', d: 'A large knife used as a weapon' },
  { w: 'canoodle', d: 'To kiss and cuddle' },
  { w: 'pettifogger', d: 'A lawyer who handles small cases using petty tricks' },
  { w: 'popinjay', d: 'A vain person who loves to show off' },
  { w: 'mollycoddle', d: 'To treat someone too gently; to pamper' },
  { w: 'rigmarole', d: 'A long and complicated process' },
  { w: 'myrmidon', d: 'A follower who obeys orders without asking questions' },
  { w: 'fugacious', d: 'Lasting only a short time' },
  { w: 'pulchritude', d: 'Beauty' },
  { w: 'defalcate', d: 'To steal money that you were trusted to look after' },
  { w: 'impignorate', d: 'To pawn something' },
  { w: 'gardyloo', d: 'A warning shout before throwing dirty water out of a window' },
  { w: 'smellfungus', d: 'A person who complains about everything' },
  { w: 'pogonophobia', d: 'Fear of beards' },
  { w: 'ailurophile', d: 'A person who loves cats' },
  { w: 'agelast', d: 'A person who never laughs' },
  { w: 'spaghettification', d: 'The stretching of an object into a long thin shape by a black hole\'s gravity' },
  { w: 'palimpsest', d: 'A page that was written on, rubbed clean and written on again' },
  { w: 'sobriquet', d: 'A nickname' },
  { w: 'pareidolia', d: 'Seeing faces or shapes in random things, like clouds' },
  { w: 'syzygy', d: 'When three bodies in space, such as the Sun, Moon and Earth, line up' },
  { w: 'tatterdemalion', d: 'A person dressed in torn, ragged clothes' },
  { w: 'yex', d: 'To hiccup' },
  { w: 'gormless', d: 'Foolish; lacking common sense' },
  { w: 'frisson', d: 'A sudden feeling of excitement or fear' },
  { w: 'brouhaha', d: 'A noisy fuss about something unimportant' },
  { w: 'flummox', d: 'To confuse someone completely' },
  { w: 'higgledy-piggledy', d: 'Mixed up and messy' },
  { w: 'crapulence', d: 'Feeling sick after eating or drinking too much' },
  { w: 'bumbershoot', d: 'An umbrella' },
  { w: 'snood', d: 'A loose net or band worn over the hair' },
  { w: 'wamble', d: 'To feel sick in the stomach' },
  { w: 'gubbins', d: 'Bits and pieces; small useless things' },
  { w: 'fopdoodle', d: 'A foolish or silly person' },
  { w: 'lickspittle', d: 'A person who flatters important people to get favours' },
  // Body and health
  { w: 'canthus', d: 'The corner of the eye, where the upper and lower eyelids meet' },
  { w: 'purlicue', d: 'The space between your thumb and first finger when they are stretched apart' },
  { w: 'hallux', d: 'The big toe' },
  { w: 'minimus', d: 'The little finger or the little toe' },
  { w: 'axilla', d: 'The armpit' },
  { w: 'popliteal', d: 'To do with the hollow at the back of the knee' },
  { w: 'uvula', d: 'The small piece of flesh that hangs at the back of the throat' },
  { w: 'nares', d: 'The nostrils' },
  { w: 'vibrissae', d: 'Stiff hairs like a cat\'s whiskers, or the hairs inside your nose' },
  { w: 'frenulum', d: 'The small fold of skin under your tongue that holds it down' },
  { w: 'otalgia', d: 'Earache' },
  { w: 'cephalalgia', d: 'A headache' },
  { w: 'singultus', d: 'A hiccup' },
  { w: 'sternutation', d: 'The act of sneezing' },
  { w: 'eructation', d: 'A burp' },
  { w: 'oscitation', d: 'Yawning' },
  { w: 'horripilation', d: 'Goosebumps; the hair on your skin standing up' },
  { w: 'formication', d: 'The feeling of insects crawling on your skin when there are none' },
  { w: 'xerostomia', d: 'A dry mouth' },
  { w: 'bruxism', d: 'Grinding your teeth, often while asleep' },
  { w: 'onychophagia', d: 'The habit of biting your nails' },
  { w: 'somniloquy', d: 'Talking in your sleep' },
  { w: 'hypnopompic', d: 'To do with the half-awake state just before you fully wake up' },
  { w: 'hypnagogic', d: 'To do with the drowsy state just before you fall asleep' },
  { w: 'clinomania', d: 'A strong wish to stay in bed' },
  { w: 'brachycephalic', d: 'Having a short, wide head, like a pug' },
  { w: 'sinistral', d: 'Left-handed' },
  { w: 'dextral', d: 'Right-handed' },
  { w: 'callipygian', d: 'Having nicely shaped buttocks' },
  { w: 'pulvinar', d: 'Shaped like a cushion' },
  { w: 'chirography', d: 'Handwriting' },
  { w: 'dactylogram', d: 'A fingerprint' },
  { w: 'genuflect', d: 'To bend one knee to the ground as a sign of respect' },
  { w: 'arachibutyrophobia', d: 'Fear of peanut butter sticking to the roof of your mouth' },
  { w: 'hippopotomonstrosesquippedaliophobia', d: 'Fear of long words' },
  { w: 'nomophobia', d: 'Fear of being without your mobile phone' },
  { w: 'triskaidekaphobia', d: 'Fear of the number 13' },
  { w: 'coulrophobia', d: 'Fear of clowns' },
  { w: 'ergophobia', d: 'Fear of work' },
  { w: 'somniphobia', d: 'Fear of falling asleep' },
  { w: 'ombrophobia', d: 'Fear of rain' },
  { w: 'turophile', d: 'A person who loves cheese' },
  { w: 'cynophile', d: 'A person who loves dogs' },
  { w: 'logophile', d: 'A person who loves words' },
  { w: 'chionophile', d: 'A person or plant that loves snow and cold' },
  { w: 'opsimath', d: 'A person who starts learning late in life' },
  { w: 'philomath', d: 'A lover of learning' },
  // People
  { w: 'quockerwodger', d: 'A puppet on strings; also, a politician controlled by someone else' },
  { w: 'lothario', d: 'A man who tries to charm many women' },
  { w: 'martinet', d: 'A very strict person who insists on rules being obeyed' },
  { w: 'poltroon', d: 'A complete coward' },
  { w: 'scofflaw', d: 'A person who ignores the law, often in small ways' },
  { w: 'mountebank', d: 'A person who cheats people by selling fake medicines' },
  { w: 'blatherskite', d: 'A person who talks a lot of nonsense' },
  { w: 'gobemouche', d: 'A person who believes everything they hear' },
  { w: 'quacksalver', d: 'A fake doctor' },
  { w: 'lummox', d: 'A clumsy, stupid person' },
  { w: 'dunderhead', d: 'A stupid person' },
  { w: 'scapegrace', d: 'A naughty person who is always in trouble' },
  { w: 'wastrel', d: 'A lazy person who wastes money and time' },
  { w: 'skinflint', d: 'A person who hates spending money; a miser' },
  { w: 'gadabout', d: 'A person who keeps going out to have fun' },
  { w: 'blowhard', d: 'A person who boasts a lot' },
  { w: 'braggadocio', d: 'Loud, empty boasting' },
  { w: 'fussbudget', d: 'A person who worries and complains about small things' },
  { w: 'sluggard', d: 'A very lazy person' },
  { w: 'slugabed', d: 'A lazy person who stays in bed late' },
  { w: 'stripling', d: 'A young man who is not yet fully grown' },
  { w: 'hobbledehoy', d: 'A clumsy, awkward teenage boy' },
  { w: 'amanuensis', d: 'A person who writes down what someone else says' },
  { w: 'factotum', d: 'A person who does all kinds of jobs for someone' },
  { w: 'majordomo', d: 'The head servant of a large house' },
  { w: 'funambulist', d: 'A tightrope walker' },
  { w: 'prestidigitator', d: 'A magician who does tricks with quick hands' },
  { w: 'deltiologist', d: 'A person who collects postcards' },
  { w: 'vexillologist', d: 'A person who studies flags' },
  { w: 'oenophile', d: 'A person who loves wine' },
  { w: 'cruciverbalist', d: 'A person who loves or makes crossword puzzles' },
  { w: 'toponymist', d: 'A person who studies place names' },
  { w: 'horologist', d: 'A person who makes or repairs clocks and watches' },
  { w: 'cordwainer', d: 'A shoemaker' },
  { w: 'chandler', d: 'A person who makes or sells candles' },
  { w: 'fletcher', d: 'A person who makes arrows' },
  { w: 'cooper', d: 'A person who makes barrels' },
  { w: 'milliner', d: 'A person who makes or sells women\'s hats' },
  { w: 'haberdasher', d: 'A person who sells buttons, threads and small sewing items' },
  { w: 'costermonger', d: 'A person who sells fruit and vegetables from a cart' },
  { w: 'lamplighter', d: 'A person whose job was to light street lamps' },
  { w: 'knocker-up', d: 'A person paid to wake people up by knocking on their windows' },
  { w: 'ostler', d: 'A person who looked after horses at an inn' },
  { w: 'farrier', d: 'A person who puts shoes on horses' },
  { w: 'wainwright', d: 'A person who builds and repairs wagons' },
  { w: 'tosher', d: 'A person who searched sewers for valuable things' },
  { w: 'mudlark', d: 'A person who searches river mud for things to sell' },
  { w: 'saltimbanco', d: 'A street performer who sells fake medicines' },
  // Talk and words
  { w: 'codswallop', d: 'Nonsense' },
  { w: 'piffle', d: 'Nonsense; rubbish' },
  { w: 'bunkum', d: 'Foolish talk; nonsense' },
  { w: 'flapdoodle', d: 'Foolish talk' },
  { w: 'persiflage', d: 'Light, teasing talk' },
  { w: 'badinage', d: 'Playful, witty talk between people' },
  { w: 'logorrhoea', d: 'Talking far too much' },
  { w: 'verbigeration', d: 'Repeating the same words or phrases over and over without meaning' },
  { w: 'circumlocution', d: 'Using many words to say something simple' },
  { w: 'periphrasis', d: 'Saying something in a long, roundabout way' },
  { w: 'pleonasm', d: 'Using more words than needed, like "free gift"' },
  { w: 'malapropism', d: 'Using a wrong word that sounds like the right one, often funnily' },
  { w: 'spoonerism', d: 'Swapping the first sounds of words by mistake, like "tease my ears" for "ease my tears"' },
  { w: 'eggcorn', d: 'A word mistaken for a similar-sounding one that still seems to make sense, like "old-timers disease"' },
  { w: 'mondegreen', d: 'A misheard song lyric or phrase' },
  { w: 'paraprosdokian', d: 'A sentence whose ending surprises you and changes the meaning' },
  { w: 'pangram', d: 'A sentence that uses every letter of the alphabet' },
  { w: 'lipogram', d: 'Writing that leaves out one particular letter on purpose' },
  { w: 'aptronym', d: 'A name that suits its owner\'s job, like a dentist called Dr Fang' },
  { w: 'toponym', d: 'A word that comes from a place name' },
  { w: 'eponym', d: 'A person after whom something is named' },
  { w: 'portmanteau', d: 'A word made by joining two words, like "brunch"' },
  { w: 'neologism', d: 'A newly invented word' },
  { w: 'hapax', d: 'A word that appears only once in a writer\'s work or in a language\'s records' },
  { w: 'grandiloquent', d: 'Using big, fancy words to impress people' },
  { w: 'magniloquent', d: 'Speaking in a proud, showy way' },
  { w: 'voluble', d: 'Talking a lot, quickly and easily' },
  { w: 'stentorian', d: 'Very loud, especially of a voice' },
  { w: 'obloquy', d: 'Strong public criticism' },
  { w: 'philippic', d: 'A bitter speech attacking someone' },
  { w: 'jeremiad', d: 'A long, sad complaint about how bad things are' },
  { w: 'diatribe', d: 'An angry speech or piece of writing attacking someone' },
  { w: 'panegyric', d: 'A speech full of praise' },
  { w: 'encomium', d: 'A speech or piece of writing that praises someone highly' },
  { w: 'valediction', d: 'A farewell speech' },
  { w: 'cognomen', d: 'A family name or nickname' },
  { w: 'billingsgate', d: 'Rude and abusive language' },
  { w: 'contumely', d: 'Rude, insulting treatment' },
  // Feelings and behaviour
  { w: 'tartle', d: 'To hesitate when introducing someone because you forgot their name' },
  { w: 'velleity', d: 'A wish so weak that you do nothing about it' },
  { w: 'acedia', d: 'Laziness and not caring about anything' },
  { w: 'accismus', d: 'Pretending not to want something you actually want' },
  { w: 'abulia', d: 'Not being able to make decisions or act' },
  { w: 'anhedonia', d: 'Not being able to feel pleasure' },
  { w: 'pique', d: 'A feeling of hurt pride or irritation' },
  { w: 'dudgeon', d: 'A feeling of angry resentment' },
  { w: 'choler', d: 'Anger or bad temper' },
  { w: 'splenetic', d: 'Bad-tempered and spiteful' },
  { w: 'atrabilious', d: 'Gloomy and bad-tempered' },
  { w: 'lugubrious', d: 'Very sad and gloomy' },
  { w: 'insouciance', d: 'A relaxed, carefree attitude' },
  { w: 'sangfroid', d: 'Staying calm in danger or difficulty' },
  { w: 'phlegmatic', d: 'Calm and not easily excited' },
  { w: 'fractious', d: 'Easily irritated; likely to complain' },
  { w: 'truculent', d: 'Eager to argue or fight' },
  { w: 'pugnacious', d: 'Eager to fight' },
  { w: 'bellicose', d: 'Wanting to fight or start a war' },
  { w: 'obstreperous', d: 'Noisy and hard to control' },
  { w: 'refractory', d: 'Stubborn and hard to control' },
  { w: 'contumacious', d: 'Stubbornly refusing to obey' },
  { w: 'recalcitrant', d: 'Refusing to obey rules' },
  { w: 'intransigent', d: 'Refusing to change your views' },
  { w: 'obdurate', d: 'Stubborn; refusing to change your mind' },
  { w: 'pertinacious', d: 'Holding firmly to a plan or opinion' },
  { w: 'punctilious', d: 'Very careful to behave correctly' },
  { w: 'pusillanimous', d: 'Cowardly; lacking courage' },
  { w: 'craven', d: 'Cowardly' },
  { w: 'feckless', d: 'Lazy and not responsible' },
  { w: 'shiftless', d: 'Lazy and without ambition' },
  { w: 'indolent', d: 'Lazy' },
  { w: 'otiose', d: 'Serving no useful purpose' },
  { w: 'slothful', d: 'Lazy' },
  { w: 'torpid', d: 'Slow and without energy' },
  { w: 'somnolent', d: 'Sleepy' },
  { w: 'crapulous', d: 'Feeling unwell from eating or drinking too much' },
  { w: 'edacious', d: 'Very greedy for food' },
  { w: 'esurient', d: 'Hungry or greedy' },
  { w: 'abstemious', d: 'Not eating or drinking much' },
  { w: 'parsimonious', d: 'Very unwilling to spend money' },
  { w: 'penurious', d: 'Very poor' },
  { w: 'impecunious', d: 'Having little or no money' },
  { w: 'munificent', d: 'Very generous' },
  { w: 'avuncular', d: 'Kind and friendly, like an uncle' },
  { w: 'convivial', d: 'Friendly and lively' },
  { w: 'jocund', d: 'Cheerful and light-hearted' },
  { w: 'waggish', d: 'Playful and joking' },
  { w: 'risible', d: 'So silly that it makes people laugh' },
  { w: 'nugatory', d: 'Of no value or importance' },
  { w: 'quotidian', d: 'Ordinary and everyday' },
  { w: 'supercilious', d: 'Behaving as if you are better than others' },
  { w: 'vainglorious', d: 'Too proud of yourself' },
  { w: 'meretricious', d: 'Attractive on the outside but of no real value' },
  { w: 'specious', d: 'Seeming right but actually wrong' },
  { w: 'mendacious', d: 'Not telling the truth' },
  { w: 'perfidious', d: 'Disloyal; likely to betray people' },
  { w: 'obsequious', d: 'Too eager to please or obey' },
  { w: 'unctuous', d: 'Too friendly or flattering, in an oily way' },
  { w: 'sententious', d: 'Fond of giving moral lectures' },
  { w: 'chimerical', d: 'Imaginary; existing only as a wild idea' },
  // Things around us
  { w: 'aiguillette', d: 'A decorative cord worn on the shoulder of a uniform' },
  { w: 'asterism', d: 'A group of three asterisks in a triangle (⁂)' },
  { w: 'pilcrow', d: 'The ¶ symbol that marks a paragraph' },
  { w: 'diacritic', d: 'A mark added to a letter, like the dots on ü' },
  { w: 'virgule', d: 'The slash mark (/)' },
  { w: 'solidus', d: 'A slanting line used in fractions, like 1/2' },
  { w: 'guillemets', d: 'The « » marks used as quotation marks in some languages' },
  { w: 'dingbat', d: 'A small decorative symbol in printing, like a star or arrow' },
  { w: 'colophon', d: 'A note at the end of a book about how it was printed' },
  { w: 'frontispiece', d: 'A picture facing the title page of a book' },
  { w: 'marginalia', d: 'Notes written in the margins of a book' },
  { w: 'bibelot', d: 'A small decorative object' },
  { w: 'tchotchke', d: 'A small, cheap ornament or trinket' },
  { w: 'gewgaw', d: 'A showy but worthless thing' },
  { w: 'doohickey', d: 'A small gadget whose name you do not know' },
  { w: 'grommet', d: 'A metal ring that strengthens a hole in cloth or leather' },
  { w: 'escutcheon', d: 'The metal plate around a keyhole or door handle' },
  { w: 'finial', d: 'A decorative piece on top of a roof, post or lamp' },
  { w: 'jamb', d: 'The side post of a door or window frame' },
  { w: 'transom', d: 'A small window above a door' },
  { w: 'baluster', d: 'One of the small posts that hold up a staircase rail' },
  { w: 'newel', d: 'The main post at the top or bottom of a staircase' },
  { w: 'crenellation', d: 'The gaps in the top wall of a castle' },
  { w: 'oubliette', d: 'A secret prison cell entered only through a trapdoor in the roof' },
  { w: 'portcullis', d: 'A heavy iron gate that slides down at a castle entrance' },
  { w: 'belvedere', d: 'A building or tower built to give a fine view' },
  { w: 'folly', d: 'A fancy building built only for decoration' },
  { w: 'ha-ha', d: 'A ditch with a wall inside it that keeps animals out without blocking the view' },
  { w: 'snickelway', d: 'A narrow lane between buildings' },
  { w: 'ginnel', d: 'A narrow passage between buildings' },
  { w: 'culvert', d: 'A tunnel that carries water under a road' },
  { w: 'sluice', d: 'A sliding gate that controls the flow of water' },
  { w: 'weir', d: 'A low wall built across a river to control the water' },
  { w: 'causeway', d: 'A raised road across water or wet ground' },
  { w: 'antimacassar', d: 'A cloth put on the back of a chair to keep it clean from hair oil' },
  { w: 'chiffonier', d: 'A tall chest of drawers' },
  { w: 'escritoire', d: 'A small writing desk' },
  { w: 'davenport', d: 'A small writing desk with drawers, or a large sofa' },
  { w: 'credenza', d: 'A long low cupboard, often in a dining room' },
  { w: 'epergne', d: 'A decorative stand for fruit or flowers in the middle of a table' },
  { w: 'tureen', d: 'A deep dish with a lid for serving soup' },
  { w: 'samovar', d: 'A large metal urn used to boil water for tea' },
  { w: 'trivet', d: 'A small stand for a hot pot or dish' },
  { w: 'spurtle', d: 'A wooden stick for stirring porridge' },
  { w: 'mandoline', d: 'A kitchen tool for slicing vegetables thinly' },
  { w: 'ramekin', d: 'A small dish for baking and serving one portion' },
  { w: 'demitasse', d: 'A small cup for strong coffee' },
  { w: 'tantalus', d: 'A locked stand for bottles that lets you see them but not take them' },
  { w: 'fob', d: 'A small chain or ornament attached to a watch or keys' },
  { w: 'reticule', d: 'A small drawstring handbag' },
  { w: 'spats', d: 'Cloth coverings worn over the top of shoes and ankles' },
  { w: 'cummerbund', d: 'A wide cloth belt worn with a dinner suit' },
  { w: 'jodhpurs', d: 'Tight riding trousers, named after a city in Rajasthan' },
  { w: 'fascinator', d: 'A small decorative hat or hair piece' },
  { w: 'wimple', d: 'A cloth worn by nuns that covers the head and neck' },
  { w: 'farthingale', d: 'A hooped frame worn under old-fashioned skirts to make them stand out' },
  { w: 'brogue', d: 'A strong leather shoe with patterns of small holes' },
  { w: 'espadrille', d: 'A light canvas shoe with a rope sole' },
  { w: 'pince-nez', d: 'Glasses held on the nose by a spring, with no arms' },
  { w: 'lorgnette', d: 'Glasses held up to the eyes on a handle' },
  // Nature and science
  { w: 'gloaming', d: 'Twilight; the time just after sunset' },
  { w: 'crepuscule', d: 'Twilight' },
  { w: 'antelucan', d: 'Before dawn' },
  { w: 'matutinal', d: 'Happening in the morning' },
  { w: 'brumal', d: 'Wintry; to do with winter' },
  { w: 'aestival', d: 'To do with summer' },
  { w: 'hibernal', d: 'To do with winter' },
  { w: 'nimbus', d: 'A dark rain cloud, or a halo around a head' },
  { w: 'virga', d: 'Rain that falls from a cloud but dries up before it reaches the ground' },
  { w: 'graupel', d: 'Soft small pellets of snow and ice' },
  { w: 'haboob', d: 'A violent dust storm' },
  { w: 'williwaw', d: 'A sudden cold wind blowing down from mountains to the sea' },
  { w: 'zephyr', d: 'A soft, gentle breeze' },
  { w: 'sirocco', d: 'A hot, dusty wind that blows from North Africa' },
  { w: 'fulgurite', d: 'A glassy tube formed when lightning strikes sand' },
  { w: 'brontide', d: 'A low rumbling sound like distant thunder, heard in some places' },
  { w: 'gegenschein', d: 'A faint patch of light in the night sky opposite the Sun' },
  { w: 'noctilucent', d: 'Shining at night, like some very high clouds' },
  { w: 'gibbous', d: 'Of the Moon: more than half lit but not full' },
  { w: 'sidereal', d: 'To do with the stars' },
  { w: 'albedo', d: 'How much light a surface reflects' },
  { w: 'sastrugi', d: 'Wavy ridges on snow made by the wind' },
  { w: 'penitentes', d: 'Tall spikes of snow or ice formed high in the mountains' },
  { w: 'drumlin', d: 'A long, oval hill made by a glacier' },
  { w: 'esker', d: 'A long, winding ridge of sand and gravel left by a glacier' },
  { w: 'tarn', d: 'A small mountain lake' },
  { w: 'littoral', d: 'To do with the seashore' },
  { w: 'riparian', d: 'To do with the banks of a river' },
  { w: 'sylvan', d: 'To do with woods and forests' },
  { w: 'fossorial', d: 'Adapted for digging, like moles' },
  { w: 'piscivorous', d: 'Eating fish' },
  { w: 'frugivorous', d: 'Eating fruit' },
  { w: 'myrmecophagous', d: 'Eating ants' },
  { w: 'ursine', d: 'Like a bear' },
  { w: 'lupine', d: 'Like a wolf' },
  { w: 'porcine', d: 'Like a pig' },
  { w: 'leonine', d: 'Like a lion' },
  { w: 'corvine', d: 'Like a crow or raven' },
  { w: 'anserine', d: 'Like a goose; silly' },
  { w: 'vermiform', d: 'Shaped like a worm' },
  { w: 'pavonine', d: 'Like a peacock' },
  { w: 'murmuration', d: 'A huge flock of starlings flying together in shifting shapes' },
  { w: 'axolotl', d: 'A Mexican salamander that keeps its baby features as an adult' },
  { w: 'pangolin', d: 'An anteater covered in hard scales that rolls into a ball' },
  { w: 'aye-aye', d: 'A lemur from Madagascar with a very long thin middle finger' },
  { w: 'quokka', d: 'A small smiling-faced animal from Australia' },
  { w: 'dugong', d: 'A sea animal that eats grass, related to the manatee' },
  { w: 'blobfish', d: 'A deep-sea fish that looks like a sad jelly blob out of water' },
  { w: 'nudibranch', d: 'A colourful sea slug' },
  { w: 'tardigrade', d: 'A tiny water animal, also called a water bear, that can survive almost anything' },
  { w: 'cassowary', d: 'A large flightless bird with a horn-like crest on its head' },
  { w: 'okapi', d: 'An African animal related to the giraffe, with zebra-like stripes on its legs' },
  { w: 'galago', d: 'A small African animal with big eyes, also called a bushbaby' },
  { w: 'loris', d: 'A small slow-moving animal with big round eyes' },
  { w: 'serow', d: 'A goat-like animal found in the Himalayas' },
  { w: 'takin', d: 'A large goat-antelope found in the eastern Himalayas' },
  { w: 'dhole', d: 'The Asian wild dog' },
  { w: 'catkin', d: 'A long, hanging bunch of tiny flowers on some trees' },
  { w: 'deliquesce', d: 'To melt away, or to soak up water from the air and turn liquid' },
  { w: 'friable', d: 'Easily broken into small pieces' },
  { w: 'opalescent', d: 'Showing many shifting colours like an opal' },
  { w: 'chatoyant', d: 'Shining with a moving band of light, like a cat\'s eye' },
  { w: 'gossamer', d: 'A very fine, light thread, like a spider\'s web' },
  // Food
  { w: 'comestible', d: 'Something that can be eaten' },
  { w: 'victuals', d: 'Food and drink' },
  { w: 'viands', d: 'Food, especially fine food' },
  { w: 'collation', d: 'A light meal' },
  { w: 'elevenses', d: 'A small snack eaten in the middle of the morning' },
  { w: 'prandial', d: 'To do with a meal, especially dinner' },
  { w: 'postprandial', d: 'After a meal' },
  { w: 'gustatory', d: 'To do with taste' },
  { w: 'piquant', d: 'Pleasantly sharp or spicy in taste' },
  { w: 'toothsome', d: 'Tasty' },
  { w: 'ambrosia', d: 'The food of the gods; something delicious' },
  { w: 'macedoine', d: 'A mix of chopped fruit or vegetables' },
  { w: 'roux', d: 'A mix of butter and flour used to thicken sauces' },
  { w: 'mirepoix', d: 'Chopped onions, carrots and celery used as a base in cooking' },
  { w: 'chiffonade', d: 'Leaves cut into very thin ribbons' },
  { w: 'brunoise', d: 'Vegetables cut into very tiny cubes' },
  { w: 'sous-vide', d: 'Cooking food sealed in a bag in warm water for a long time' },
  { w: 'flummery', d: 'A soft sweet pudding; also, empty praise' },
  { w: 'syllabub', d: 'An old English dessert of whipped cream and wine' },
  { w: 'blancmange', d: 'A sweet, jelly-like milk pudding' },
  { w: 'frangipane', d: 'A sweet almond cream used in pastries' },
  { w: 'zabaglione', d: 'An Italian dessert of whipped egg yolks and sugar' },
  { w: 'kedgeree', d: 'A British dish of rice, fish and eggs that came from khichdi' },
  { w: 'mulligatawny', d: 'A spicy soup, from the Tamil words for pepper water' },
  { w: 'piccalilli', d: 'A bright yellow pickle of chopped vegetables and mustard' },
  { w: 'crudités', d: 'Raw vegetables cut up and served with a dip' },
  { w: 'amuse-bouche', d: 'A tiny free snack served before a meal' },
  { w: 'digestif', d: 'A drink taken after a meal to help digestion' },
  { w: 'aperitif', d: 'A drink taken before a meal' },
  // Doing things
  { w: 'dawdle', d: 'To waste time; to move slowly' },
  { w: 'dillydally', d: 'To waste time by not making up your mind' },
  { w: 'shilly-shally', d: 'To keep changing your mind' },
  { w: 'cunctation', d: 'Delay; putting things off' },
  { w: 'galumph', d: 'To move in a noisy, clumsy way' },
  { w: 'perambulate', d: 'To walk around' },
  { w: 'circumambulate', d: 'To walk all the way around something' },
  { w: 'traipse', d: 'To walk wearily or without a clear purpose' },
  { w: 'vamoose', d: 'To leave quickly' },
  { w: 'scarper', d: 'To run away' },
  { w: 'lollop', d: 'To move in a clumsy, bouncing way' },
  { w: 'gambol', d: 'To run and jump playfully' },
  { w: 'caper', d: 'To skip about playfully' },
  { w: 'cavort', d: 'To jump around excitedly' },
  { w: 'gurn', d: 'To pull a funny or ugly face' },
  { w: 'guffaw', d: 'To laugh loudly' },
  { w: 'chortle', d: 'To laugh happily' },
  { w: 'snigger', d: 'To laugh quietly and unkindly' },
  { w: 'titter', d: 'To laugh in a nervous, giggly way' },
  { w: 'harrumph', d: 'To clear your throat noisily to show you are annoyed' },
  { w: 'kvetch', d: 'To complain all the time' },
  { w: 'grouse', d: 'To complain; also, a kind of bird' },
  { w: 'carp', d: 'To keep complaining about small things; also, a fish' },
  { w: 'cavil', d: 'To make silly objections' },
  { w: 'wrangle', d: 'To argue for a long time' },
  { w: 'truckle', d: 'To give in to someone more powerful' },
  { w: 'wheedle', d: 'To get something by flattering someone' },
  { w: 'inveigle', d: 'To trick someone into doing something' },
  { w: 'flimflam', d: 'To cheat someone; also, nonsense' },
  { w: 'finagle', d: 'To get something by being clever or tricky' },
  { w: 'purloin', d: 'To steal' },
  { w: 'filch', d: 'To steal something small' },
  { w: 'snaffle', d: 'To take something quickly for yourself' },
  { w: 'scrounge', d: 'To get something by asking others for it' },
  { w: 'cadge', d: 'To ask for things without paying' },
  { w: 'mooch', d: 'To get things free from others; also, to hang around' },
  { w: 'loll', d: 'To sit or lie in a lazy way' },
  { w: 'fossick', d: 'To search around for something' },
  { w: 'ferret', d: 'To search hard for something; also, a small animal' },
  { w: 'kibitz', d: 'To give advice nobody asked for while others play a game' },
  { w: 'natter', d: 'To chat for a long time about small things' },
  { w: 'chinwag', d: 'A friendly chat' },
  { w: 'confabulate', d: 'To chat; also, to make up memories without meaning to' },
  { w: 'prevaricate', d: 'To avoid telling the full truth' },
  { w: 'obfuscate', d: 'To make something unclear on purpose' },
  { w: 'equivocate', d: 'To speak unclearly on purpose to avoid giving an answer' },
  { w: 'pontificate', d: 'To give opinions as if you are an expert' },
  { w: 'expostulate', d: 'To argue strongly against something' },
  { w: 'remonstrate', d: 'To complain or protest strongly' },
  { w: 'vituperate', d: 'To criticise someone angrily' },
  { w: 'castigate', d: 'To scold someone severely' },
  { w: 'excoriate', d: 'To criticise very harshly; also, to scrape off skin' },
  { w: 'lambaste', d: 'To criticise harshly' },
  { w: 'upbraid', d: 'To scold someone' },
  { w: 'pettifog', d: 'To argue over small, unimportant details' },
  { w: 'gobsmack', d: 'To amaze someone so much they cannot speak' },
  { w: 'gainsay', d: 'To deny or contradict' },
  { w: 'obviate', d: 'To remove a need or problem before it comes up' },
  { w: 'masticate', d: 'To chew food' },
  { w: 'quaff', d: 'To drink something quickly and in large gulps' },
  { w: 'gormandize', d: 'To eat greedily' },
  { w: 'nictitate', d: 'To blink' },
  { w: 'susurrate', d: 'To whisper' },
  { w: 'ululate', d: 'To make a long, high, wavering cry' },
  { w: 'caterwaul', d: 'To make a loud, ugly wailing noise, like cats fighting' },
  // Odd and old words
  { w: 'flapdragon', d: 'An old party game of snatching raisins from burning brandy' },
  { w: 'snapdragon', d: 'A garden flower; also, an old game of grabbing raisins from a flaming bowl' },
  { w: 'kakistocracy', d: 'Government by the worst, least qualified people' },
  { w: 'gerontocracy', d: 'Government by old people' },
  { w: 'kleptocracy', d: 'Government by rulers who steal from their country' },
  { w: 'ochlocracy', d: 'Rule by a mob' },
  { w: 'plutocracy', d: 'Government by the rich' },
  { w: 'sinecure', d: 'A job that pays well but needs little work' },
  { w: 'boondoggle', d: 'A useless project that wastes time and money' },
  { w: 'skulduggery', d: 'Dishonest, secret behaviour' },
  { w: 'fracas', d: 'A noisy fight' },
  { w: 'donnybrook', d: 'A noisy, wild fight' },
  { w: 'imbroglio', d: 'A very confusing and embarrassing situation' },
  { w: 'contretemps', d: 'A small disagreement or embarrassing mishap' },
  { w: 'snafu', d: 'A situation where everything has gone wrong' },
  { w: 'farrago', d: 'A confused mixture' },
  { w: 'gallimaufry', d: 'A jumble or mixture of things' },
  { w: 'olio', d: 'A mixture of different things' },
  { w: 'salmagundi', d: 'A salad of many mixed things; also, any mixture' },
  { w: 'panoply', d: 'A complete, impressive collection of things' },
  { w: 'scintilla', d: 'A tiny trace or amount' },
  { w: 'soupcon', d: 'A very small amount; a hint' },
  { w: 'scads', d: 'A large amount' },
  { w: 'sennight', d: 'A week (seven nights)' },
  { w: 'quincentenary', d: 'A 500th anniversary' },
  { w: 'sesquicentennial', d: 'A 150th anniversary' },
  { w: 'lustrum', d: 'A period of five years' },
  { w: 'quinquennial', d: 'Happening every five years' },
  { w: 'hebdomadal', d: 'Weekly' },
  { w: 'yestereve', d: 'Yesterday evening' },
  { w: 'overmorrow', d: 'The day after tomorrow' },
  { w: 'forsooth', d: 'Indeed (an old word, often used jokingly)' },
  { w: 'prithee', d: 'Please (an old word)' },
  { w: 'zounds', d: 'An old word used to show surprise or anger' },
  { w: 'gadzooks', d: 'An old word used to show surprise' },
  { w: 'egad', d: 'An old word used to show surprise' },
  { w: 'fiddle-faddle', d: 'Nonsense; trivial fuss' },
  { w: 'mubble-fubbles', d: 'A low, depressed mood' },
  { w: 'grinagog', d: 'A person who is always grinning' },
  { w: 'jollux', d: 'A fat person (an old slang word)' },
  { w: 'snoutfair', d: 'A good-looking person' },
  { w: 'stravaig', d: 'To wander about without a purpose' },
  { w: 'scurryfunge', d: 'To rush around cleaning the house just before guests arrive' },
  { w: 'grufeling', d: 'Lying comfortably wrapped up in a warm bed' },
  { w: 'hurkle-durkle', d: 'To lie in bed long after it is time to get up' },
  { w: 'beefwitted', d: 'Stupid; dull' },
  { w: 'clatterfart', d: 'A person who gossips and chatters too much' },
  { w: 'fudgel', d: 'To pretend to work when you are not working' },
  { w: 'groak', d: 'To silently watch people eat, hoping they will share' },
  { w: 'lunting', d: 'Walking while smoking a pipe' },
  { w: 'ploiter', d: 'To work at something without making progress' },
  { w: 'rawgabbit', d: 'A person who talks confidently about things they know nothing about' },
  { w: 'crambazzled', d: 'Looking worn out and old before your time from too much drinking' },
  { w: 'snirtle', d: 'To try to hold back a laugh' },
  { w: 'sillytonian', d: 'A silly person who is easily fooled' },
  { w: 'blatteroon', d: 'A person who will not stop talking' },
]
