// Dictionary Bluff words: real but rare English words, each with its meaning in plain English.

export interface BluffWord { w: string; d: string }

export const BLUFF_WORDS: BluffWord[] = [
  { w: 'petrichor', d: 'The pleasant smell of the earth after rain' },
  { w: 'defenestrate', d: 'To throw someone out of a window' },
  { w: 'borborygmus', d: 'The rumbling sound your stomach makes' },
  { w: 'sesquipedalian', d: 'Fond of using very long words' },
  { w: 'snollygoster', d: 'A clever but dishonest person, especially a politician' },
  { w: 'quidnunc', d: 'A person who always wants to know the latest gossip' },
  { w: 'lollygag', d: 'To waste time doing nothing useful' },
  { w: 'cattywampus', d: 'Crooked; not lined up properly' },
  { w: 'bumfuzzle', d: 'To confuse someone' },
  { w: 'widdershins', d: 'In the anticlockwise direction' },
  { w: 'kerfuffle', d: 'A noisy fuss or argument' },
  { w: 'flibbertigibbet', d: 'A silly person who talks too much' },
  { w: 'gongoozler', d: 'A person who likes to watch boats on a canal' },
  { w: 'absquatulate', d: 'To leave suddenly without telling anyone' },
  { w: 'taradiddle', d: 'A small lie; silly nonsense' },
  { w: 'hornswoggle', d: 'To cheat or trick someone' },
  { w: 'ultracrepidarian', d: 'A person who gives opinions on things they know nothing about' },
  { w: 'bibliopole', d: 'A person who buys and sells rare books' },
  { w: 'apricity', d: 'The warmth of the sun on a winter day' },
  { w: 'phosphene', d: 'The lights and colours you see when you rub your closed eyes' },
  { w: 'tmesis', d: 'Breaking a word into two by putting another word in the middle, as in "abso-very-lutely"' },
  { w: 'zugzwang', d: 'In chess, a position where every possible move makes things worse' },
  { w: 'yarborough', d: 'A hand of cards with no card higher than a nine' },
  { w: 'pandiculation', d: 'Stretching your body while yawning, usually after waking up' },
  { w: 'philtrum', d: 'The small groove between your nose and your upper lip' },
  { w: 'glabella', d: 'The smooth part of the forehead between the eyebrows' },
  { w: 'lunule', d: 'The white half-moon shape at the bottom of a fingernail' },
  { w: 'aglet', d: 'The plastic or metal tip at the end of a shoelace' },
  { w: 'ferrule', d: 'The metal band that holds the eraser on a pencil' },
  { w: 'tittle', d: 'The dot over a small letter i or j' },
  { w: 'zarf', d: 'A holder for a hot cup that has no handle' },
  { w: 'muntin', d: 'A strip of wood that separates the glass panes of a window' },
  { w: 'obelus', d: 'The ÷ sign used for division' },
  { w: 'octothorpe', d: 'The # symbol, also called the hash' },
  { w: 'interrobang', d: 'A punctuation mark that combines a question mark and an exclamation mark' },
  { w: 'jentacular', d: 'To do with breakfast' },
  { w: 'deipnosophist', d: 'A person who is good at conversation over dinner' },
  { w: 'nudiustertian', d: 'Of the day before yesterday' },
  { w: 'crepuscular', d: 'Active at dawn and dusk, like some animals' },
  { w: 'vespertine', d: 'Active or blooming in the evening' },
  { w: 'susurrus', d: 'A soft whispering or rustling sound' },
  { w: 'tintinnabulation', d: 'The ringing sound of bells' },
  { w: 'mumpsimus', d: 'A person who sticks to a mistake even after being shown it is wrong' },
  { w: 'logomachy', d: 'An argument about the meaning of words' },
  { w: 'floccinaucinihilipilification', d: 'The habit of thinking that something is worthless' },
  { w: 'bloviate', d: 'To talk for a long time in a show-off way' },
  { w: 'collywobbles', d: 'A nervous, uneasy feeling in the stomach' },
  { w: 'erinaceous', d: 'Like a hedgehog' },
  { w: 'vulpine', d: 'Like a fox; sly and clever' },
  { w: 'lucubration', d: 'Hard study or writing done late at night' },
  { w: 'omphalos', d: 'The belly button; also, the centre of something' },
  { w: 'uxorious', d: 'Too fond of, or too obedient to, one\'s wife' },
  { w: 'ninnyhammer', d: 'A foolish person' },
  { w: 'slubberdegullion', d: 'A dirty, lazy, good-for-nothing person' },
  { w: 'cachinnate', d: 'To laugh very loudly' },
  { w: 'tergiversate', d: 'To keep changing your opinion or side' },
  { w: 'perendinate', d: 'To put something off until the day after tomorrow' },
  { w: 'snickersnee', d: 'A large knife used as a weapon' },
  { w: 'canoodle', d: 'To kiss and cuddle' },
  { w: 'pettifogger', d: 'A lawyer who handles small cases using petty tricks' },
  { w: 'popinjay', d: 'A vain person who loves to show off' },
  { w: 'mollycoddle', d: 'To treat someone too gently; to pamper' },
  { w: 'rigmarole', d: 'A long and complicated process' },
  { w: 'myrmidon', d: 'A follower who obeys orders without asking questions' },
  { w: 'fugacious', d: 'Lasting only a short time' },
  { w: 'pulchritude', d: 'Beauty' },
  { w: 'defalcate', d: 'To steal money that you were trusted to look after' },
  { w: 'impignorate', d: 'To pawn something' },
  { w: 'gardyloo', d: 'A warning shout before throwing dirty water out of a window' },
  { w: 'smellfungus', d: 'A person who complains about everything' },
  { w: 'pogonophobia', d: 'Fear of beards' },
  { w: 'ailurophile', d: 'A person who loves cats' },
  { w: 'agelast', d: 'A person who never laughs' },
  { w: 'spaghettification', d: 'The stretching of an object into a long thin shape by a black hole\'s gravity' },
  { w: 'palimpsest', d: 'A page that was written on, rubbed clean and written on again' },
  { w: 'sobriquet', d: 'A nickname' },
  { w: 'pareidolia', d: 'Seeing faces or shapes in random things, like clouds' },
  { w: 'syzygy', d: 'When three bodies in space, such as the Sun, Moon and Earth, line up' },
  { w: 'tatterdemalion', d: 'A person dressed in torn, ragged clothes' },
  { w: 'yex', d: 'To hiccup' },
  { w: 'gormless', d: 'Foolish; lacking common sense' },
  { w: 'frisson', d: 'A sudden feeling of excitement or fear' },
  { w: 'brouhaha', d: 'A noisy fuss about something unimportant' },
  { w: 'flummox', d: 'To confuse someone completely' },
  { w: 'higgledy-piggledy', d: 'Mixed up and messy' },
  { w: 'crapulence', d: 'Feeling sick after eating or drinking too much' },
  { w: 'bumbershoot', d: 'An umbrella' },
  { w: 'snood', d: 'A loose net or band worn over the hair' },
  { w: 'wamble', d: 'To feel sick in the stomach' },
  { w: 'gubbins', d: 'Bits and pieces; small useless things' },
  { w: 'fopdoodle', d: 'A foolish or silly person' },
  { w: 'lickspittle', d: 'A person who flatters important people to get favours' },
]
