// Connections groups. A board takes four groups that share no word and no theme, so each board has one answer.
// Each row: [group name, level 1 easy … 4 tricky, themes the words could also belong to, the words (4 or 5; a board
// shows 4)]. Two groups with a theme in common never share a board.
export interface Group { name: string; level: number; tags: string[]; words: string[] }

const RAW: [string, number, string, string][] = [
  // ---------- easy: plain categories ----------
  ['Indian rivers', 1, 'river geo', 'Ganga, Yamuna, Godavari, Kaveri, Narmada'],
  ['Planets', 1, 'space', 'Mercury, Venus, Jupiter, Saturn, Neptune'],
  ['Indian sweets', 1, 'food', 'Jalebi, Rasgulla, Barfi, Ladoo, Peda'],
  ['Fruits', 1, 'food', 'Guava, Papaya, Lychee, Pomegranate, Chikoo'],
  ['Musical instruments', 1, 'music', 'Tabla, Sitar, Veena, Harmonium, Sarod'],
  ['Big Indian cities', 1, 'city geo', 'Mumbai, Chennai, Kolkata, Hyderabad, Pune'],
  ['Vegetables', 1, 'food', 'Brinjal, Okra, Cauliflower, Spinach, Radish'],
  ['Birds', 1, 'animal', 'Sparrow, Parrot, Peacock, Pigeon, Crow'],
  ['Wild animals', 1, 'animal', 'Tiger, Leopard, Rhino, Hippo, Cheetah'],
  ['In an Indian kitchen', 1, 'home kitchen', 'Tawa, Kadhai, Belan, Pressure cooker, Chakla'],
  ['Months', 1, 'time', 'January, March, August, October, December'],
  ['Days of the week', 1, 'time', 'Monday, Tuesday, Thursday, Saturday, Sunday'],
  ['Spices', 1, 'food', 'Turmeric, Cumin, Cardamom, Clove, Cinnamon'],
  ['Shapes', 1, 'maths', 'Circle, Triangle, Square, Hexagon, Oval'],
  ['Weather', 1, 'weather', 'Rain, Fog, Thunder, Hail, Drizzle'],
  ['Footwear', 1, 'clothes', 'Sandal, Slipper, Sneaker, Boot, Chappal'],
  ['Indian clothes', 1, 'clothes', 'Kurta, Saree, Lehenga, Sherwani, Dhoti'],
  ['Sea creatures', 1, 'animal sea', 'Octopus, Dolphin, Starfish, Jellyfish, Whale'],
  ['Insects', 1, 'animal', 'Ant, Mosquito, Butterfly, Cockroach, Grasshopper'],
  ['Flowers', 1, 'plant', 'Rose, Lotus, Marigold, Jasmine, Sunflower'],
  ['Trees', 1, 'plant', 'Neem, Banyan, Peepal, Coconut, Teak'],
  ['In a classroom', 1, 'school', 'Blackboard, Chalk, Duster, Bench, Register'],
  ['Stationery', 1, 'school', 'Pencil, Eraser, Sharpener, Stapler, Ruler'],
  ['Indian breads', 1, 'food', 'Roti, Naan, Paratha, Kulcha, Bhatura'],
  ['Rice dishes', 1, 'food', 'Biryani, Pulao, Khichdi, Curd rice, Lemon rice'],
  ['Drinks', 1, 'food', 'Lassi, Chai, Coffee, Nimbu pani, Jaljeera'],
  ['Chai-time snacks', 1, 'food', 'Samosa, Pakora, Kachori, Vada, Mathri'],
  ['Board games', 1, 'game', 'Ludo, Chess, Carrom, Monopoly, Scrabble'],
  ['Sports', 1, 'sport', 'Hockey, Kabaddi, Badminton, Tennis, Wrestling'],
  ['Joints', 1, 'body', 'Elbow, Knee, Ankle, Wrist, Shoulder'],
  ['On your face', 1, 'body', 'Nose, Chin, Cheek, Eyebrow, Forehead'],
  ['Relatives', 1, 'family person', 'Mausi, Chacha, Bua, Mama, Nani'],
  ['In a bathroom', 1, 'home', 'Bucket, Mug, Geyser, Towel, Soap'],
  ['Furniture', 1, 'home', 'Sofa, Cupboard, Almirah, Stool, Bed'],
  ['Vehicles', 1, 'vehicle', 'Auto, Bus, Truck, Scooter, Tractor'],
  ['Jobs', 1, 'job person', 'Doctor, Teacher, Plumber, Pilot, Tailor'],
  ['Feelings', 1, 'feeling', 'Happy, Angry, Jealous, Nervous, Proud'],
  ['Metals', 1, 'element', 'Iron, Copper, Silver, Zinc, Aluminium'],
  ['Gems', 1, 'jewel', 'Ruby, Emerald, Sapphire, Diamond, Pearl'],
  ['Continents', 1, 'geo', 'Asia, Africa, Europe, Australia, Antarctica'],
  ['Oceans and seas', 1, 'geo sea', 'Pacific, Atlantic, Arabian, Arctic, Caribbean'],
  ['Festivals', 1, 'festival', 'Diwali, Holi, Eid, Onam, Baisakhi'],
  ['Up in the sky', 1, 'space weather', 'Cloud, Rainbow, Moon, Comet, Kite'],
  ['Farm animals', 1, 'animal', 'Cow, Buffalo, Goat, Sheep, Hen'],
  ['Pets', 1, 'animal', 'Dog, Cat, Rabbit, Goldfish, Hamster'],
  ['Dals', 1, 'food', 'Moong, Masoor, Toor, Urad, Chana'],
  ['Ways to cook', 1, 'kitchen', 'Boil, Fry, Roast, Steam, Bake'],
  ['Heroes of the 90s', 1, 'film person', 'Shah Rukh, Salman, Aamir, Govinda, Akshay'],
  ['Cricket shots', 1, 'cricket', 'Cut, Pull, Sweep, Hook, Drive'],
  ['Fielding positions', 1, 'cricket', 'Slip, Gully, Point, Mid-off, Fine leg'],
  ['Ways to get out', 1, 'cricket', 'Bowled, Caught, Stumped, Run out, LBW'],
  ['Social media apps', 1, 'tech', 'Instagram, WhatsApp, Snapchat, Facebook, Threads'],
  ['Computer parts', 1, 'tech', 'Keyboard, Mouse, Monitor, Speaker, Webcam'],
  ['Beach bag', 1, 'travel', 'Sunscreen, Goggles, Flip-flops, Hat, Umbrella'],
  ['Colours', 1, 'colour', 'Maroon, Turquoise, Beige, Lavender, Magenta'],
  ['Wedding events', 1, 'wedding', 'Mehendi, Sangeet, Baraat, Pheras, Vidaai'],
  ['On a cricket ground', 1, 'cricket', 'Stumps, Bails, Crease, Pitch, Boundary'],
  ['Parts of a tree', 1, 'plant', 'Root, Trunk, Branch, Leaf, Bark'],
  ['Parts of a house', 1, 'home', 'Roof, Balcony, Staircase, Terrace, Verandah'],
  ['Desserts', 1, 'food', 'Kheer, Halwa, Kulfi, Phirni, Rabri'],
  ['Indian states', 1, 'geo state', 'Kerala, Punjab, Assam, Gujarat, Odisha'],
  ['Hill stations', 1, 'geo travel', 'Shimla, Manali, Ooty, Darjeeling, Munnar'],
  ['Mountains', 1, 'geo', 'Everest, Kanchenjunga, Kilimanjaro, Fuji, Nanda Devi'],
  ['Deserts', 1, 'geo', 'Thar, Sahara, Gobi, Kalahari, Atacama'],
  ['Currencies', 1, 'money', 'Rupee, Dollar, Euro, Yen, Pound'],
  ['Languages of India', 1, 'language', 'Tamil, Bengali, Marathi, Kannada, Malayalam'],
  ['Dances of India', 1, 'dance', 'Bharatanatyam, Kathak, Bhangra, Garba, Odissi'],
  ['Film villains', 1, 'film person', 'Gabbar, Mogambo, Shakaal, Kancha, Crime Master Gogo'],
  ['Superheroes', 1, 'film person', 'Batman, Spider-Man, Krrish, Shaktimaan, Thor'],
  ['Cartoon characters', 1, 'cartoon person', 'Doraemon, Shinchan, Chhota Bheem, Tom, Mickey'],
  ['Chess pieces', 1, 'game person', 'King, Queen, Rook, Bishop, Knight'],
  ['Card suits', 1, 'game', 'Hearts, Spades, Clubs, Diamonds'],
  ['Units of length', 1, 'unit', 'Metre, Inch, Foot, Mile, Kilometre'],
  ['Units of weight', 1, 'unit', 'Gram, Kilo, Tonne, Ounce, Quintal'],
  ['Maths operations', 1, 'maths', 'Add, Subtract, Multiply, Divide'],
  ['Things with keys', 1, 'tech home music', 'Piano, Laptop, Lock, Typewriter'],
  ['Bags', 1, 'travel', 'Backpack, Suitcase, Purse, Tiffin bag, Duffel'],
  ['Hairstyles', 1, 'body', 'Ponytail, Braid, Bun, Fringe, Mohawk'],
  ['In a garden', 1, 'plant home', 'Hose, Swing, Flower pot, Fountain, Lawn'],
  ['Baby animals', 1, 'animal', 'Puppy, Kitten, Calf, Cub, Lamb'],
  ['Animal sounds', 1, 'animal sound', 'Moo, Bark, Roar, Hiss, Quack'],
  ['Exam words', 1, 'school', 'Syllabus, Revision, Admit card, Result, Topper'],
  ['Office words', 1, 'job', 'Meeting, Deadline, Appraisal, Salary, Boss'],
  ['At a railway station', 1, 'travel train', 'Platform, Coolie, Ticket counter, Waiting room, Signal'],
  ['At an airport', 1, 'travel', 'Boarding pass, Runway, Check-in, Gate, Terminal'],
  ['In a hospital', 1, 'health job', 'Stretcher, Ward, Injection, Bandage, Nurse'],
  ['Illnesses', 1, 'health', 'Fever, Cough, Cold, Dengue, Malaria'],
  ['Sports shoes', 1, 'sport clothes', 'Spikes, Studs, Trainers, Cleats'],
  ['Martial arts', 1, 'sport', 'Karate, Judo, Kung fu, Taekwondo, Kalaripayattu'],
  ['Athletics events', 1, 'sport', 'Javelin, Discus, Shot put, Hurdles, Marathon'],
  ['At a bank', 1, 'money', 'Cheque, Passbook, Locker, ATM, Loan'],
  ['At a bakery', 1, 'food', 'Bun, Croissant, Baguette, Pav, Rusk'],
  ['Pizza toppings', 1, 'food', 'Olives, Mushroom, Jalapeno, Paneer tikka, Sweet corn'],
  ['Ice cream flavours', 1, 'food', 'Vanilla, Chocolate, Butterscotch, Strawberry, Pista'],
  ['Cold things', 1, 'weather food', 'Ice, Snow, Freezer, Glacier, Popsicle'],
  ['Hot things', 1, 'weather food', 'Sun, Lava, Oven, Chilli, Tandoor'],

  // ---------- medium: a bit more to know ----------
  ['Indian cricketers', 2, 'cricket person', 'Tendulkar, Dhoni, Kohli, Dravid, Kumble'],
  ['Mughal emperors', 2, 'history person', 'Babur, Humayun, Akbar, Jahangir, Aurangzeb'],
  ['Monuments', 2, 'monument', 'Charminar, Hawa Mahal, Gateway of India, Red Fort, Qutub Minar'],
  ['Shah Rukh Khan films', 2, 'film', 'Swades, Chak De India, Devdas, Pathaan, Jawan'],
  ['Aamir Khan films', 2, 'film', 'Lagaan, Dangal, PK, Ghajini, Taare Zameen Par'],
  ['Amitabh Bachchan films', 2, 'film', 'Sholay, Deewaar, Zanjeer, Don, Piku'],
  ['Board exam subjects', 2, 'school', 'Physics, Chemistry, Biology, Economics, Accountancy'],
  ['Baraat things', 2, 'wedding', 'Dhol, Shehnai, Ghodi, Doli, Sehra'],
  ['IPL teams', 2, 'cricket', 'CSK, MI, RCB, KKR, SRH'],
  ['Car makers', 2, 'brand vehicle', 'Maruti, Hyundai, Tata, Mahindra, Toyota'],
  ['Phone brands', 2, 'brand tech', 'Samsung, Apple, OnePlus, Xiaomi, Vivo'],
  ['Shoe brands', 2, 'brand clothes animal', 'Nike, Adidas, Puma, Bata, Reebok'],
  ['Fast food chains', 2, 'brand food', 'McDonald\'s, KFC, Domino\'s, Subway, Burger King'],
  ['Biscuits', 2, 'brand food', 'Parle-G, Marie, Bourbon, Hide & Seek, Monaco'],
  ['Chocolate bars', 2, 'brand food', 'Dairy Milk, KitKat, Five Star, Munch, Perk'],
  ['Cold drinks', 2, 'brand food', 'Thums Up, Limca, Frooti, Maaza, Sprite'],
  ['Harry Potter words', 2, 'book', 'Hogwarts, Quidditch, Horcrux, Muggle, Dementor'],
  ['Avengers', 2, 'film person', 'Hulk, Black Widow, Hawkeye, Iron Man, Captain America'],
  ['Friends characters', 2, 'tv person', 'Joey, Chandler, Monica, Phoebe, Ross'],
  ['Old TV shows', 2, 'tv', 'CID, Shaktimaan, Mahabharat, Office Office, Malgudi Days'],
  ['Reality shows', 2, 'tv', 'KBC, Indian Idol, Roadies, Shark Tank, Bigg Boss'],
  ['Scientists', 2, 'science person', 'Newton, Einstein, Raman, Curie, Darwin'],
  ['Painters', 2, 'art person', 'Picasso, Van Gogh, Husain, Raja Ravi Varma, Da Vinci'],
  ['Freedom fighters', 2, 'history person', 'Bhagat Singh, Rani Laxmibai, Subhas Chandra Bose, Sardar Patel, Lala Lajpat Rai'],
  ['Prime ministers', 2, 'history person', 'Nehru, Shastri, Vajpayee, Manmohan Singh, Indira Gandhi'],
  ['World capitals', 2, 'city geo', 'Paris, Tokyo, Cairo, Canberra, Ottawa'],
  ['South American countries', 2, 'geo country', 'Brazil, Argentina, Chile, Peru, Colombia'],
  ['India\'s neighbours', 2, 'geo country', 'Nepal, Bhutan, Bangladesh, Myanmar, Sri Lanka'],
  ['European countries', 2, 'geo country', 'Spain, Germany, Norway, Greece, Portugal'],
  ['Rivers of the world', 2, 'river geo', 'Nile, Amazon, Thames, Danube, Mississippi'],
  ['Dog breeds', 2, 'animal', 'Labrador, Beagle, Pug, Dalmatian, Husky'],
  ['Snakes', 2, 'animal', 'Cobra, Python, Viper, Krait, Anaconda'],
  ['Out in space', 2, 'space', 'Galaxy, Nebula, Black hole, Asteroid, Satellite'],
  ['ISRO missions', 2, 'space', 'Chandrayaan, Mangalyaan, Aditya-L1, Gaganyaan'],
  ['Parts of the eye', 2, 'body', 'Retina, Pupil, Iris, Cornea, Lens'],
  ['Organs', 2, 'body', 'Liver, Kidney, Lungs, Heart, Brain'],
  ['Bones', 2, 'body', 'Skull, Rib, Spine, Femur, Collarbone'],
  ['Gases', 2, 'element science', 'Oxygen, Hydrogen, Carbon dioxide, Nitrogen, Helium'],
  ['Kinds of triangle', 2, 'maths', 'Equilateral, Isosceles, Scalene, Right-angled'],
  ['Programming languages', 2, 'tech animal', 'Python, Java, Ruby, Swift, Rust'],
  ['Yoga poses', 2, 'health', 'Tree pose, Cobra pose, Child\'s pose, Downward dog, Lotus pose'],
  ['Kinds of tea', 2, 'food', 'Masala, Green, Ginger, Lemon, Kashmiri kahwa'],
  ['Coffee drinks', 2, 'food', 'Espresso, Latte, Cappuccino, Mocha, Filter coffee'],
  ['South Indian breakfast', 2, 'food', 'Idli, Dosa, Upma, Pongal, Appam'],
  ['Mumbai street food', 2, 'food', 'Vada pav, Pav bhaji, Bhel puri, Ragda pattice, Bombay sandwich'],
  ['Kebabs', 2, 'food', 'Seekh, Galouti, Shami, Reshmi, Kakori'],
  ['Paneer dishes', 2, 'food', 'Shahi paneer, Palak paneer, Kadai paneer, Paneer bhurji, Matar paneer'],
  ['On a thali', 2, 'food', 'Raita, Papad, Salad, Sabzi, Dal'],
  ['Bengali food', 2, 'food', 'Mishti doi, Sandesh, Machher jhol, Luchi, Kosha mangsho'],
  ['In Goa', 2, 'travel', 'Baga, Calangute, Feni, Dudhsagar, Anjuna'],
  ['Boats', 2, 'vehicle sea', 'Canoe, Ferry, Yacht, Kayak, Houseboat'],
  ['Shops', 2, 'shop job', 'Kirana, Chemist, Stationer, Florist, Barber'],
  ['At a barber', 2, 'shop', 'Razor, Scissors, Comb, Trimmer, Foam'],
  ['Pet names for a partner', 2, 'love talk', 'Darling, Sweetheart, Jaan, Babu, Shona'],
  ['At a gym', 2, 'health', 'Treadmill, Dumbbell, Barbell, Bench press, Protein shake'],
  ['Exercises', 2, 'health', 'Push-up, Squat, Plank, Burpee, Lunge'],
  ['At a mela', 2, 'fair', 'Ferris wheel, Candy floss, Bumper cars, Merry-go-round, Ring toss'],
  ['At a circus', 2, 'fair person', 'Clown, Juggler, Trapeze, Ringmaster, Tightrope'],
  ['Divine weapons in the epics', 2, 'myth', 'Gandiva, Sudarshan Chakra, Brahmastra, Pashupatastra, Trishul'],
  ['Pandavas', 2, 'myth person', 'Yudhishthira, Bhima, Arjuna, Nakula, Sahadeva'],
  ['Greek gods', 2, 'myth person', 'Zeus, Poseidon, Athena, Apollo, Hermes'],
  ['Hindi numbers', 2, 'number', 'Ek, Do, Teen, Char, Paanch'],
  ['Roman numerals', 2, 'number letter', 'X, V, L, C, M'],
  ['Pasta', 2, 'food', 'Penne, Fusilli, Spaghetti, Macaroni, Lasagne'],
  ['Cheeses', 2, 'food', 'Cheddar, Mozzarella, Parmesan, Feta, Gouda'],
  ['Nuts', 2, 'food', 'Almond, Cashew, Walnut, Pistachio, Peanut'],
  ['Party games', 2, 'game', 'Antakshari, Dumb charades, Musical chairs, Truth or dare, Passing the parcel'],
  ['Detectives', 2, 'book tv person', 'Sherlock, Byomkesh, Feluda, Poirot, Karamchand'],
  ['Comic book villains', 2, 'film person', 'Joker, Thanos, Loki, Venom, Magneto'],
  ['Disney princesses', 2, 'film cartoon person', 'Cinderella, Ariel, Jasmine, Elsa, Moana'],
  ['Pixar films', 2, 'film cartoon', 'Toy Story, Up, Coco, Ratatouille, Inside Out'],
  ['Kinds of cloud', 2, 'weather science', 'Cumulus, Cirrus, Stratus, Nimbus'],
  ['Storms', 2, 'weather', 'Cyclone, Tornado, Typhoon, Hurricane, Blizzard'],
  ['In a newspaper', 2, 'news', 'Headline, Editorial, Classifieds, Horoscope, Crossword'],
  ['Parts of a book', 2, 'book', 'Chapter, Index, Preface, Cover, Spine'],
  ['Punctuation', 2, 'letter', 'Comma, Colon, Hyphen, Apostrophe, Full stop'],
  ['In a wallet', 2, 'money', 'Cash, Debit card, Aadhaar, Coins, Receipts'],
  ['UPI apps', 2, 'brand tech money', 'Paytm, PhonePe, Google Pay, BHIM, Amazon Pay'],
  ['Shopping apps', 2, 'brand tech shop', 'Amazon, Flipkart, Myntra, Meesho, Nykaa'],
  ['Delivery apps', 2, 'brand tech food', 'Zomato, Swiggy, Blinkit, Zepto, Instamart'],
  ['Streaming apps', 2, 'brand tech tv', 'Netflix, Hotstar, Prime Video, JioCinema, SonyLIV'],
  ['Ride apps', 2, 'brand tech vehicle', 'Uber, Ola, Rapido, BluSmart, InDrive'],
  ['In a cricket kit', 2, 'cricket', 'Bat, Pads, Gloves, Helmet, Abdomen guard'],
  ['Tennis players', 2, 'sport person', 'Federer, Nadal, Djokovic, Serena, Sania'],
  ['Footballers', 2, 'sport person', 'Messi, Ronaldo, Neymar, Mbappe, Chhetri'],
  ['Indian Olympic medallists', 2, 'sport person', 'Neeraj Chopra, Abhinav Bindra, P V Sindhu, Mary Kom, Mirabai Chanu'],
  ['On a phone call', 2, 'talk', 'Hello, Can you hear me, Network issue, Call you back, Bye'],
  ['Entrance exams', 2, 'school', 'JEE, NEET, CAT, UPSC, GATE'],
  ['In college', 2, 'school', 'Canteen, Hostel, Library, Fest, Placement'],
  ['Hostel life', 2, 'school', 'Warden, Mess, Maggi, Roommate, Curfew'],
  ['Men\'s haircuts', 2, 'body', 'Crew cut, Undercut, Buzz cut, Fade, Side part'],
  ['On your head', 2, 'clothes', 'Turban, Cap, Topi, Dupatta, Bandana'],
  ['Jewellery', 2, 'jewel', 'Nose ring, Anklet, Bangle, Earring, Mangalsutra'],
  ['Makeup', 2, 'beauty', 'Kajal, Lipstick, Foundation, Blush, Mascara'],
  ['Skincare', 2, 'beauty', 'Toner, Serum, Moisturiser, Face wash, Sunscreen gel'],

  // ---------- hard: you need to know a bit more ----------
  ['Bowling styles', 3, 'cricket', 'Off-spin, Leg-spin, Yorker, Bouncer, Googly'],
  ['Cricket words', 3, 'cricket', 'Duck, Hat-trick, Maiden, Century, Powerplay'],
  ['In Sholay', 3, 'film', 'Ramgarh, Jai and Veeru, Basanti, Thakur, Kitne aadmi the'],
  ['In DDLJ', 3, 'film', 'Mustard fields, Raj and Simran, Ja Simran ja, Palat, Train scene'],
  ['Mahabharata characters', 3, 'myth person', 'Karna, Bhishma, Draupadi, Shakuni, Duryodhana'],
  ['Ramayana characters', 3, 'myth person', 'Hanuman, Lakshman, Ravana, Sita, Vibhishana'],
  ['Akbar\'s court', 3, 'history person', 'Birbal, Tansen, Todar Mal, Abul Fazl'],
  ['Forts of Rajasthan', 3, 'monument geo', 'Amer, Mehrangarh, Chittorgarh, Jaisalmer, Kumbhalgarh'],
  ['UNESCO sites in India', 3, 'monument geo', 'Hampi, Khajuraho, Ajanta, Ellora, Konark'],
  ['National parks', 3, 'animal geo', 'Kaziranga, Jim Corbett, Ranthambore, Gir, Sundarbans'],
  ['North-East states', 3, 'geo state', 'Mizoram, Nagaland, Manipur, Tripura, Meghalaya'],
  ['Union territories', 3, 'geo state', 'Lakshadweep, Puducherry, Chandigarh, Ladakh, Andaman and Nicobar'],
  ['Old names of cities', 3, 'city geo', 'Bombay, Madras, Calcutta, Poona, Baroda'],
  ['Port cities', 3, 'city geo sea', 'Visakhapatnam, Kochi, Mangaluru, Paradip, Kandla'],
  ['Words for money', 3, 'money talk', 'Paisa, Dough, Moolah, Bucks, Lakhs'],
  ['What friends call each other', 3, 'talk', 'Bro, Yaar, Dude, Buddy, Bhai'],
  ['Hinglish', 3, 'talk word', 'Timepass, Jugaad, Prepone, Pakka, Cousin brother'],
  ['Things mom says', 3, 'talk family', 'Sweater pehno, Khana kha lo, Phone rakh do, Sharma ji ka beta, Light band karo'],
  ['WhatsApp things', 3, 'tech', 'Blue tick, Last seen, Status, Group admin, Forwarded many times'],
  ['Instagram things', 3, 'tech', 'Reel, Story, Close friends, Finsta, Explore page'],
  ['Things coders say', 3, 'tech', 'It works on my machine, Bug, Deploy, Merge conflict, Stack Overflow'],
  ['Keyboard shortcuts', 3, 'tech', 'Ctrl C, Ctrl V, Ctrl Z, Alt Tab, Ctrl S'],
  ['In a chemistry lab', 3, 'science school', 'Beaker, Burette, Pipette, Test tube, Litmus'],
  ['Physics words', 3, 'science school', 'Gravity, Friction, Inertia, Momentum, Velocity'],
  ['Angles', 3, 'maths', 'Acute, Obtuse, Reflex, Right angle, Straight angle'],
  ['Things with eight', 3, 'number', 'Spider legs, Octopus arms, Octagon sides, Bits in a byte'],
  ['Things with seven', 3, 'number', 'Colours in a rainbow, Days in a week, Wonders of the world, Notes of sargam'],
  ['Things with eleven', 3, 'number cricket', 'Cricket team, Football team, Ocean\'s Eleven, Stranger Things girl'],
  ['Sanskrit words in English', 3, 'word', 'Avatar, Karma, Guru, Mantra, Nirvana'],
  ['Hindi words in English', 3, 'word', 'Jungle, Shampoo, Pyjamas, Bungalow, Thug'],
  ['Brands named after animals', 3, 'brand animal vehicle', 'Jaguar, Red Bull, Mustang, Dove, Lacoste'],
  ['Famous Gandhis', 3, 'history person', 'Mahatma, Indira, Rajiv, Kasturba, Sonia'],
  ['Famous Kumars', 3, 'film person', 'Akshay Kumar, Kishore Kumar, Dilip Kumar, Manoj Kumar, Rajendra Kumar'],
  ['Famous Kapoors', 3, 'film person', 'Raj Kapoor, Shashi Kapoor, Ranbir Kapoor, Kareena Kapoor, Anil Kapoor'],
  ['Famous Singhs', 3, 'person', 'Yuvraj, Harbhajan, Milkha, Arijit, Diljit'],
  ['Famous Chopras', 3, 'person', 'Priyanka, Parineeti, Yash, Aditya, Neeraj'],
  ['Famous Sharmas', 3, 'person', 'Rohit, Anushka, Ishant, Kapil, Kartik'],
  ['Famous Bachchans', 3, 'film person', 'Amitabh, Jaya, Abhishek, Aishwarya, Harivansh Rai'],
  ['In every film climax', 3, 'film', 'Godown, Police arriving late, Mother crying, Last-minute twist, Villain\'s speech'],
  ['In a Bollywood dream song', 3, 'film', 'Swiss Alps, Chiffon saree, Fog machine, Slow motion, Wind in the hair'],
  ['Shah Rukh is Rahul or Raj', 3, 'film', 'Kuch Kuch Hota Hai, Dil To Pagal Hai, Chennai Express, Yes Boss, Mohabbatein'],
  ['Rajinikanth films', 3, 'film', 'Sivaji, Enthiran, Kabali, Jailer, Baasha'],
  ['Rajkumar Hirani films', 3, 'film', 'Munna Bhai MBBS, Lage Raho Munna Bhai, Sanju, Dunki'],
  ['A number in the title', 3, 'film number', '3 Idiots, 2 States, 102 Not Out, 1920, 83'],
  ['Films with "Dil"', 3, 'film', 'Dil Chahta Hai, Dil Se, Dilwale, Dil Dhadakne Do, Dil Bechara'],
  ['Cricket World Cup winners', 3, 'cricket country geo', 'West Indies, Australia, England, Pakistan'],
  ['Business leaders', 3, 'person money', 'Ratan Tata, Mukesh Ambani, Narayana Murthy, Azim Premji, Kiran Mazumdar-Shaw'],
  ['Tech CEOs', 3, 'person tech', 'Sundar Pichai, Satya Nadella, Elon Musk, Tim Cook, Mark Zuckerberg'],
  ['Singers', 3, 'music person', 'Lata Mangeshkar, Asha Bhosle, Shreya Ghoshal, Sonu Nigam, Udit Narayan'],
  ['Music directors', 3, 'music person', 'A R Rahman, Pritam, Vishal-Shekhar, Shankar-Ehsaan-Loy, Amit Trivedi'],
  ['Comedians', 3, 'person tv', 'Zakir Khan, Bhuvan Bam, Johnny Lever, Rajpal Yadav, Kapil Sharma'],
  ['On KBC', 3, 'tv', 'Lifeline, Fastest finger first, Computer ji, Lock kiya jaye, Audience poll'],
  ['On Bigg Boss', 3, 'tv', 'Housemates, Eviction, Captaincy task, Weekend Ka Vaar, Nomination'],
  ['Taarak Mehta characters', 3, 'tv person', 'Jethalal, Daya, Babita, Bhide, Tapu'],
  ['Chhota Bheem characters', 3, 'cartoon person', 'Raju, Chutki, Kalia, Dholu, Bholu'],
  ['Doraemon gadgets', 3, 'cartoon', 'Anywhere Door, Bamboo copter, Time machine, Memory bread, Small light'],
  ['Pokemon', 3, 'cartoon game', 'Pikachu, Charmander, Bulbasaur, Squirtle, Jigglypuff'],
  ['Video games', 3, 'game tech', 'Minecraft, PUBG, Free Fire, GTA, Fortnite'],
  ['Phone games', 3, 'game tech', 'Temple Run, Subway Surfers, Candy Crush, Angry Birds, Clash of Clans'],
  ['Chess words', 3, 'game', 'Checkmate, Castling, Stalemate, Gambit, En passant'],
  ['Teen Patti words', 3, 'game', 'Blind, Chaal, Show, Trail, Pure sequence'],
  ['On a Monopoly board', 3, 'game', 'Jail, Chance, Community Chest, Free Parking, Go'],
  ['Carrom words', 3, 'game', 'Striker, Pocket, Rebound, Red coin, Foul'],
  ['Parts of a bicycle', 3, 'vehicle', 'Handlebar, Kickstand, Mudguard, Spokes, Chain'],
  ['On Indian roads', 3, 'vehicle', 'Zebra crossing, Speed breaker, Toll plaza, Flyover, Pothole'],
  ['On an Indian train', 3, 'travel train', 'Berth, TT, Pantry car, Tatkal, Chain pulling'],
  ['Monsoon', 3, 'weather', 'Puddle, Waterlogging, Gumboots, Leaking roof, Wet socks'],
  ['North Indian winter', 3, 'weather', 'Rajai, Heater, Gajar halwa, Monkey cap, Bonfire'],
  ['Indian summer', 3, 'weather', 'Cooler, Power cut, Aam panna, Mango shake, Summer vacation'],
  ['At a Holi party', 3, 'festival', 'Gulal, Pichkari, Bhang, Gujiya, Water balloons'],
  ['Diwali', 3, 'festival', 'Diya, Rangoli, Crackers, Lakshmi puja, Sweets box'],
  ['Christmas', 3, 'festival', 'Santa, Carol, Stocking, Plum cake, Mistletoe'],
  ['Eid', 3, 'festival', 'Sewaiyan, Eidi, Moon sighting, Iftar, Sheer khurma'],
  ['Navratri', 3, 'festival dance', 'Dandiya, Fasting, Chaniya choli, Pandal, Kanya puja'],
  ['Shades of blue', 3, 'colour', 'Navy, Sky blue, Royal blue, Teal, Cobalt'],
  ['Shades of red', 3, 'colour', 'Crimson, Scarlet, Cherry red, Rust, Wine'],
  ['Trousers', 3, 'clothes', 'Jeans, Shorts, Chinos, Joggers, Cargos'],
  ['Chicken dishes', 3, 'food', 'Butter chicken, Tandoori chicken, Chilli chicken, Chicken 65, Chicken lollipop'],
  ['___ masala', 3, 'food', 'Garam, Chaat, Chana, Tikka, Kitchen King'],
  ['___ puri', 3, 'food', 'Pani, Sev, Dahi, Bhel, Aloo'],

  // ---------- tricky: wordplay ----------
  ['___ball', 4, 'sport body weather', 'Foot, Basket, Hand, Base, Snow'],
  ['___fly', 4, 'animal food element', 'Butter, Dragon, Fire, House, Horse'],
  ['___cake', 4, 'food', 'Cup, Pan, Cheese, Fish, Pound'],
  ['___box', 4, 'home', 'Lunch, Sand, Juke, Match, Shoe'],
  ['___light', 4, 'home space', 'Moon, Star, Flash, Spot, Torch'],
  ['___man', 4, 'job person weather', 'Post, Fire, Snow, Super, Spider'],
  ['___house', 4, 'home colour animal', 'Light, Green, Ware, Club, Dog'],
  ['___fish', 4, 'animal sea', 'Cat, Sword, Gold, Jelly, Star'],
  ['Sun___', 4, 'weather space plant', 'Flower, Rise, Glasses, Burn, Set'],
  ['Rain___', 4, 'weather', 'Bow, Coat, Drop, Fall, Forest'],
  ['Black___', 4, 'colour', 'Board, Mail, Out, Smith, Berry'],
  ['Fire___', 4, 'element job home', 'Work, Place, Fighter, Wall, Proof'],
  ['Water___', 4, 'sea food', 'Melon, Fall, Proof, Park, Bottle'],
  ['Head___', 4, 'body', 'Ache, Line, Phone, Master, Quarters'],
  ['Hand___', 4, 'body', 'Shake, Writing, Bag, Cuffs, Made'],
  ['Time___', 4, 'time', 'Table, Pass, Line, Zone, Bomb'],
  ['Book___', 4, 'book', 'Mark, Worm, Shelf, Keeper, Store'],
  ['___ cut', 4, 'job body', 'Power, Hair, Short, Paper, Price'],
  ['___ card', 4, 'money school', 'Report, Credit, Birthday, Business, Yellow'],
  ['___ station', 4, 'job travel', 'Police, Radio, Gas, Space, Petrol'],
  ['___ queen', 4, 'person', 'Drama, Beauty, Ice, Dancing, Prom'],
  ['___ chair', 4, 'home', 'Wheel, Rocking, Deck, Musical, Easy'],
  ['___fall', 4, 'weather', 'Night, Land, Pit, Down, Free'],
  ['Smart ___', 4, 'tech', 'Phone, Watch, TV, Card, City'],
  ['___ chips', 4, 'food tech game', 'Potato, Poker, Chocolate, Banana, Micro'],
  ['___wala', 4, 'talk job', 'Chai, Doodh, Sabzi, Auto, Kabadi'],
  ['___wood', 4, 'film', 'Bolly, Holly, Tolly, Kolly, Molly'],
  ['Things you can break', 4, 'feeling', 'Heart, Record, Promise, News, Silence'],
  ['Things you drop', 4, 'talk', 'Hint, Bomb, Jaw, Ball, Mic'],
  ['Things you crack', 4, 'talk food', 'Joke, Code, Egg, Safe, Knuckles'],
  ['Things you pull', 4, 'talk body', 'Leg, Strings, Muscle, Prank, Rank'],
  ['Things with teeth', 4, 'home animal', 'Comb, Saw, Zip, Gear, Shark'],
  ['Things that bark', 4, 'plant animal', 'Tree, Dog, Seal, Fox, Deer'],
  ['Things with rings', 4, 'space sport food', 'Saturn, Onion, Olympics, Boxing, Circus'],
  ['Things with scales', 4, 'animal music', 'Fish, Piano, Map, Lizard, Weighing machine'],
  ['Things with needles', 4, 'plant animal home', 'Pine tree, Cactus, Compass, Sewing kit, Porcupine'],
  ['Things with wings', 4, 'animal vehicle', 'Plane, Angel, Hospital, Bat, Chicken'],
  ['Come in pairs', 4, 'clothes body', 'Socks, Chopsticks, Twins, Scissors, Trousers'],
  ['Hide the word ANT', 4, 'animal word', 'Elephant, Pantry, Giant, Plant, Infant'],
  ['Hide a body part', 4, 'body word', 'Shinchan, Earth, Handle, Leggings'],
  ['Hide a number', 4, 'number word', 'Often, Lonely, Weight, Canine, Network'],
  ['Start with a body part', 4, 'body word', 'Armchair, Legend, Handsome, Footnote, Chinese'],
  ['Palindromes', 4, 'word', 'Madam, Racecar, Level, Radar, Noon'],
  ['Anagrams of LISTEN', 4, 'word', 'Silent, Enlist, Tinsel, Inlets'],
  ['Silent first letter', 4, 'word', 'Knife, Write, Psychology, Honest, Gnome'],
  ['Sound like letters', 4, 'word letter', 'Pea, Tea, Sea, Bee, Eye'],
  ['Comic book sounds', 4, 'sound', 'Bang, Pow, Zap, Boom, Splash'],
  ['Things with stripes', 4, 'animal', 'Zebra, Barcode, Barber pole, Candy cane, Skunk'],
  ['Things with spots', 4, 'animal health game', 'Ladybird, Giraffe, Domino, Measles, Dice'],
]

export const GROUPS: Group[] = RAW.map(([name, level, tags, words]) => ({ name, level, tags: tags.split(' '), words: words.split(',').map(w => w.trim()).filter(Boolean) }))
