// Words to draw in Draw & Guess, by theme, and the phrases Telephone falls back on when someone writes nothing.

export const THEMES: Record<string, string[]> = {
  easy: [
    'sun', 'moon', 'star', 'tree', 'house', 'car', 'ball', 'cat', 'dog', 'fish', 'apple', 'banana', 'book', 'chair', 'table',
    'clock', 'cup', 'shoe', 'hat', 'key', 'door', 'flower', 'heart', 'cloud', 'rain', 'umbrella', 'boat', 'bus', 'train',
    'kite', 'bird', 'egg', 'ice cream', 'cake', 'pencil', 'phone', 'glasses', 'bed', 'lamp', 'fan', 'bottle', 'bag',
    'rainbow', 'mountain', 'snowman', 'balloon', 'candle', 'ladder', 'spoon', 'fork', 'bridge', 'window', 'smile', 'eye',
    'hand', 'nose', 'tooth', 'bell', 'drum', 'guitar', 'rocket', 'robot', 'crown', 'ring', 'gift', 'pizza', 'bicycle',
    'ear', 'mouth', 'foot', 'leg', 'hair', 'beard', 'moustache', 'finger', 'thumb', 'lips', 'eyebrow', 'skeleton', 'ghost',
    'angel', 'king', 'queen', 'pirate', 'clown', 'cowboy', 'wizard', 'witch', 'baby', 'grandma', 'teacher', 'doctor', 'police',
    'farmer', 'astronaut', 'superhero', 'mermaid', 'dragon', 'alien', 'monster', 'vampire', 'zombie', 'ninja', 'princess',
    'castle', 'tent', 'igloo', 'tower', 'lighthouse', 'windmill', 'well', 'fence', 'gate', 'road', 'traffic light', 'sign board',
    'car tyre', 'truck', 'tractor', 'helicopter', 'aeroplane', 'ship', 'submarine', 'parachute', 'hot air balloon', 'skateboard',
    'scooter', 'ambulance', 'fire engine', 'jeep', 'motorbike', 'wheel', 'anchor', 'flag', 'map', 'compass', 'globe', 'telescope',
    'magnet', 'battery', 'bulb', 'torch', 'hammer', 'saw', 'axe', 'screwdriver', 'nail', 'needle', 'thread', 'button', 'zip',
    'scissors', 'comb', 'brush', 'toothbrush', 'soap', 'towel', 'bucket', 'mug', 'tap', 'shower', 'bathtub', 'mirror', 'sofa',
    'pillow', 'blanket', 'cupboard', 'drawer', 'shelf', 'carpet', 'curtain', 'photo frame', 'vase', 'plant pot', 'calendar',
    'envelope', 'stamp', 'letter', 'newspaper', 'magazine', 'notebook', 'eraser', 'ruler', 'crayon', 'paintbrush', 'paper plane',
    'paper boat', 'sandcastle', 'treasure chest', 'map with an X', 'trophy', 'medal', 'whistle', 'dice', 'playing card', 'chess',
    'yo-yo', 'spinning top', 'marbles', 'teddy bear', 'doll', 'puppet', 'mask', 'party hat', 'confetti', 'piñata', 'swing',
    'slide', 'see-saw', 'sun hat', 'scarf', 'gloves', 'socks', 'boots', 'jacket', 'shirt', 'dress', 'shorts', 'tie', 'belt',
    'watch', 'necklace', 'earring', 'purse', 'wallet', 'suitcase', 'backpack', 'basket', 'box', 'jar', 'lock', 'chain', 'rope',
    'web', 'snowflake', 'lightning', 'tornado', 'volcano', 'island', 'waterfall', 'wave', 'sunset', 'planet', 'comet', 'shooting star',
  ],
  animals: [
    'elephant', 'giraffe', 'lion', 'tiger', 'monkey', 'snake', 'crocodile', 'zebra', 'kangaroo', 'penguin', 'owl', 'parrot',
    'peacock', 'camel', 'cow', 'buffalo', 'goat', 'horse', 'donkey', 'rabbit', 'mouse', 'frog', 'turtle', 'octopus',
    'jellyfish', 'shark', 'whale', 'dolphin', 'crab', 'spider', 'butterfly', 'bee', 'ant', 'mosquito', 'snail', 'bat',
    'squirrel', 'hedgehog', 'panda', 'koala', 'deer', 'bear', 'wolf', 'fox', 'duck', 'hen', 'eagle', 'flamingo', 'dinosaur',
    'unicorn', 'lizard', 'cockroach', 'pig', 'sheep', 'rhino', 'hippo', 'starfish', 'seahorse', 'worm', 'scorpion',
    'cheetah', 'leopard', 'jaguar', 'polar bear', 'gorilla', 'chimpanzee', 'orangutan', 'sloth', 'raccoon', 'skunk', 'beaver',
    'otter', 'walrus', 'seal', 'sea lion', 'penguin chick', 'puffin', 'ostrich', 'emu', 'swan', 'goose', 'turkey', 'rooster',
    'chick', 'pigeon', 'crow', 'sparrow', 'woodpecker', 'kingfisher', 'hummingbird', 'vulture', 'hawk', 'toucan', 'pelican',
    'stork', 'crane', 'heron', 'parrot in a cage', 'bat hanging upside down', 'dragonfly', 'ladybird', 'grasshopper', 'caterpillar',
    'moth', 'firefly', 'wasp', 'beetle', 'centipede', 'tadpole', 'salamander', 'chameleon', 'iguana', 'cobra', 'python', 'tortoise',
    'alligator', 'goldfish', 'clownfish', 'pufferfish', 'swordfish', 'stingray', 'eel', 'squid', 'lobster', 'prawn', 'shrimp',
    'oyster', 'clam', 'snail shell', 'coral', 'sea turtle', 'killer whale', 'narwhal', 'manatee', 'walking stick insect',
    'llama', 'alpaca', 'yak', 'bison', 'moose', 'reindeer', 'antelope', 'gazelle', 'warthog', 'hyena', 'jackal', 'mongoose',
    'meerkat', 'armadillo', 'anteater', 'porcupine', 'hamster', 'guinea pig', 'ferret', 'mole', 'rat', 'kitten', 'puppy',
    'calf', 'foal', 'lamb', 'piglet', 'duckling', 'bunny', 'cub', 'mule', 'ox', 'bull', 'buffalo with horns', 'pony', 'zebra crossing a road',
    'cat chasing a mouse', 'dog with a bone', 'monkey eating a banana', 'elephant spraying water', 'bird in a nest', 'fish in a bowl',
    'spider web', 'bee hive', 'ant hill', 'bird cage', 'kennel', 'stable', 'aquarium', 'feather', 'paw print', 'horseshoe',
    'peacock feather', 'shark fin', 'tiger stripes', 'cat whiskers', 'elephant trunk', 'dinosaur egg', 'snake skin', 'butterfly net',
    'T. rex', 'pterodactyl', 'woolly mammoth', 'sabre-tooth tiger', 'phoenix', 'Pegasus', 'yeti', 'Loch Ness monster',
  ],
  food: [
    'pizza', 'burger', 'sandwich', 'noodles', 'french fries', 'popcorn', 'donut', 'cupcake', 'chocolate', 'lollipop',
    'watermelon', 'mango', 'grapes', 'pineapple', 'coconut', 'strawberry', 'cherry', 'carrot', 'tomato', 'onion', 'potato',
    'corn', 'egg', 'cheese', 'bread', 'butter', 'milk', 'tea', 'coffee', 'juice', 'cookie', 'cake', 'ice cream', 'soup',
    'sushi', 'hot dog', 'taco', 'pancake', 'honey', 'peanut', 'chilli', 'lemon', 'orange', 'pear', 'brinjal', 'cucumber',
    'mushroom', 'pumpkin', 'banana split', 'birthday cake', 'pasta', 'salad', 'omelette', 'toast', 'cereal',
    'apple pie', 'muffin', 'croissant', 'bagel', 'waffle', 'pretzel', 'spaghetti', 'lasagne', 'burrito', 'nachos', 'sushi roll',
    'dumplings', 'spring roll', 'fried egg', 'boiled egg', 'sausage', 'chicken leg', 'fish fry', 'kebab', 'steak', 'meatball',
    'cheese slice', 'cheese grater', 'butter knife', 'jam jar', 'peanut butter', 'cornflakes', 'milkshake', 'smoothie',
    'cold drink', 'soda can', 'water bottle', 'teapot', 'kettle', 'coffee cup', 'straw', 'ice cube', 'ice lolly', 'cone',
    'sundae', 'jelly', 'pudding', 'custard', 'candy floss', 'candy', 'chewing gum', 'marshmallow', 'chocolate bar', 'gingerbread man',
    'fortune cookie', 'cherry on top', 'whipped cream', 'sprinkles', 'wedding cake', 'pie', 'tart', 'brownie', 'cheesecake',
    'blueberry', 'raspberry', 'kiwi', 'peach', 'plum', 'apricot', 'papaya', 'guava', 'pomegranate', 'litchi', 'jackfruit',
    'custard apple', 'fig', 'dates', 'avocado', 'dragon fruit', 'lime', 'grapefruit', 'melon', 'banana peel', 'apple core',
    'broccoli', 'cauliflower', 'cabbage', 'lettuce', 'spinach', 'peas', 'beans', 'capsicum', 'garlic', 'ginger', 'radish',
    'beetroot', 'sweet potato', 'ladyfinger', 'bitter gourd', 'bottle gourd', 'green chilli', 'olive', 'pickle', 'peanuts',
    'almond', 'walnut', 'cashew', 'pistachio', 'rice', 'wheat', 'flour', 'sugar', 'salt shaker', 'pepper', 'ketchup bottle',
    'mustard', 'mayonnaise', 'honeycomb', 'egg carton', 'loaf of bread', 'sandwich toaster', 'frying pan', 'rolling pin',
    'chopping board', 'lunch box', 'picnic basket', 'shopping cart', 'fridge', 'oven', 'microwave', 'blender', 'toaster',
    'chef hat', 'apron', 'menu card', 'restaurant bill', 'food truck', 'pizza box', 'popcorn bucket', 'coconut water', 'sugarcane',
  ],
  desi: [
    'samosa', 'jalebi', 'chai', 'dosa', 'idli', 'pani puri', 'vada pav', 'biryani', 'roti', 'paratha', 'lassi', 'kulfi',
    'ladoo', 'gulab jamun', 'pav bhaji', 'rangoli', 'diya', 'kite', 'rickshaw', 'auto rickshaw', 'cricket bat', 'stumps',
    'Taj Mahal', 'India Gate', 'Qutub Minar', 'Lotus Temple', 'turban', 'saree', 'kurta', 'bindi', 'mehndi', 'bangles',
    'tabla', 'sitar', 'harmonium', 'dhol', 'peacock', 'elephant', 'cow', 'mango', 'coconut tree', 'tiffin', 'pressure cooker',
    'tawa', 'chapati', 'matka', 'charpai', 'ceiling fan', 'scooter', 'local train', 'dabbawala', 'chai stall', 'pandal',
    'Ganesha', 'Holi', 'Diwali', 'firecracker', 'jhula', 'tiranga', 'Ashoka Chakra', 'lotus', 'tulsi', 'bullock cart',
    'nimbu mirchi', 'pagdi', 'gilli danda', 'carrom board', 'ludo', 'auto', 'bus conductor', 'thali', 'paan', 'chakli',
    'pakoda', 'bhel puri', 'chole bhature', 'momos', 'Maggi', 'rasgulla', 'barfi', 'kaju katli', 'kheer', 'halwa', 'modak',
    'puri', 'naan', 'kachori', 'dhokla', 'uttapam', 'medu vada', 'sambar', 'coconut chutney', 'banana leaf meal', 'filter coffee',
    'cutting chai', 'kulhad', 'lemon soda', 'golgappa cart', 'bhutta', 'chana jor', 'papad', 'achaar', 'masala box', 'mortar and pestle',
    'chulha', 'lota', 'steel glass', 'steel plate', 'tiffin carrier', 'pressure cooker whistle', 'idli stand', 'chakla belan', 'kadai',
    'dhoti', 'lungi', 'sherwani', 'lehenga', 'dupatta', 'jhumka', 'nose ring', 'mangalsutra', 'kolhapuri chappal', 'mojari',
    'Gandhi topi', 'Nehru jacket', 'veena', 'shehnai', 'bansuri', 'mridangam', 'dholak', 'ghungroo', 'kathakali face', 'Bharatanatyam pose',
    'garba', 'bhangra', 'dandiya sticks', 'Diwali lights', 'rakhi', 'Holi colours', 'pichkari', 'gulal', 'kite fight', 'manja',
    'Christmas star', 'Eid moon', 'Durga Puja', 'Ganpati idol', 'dahi handi', 'Onam boat race', 'Pongal pot', 'Lohri bonfire',
    'wedding mandap', 'baraat horse', 'band baaja', 'shaadi card', 'varmala', 'haldi ceremony', 'mehndi hands', 'doli',
    'Red Fort', 'Gateway of India', 'Charminar', 'Hawa Mahal', 'Golden Temple', 'Howrah Bridge', 'Victoria Memorial', 'Konark wheel',
    'Statue of Unity', 'Mysore Palace', 'Meenakshi Temple', 'houseboat', 'Himalayas', 'Ganga ghat', 'camel safari', 'tea garden',
    'Mumbai local', 'Delhi Metro', 'toy train', 'Vande Bharat', 'tempo', 'e-rickshaw', 'cycle rickshaw', 'tonga', 'truck art',
    'Horn OK Please', 'speed breaker', 'pothole', 'traffic police', 'toll plaza', 'dhaba', 'kirana shop', 'sabzi wala', 'chaiwala',
    'doodhwala', 'raddiwala', 'presswala', 'paanwala', 'barber shop', 'tailor', 'cobbler', 'street dog', 'monkey on a roof',
    'cow on the road', 'water tank on a roof', 'clothesline', 'cooler', 'inverter', 'power cut', 'gas cylinder', 'ration card',
    'Aadhaar card', 'rupee coin', 'piggy bank', 'gullak', 'lottery ticket', 'cricket ball', 'tennis ball cricket', 'gully cricket',
    'kabaddi', 'kho-kho', 'pithu', 'kanche', 'lattoo', 'snakes and ladders', 'antakshari', 'Shaktimaan', 'Chhota Bheem', 'Doordarshan',
  ],
  actions: [
    'sleeping', 'running', 'swimming', 'dancing', 'singing', 'cooking', 'reading', 'writing', 'jumping', 'crying', 'laughing',
    'eating', 'drinking', 'sneezing', 'yawning', 'fishing', 'flying', 'driving', 'cycling', 'climbing', 'falling', 'fighting',
    'hugging', 'waving', 'clapping', 'thinking', 'praying', 'shopping', 'painting', 'skating', 'surfing', 'skiing', 'juggling',
    'bowling', 'batting', 'kicking', 'throwing', 'catching', 'brushing teeth', 'taking a selfie', 'texting', 'snoring',
    'sweeping', 'ironing', 'washing clothes', 'raining', 'melting', 'exploding', 'whistling', 'lifting weights', 'meditating',
    'walking', 'jogging', 'crawling', 'hopping', 'skipping', 'sliding', 'swinging', 'spinning', 'rolling', 'diving', 'floating',
    'sinking', 'rowing', 'sailing', 'riding a horse', 'riding a bike', 'flying a kite', 'kicking a ball', 'shooting a basket',
    'serving in tennis', 'hitting a six', 'bowling a ball', 'taking a catch', 'scoring a goal', 'saving a goal', 'boxing',
    'wrestling', 'doing yoga', 'doing push-ups', 'stretching', 'skydiving', 'bungee jumping', 'rock climbing', 'camping',
    'hiking', 'fishing on a boat', 'building a snowman', 'making a sandcastle', 'blowing bubbles', 'blowing a balloon',
    'popping a balloon', 'blowing out candles', 'cutting a cake', 'opening a gift', 'wrapping a gift', 'making tea', 'baking',
    'frying', 'chopping vegetables', 'washing dishes', 'mopping', 'dusting', 'folding clothes', 'making the bed', 'watering plants',
    'gardening', 'digging', 'planting a tree', 'mowing the lawn', 'painting a wall', 'fixing a car', 'changing a tyre', 'hammering a nail',
    'sewing', 'knitting', 'drawing', 'colouring', 'cutting paper', 'writing a letter', 'posting a letter', 'typing', 'printing',
    'taking a photo', 'recording a video', 'watching TV', 'listening to music', 'playing guitar', 'playing drums', 'playing piano',
    'conducting an orchestra', 'acting', 'bowing', 'saluting', 'shaking hands', 'high five', 'pointing', 'shrugging', 'nodding',
    'winking', 'blinking', 'frowning', 'smiling', 'shouting', 'whispering', 'sighing', 'coughing', 'hiccuping', 'shivering',
    'sweating', 'blushing', 'fainting', 'sleepwalking', 'dreaming', 'waking up', 'stretching after waking', 'brushing hair',
    'shaving', 'putting on makeup', 'tying shoelaces', 'getting dressed', 'taking a bath', 'drying hair', 'cutting nails',
    'counting money', 'paying', 'bargaining', 'queueing', 'waiting for a bus', 'catching a train', 'missing a bus', 'hailing a taxi',
    'parking', 'honking', 'getting a ticket', 'falling asleep in class', 'raising a hand', 'cheating in an exam', 'reading a map',
    'getting lost', 'searching', 'hiding', 'peeking', 'sneaking', 'chasing', 'escaping', 'tripping', 'slipping on a banana peel',
    'carrying a heavy box', 'pushing a car', 'pulling a rope', 'tug of war', 'arm wrestling', 'pillow fight', 'snowball fight',
    'water balloon fight', 'proposing', 'getting married', 'dancing at a wedding', 'babysitting', 'walking a dog', 'feeding a cat',
    'milking a cow', 'riding an elephant', 'charming a snake', 'juggling fire', 'magic trick', 'walking a tightrope', 'lighting a diya',
  ],
  places: [
    'beach', 'school', 'hospital', 'airport', 'railway station', 'temple', 'church', 'mosque', 'park', 'zoo', 'farm', 'forest',
    'desert', 'island', 'volcano', 'waterfall', 'cave', 'castle', 'museum', 'library', 'cinema', 'restaurant', 'kitchen',
    'bathroom', 'bedroom', 'classroom', 'playground', 'market', 'mall', 'bank', 'police station', 'fire station', 'circus',
    'stadium', 'swimming pool', 'gym', 'office', 'space station', 'moon', 'lighthouse', 'bus stop', 'petrol pump', 'village',
    'city', 'river', 'lake', 'hill station', 'tent', 'igloo', 'pyramid', 'Eiffel Tower', 'Statue of Liberty',
    'mountain', 'valley', 'glacier', 'canyon', 'jungle', 'rainforest', 'swamp', 'pond', 'ocean', 'coral reef', 'harbour', 'port',
    'pier', 'bridge', 'tunnel', 'dam', 'well', 'windmill', 'farmhouse', 'barn', 'treehouse', 'hut', 'cottage', 'palace', 'fort',
    'tower', 'skyscraper', 'apartment', 'hotel', 'motel', 'hostel', 'prison', 'court', 'post office', 'parliament', 'factory',
    'warehouse', 'garage', 'car wash', 'parking lot', 'highway', 'toll booth', 'roundabout', 'traffic jam', 'zebra crossing',
    'footpath', 'alley', 'street market', 'flea market', 'supermarket', 'bakery', 'butcher shop', 'pharmacy', 'clinic',
    'dentist', 'barber shop', 'beauty parlour', 'tailor shop', 'shoe shop', 'toy shop', 'bookshop', 'jewellery shop', 'ice cream parlour',
    'coffee shop', 'food court', 'dhaba', 'canteen', 'hostel room', 'dining room', 'living room', 'balcony', 'terrace', 'attic',
    'basement', 'staircase', 'lift', 'escalator', 'corridor', 'garden', 'backyard', 'rooftop', 'courtyard', 'pooja room',
    'stage', 'theatre', 'concert', 'nightclub', 'bowling alley', 'arcade', 'theme park', 'water park', 'roller coaster', 'Ferris wheel',
    'carnival', 'mela', 'fair', 'aquarium', 'planetarium', 'observatory', 'science lab', 'art gallery', 'studio', 'newsroom',
    'cricket ground', 'football field', 'tennis court', 'basketball court', 'race track', 'golf course', 'ski slope', 'ice rink',
    'boxing ring', 'wrestling akhada', 'chess club', 'airport lounge', 'runway', 'control tower', 'helipad', 'bus depot',
    'metro station', 'platform', 'ticket counter', 'ship deck', 'submarine', 'spaceship', 'Mars', 'black hole', 'galaxy',
    'North Pole', 'South Pole', 'Sahara', 'Amazon', 'Great Wall of China', 'Taj Mahal', 'Big Ben', 'Leaning Tower of Pisa',
    'Sydney Opera House', 'Colosseum', 'Stonehenge', 'Mount Everest', 'Niagara Falls', 'Grand Canyon', 'Burj Khalifa', 'Disneyland',
    'haunted house', 'graveyard', 'secret tunnel', 'treasure island', 'desert island', 'oasis', 'underwater city', 'cloud castle',
  ],
  tech: [
    'laptop', 'keyboard', 'mouse', 'headphones', 'charger', 'Wi-Fi', 'password', 'email', 'bug', 'robot', 'drone', 'satellite',
    'battery', 'USB', 'printer', 'camera', 'smartwatch', 'selfie stick', 'hashtag', 'emoji', 'like button', 'cloud', 'server',
    'code', 'loading', 'error', 'game controller', 'virtual reality', 'QR code', 'barcode', 'calculator', 'microchip',
    'exam', 'hostel', 'canteen', 'assignment', 'deadline', 'professor', 'attendance', 'library card', 'degree', 'notebook',
    'backpack', 'whiteboard', 'projector', 'lab coat', 'microscope', 'test tube', 'calendar', 'alarm clock', 'coffee mug',
    'all-nighter', 'group project', 'placement', 'internship', 'resume', 'video call', 'mute button', 'screenshot',
    'smartphone', 'tablet', 'desktop computer', 'monitor', 'speaker', 'microphone', 'webcam', 'earbuds', 'power bank', 'extension board',
    'plug', 'socket', 'cable', 'router', 'antenna', 'remote control', 'television', 'radio', 'tape recorder', 'floppy disk', 'CD',
    'pen drive', 'hard disk', 'memory card', 'SIM card', 'chip', 'circuit', 'motherboard', 'fan inside a laptop', 'touchscreen',
    'swipe', 'notification', 'battery low', 'airplane mode', 'Bluetooth', 'GPS', 'location pin', 'map app', 'search bar', 'download',
    'upload', 'buffering', 'blue screen', 'spam', 'virus', 'hacker', 'firewall', 'lock screen', 'fingerprint scanner', 'face unlock',
    'OTP', 'captcha', 'cookie', 'pop-up', 'dark mode', 'trash bin', 'folder', 'cursor', 'scroll', 'zoom', 'copy and paste', 'undo',
    'robot arm', 'self-driving car', 'electric car', 'charging station', 'solar panel', 'wind turbine', 'smart speaker', 'VR headset',
    '3D printer', 'hologram', 'AI chatbot', 'app store', 'video game', 'joystick', 'arcade machine', 'Tetris', 'Pac-Man', 'Mario',
    'influencer', 'reel', 'livestream', 'subscribe button', 'thumbs up', 'heart react', 'trending', 'meme', 'viral video', 'unboxing',
    'podcast', 'vlog', 'online class', 'Zoom call', 'raise hand button', 'chat box', 'group chat', 'voice note', 'blue ticks', 'last seen',
    'typing dots', 'selfie', 'filter', 'photo booth', 'printer jam', 'paper stuck', 'stapler', 'sticky note', 'highlighter', 'file',
    'ID card', 'lanyard', 'office chair', 'cubicle', 'meeting room', 'presentation', 'pie chart', 'bar graph', 'spreadsheet',
    'calculator watch', 'scientific calculator', 'formula', 'periodic table', 'beaker', 'Bunsen burner', 'magnifying glass',
    'lab rat', 'DNA', 'atom', 'rocket launch', 'Chandrayaan', 'Mars rover', 'space suit', 'canteen samosa', 'hostel bunk bed',
    'exam hall', 'answer sheet', 'question paper', 'report card', 'convocation cap', 'degree scroll', 'college fest',
    'proxy attendance', 'last bench', 'back paper', 'viva', 'lab record', 'coding', 'bug fix', 'coffee at 3 a.m.', 'job offer',
  ],
}

export function drawWords(theme: string): string[] {
  if (theme !== 'mixed' && THEMES[theme]) return THEMES[theme]
  return [...new Set([...THEMES.easy, ...THEMES.animals, ...THEMES.food, ...THEMES.desi, ...THEMES.actions, ...THEMES.places, ...THEMES.tech])]
}

export const TELEPHONE_STARTS: string[] = [
  'A monkey riding a rocket', 'An elephant doing yoga', 'A cat stealing samosas', 'Grandma winning a dance battle',
  'A cow stuck in traffic', 'A dinosaur at a wedding', 'A ghost eating ice cream', 'A robot making chai',
  'A fish riding a bicycle', 'A penguin on a beach holiday', 'A tiger at the barber shop', 'An alien buying vegetables',
  'Cricket match on the moon', 'A snake playing the flute', 'A pizza with too many toppings', 'A superhero afraid of cockroaches',
  'A goat taking a selfie', 'A teacher asleep in class', 'A king lost in a mall', 'A crocodile brushing its teeth',
  'Two dogs having a phone call', 'A chicken crossing a busy road', 'An auto rickshaw flying in the sky', 'A shark at a birthday party',
  'A camel in the snow', 'A baby driving a bus', 'A cloud raining laddoos', 'A giraffe wearing a tie', 'A bear stuck in a lift',
  'A volcano erupting popcorn', 'A wizard doing homework', 'An owl working night shift', 'A pirate looking for Wi-Fi',
  'A mosquito at the gym', 'A horse in a swimming pool', 'A frog proposing to a princess', 'A banana slipping on a person',
  'A tree wearing sunglasses', 'Santa Claus in Mumbai local train', 'A lion scared of a mouse', 'An astronaut eating dosa',
  'A spider knitting a sweater', 'A cat ruling the world', 'A dragon making toast', 'Bollywood hero fighting ten villains',
  'A family on one scooter', 'A peacock dancing in the rain', 'A potato with a moustache', 'A mango that can talk',
  'The last slice of pizza', 'A selfie with a lion', 'A zombie at a job interview', 'An octopus playing drums',
  'A dog driving an auto rickshaw', 'A buffalo on a skateboard', 'A tortoise winning a race', 'A parrot reading the news',
  'A monkey stealing glasses', 'A rat eating a laddoo', 'A squirrel with a laptop', 'A kangaroo at the post office',
  'A hippo doing ballet', 'A panda eating noodles', 'A cat in a space suit', 'A dog teaching a class', 'A cow in a cinema hall',
  'A goat on a mountain bike', 'An ant carrying a mango', 'A bee stuck in honey', 'A pigeon stealing a samosa', 'A duck in a raincoat',
  'A whale in a bathtub', 'A snail in a hurry', 'A lizard on the ceiling fan', 'A fish in a fishbowl looking bored',
  'A rooster with an alarm clock', 'A camel at a petrol pump', 'A donkey wearing headphones', 'A polar bear in the desert',
  'A penguin selling ice cream', 'A koala sleeping in class', 'A crab doing a handstand', 'A bat hanging from a clothesline',
  'A sheep counting people', 'A tiger on a diet', 'A hen laying a golden egg', 'A jellyfish at a disco', 'A dog chasing its tail',
  'A cat knocking a glass off a table', 'A mosquito drinking from a straw', 'A pig in a mud bath', 'A horse at a wedding baraat',
  'An elephant hiding behind a tree', 'A bear eating a honey jar', 'A peacock taking a selfie', 'A giraffe stuck under a bridge',
  'Uncle dancing at a wedding', 'Aunty asking for marks', 'A baby eating a lemon', 'Dad stuck in a traffic jam',
  'Mom with a slipper', 'A cricketer hitting a six through a window', 'A teacher with a giant chalk', 'A boy hiding his report card',
  'A girl flying a kite on a roof', 'Friends on a road trip', 'A family photo where nobody is ready', 'Grandpa reading the newspaper',
  'A chef dropping a cake', 'A doctor giving an injection', 'A dentist pulling a tooth', 'A barber cutting too much hair',
  'A tailor measuring a giant', 'A policeman chasing a thief', 'A pilot asleep in the cockpit', 'A farmer driving a tractor',
  'A painter painting himself', 'A singer losing their voice', 'A magician pulling a rabbit out of a hat', 'A clown crying',
  'A king on a throne made of pizza', 'A queen wearing sunglasses', 'A pirate with a parrot', 'A ninja in a library',
  'A cowboy riding a cow', 'A wizard turning a frog into a prince', 'A mermaid on a beach towel', 'A vampire at the dentist',
  'A ghost scared of the dark', 'A witch on a vacuum cleaner', 'A robot falling in love', 'An alien learning to cook',
  'A superhero doing laundry', 'A villain watering plants', 'A dragon at a birthday party', 'A unicorn at a petrol pump',
  'A snowman in summer', 'Santa on a camel', 'A pumpkin with a face', 'A sun wearing a cap', 'A moon eating a cookie',
  'A cloud wearing a jacket', 'A rainbow made of ice cream', 'A tree growing money', 'A flower that bites', 'A cactus giving a hug',
  'A mountain with a nose', 'A river of chocolate', 'A house on chicken legs', 'A car with wings', 'A bus full of animals',
  'A train going into the sea', 'A boat on a road', 'A rocket made of bamboo', 'A bicycle for ten people', 'A flying carpet in traffic',
  'A traffic light that is always red', 'A lift that goes sideways', 'A phone with legs', 'A laptop eating paper', 'A TV watching people',
  'A fridge full of shoes', 'A fan blowing someone away', 'A pressure cooker exploding', 'A washing machine with a dog inside',
  'An umbrella with holes', 'A pillow fight in a hostel', 'A giant samosa', 'A dosa as long as a train', 'Chai in a bucket',
  'Biryani for one hundred people', 'A jalebi maze', 'A pani puri explosion', 'A pizza delivery to the moon', 'Ice cream melting in the sun',
  'A burger taller than a building', 'Popcorn raining at a cinema', 'A cake with a hundred candles', 'A banana phone',
  'A watermelon with a zip', 'A chilli breathing fire', 'An onion making people cry', 'A coconut falling on a head', 'A tomato blushing',
  'Cricket in the rain', 'A football hitting the referee', 'A goalkeeper sleeping', 'A tennis match between two cats',
  'A swimming race with a shark', 'A marathon in pyjamas', 'A chess game between a king and a queen', 'A tug of war with an elephant',
  'A wrestling match between two babies', 'A kabaddi player out of breath', 'Gully cricket with a dog fielding', 'A broken window and a cricket ball',
  'Exam hall with one empty chair', 'A student copying from a cow', 'A school bus on the moon', 'A homework-eating dog',
  'A WhatsApp group that will not stop', 'A selfie gone wrong', 'Phone battery at one percent', 'Wi-Fi on top of a mountain',
  'A meeting where everyone is asleep', 'Monday morning', 'The last day of holidays', 'Power cut during a cricket final',
  'A wedding in the rain', 'A birthday surprise gone wrong', 'Diwali lights on a cow', 'Holi colours on a white cat',
  'A kite stuck on a tree', 'A dhol player at a baraat', 'A traffic jam of bullock carts', 'A Mumbai local at rush hour', 'A crowded bus with a goat',
  'An auto driver saying no', 'A queue at the railway station', 'A monkey at the Taj Mahal', 'A camel at India Gate',
]
