// Closest Wins questions. Answers are well-established figures; where a number is rounded or has changed, the note
// says so. log: closeness by ratio (heights, distances, big counts); otherwise by difference (years, small counts).

export interface Estimate { q: string; a: number; unit: string; log: boolean; note?: string }

const year = (q: string, a: number, note?: string): Estimate => ({ q, a, unit: 'year', log: false, note })
const count = (q: string, a: number, unit = '', note?: string): Estimate => ({ q, a, unit, log: false, note })
const size = (q: string, a: number, unit: string, note?: string): Estimate => ({ q, a, unit, log: true, note })

export const ESTIMATES: Estimate[] = [
  // Heights and sizes
  size('How tall is Mount Everest?', 8849, 'metres', 'Measured jointly by Nepal and China in 2020.'),
  size('How tall is the Burj Khalifa in Dubai?', 828, 'metres'),
  size('How many floors does the Burj Khalifa have?', 163, 'floors'),
  size('How tall is the Statue of Unity in Gujarat (the statue itself)?', 182, 'metres', 'The tallest statue in the world.'),
  size('How tall is the Qutub Minar?', 73, 'metres', 'About 72.5 m.'),
  size('How tall is India Gate in Delhi?', 42, 'metres'),
  size('How tall is the Eiffel Tower today, with its antennas?', 330, 'metres'),
  size('How tall is the Statue of Liberty, from the ground to the torch?', 93, 'metres', 'The statue alone is about 46 m; the rest is the pedestal.'),
  size('How tall is Kanchenjunga, the highest mountain in India?', 8586, 'metres'),
  size('How deep is the deepest known point of the ocean (Challenger Deep)?', 10935, 'metres', 'About 10.9 km, in the Mariana Trench.'),
  size('How long is a cricket pitch, wicket to wicket?', 20.12, 'metres', 'Exactly 22 yards.'),
  size('How long can the largest blue whales grow?', 30, 'metres', 'About 30 m: the biggest animal that has ever lived.'),
  size('How much does an adult male African elephant weigh?', 6000, 'kg', 'About 6,000 kg; females are about half that.'),
  size('How much does a cricket ball weigh?', 160, 'grams', 'Between 155.9 and 163 g for men\'s cricket.'),
  size('How many grams are there in one tola of gold?', 11.66, 'grams', '1 tola = 11.6638 g.'),
  size('How many litres of blood does an adult human body have?', 5, 'litres', 'About 5 litres.'),
  size('What is the diameter of the Earth?', 12742, 'km'),
  size('What is the average distance from the Earth to the Moon?', 384400, 'km'),
  size('What is the average distance from the Earth to the Sun?', 150, 'million km', 'About 149.6 million km.'),
  size('How fast does light travel?', 300000, 'km per second', '299,792 km per second.'),
  size('How fast does sound travel in air at room temperature?', 343, 'metres per second'),
  size('How hot is the surface of the Sun?', 5500, '°C', 'About 5,500 °C.'),
  size('What is the top speed of a cheetah?', 110, 'km/h', 'Roughly 100 to 120 km/h in short bursts.'),
  size('How long is a marathon?', 42.195, 'km'),
  size('How far is Mumbai from Delhi in a straight line?', 1150, 'km', 'About 1,150 km as the crow flies; much more by road.'),
  size('How far is it from Kashmir to Kanyakumari, India\'s north-south length?', 3214, 'km'),
  size('How long is the river Ganga?', 2525, 'km'),
  size('How long is the Great Wall of China, counting all its branches?', 21196, 'km', 'From China\'s 2012 survey.'),
  size('What is the area of India?', 32.87, 'lakh sq km', '3,287,263 square km.'),
  size('What was India\'s population in the 2011 census?', 121, 'crore', '121.09 crore, or about 1.21 billion.'),
  size('What is the population of the whole world, roughly?', 800, 'crore', 'It passed 8 billion (800 crore) in 2022.'),
  size('How many runs did Sachin Tendulkar score in Test cricket?', 15921, 'runs'),
  size('How many Test wickets did Muttiah Muralitharan take?', 800, 'wickets'),
  size('What was the promised price of the Tata Nano when it was launched in 2008?', 100000, 'rupees', 'One lakh rupees.'),
  size('How many seconds are there in one day?', 86400, 'seconds'),
  size('How many minutes are there in one day?', 1440, 'minutes'),
  size('How many hours are there in a week?', 168, 'hours'),
  size('What is the boiling point of water in Fahrenheit?', 212, '°F'),
  size('How far did Neeraj Chopra throw the javelin to win gold at the Tokyo Olympics?', 87.58, 'metres'),
  size('What is the highest score by one batter in a one-day international?', 264, 'runs', 'Rohit Sharma, against Sri Lanka in 2014.'),
  size('What is the highest score by one batter in a Test innings?', 400, 'runs', 'Brian Lara, 400 not out, in 2004.'),

  // Counts
  count('How many keys does a standard piano have?', 88, 'keys'),
  count('How many bones are there in an adult human body?', 206, 'bones'),
  count('How many teeth does an adult have, counting wisdom teeth?', 32, 'teeth'),
  count('How many hearts does an octopus have?', 3, 'hearts'),
  count('How many countries are members of the United Nations?', 193, 'countries'),
  count('How many states does India have?', 28, 'states'),
  count('How many union territories does India have?', 8, 'union territories'),
  count('How many languages are listed in the Eighth Schedule of the Indian Constitution?', 22, 'languages'),
  count('How many spokes does the Ashoka Chakra on the Indian flag have?', 24, 'spokes'),
  count('How many squares are there on a chessboard?', 64, 'squares'),
  count('How many chemical elements are in the periodic table?', 118, 'elements'),
  count('How many stars are on the flag of the USA?', 50, 'stars'),
  count('How many moons does Mars have?', 2, 'moons'),
  count('How many time zones does India use?', 1, 'time zones', 'Just one: Indian Standard Time.'),
  count('How many players from each team are on the court in kabaddi?', 7, 'players'),
  count('How many episodes did the original Ramayan TV serial (1987) have?', 78, 'episodes'),
  count('How many episodes did B. R. Chopra\'s Mahabharat (1988) have?', 94, 'episodes'),
  count('How many international centuries did Sachin Tendulkar score?', 100, 'centuries'),
  count('How many wickets did Anil Kumble take in one Test innings against Pakistan in 1999?', 10, 'wickets'),
  count('How many Harry Potter books are there in the main series?', 7, 'books'),
  count('How many characters could a tweet have before 2017?', 140, 'characters'),
  count('How many years did it take to build the Taj Mahal?', 22, 'years', 'Roughly 1632 to 1653.'),
  count('How many Earth days was Chandrayaan-3\'s lander built to work on the Moon?', 14, 'days', 'One lunar day.'),

  // Years
  year('In which year did India win its first Cricket World Cup?', 1983),
  year('In which year was the first Cricket World Cup played?', 1975),
  year('In which year did the Indian Constitution come into effect?', 1950),
  year('In which year did Mahatma Gandhi lead the Dandi Salt March?', 1930),
  year('In which year did work on the Taj Mahal begin?', 1632),
  year('In which year was the Charminar in Hyderabad built?', 1591),
  year('In which year was the Gateway of India completed?', 1924),
  year('In which year did the first passenger train in India run, from Bombay to Thane?', 1853),
  year('In which year did the Delhi Metro start running?', 2002),
  year('In which year was ISRO founded?', 1969),
  year('In which year did Chandrayaan-3 land on the Moon?', 2023),
  year('In which year did humans first walk on the Moon?', 1969),
  year('In which year did the Titanic sink?', 1912),
  year('In which year did World War II end?', 1945),
  year('In which year did the Berlin Wall fall?', 1989),
  year('In which year was the first FIFA World Cup held?', 1930),
  year('In which year did India first host the Asian Games?', 1951),
  year('In which year was the first IPL season played?', 2008),
  year('In which year did Sachin Tendulkar play his first international match?', 1989),
  year('In which year did Virat Kohli make his one-day international debut?', 2008),
  year('In which year did Abhinav Bindra win India\'s first individual Olympic gold?', 2008),
  year('In which year was the rupee symbol ₹ adopted?', 2010),
  year('In which year was Sholay released?', 1975),
  year('In which year was Dilwale Dulhania Le Jayenge released?', 1995),
  year('In which year was Mughal-e-Azam released?', 1960),
  year('In which year was Amitabh Bachchan born?', 1942),
  year('In which year did Shah Rukh Khan\'s first film, Deewana, release?', 1992),
  year('In which year did the Eiffel Tower open?', 1889),
  year('In which year was Google founded?', 1998),
  year('In which year did YouTube launch?', 2005),
  year('In which year did Facebook launch?', 2004),
  year('In which year did Instagram launch?', 2010),
  year('In which year was WhatsApp founded?', 2009),
  year('In which year was the first iPhone released?', 2007),
  year('In which year was the first Harry Potter book published?', 1997),
  year('In which year did UPI payments launch in India?', 2016),

  // More heights, lengths and sizes
  size('How tall is K2, the second-highest mountain in the world?', 8611, 'metres'),
  size('How tall is Nanda Devi?', 7816, 'metres'),
  size('How tall is Mount Kilimanjaro in Africa?', 5895, 'metres'),
  size('How deep is Lake Baikal, the deepest lake in the world?', 1642, 'metres'),
  size('How long is the river Nile?', 6650, 'km', 'About 6,650 km; some measurements differ.'),
  size('How long is the river Godavari?', 1465, 'km'),
  size('How long is the river Yamuna?', 1376, 'km'),
  size('How long is the river Narmada?', 1312, 'km'),
  size('How big is the Sahara desert?', 92, 'lakh sq km', 'About 9.2 million square km.'),
  size('How big is Russia, the largest country?', 171, 'lakh sq km', 'About 17.1 million square km.'),
  size('How tall is Angel Falls in Venezuela, the highest waterfall?', 979, 'metres'),
  size('How tall is Jog Falls in Karnataka?', 253, 'metres'),
  size('How tall is Victoria Falls in Africa?', 108, 'metres'),
  size('How far below sea level is the shore of the Dead Sea?', 430, 'metres', 'About 430 m below sea level, and still falling.'),
  size('How long is the main span of the Golden Gate Bridge?', 1280, 'metres'),
  size('How tall is the Leaning Tower of Pisa?', 56, 'metres'),
  size('How tall is the Big Ben clock tower in London?', 96, 'metres'),
  size('How tall are the Petronas Towers in Kuala Lumpur?', 452, 'metres'),
  size('How tall is the Shanghai Tower?', 632, 'metres'),
  size('How tall is Taipei 101?', 508, 'metres'),
  size('How tall is the Empire State Building, up to its roof?', 381, 'metres', '443 m with its antenna.'),
  size('How tall is One World Trade Center in New York?', 541, 'metres'),
  size('How tall is the Charminar?', 56, 'metres', 'About 56 m to the top of its minarets.'),
  size('How tall is the Gateway of India?', 26, 'metres'),
  size('How tall is the Lotus Temple in Delhi?', 34, 'metres'),
  size('How tall is the Christ the Redeemer statue in Rio, without its base?', 30, 'metres', '38 m with the base.'),
  size('How tall was the Great Pyramid of Giza when it was built?', 146, 'metres', 'About 146.6 m; it is about 138 m today.'),
  size('How tall is the Tehri Dam, the tallest dam in India?', 260, 'metres', 'About 260.5 m.'),
  size('How tall is the Bhakra Dam?', 226, 'metres'),
  size('How high above the river is the Chenab rail bridge in Jammu and Kashmir?', 359, 'metres', 'The highest railway bridge in the world.'),
  size('How long is the Atal Tunnel under the Rohtang Pass?', 9.02, 'km'),
  size('How long is the Bandra-Worli Sea Link in Mumbai?', 5.6, 'km'),
  size('How long is Atal Setu, the Mumbai Trans Harbour Link?', 21.8, 'km', 'India\'s longest sea bridge.'),
  size('How long is the old Pamban rail bridge to Rameswaram?', 2.07, 'km', 'About 2,065 m.'),
  size('How long is the wall around Kumbhalgarh Fort in Rajasthan?', 36, 'km', 'Often called the second-longest wall in the world.'),
  size('How long is an Olympic swimming pool?', 50, 'metres'),
  size('How high is a basketball hoop from the floor?', 3.05, 'metres', 'Exactly 10 feet.'),
  size('How wide is a football goal?', 7.32, 'metres', 'Exactly 8 yards.'),
  size('How far is the penalty spot from the goal line in football?', 11, 'metres', '12 yards.'),
  size('How heavy is the shot put in men\'s athletics?', 7.26, 'kg', '16 pounds.'),
  size('How long is a standard cricket bat, at most?', 96.5, 'cm', 'The laws allow up to 38 inches.'),
  size('What is the circumference of the Earth around the equator?', 40075, 'km'),
  size('What is the diameter of the Moon?', 3474, 'km'),
  size('What is the diameter of the Sun?', 13.9, 'lakh km', 'About 1.39 million km.'),
  size('How many times wider than the Earth is Jupiter?', 11, 'times'),
  size('How far is the International Space Station above the Earth?', 400, 'km', 'It stays roughly 400 km up.'),
  size('How long is a light-year?', 9.46, 'lakh crore km', 'About 9.46 trillion km.'),
  size('How far away is Proxima Centauri, the nearest star after the Sun?', 4.24, 'light-years'),
  size('How long is the longest bone in your body, the thigh bone, in an adult?', 48, 'cm', 'About 48 cm, roughly a quarter of your height.'),
  size('How long is the stapes in the ear, the smallest bone in the body?', 3, 'mm'),
  size('How long is the small intestine of an adult?', 6, 'metres', 'Roughly 6 to 7 m.'),
  size('How much does an adult human brain weigh?', 1.4, 'kg'),
  size('How much do fingernails grow in a month?', 3.5, 'mm', 'About 3.5 mm.'),
  size('How much does hair on your head grow in a month?', 1.25, 'cm', 'About 1.25 cm.'),
  size('How tall can an adult male giraffe grow?', 5.5, 'metres', 'Up to about 5.5 m.'),
  size('How much does an ostrich egg weigh?', 1.4, 'kg', 'About 1.3 to 1.5 kg.'),
  size('How much does an adult blue whale weigh?', 150, 'tonnes', 'Around 150 tonnes; the biggest are heavier.'),
  size('How much does an adult male Bengal tiger weigh?', 220, 'kg', 'About 180 to 260 kg.'),
  size('How much does a newborn baby weigh on average?', 3, 'kg', 'About 3 kg; in India the average is a little lower.'),
  size('How much does a tennis ball weigh?', 58, 'grams', 'Between 56 and 59.4 g.'),
  size('How much does a football weigh?', 430, 'grams', 'Between 410 and 450 g.'),
  size('How much does a shuttlecock weigh?', 5, 'grams', 'Between 4.75 and 5.5 g.'),
  size('How much does a basketball weigh?', 600, 'grams', 'About 600 g.'),

  // Speeds
  size('What is the design top speed of the Vande Bharat Express?', 180, 'km/h', 'It runs at up to 160 km/h on most routes.'),
  size('How fast do Japan\'s fastest bullet trains run in service?', 320, 'km/h'),
  size('How fast does a passenger jet fly when cruising?', 900, 'km/h', 'About 850 to 950 km/h.'),
  size('What was Usain Bolt\'s top speed in his 9.58 s world record run?', 44.7, 'km/h'),
  size('How fast can a Formula 1 car go?', 370, 'km/h', 'The race record is about 372 km/h.'),
  size('How fast did Concorde fly?', 2180, 'km/h', 'About twice the speed of sound.'),
  size('What is the fastest recorded ball in cricket?', 161.3, 'km/h', 'Shoaib Akhtar, at the 2003 World Cup.'),
  size('What is the fastest recorded badminton smash?', 565, 'km/h', 'By India\'s Satwiksairaj Rankireddy in 2023.'),
  size('How fast can a peregrine falcon dive?', 320, 'km/h', 'Often over 300 km/h; the fastest animal on Earth.'),
  size('How fast can a racing greyhound run?', 70, 'km/h'),
  size('How fast does the Earth move around the Sun?', 30, 'km per second', 'About 107,000 km/h.'),
  size('How fast must a rocket go to escape the Earth\'s gravity?', 11.2, 'km per second'),
  size('How many minutes does sunlight take to reach the Earth?', 8.3, 'minutes', 'About 8 minutes 20 seconds.'),
  size('How many minutes does the International Space Station take to go once around the Earth?', 92, 'minutes'),

  // Space and science
  size('How old is the Earth?', 4.54, 'billion years'),
  size('How old is the universe?', 13.8, 'billion years'),
  size('How hot is the centre of the Earth?', 5200, '°C', 'Estimates are around 5,000 to 6,000 °C.'),
  size('How hot is the surface of Venus, the hottest planet?', 465, '°C'),
  size('At what temperature does water boil on top of Mount Everest?', 70, '°C', 'About 70 °C, because the air pressure is so low.'),
  size('How many Earths could fit inside the Sun?', 1300000, 'Earths', 'About 1.3 million.'),
  size('How many Earth days does Mars take to go around the Sun?', 687, 'days'),
  size('How long is one day on Mars?', 24.6, 'hours', '24 hours 37 minutes.'),
  size('How many days does the Moon take to go once around the Earth?', 27.3, 'days', '27.3 days; new moon to new moon takes 29.5.'),
  size('If you weigh 60 kg on Earth, what would a scale show on the Moon?', 10, 'kg', 'The Moon\'s gravity is about one sixth of Earth\'s.'),
  size('How many neurons does the human brain have?', 86, 'billion'),
  size('How many cells does an adult human body have?', 37, 'trillion', 'About 37 trillion, by a 2013 estimate.'),
  size('How many hairs are there on a human head?', 100000, 'hairs', 'About 100,000.'),
  size('How many times does a human heart beat in a day?', 100000, 'beats', 'About 100,000.'),
  size('How many breaths does an adult take in a day?', 22000, 'breaths', 'About 22,000.'),
  size('How long are all the blood vessels in one human body, laid end to end?', 100000, 'km', 'About 100,000 km: enough to go around the Earth twice.'),
  size('How many muscles are there in the human body?', 600, 'muscles', 'About 600.'),
  size('How many base pairs does human DNA have?', 3, 'billion', 'About 3 billion.'),
  size('How many days does a red blood cell live?', 120, 'days'),
  size('How many Scoville heat units does the bhut jolokia (ghost pepper) have?', 1000000, 'SHU', 'Over a million.'),
  size('How many seeds are there on the outside of a strawberry?', 200, 'seeds', 'About 200.'),
  size('How many pixels does a Full HD screen have?', 2073600, 'pixels', '1,920 × 1,080.'),
  size('How many different ways can a chess game start, counting the first move of each player?', 400, 'ways', 'White has 20 choices and Black has 20, so 400.'),

  // India in numbers
  size('How many seats in the Lok Sabha are filled by election?', 543, 'seats'),
  size('What is the most members the Rajya Sabha can have?', 250, 'members'),
  size('How many articles did the Constitution of India have when it was adopted?', 395, 'articles'),
  size('How many villages were counted in India in the 2011 census?', 6.4, 'lakh', '6,40,867 villages.'),
  size('What was the population of Mumbai city in the 2011 census?', 1.24, 'crore'),
  size('What was the population of Delhi in the 2011 census?', 1.68, 'crore'),
  size('What was the population of Sikkim, the least populated state, in the 2011 census?', 6.1, 'lakh'),
  size('How many people lived in each square km of India in 2011, on average?', 382, 'people'),
  size('How many tigers were counted in India in 2022?', 3682, 'tigers', 'The average estimate of the 2022 count; about 75% of the world\'s wild tigers.'),
  size('How many post offices does India have?', 160000, 'post offices', 'About 1.6 lakh: the biggest postal network in the world.'),
  size('How many kinds of birds are found in India?', 1300, 'species', 'About 1,300.'),
  size('How many varieties of mango are grown in India?', 1000, 'varieties', 'Over 1,000.'),
  size('How many rooms does Rashtrapati Bhavan have?', 340, 'rooms'),
  size('How many windows does the Hawa Mahal in Jaipur have?', 953, 'windows'),
  size('How many steps does the Chand Baori stepwell in Rajasthan have?', 3500, 'steps'),
  size('How many satellites did ISRO launch on one rocket in 2017, a world record at the time?', 104, 'satellites'),
  size('How much did the Mangalyaan mission to Mars cost?', 450, 'crore rupees', 'About 450 crore: less than many Hollywood films.'),
  size('How much did Chandrayaan-3 cost?', 615, 'crore rupees', 'About 615 crore.'),
  size('How many days did Chandrayaan-3 take to reach the Moon, from launch to landing?', 40, 'days', 'Launched 14 July 2023, landed 23 August.'),
  size('What was the biggest note the Reserve Bank of India ever printed?', 10000, 'rupees', 'The 10,000-rupee note, in 1938 and again in 1954.'),
  size('What was the top prize in Kaun Banega Crorepati when it started in 2000?', 10000000, 'rupees', 'One crore rupees.'),
  size('How much did Rishabh Pant go for in the 2025 IPL auction, a record?', 27, 'crore rupees'),
  size('How much does an Indian postcard cost?', 50, 'paise'),
  size('How many people could the Narendra Modi Stadium in Ahmedabad seat?', 132000, 'people', 'About 1.32 lakh: the largest cricket stadium in the world.'),
  size('How many runs did Sachin Tendulkar score in one-day internationals?', 18426, 'runs'),
  size('How many Test wickets did Anil Kumble take?', 619, 'wickets'),
  size('How many Test wickets did Kapil Dev take?', 434, 'wickets'),
  size('How many runs did MS Dhoni score in one-day internationals?', 10773, 'runs'),
  size('What is the highest team score in a one-day international?', 498, 'runs', 'England, against the Netherlands in 2022.'),
  size('What is the lowest team score in a Test innings?', 26, 'runs', 'New Zealand, against England in 1955.'),
  size('What is India\'s lowest score in a Test innings?', 36, 'runs', 'Against Australia in Adelaide, 2020.'),
  size('What is Don Bradman\'s Test batting average?', 99.94, 'runs'),
  size('What is the highest score by one batter in first-class cricket?', 501, 'runs', 'Brian Lara, 501 not out, in 1994.'),

  // Sport records
  size('What is the men\'s 100 m world record?', 9.58, 'seconds', 'Usain Bolt, 2009.'),
  size('What is the men\'s high jump world record?', 2.45, 'metres', 'Javier Sotomayor, 1993.'),
  size('What is the men\'s long jump world record?', 8.95, 'metres', 'Mike Powell, 1991.'),
  size('What is the men\'s javelin world record?', 98.48, 'metres', 'Jan Železný, 1996.'),
  size('How long did the fastest marathon ever run take?', 121, 'minutes', 'Kelvin Kiptum: 2 hours 0 minutes 35 seconds, in 2023.'),
  size('How much did Avatar (2009) earn at the box office worldwide?', 2.9, 'billion dollars', 'About 2.92 billion: the highest-grossing film ever.'),
  size('How much did the first iPhone cost when it came out in 2007?', 499, 'US dollars', 'For the 4 GB model.'),
  size('How much did it cost to build the Burj Khalifa?', 1.5, 'billion dollars'),

  // More counts
  count('How many players are on the field for one team in kho-kho?', 9, 'players'),
  count('How many players does a volleyball team have on the court?', 6, 'players'),
  count('How many players does a basketball team have on the court?', 5, 'players'),
  count('How many players does a hockey team have on the field?', 11, 'players'),
  count('How many players are in a rugby union team on the field?', 15, 'players'),
  count('How many players does a polo team have?', 4, 'players'),
  count('How many players does a water polo team have in the water?', 7, 'players'),
  count('How many minutes does a field hockey match last?', 60, 'minutes', 'Four quarters of 15 minutes.'),
  count('How many minutes does a kabaddi match last?', 40, 'minutes', 'Two halves of 20 minutes.'),
  count('How many points win a game of badminton?', 21, 'points'),
  count('How many points win a game of table tennis?', 11, 'points'),
  count('How many points win a set of volleyball (not the last set)?', 25, 'points'),
  count('How many holes are there on a full golf course?', 18, 'holes'),
  count('How many events are there in a decathlon?', 10, 'events'),
  count('How many events are there in a heptathlon?', 7, 'events'),
  count('How many teams play in the IPL?', 10, 'teams', 'Ten since 2022.'),
  count('How many times has Australia won the men\'s Cricket World Cup?', 6, 'times', '1987, 1999, 2003, 2007, 2015 and 2023.'),
  count('How many times has Brazil won the FIFA World Cup?', 5, 'times'),
  count('How many Olympic gold medals did Michael Phelps win?', 23, 'gold medals'),
  count('How many Wimbledon singles titles did Roger Federer win?', 8, 'titles'),
  count('How many Grand Slam singles titles has Novak Djokovic won?', 24, 'titles', 'As of 2025.'),
  count('How many one-day international double centuries has Rohit Sharma scored?', 3, 'double centuries'),
  count('How many Test centuries did Sachin Tendulkar score?', 51, 'centuries'),
  count('How many one-day international centuries did Sachin Tendulkar score?', 49, 'centuries'),
  count('How many legs does a spider have?', 8, 'legs'),
  count('How many legs does a crab have, counting its claws?', 10, 'legs'),
  count('How many eyes does a honeybee have?', 5, 'eyes', 'Two big ones and three small ones on top of its head.'),
  count('How many teeth does an adult dog have?', 42, 'teeth'),
  count('How many milk teeth does a child have?', 20, 'teeth'),
  count('How many chromosomes does a human cell have?', 46, 'chromosomes'),
  count('How many ribs does a human have?', 24, 'ribs', '12 pairs.'),
  count('How many bones are there in one human hand?', 27, 'bones'),
  count('How many vertebrae make up the human spine?', 33, 'vertebrae', '33, some of which join together as we grow.'),
  count('How many chambers does the human heart have?', 4, 'chambers'),
  count('How many lobes do the two human lungs have in total?', 5, 'lobes', 'Three on the right and two on the left.'),
  count('How many compartments does a cow\'s stomach have?', 4, 'compartments'),
  count('How many months does an elephant pregnancy last?', 22, 'months'),
  count('How many weeks does a human pregnancy usually last?', 40, 'weeks'),
  count('What is the normal human body temperature?', 37, '°C'),
  count('What percentage of the air is nitrogen?', 78, '%'),
  count('What percentage of the air is oxygen?', 21, '%'),
  count('What percentage of the Earth\'s surface is covered by water?', 71, '%'),
  count('What percentage of an adult\'s body is water?', 60, '%', 'About 60%.'),
  count('What percentage of a watermelon is water?', 92, '%'),
  count('What percentage of a cucumber is water?', 96, '%'),
  count('What percentage of an adult\'s body weight is blood?', 7, '%', 'About 7%.'),
  count('How many calories are there in one gram of fat?', 9, 'calories'),
  count('How many calories are there in one gram of protein?', 4, 'calories'),
  count('What is the atomic number of gold?', 79),
  count('What is the atomic number of iron?', 26),
  count('What is the atomic number of carbon?', 6),
  count('What is the atomic number of oxygen?', 8),
  count('How hard is a diamond on the Mohs scale?', 10),
  count('What is the pH of pure water?', 7),
  count('How many planets are there in our solar system?', 8, 'planets'),
  count('How many people have walked on the Moon?', 12, 'people'),
  count('How many fundamental rights does the Indian Constitution give?', 6, 'rights'),
  count('How many fundamental duties are there in the Indian Constitution?', 11, 'duties'),
  count('How many schedules does the Indian Constitution have?', 12, 'schedules'),
  count('How many lions are there on India\'s national emblem, counting the one at the back?', 4, 'lions', 'Only three can be seen from the front.'),
  count('How many languages are printed in the panel on the back of a rupee note?', 15, 'languages', 'Plus Hindi and English on the front.'),
  count('How many annas made one rupee before 1957?', 16, 'annas'),
  count('How many high courts does India have?', 25, 'high courts'),
  count('How many IITs are there in India?', 23, 'IITs'),
  count('How many states does the Tropic of Cancer pass through in India?', 8, 'states'),
  count('How many Indian states share a border with Bangladesh?', 5, 'states', 'West Bengal, Assam, Meghalaya, Tripura and Mizoram.'),
  count('How many islands make up Lakshadweep?', 36, 'islands'),
  count('How many minarets does the Taj Mahal have?', 4, 'minarets'),
  count('How many notes (swaras) are there in Indian classical music?', 7, 'swaras', 'Sa, Re, Ga, Ma, Pa, Dha, Ni.'),
  count('How many classical dance forms does the Sangeet Natak Akademi recognise?', 8, 'dance forms'),
  count('How many chapters does the Bhagavad Gita have?', 18, 'chapters'),
  count('How many kandas (books) does the Ramayana have?', 7, 'books'),
  count('How many books (parvas) does the Mahabharata have?', 18, 'books'),
  count('How many songs does the film Hum Aapke Hain Koun..! have?', 14, 'songs'),
  count('How many Oscars did the film Titanic win?', 11, 'Oscars'),
  count('How many Harry Potter films are there?', 8, 'films'),
  count('How many seasons of Friends were made?', 10, 'seasons'),
  size('How many episodes of Friends were made?', 236, 'episodes'),
  count('How many seasons of Game of Thrones were made?', 8, 'seasons'),
  count('How many members does BTS have?', 7, 'members'),
  count('How many questions did you need to answer to win one crore in the first season of KBC?', 15, 'questions'),
  count('How many characters can a tweet have now, for most users?', 280, 'characters'),
  count('How many bits make one byte?', 8, 'bits'),
  count('How many digits does an Aadhaar number have?', 12, 'digits'),
  count('How many characters does a PAN card number have?', 10, 'characters'),
  count('How many digits does an Indian PIN code have?', 6, 'digits'),
  count('How many characters does a bank IFSC code have?', 11, 'characters'),
  count('How many digits are there on most debit and credit cards?', 16, 'digits'),
  count('How many keys does a phone keypad have, counting * and #?', 12, 'keys'),
  count('How big was the screen of the first iPhone?', 3.5, 'inches'),
  size('How many people can be in one WhatsApp group?', 1024, 'people', 'Raised to 1,024 in 2022.'),
  count('What was India\'s literacy rate in the 2011 census?', 74, '%', '74.04%.'),
  count('What was Kerala\'s literacy rate in the 2011 census?', 94, '%'),
  size('How many women were there for every 1,000 men in India in the 2011 census?', 943, 'women'),

  // More years: India
  year('In which year was the Battle of Plassey fought?', 1757),
  year('In which year did the Revolt of 1857 begin?', 1857),
  year('In which year did the Jallianwala Bagh massacre happen?', 1919),
  year('In which year was the Quit India Movement launched?', 1942),
  year('In which year was the Indian National Congress founded?', 1885),
  year('In which year was Bengal first partitioned by the British?', 1905),
  year('In which year did Mahatma Gandhi come back to India from South Africa?', 1915),
  year('In which year was Bhagat Singh hanged?', 1931),
  year('In which year did Goa become part of India?', 1961),
  year('In which year did India carry out its first nuclear test at Pokhran?', 1974),
  year('In which year did India carry out the Pokhran-II nuclear tests?', 1998),
  year('In which year did Sikkim become a state of India?', 1975),
  year('In which year did India\'s first general election begin?', 1951),
  year('In which year was Aryabhata, India\'s first satellite, launched?', 1975),
  year('In which year did Rakesh Sharma become the first Indian in space?', 1984),
  year('In which year did Mangalyaan reach Mars?', 2014),
  year('In which year was Chandrayaan-1 launched?', 2008),
  year('In which year did Kalpana Chawla first go to space?', 1997),
  year('In which year did Doordarshan begin?', 1959),
  year('In which year did colour TV come to India, with the Asian Games in Delhi?', 1982),
  year('In which year were the first films shown in India, by the Lumière brothers in Bombay?', 1896),
  year('In which year did Rabindranath Tagore win the Nobel Prize in Literature?', 1913),
  year('In which year did C. V. Raman win the Nobel Prize in Physics?', 1930),
  year('In which year did Mother Teresa win the Nobel Peace Prize?', 1979),
  year('In which year did Amartya Sen win the Nobel Prize in Economics?', 1998),
  year('In which year did Kailash Satyarthi win the Nobel Peace Prize?', 2014),
  year('In which year was the Red Fort in Delhi completed?', 1648),
  year('In which year was the Hawa Mahal in Jaipur built?', 1799),
  year('In which year did the Victoria Memorial in Kolkata open?', 1921),
  year('In which year did the Howrah Bridge open?', 1943),
  year('In which year did the Bandra-Worli Sea Link open?', 2009),
  year('In which year did the Kolkata Metro, India\'s first metro, start running?', 1984),
  year('In which year did India play its first Test match?', 1932),
  year('In which year did India win its first Test match?', 1952),
  year('In which year did India win the first T20 World Cup?', 2007),
  year('In which year did India win its second Cricket World Cup?', 2011),
  year('In which year did India win its second T20 World Cup?', 2024),
  year('In which year did India win its first Olympic gold in hockey?', 1928),
  year('In which year did Milkha Singh finish fourth in the Olympic 400 m final?', 1960),
  year('In which year did Karnam Malleswari become the first Indian woman to win an Olympic medal?', 2000),
  year('In which year did Leander Paes win an Olympic bronze in tennis?', 1996),
  year('In which year did Viswanathan Anand become India\'s first chess grandmaster?', 1988),
  year('In which year did Sachin Tendulkar retire from international cricket?', 2013),
  year('In which year did Delhi host the Commonwealth Games?', 2010),
  year('In which year did the Pro Kabaddi League begin?', 2014),
  year('In which year did Indira Gandhi first become Prime Minister?', 1966),
  year('In which year did A. P. J. Abdul Kalam become President of India?', 2002),
  year('In which year was the Statue of Unity opened?', 2018),
  year('In which year did GST start in India?', 2017),
  year('In which year was the first Aadhaar number given out?', 2010),
  year('In which year did Jio launch its 4G service for everyone?', 2016),
  year('In which year was Flipkart founded?', 2007),
  year('In which year was Zomato founded?', 2008),
  year('In which year was Swiggy founded?', 2014),
  year('In which year was the Maruti 800 launched?', 1983),
  year('In which year was Amul founded?', 1946),
  year('In which year was Parle-G (then Parle Gluco) first made?', 1939),
  year('In which year was the Reserve Bank of India set up?', 1935),
  year('In which year did the first IIT open, at Kharagpur?', 1951),
  year('In which year was Mahatma Gandhi born?', 1869),
  year('In which year was Jawaharlal Nehru born?', 1889),
  year('In which year did Swami Vivekananda give his famous speech in Chicago?', 1893),
  year('In which year was Lata Mangeshkar born?', 1929),
  year('In which year was Sachin Tendulkar born?', 1973),
  year('In which year was Virat Kohli born?', 1988),
  year('In which year was MS Dhoni born?', 1981),
  year('In which year did A. R. Rahman win two Oscars for Slumdog Millionaire?', 2009),
  year('In which year did "Naatu Naatu" from RRR win the Oscar for Best Original Song?', 2023),
  year('In which year was Hum Aapke Hain Koun..! released?', 1994),
  year('In which year was Kuch Kuch Hota Hai released?', 1998),
  year('In which year was 3 Idiots released?', 2009),
  year('In which year was Lagaan released?', 2001),
  year('In which year was Baahubali: The Beginning released?', 2015),
  year('In which year was Mr. India released?', 1987),
  year('In which year did Kaun Banega Crorepati first air?', 2000),
  year('In which year did Shaktimaan first air?', 1997),
  year('In which year did the ₹2,000 note come out?', 2016),

  // More years: the world
  year('In which year did Columbus first reach the Americas?', 1492),
  year('In which year was the Magna Carta signed?', 1215),
  year('In which year did the French Revolution begin?', 1789),
  year('In which year did the USA declare independence?', 1776),
  year('In which year did World War I begin?', 1914),
  year('In which year did World War I end?', 1918),
  year('In which year did World War II begin?', 1939),
  year('In which year did the Wright brothers make the first powered flight?', 1903),
  year('In which year did Yuri Gagarin become the first person in space?', 1961),
  year('In which year was Sputnik, the first satellite, launched?', 1957),
  year('In which year was the Hubble Space Telescope launched?', 1990),
  year('In which year did the first website go online?', 1991),
  year('In which year was the first email sent?', 1971),
  year('In which year was Microsoft founded?', 1975),
  year('In which year was Apple founded?', 1976),
  year('In which year was Amazon founded?', 1994),
  year('In which year did Twitter launch?', 2006),
  year('In which year was Netflix founded?', 1997),
  year('In which year did Wikipedia launch?', 2001),
  year('In which year did the first Android phone go on sale?', 2008),
  year('In which year was the first Bitcoin created?', 2009),
  year('In which year was ChatGPT released?', 2022),
  year('In which year did the Nokia 3310 come out?', 2000),
  year('In which year did Alexander Graham Bell patent the telephone?', 1876),
  year('In which year did Alexander Fleming discover penicillin?', 1928),
  year('In which year was the shape of DNA, the double helix, discovered?', 1953),
  year('In which year was Dolly the sheep, the first cloned mammal, born?', 1996),
  year('In which year was the world\'s first test-tube baby born?', 1978),
  year('In which year did Einstein publish his special theory of relativity?', 1905),
  year('In which year did Isaac Newton publish his laws of motion (the Principia)?', 1687),
  year('In which year was William Shakespeare born?', 1564),
  year('In which year was the Statue of Liberty unveiled?', 1886),
  year('In which year did the Panama Canal open?', 1914),
  year('In which year did the Suez Canal open?', 1869),
  year('In which year did the Chernobyl nuclear disaster happen?', 1986),
  year('In which year were the first modern Olympic Games held?', 1896),
  year('In which year were the Olympics first held in Asia, in Tokyo?', 1964),
  year('In which year was Mount Everest first climbed?', 1953),
  year('In which year did Roald Amundsen reach the South Pole?', 1911),
  year('In which year did Disneyland open?', 1955),
  year('In which year did Mickey Mouse first appear?', 1928),
  year('In which year did the first Star Wars film come out?', 1977),
  year('In which year did Jurassic Park come out?', 1993),
  year('In which year did the film Titanic come out?', 1997),
  year('In which year did Avengers: Endgame come out?', 2019),
  year('In which year did the first Pokémon games come out?', 1996),
  year('In which year did Super Mario Bros. come out?', 1985),
  year('In which year did the first PlayStation come out?', 1994),
  year('In which year was the Rubik\'s Cube invented?', 1974),
  year('In which year did euro coins and notes come into use?', 2002),
  year('In which year did the Burj Khalifa open?', 2010),
  year('In which year did Thomas Edison patent his light bulb?', 1880),
  year('In which year did the Covid-19 outbreak become a pandemic?', 2020),
  year('In which year did the first Harry Potter film come out?', 2001),
  year('In which year did the first iPad come out?', 2010),
  year('In which year did India first launch a satellite on its own rocket (Rohini, on SLV-3)?', 1980),
  year('In which year did Sunil Gavaskar become the first batter to score 10,000 Test runs?', 1987),
  year('In which year did K. D. Jadhav win India\'s first individual Olympic medal?', 1952),
  year('In which year did Saina Nehwal win an Olympic bronze in badminton?', 2012),
  year('In which year did P. V. Sindhu win an Olympic silver in badminton?', 2016),
  year('In which year did Mary Kom win an Olympic bronze in boxing?', 2012),
  year('In which year did D. Gukesh become the world chess champion?', 2024),
  year('In which year did the Konkan Railway start running along its full length?', 1998),
  year('In which year did the British announce that India\'s capital would move from Calcutta to Delhi?', 1911),
  year('In which year was New Delhi officially opened as the capital?', 1931),
  year('In which year did the Amul girl first appear in ads?', 1966),
  year('In which year did the Taj Mahal become a UNESCO World Heritage Site?', 1983),
  year('In which year did Reita Faria become the first Indian to win Miss World?', 1966),
  year('In which year did Sushmita Sen win Miss Universe?', 1994),
  year('In which year did Harnaaz Sandhu win Miss Universe?', 2021),

  // Games, boards and courts
  count('How many squares are there on a Snakes and Ladders board?', 100, 'squares'),
  count('How many cards are there in a pack, not counting jokers?', 52, 'cards'),
  count('How many dots are there on a dice altogether?', 21, 'dots'),
  count('How many pieces does each player start with in chess?', 16, 'pieces'),
  count('How many coins are on a carrom board at the start, not counting the striker?', 19, 'coins', '9 white, 9 black and the red queen.'),
  size('How many tiles are there in an English Scrabble set?', 100, 'tiles'),
  size('How many squares are there on a Scrabble board?', 225, 'squares', '15 by 15.'),
  count('How many coloured squares are there on the outside of a Rubik\'s Cube?', 54, 'squares'),
  count('How many dominoes are there in a standard double-six set?', 28, 'dominoes'),
  count('How many strings does a guitar usually have?', 6, 'strings'),
  count('How many strings does a violin have?', 4, 'strings'),
  size('How long is a kabaddi court for men?', 13, 'metres', '13 m long and 10 m wide.'),
  size('How long is a badminton court?', 13.4, 'metres'),
  size('How long is a tennis court?', 23.77, 'metres'),
  size('How tall is a table tennis net?', 15.25, 'cm'),
  size('How tall are cricket stumps?', 71.1, 'cm', '28 inches.'),
  size('How wide is a cricket pitch?', 3.05, 'metres', '10 feet.'),

  // The world
  count('How many stripes are there on the flag of the USA?', 13, 'stripes'),
  count('How many stars are there on the flag of China?', 5, 'stars'),
  count('How many countries are there in Africa?', 54, 'countries'),
  count('How many countries are there in South America?', 12, 'countries'),
  count('How many countries are in the European Union?', 27, 'countries'),
  count('How many time zones does Russia have?', 11, 'time zones'),
  count('How many official languages does the United Nations have?', 6, 'languages'),
  count('How many permanent members does the UN Security Council have?', 5, 'members'),
  size('How tall is the Burj Al Arab hotel in Dubai?', 321, 'metres'),
  size('How tall is the Statue of Equality in Hyderabad?', 66, 'metres', '216 feet.'),
  size('How tall is the Thiruvalluvar Statue at Kanyakumari?', 41, 'metres', '133 feet: one for each chapter of the Thirukkural.'),
  size('How big is Delhi?', 1484, 'sq km'),
  size('How big is Goa, the smallest state?', 3702, 'sq km'),
  size('How heavy is the Kohinoor diamond today?', 105.6, 'carats'),
  size('How long is the Mumbai-Pune Expressway?', 94.5, 'km'),
  size('How long is the Yamuna Expressway from Greater Noida to Agra?', 165, 'km'),
  size('How long is the platform at Gorakhpur station, the longest in the world?', 1366, 'metres'),
  count('How many platforms does Howrah station have?', 23, 'platforms'),

  // Animals
  count('How many legs does an insect have?', 6, 'legs'),
  count('How many arms does a starfish usually have?', 5, 'arms'),
  count('How many wings does a honeybee have?', 4, 'wings'),
  count('How many teeth does an adult cat have?', 30, 'teeth'),
  count('How many hours a day can a koala sleep?', 20, 'hours', 'Up to 20 to 22 hours.'),
  size('How much water can an adult elephant drink in a day?', 150, 'litres', 'Around 150 to 200 litres.'),

  // Units
  count('How many teaspoons make one tablespoon?', 3, 'teaspoons'),
  count('How many millilitres are there in a teaspoon?', 5, 'ml'),
  size('How many grams are there in a pound?', 454, 'grams'),
  size('How many centimetres are there in an inch?', 2.54, 'cm'),
  size('How many kilometres are there in a mile?', 1.61, 'km'),
  size('How many feet are there in a metre?', 3.28, 'feet'),
  size('How many square feet are there in a square metre?', 10.76, 'sq ft'),
  size('How many square feet are there in one acre?', 43560, 'sq ft'),
  size('How many litres are there in an American gallon?', 3.79, 'litres'),
]
