// Closest Wins questions. Answers are well-established figures; where a number is rounded or has changed, the note
// says so. log: closeness by ratio (heights, distances, big counts); otherwise by difference (years, small counts).

export interface Estimate { q: string; a: number; unit: string; log: boolean; note?: string }

const year = (q: string, a: number, note?: string): Estimate => ({ q, a, unit: 'year', log: false, note })
const count = (q: string, a: number, unit = '', note?: string): Estimate => ({ q, a, unit, log: false, note })
const size = (q: string, a: number, unit: string, note?: string): Estimate => ({ q, a, unit, log: true, note })

export const ESTIMATES: Estimate[] = [
  // Heights and sizes
  size('How tall is Mount Everest?', 8849, 'metres', 'Measured jointly by Nepal and China in 2020.'),
  size('How tall is the Burj Khalifa in Dubai?', 828, 'metres'),
  size('How many floors does the Burj Khalifa have?', 163, 'floors'),
  size('How tall is the Statue of Unity in Gujarat (the statue itself)?', 182, 'metres', 'The tallest statue in the world.'),
  size('How tall is the Qutub Minar?', 73, 'metres', 'About 72.5 m.'),
  size('How tall is India Gate in Delhi?', 42, 'metres'),
  size('How tall is the Eiffel Tower today, with its antennas?', 330, 'metres'),
  size('How tall is the Statue of Liberty, from the ground to the torch?', 93, 'metres', 'The statue alone is about 46 m; the rest is the pedestal.'),
  size('How tall is Kanchenjunga, the highest mountain in India?', 8586, 'metres'),
  size('How deep is the deepest known point of the ocean (Challenger Deep)?', 10935, 'metres', 'About 10.9 km, in the Mariana Trench.'),
  size('How long is a cricket pitch, wicket to wicket?', 20.12, 'metres', 'Exactly 22 yards.'),
  size('How long can the largest blue whales grow?', 30, 'metres', 'About 30 m: the biggest animal that has ever lived.'),
  size('How much does an adult male African elephant weigh?', 6000, 'kg', 'About 6,000 kg; females are about half that.'),
  size('How much does a cricket ball weigh?', 160, 'grams', 'Between 155.9 and 163 g for men\'s cricket.'),
  size('How many grams are there in one tola of gold?', 11.66, 'grams', '1 tola = 11.6638 g.'),
  size('How many litres of blood does an adult human body have?', 5, 'litres', 'About 5 litres.'),
  size('What is the diameter of the Earth?', 12742, 'km'),
  size('What is the average distance from the Earth to the Moon?', 384400, 'km'),
  size('What is the average distance from the Earth to the Sun?', 150, 'million km', 'About 149.6 million km.'),
  size('How fast does light travel?', 300000, 'km per second', '299,792 km per second.'),
  size('How fast does sound travel in air at room temperature?', 343, 'metres per second'),
  size('How hot is the surface of the Sun?', 5500, '°C', 'About 5,500 °C.'),
  size('What is the top speed of a cheetah?', 110, 'km/h', 'Roughly 100 to 120 km/h in short bursts.'),
  size('How long is a marathon?', 42.195, 'km'),
  size('How far is Mumbai from Delhi in a straight line?', 1150, 'km', 'About 1,150 km as the crow flies; much more by road.'),
  size('How far is it from Kashmir to Kanyakumari, India\'s north-south length?', 3214, 'km'),
  size('How long is the river Ganga?', 2525, 'km'),
  size('How long is the Great Wall of China, counting all its branches?', 21196, 'km', 'From China\'s 2012 survey.'),
  size('What is the area of India?', 32.87, 'lakh sq km', '3,287,263 square km.'),
  size('What was India\'s population in the 2011 census?', 121, 'crore', '121.09 crore, or about 1.21 billion.'),
  size('What is the population of the whole world, roughly?', 800, 'crore', 'It passed 8 billion (800 crore) in 2022.'),
  size('How many runs did Sachin Tendulkar score in Test cricket?', 15921, 'runs'),
  size('How many Test wickets did Muttiah Muralitharan take?', 800, 'wickets'),
  size('What was the promised price of the Tata Nano when it was launched in 2008?', 100000, 'rupees', 'One lakh rupees.'),
  size('How many seconds are there in one day?', 86400, 'seconds'),
  size('How many minutes are there in one day?', 1440, 'minutes'),
  size('How many hours are there in a week?', 168, 'hours'),
  size('What is the boiling point of water in Fahrenheit?', 212, '°F'),
  size('How far did Neeraj Chopra throw the javelin to win gold at the Tokyo Olympics?', 87.58, 'metres'),
  size('What is the highest score by one batter in a one-day international?', 264, 'runs', 'Rohit Sharma, against Sri Lanka in 2014.'),
  size('What is the highest score by one batter in a Test innings?', 400, 'runs', 'Brian Lara, 400 not out, in 2004.'),

  // Counts
  count('How many keys does a standard piano have?', 88, 'keys'),
  count('How many bones are there in an adult human body?', 206, 'bones'),
  count('How many teeth does an adult have, counting wisdom teeth?', 32, 'teeth'),
  count('How many hearts does an octopus have?', 3, 'hearts'),
  count('How many countries are members of the United Nations?', 193, 'countries'),
  count('How many states does India have?', 28, 'states'),
  count('How many union territories does India have?', 8, 'union territories'),
  count('How many languages are listed in the Eighth Schedule of the Indian Constitution?', 22, 'languages'),
  count('How many spokes does the Ashoka Chakra on the Indian flag have?', 24, 'spokes'),
  count('How many squares are there on a chessboard?', 64, 'squares'),
  count('How many chemical elements are in the periodic table?', 118, 'elements'),
  count('How many stars are on the flag of the USA?', 50, 'stars'),
  count('How many moons does Mars have?', 2, 'moons'),
  count('How many time zones does India use?', 1, 'time zones', 'Just one: Indian Standard Time.'),
  count('How many players from each team are on the court in kabaddi?', 7, 'players'),
  count('How many episodes did the original Ramayan TV serial (1987) have?', 78, 'episodes'),
  count('How many episodes did B. R. Chopra\'s Mahabharat (1988) have?', 94, 'episodes'),
  count('How many international centuries did Sachin Tendulkar score?', 100, 'centuries'),
  count('How many wickets did Anil Kumble take in one Test innings against Pakistan in 1999?', 10, 'wickets'),
  count('How many Harry Potter books are there in the main series?', 7, 'books'),
  count('How many characters could a tweet have before 2017?', 140, 'characters'),
  count('How many years did it take to build the Taj Mahal?', 22, 'years', 'Roughly 1632 to 1653.'),
  count('How many Earth days was Chandrayaan-3\'s lander built to work on the Moon?', 14, 'days', 'One lunar day.'),

  // Years
  year('In which year did India win its first Cricket World Cup?', 1983),
  year('In which year was the first Cricket World Cup played?', 1975),
  year('In which year did the Indian Constitution come into effect?', 1950),
  year('In which year did Mahatma Gandhi lead the Dandi Salt March?', 1930),
  year('In which year did work on the Taj Mahal begin?', 1632),
  year('In which year was the Charminar in Hyderabad built?', 1591),
  year('In which year was the Gateway of India completed?', 1924),
  year('In which year did the first passenger train in India run, from Bombay to Thane?', 1853),
  year('In which year did the Delhi Metro start running?', 2002),
  year('In which year was ISRO founded?', 1969),
  year('In which year did Chandrayaan-3 land on the Moon?', 2023),
  year('In which year did humans first walk on the Moon?', 1969),
  year('In which year did the Titanic sink?', 1912),
  year('In which year did World War II end?', 1945),
  year('In which year did the Berlin Wall fall?', 1989),
  year('In which year was the first FIFA World Cup held?', 1930),
  year('In which year did India first host the Asian Games?', 1951),
  year('In which year was the first IPL season played?', 2008),
  year('In which year did Sachin Tendulkar play his first international match?', 1989),
  year('In which year did Virat Kohli make his one-day international debut?', 2008),
  year('In which year did Abhinav Bindra win India\'s first individual Olympic gold?', 2008),
  year('In which year was the rupee symbol ₹ adopted?', 2010),
  year('In which year was Sholay released?', 1975),
  year('In which year was Dilwale Dulhania Le Jayenge released?', 1995),
  year('In which year was Mughal-e-Azam released?', 1960),
  year('In which year was Amitabh Bachchan born?', 1942),
  year('In which year did Shah Rukh Khan\'s first film, Deewana, release?', 1992),
  year('In which year did the Eiffel Tower open?', 1889),
  year('In which year was Google founded?', 1998),
  year('In which year did YouTube launch?', 2005),
  year('In which year did Facebook launch?', 2004),
  year('In which year did Instagram launch?', 2010),
  year('In which year was WhatsApp founded?', 2009),
  year('In which year was the first iPhone released?', 2007),
  year('In which year was the first Harry Potter book published?', 1997),
  year('In which year did UPI payments launch in India?', 2016),
]
