// Imposter word pairs. The group gets one word; in Undercover the imposter gets the other, close enough that they do
// not notice at first. In the classic mode the imposter only sees the category.

export interface Pair { cat: string; a: string; b: string }

const P = (cat: string, list: [string, string][]) => list.map(([a, b]) => ({ cat, a, b }))

export const IMPOSTER_PAIRS: Pair[] = [
  ...P('Food', [
    ['Samosa', 'Kachori'], ['Pizza', 'Burger'], ['Dosa', 'Uttapam'], ['Idli', 'Dhokla'], ['Biryani', 'Pulao'], ['Pani puri', 'Bhel puri'],
    ['Jalebi', 'Imarti'], ['Gulab jamun', 'Rasgulla'], ['Momos', 'Dumplings'], ['Maggi', 'Pasta'], ['Paratha', 'Naan'],
    ['Chole bhature', 'Puri sabzi'], ['Pav bhaji', 'Vada pav'], ['Ice cream', 'Kulfi'], ['Chocolate', 'Toffee'], ['Sandwich', 'Wrap'],
    ['Cake', 'Pastry'], ['Popcorn', 'Chips'], ['Rajma chawal', 'Kadhi chawal'], ['Butter chicken', 'Paneer butter masala'],
    ['Lassi', 'Buttermilk'], ['Tea', 'Coffee'], ['Coconut water', 'Sugarcane juice'], ['Mango', 'Papaya'], ['Banana', 'Apple'],
    ['Watermelon', 'Muskmelon'], ['Ladoo', 'Barfi'], ['Khichdi', 'Daliya'], ['Poha', 'Upma'], ['Omelette', 'Bhurji'],
  ]),
  ...P('Places', [
    ['Beach', 'Swimming pool'], ['School', 'College'], ['Hospital', 'Clinic'], ['Airport', 'Railway station'], ['Mall', 'Market'],
    ['Cinema hall', 'Theatre'], ['Temple', 'Gurudwara'], ['Library', 'Bookshop'], ['Gym', 'Yoga class'], ['Park', 'Garden'],
    ['Hill station', 'Beach resort'], ['Goa', 'Kerala'], ['Manali', 'Shimla'], ['Mumbai', 'Delhi'], ['Hostel', 'PG'],
    ['Office', 'Co-working space'], ['Zoo', 'Safari'], ['Restaurant', 'Dhaba'], ['Bank', 'ATM'], ['Wedding hall', 'Banquet'],
  ]),
  ...P('Things', [
    ['Umbrella', 'Raincoat'], ['Laptop', 'Tablet'], ['Phone', 'Smartwatch'], ['Pen', 'Pencil'], ['Fan', 'Cooler'],
    ['Pillow', 'Blanket'], ['Toothbrush', 'Comb'], ['Shoes', 'Slippers'], ['Watch', 'Bracelet'], ['Backpack', 'Suitcase'],
    ['Mirror', 'Window'], ['Candle', 'Diya'], ['Scissors', 'Knife'], ['Bucket', 'Mug'], ['Chair', 'Stool'], ['Sofa', 'Bed'],
    ['Headphones', 'Earphones'], ['Camera', 'Binoculars'], ['Key', 'Lock'], ['Wallet', 'Purse'], ['Book', 'Newspaper'],
    ['Television', 'Projector'], ['Pressure cooker', 'Kadai'], ['Fridge', 'Freezer'], ['Sunglasses', 'Spectacles'],
  ]),
  ...P('Animals', [
    ['Lion', 'Tiger'], ['Dog', 'Wolf'], ['Cat', 'Leopard'], ['Horse', 'Donkey'], ['Crocodile', 'Lizard'], ['Eagle', 'Parrot'],
    ['Cow', 'Buffalo'], ['Monkey', 'Gorilla'], ['Shark', 'Dolphin'], ['Rabbit', 'Squirrel'], ['Butterfly', 'Moth'],
    ['Snake', 'Earthworm'], ['Camel', 'Giraffe'], ['Duck', 'Swan'], ['Bee', 'Wasp'], ['Frog', 'Toad'], ['Mosquito', 'Fly'],
  ]),
  ...P('Sports and games', [
    ['Cricket', 'Baseball'], ['Football', 'Hockey'], ['Badminton', 'Tennis'], ['Chess', 'Carrom'], ['Ludo', 'Snakes and ladders'],
    ['Kabaddi', 'Kho-kho'], ['Swimming', 'Diving'], ['Boxing', 'Wrestling'], ['PUBG', 'Free Fire'], ['Cycling', 'Running'],
    ['Table tennis', 'Squash'], ['Volleyball', 'Basketball'], ['Gilli danda', 'Pithu'], ['Cards', 'Dice'],
  ]),
  ...P('Jobs', [
    ['Doctor', 'Nurse'], ['Teacher', 'Principal'], ['Pilot', 'Air hostess'], ['Chef', 'Waiter'], ['Police officer', 'Security guard'],
    ['Actor', 'Singer'], ['Engineer', 'Architect'], ['Lawyer', 'Judge'], ['Barber', 'Tailor'], ['Farmer', 'Gardener'],
    ['YouTuber', 'Influencer'], ['Dentist', 'Surgeon'], ['Shopkeeper', 'Salesman'], ['Driver', 'Conductor'],
  ]),
  ...P('Events', [
    ['Wedding', 'Engagement'], ['Birthday party', 'Farewell'], ['Diwali', 'Christmas'], ['Holi', 'Rang Panchami'], ['Exam', 'Interview'],
    ['Picnic', 'Road trip'], ['Concert', 'Stand-up show'], ['Cricket match', 'IPL final'], ['Sleepover', 'House party'],
    ['Lohri', 'Makar Sankranti'], ['Navratri', 'Durga Puja'], ['Raksha Bandhan', 'Bhai Dooj'],
  ]),
  ...P('Apps and brands', [
    ['WhatsApp', 'Telegram'], ['Instagram', 'Snapchat'], ['YouTube', 'Netflix'], ['Swiggy', 'Zomato'], ['Amazon', 'Flipkart'],
    ['Google Pay', 'PhonePe'], ['Uber', 'Ola'], ['Spotify', 'JioSaavn'], ['Coca-Cola', 'Pepsi'], ['Parle-G', 'Marie biscuit'],
    ['Dairy Milk', 'KitKat'], ['Maruti', 'Hyundai'], ['iPhone', 'Samsung'], ['McDonald\'s', 'KFC'], ['Domino\'s', 'Pizza Hut'],
  ]),
  ...P('Movies and characters', [
    ['Batman', 'Superman'], ['Spider-Man', 'Iron Man'], ['Harry Potter', 'Lord of the Rings'], ['Doraemon', 'Shin-chan'],
    ['Chhota Bheem', 'Motu Patlu'], ['Sholay', 'Deewar'], ['Mickey Mouse', 'Tom and Jerry'], ['Bahubali', 'KGF'],
    ['3 Idiots', 'Chhichhore'], ['Hera Pheri', 'Welcome'], ['Shaktimaan', 'Krrish'], ['Avengers', 'Justice League'],
  ]),
  ...P('Nature', [
    ['Rain', 'Snow'], ['Sun', 'Moon'], ['River', 'Lake'], ['Mountain', 'Volcano'], ['Forest', 'Jungle'], ['Desert', 'Beach'],
    ['Rose', 'Lotus'], ['Thunder', 'Lightning'], ['Rainbow', 'Sunset'], ['Island', 'Peninsula'], ['Star', 'Planet'],
    ['Cloud', 'Fog'], ['Wave', 'Tide'], ['Cave', 'Tunnel'], ['Waterfall', 'Fountain'], ['Earthquake', 'Landslide'], ['Storm', 'Cyclone'],
    ['Pond', 'Well'], ['Hill', 'Cliff'], ['Sand', 'Mud'], ['Leaf', 'Petal'], ['Seed', 'Nut'], ['Tree', 'Bush'], ['Grass', 'Moss'],
    ['Comet', 'Meteor'], ['Moonlight', 'Sunlight'], ['Dew', 'Frost'], ['Glacier', 'Iceberg'], ['Ocean', 'Sea'], ['Monsoon', 'Winter'],
  ]),
  ...P('Street food and snacks', [
    ['Aloo tikki', 'Samosa chaat'], ['Dahi puri', 'Sev puri'], ['Kathi roll', 'Burrito'], ['Chowmein', 'Fried rice'], ['Spring roll', 'Momos'],
    ['Pakoda', 'Cutlet'], ['Bread pakoda', 'Sandwich'], ['Corn on the cob', 'Sweet corn cup'], ['Ram laddoo', 'Dahi bhalla'],
    ['Dabeli', 'Vada pav'], ['Misal pav', 'Usal'], ['Kachori', 'Mathri'], ['Chakli', 'Murukku'], ['Khakhra', 'Thepla'], ['Fafda', 'Gathiya'],
    ['Banana chips', 'Potato chips'], ['Peanuts', 'Chana'], ['Bhutta', 'Popcorn'], ['Chicken roll', 'Egg roll'],
    ['Shawarma', 'Kebab roll'], ['Litti chokha', 'Sattu paratha'], ['Kulcha', 'Bhatura'], ['Medu vada', 'Dahi vada'], ['Sabudana vada', 'Batata vada'],
  ]),
  ...P('Meals', [
    ['Dal makhani', 'Dal tadka'], ['Chicken biryani', 'Mutton biryani'], ['Palak paneer', 'Matar paneer'], ['Aloo gobi', 'Aloo matar'],
    ['Sambar', 'Rasam'], ['Curd rice', 'Lemon rice'], ['Masala dosa', 'Rava dosa'], ['Appam', 'Neer dosa'], ['Puttu', 'Idiyappam'],
    ['Thali', 'Combo meal'], ['Tandoori chicken', 'Chicken tikka'], ['Fish curry', 'Prawn curry'], ['Egg curry', 'Egg bhurji'],
    ['Chole', 'Rajma'], ['Baingan bharta', 'Bhindi masala'], ['Kadhi', 'Sambar'], ['Pulao', 'Jeera rice'], ['Roti', 'Phulka'],
    ['Makki di roti', 'Bajra roti'], ['Sarson ka saag', 'Palak'], ['Dal baati', 'Litti'], ['Vada sambar', 'Idli sambar'],
    ['Hakka noodles', 'Schezwan noodles'], ['Manchurian', 'Chilli paneer'], ['Pasta', 'Spaghetti'], ['Lasagne', 'Pizza'], ['Burrito', 'Wrap'],
    ['Soup', 'Stew'], ['Salad', 'Raita'], ['Cornflakes', 'Muesli'], ['Bread butter', 'Bread jam'], ['Toast', 'Rusk'],
  ]),
  ...P('Sweets and desserts', [
    ['Rasmalai', 'Rabri'], ['Kaju katli', 'Soan papdi'], ['Motichoor laddoo', 'Besan laddoo'], ['Gajar halwa', 'Moong dal halwa'],
    ['Kheer', 'Phirni'], ['Sandesh', 'Rasgulla'], ['Peda', 'Barfi'], ['Ghevar', 'Malpua'], ['Mysore pak', 'Soan papdi'], ['Shrikhand', 'Mishti doi'],
    ['Modak', 'Karanji'], ['Chikki', 'Gajak'], ['Brownie', 'Chocolate cake'], ['Cheesecake', 'Pastry'], ['Muffin', 'Cupcake'],
    ['Donut', 'Bagel'], ['Waffle', 'Pancake'], ['Pudding', 'Custard'], ['Falooda', 'Kulfi'], ['Sundae', 'Milkshake'],
    ['Cotton candy', 'Lollipop'], ['Gems', 'M&Ms'], ['Five Star', 'Snickers'], ['Candy', 'Chewing gum'], ['Cookies', 'Cream biscuits'],
  ]),
  ...P('Drinks', [
    ['Masala chai', 'Green tea'], ['Cold coffee', 'Hot chocolate'], ['Filter coffee', 'Instant coffee'], ['Nimbu pani', 'Jaljeera'],
    ['Aam panna', 'Mango shake'], ['Thandai', 'Badam milk'], ['Rooh Afza', 'Rasna'], ['Frooti', 'Maaza'], ['Sprite', '7Up'],
    ['Thums Up', 'Coca-Cola'], ['Mountain Dew', 'Mirinda'], ['Red Bull', 'Sting'], ['Soda', 'Tonic water'], ['Milk', 'Curd'],
    ['Orange juice', 'Mosambi juice'], ['Kokum sharbat', 'Sol kadhi'], ['Coconut milk', 'Almond milk'], ['Haldi doodh', 'Kadha'],
  ]),
  ...P('Fruits and vegetables', [
    ['Guava', 'Pear'], ['Chikoo', 'Kiwi'], ['Litchi', 'Rambutan'], ['Jamun', 'Blueberry'], ['Orange', 'Mosambi'], ['Lemon', 'Lime'],
    ['Pomegranate', 'Dragon fruit'], ['Jackfruit', 'Durian'], ['Custard apple', 'Pineapple'], ['Plum', 'Peach'], ['Grapes', 'Cherries'],
    ['Strawberry', 'Raspberry'], ['Dates', 'Figs'], ['Almonds', 'Cashews'], ['Walnut', 'Pistachio'], ['Raisins', 'Dried apricots'],
    ['Potato', 'Sweet potato'], ['Onion', 'Garlic'], ['Ginger', 'Turmeric'], ['Cabbage', 'Cauliflower'], ['Carrot', 'Radish'],
    ['Peas', 'Beans'], ['Spinach', 'Methi'], ['Lauki', 'Tori'], ['Karela', 'Parwal'], ['Capsicum', 'Chilli'], ['Tomato', 'Beetroot'],
    ['Pumpkin', 'Lauki'], ['Brinjal', 'Zucchini'], ['Mushroom', 'Corn'], ['Coriander', 'Mint'], ['Cucumber', 'Zucchini'],
  ]),
  ...P('Around the house', [
    ['Bedsheet', 'Curtain'], ['Doormat', 'Carpet'], ['Sofa', 'Recliner'], ['Wardrobe', 'Almirah'], ['Bookshelf', 'Cupboard'],
    ['Tube light', 'Bulb'], ['Inverter', 'Generator'], ['Geyser', 'Immersion rod'], ['Washing machine', 'Dishwasher'], ['Microwave', 'Oven'],
    ['Mixer', 'Blender'], ['Toaster', 'Sandwich maker'], ['Gas stove', 'Induction'], ['Tawa', 'Frying pan'], ['Bucket', 'Tub'],
    ['Broom', 'Mop'], ['Soap', 'Shampoo'], ['Toothpaste', 'Mouthwash'], ['Towel', 'Napkin'], ['Comb', 'Hairbrush'], ['Razor', 'Trimmer'],
    ['Nail cutter', 'Scissors'], ['Hanger', 'Clothes clip'], ['Iron', 'Steamer'], ['Plate', 'Bowl'], ['Glass', 'Cup'], ['Spoon', 'Ladle'],
    ['Water bottle', 'Flask'], ['Tiffin box', 'Lunch bag'], ['Dustbin', 'Recycle bin'], ['Doorbell', 'Intercom'], ['Lock', 'Latch'],
    ['Staircase', 'Lift'], ['Balcony', 'Terrace'], ['Kitchen', 'Pantry'], ['Bathroom', 'Toilet'], ['Garage', 'Parking'], ['Gate', 'Door'],
    ['Mosquito net', 'Mosquito coil'], ['Room freshener', 'Agarbatti'], ['Calendar', 'Diary'], ['Clock', 'Watch'], ['Torch', 'Lantern'],
  ]),
  ...P('Clothes and style', [
    ['Saree', 'Lehenga'], ['Kurta', 'Shirt'], ['Jeans', 'Trousers'], ['T-shirt', 'Vest'], ['Jacket', 'Sweater'], ['Hoodie', 'Sweatshirt'],
    ['Shorts', 'Capris'], ['Skirt', 'Dress'], ['Salwar suit', 'Anarkali'], ['Sherwani', 'Bandhgala'], ['Dhoti', 'Lungi'], ['Pyjama', 'Track pants'],
    ['Cap', 'Hat'], ['Scarf', 'Muffler'], ['Gloves', 'Socks'], ['Sneakers', 'Sports shoes'], ['Sandals', 'Chappals'], ['Boots', 'Heels'],
    ['Tie', 'Bow tie'], ['Belt', 'Suspenders'], ['Earrings', 'Nose ring'], ['Necklace', 'Mangalsutra'], ['Ring', 'Bangle'], ['Anklet', 'Toe ring'],
    ['Lipstick', 'Lip balm'], ['Kajal', 'Eyeliner'], ['Perfume', 'Deodorant'], ['Nail polish', 'Mehndi'], ['Bindi', 'Sindoor'], ['Hair clip', 'Rubber band'],
    ['Raincoat', 'Windcheater'], ['Blazer', 'Suit'], ['Uniform', 'Formal wear'], ['Swimsuit', 'Shorts'],
  ]),
  ...P('School and college', [
    ['Exam', 'Quiz'], ['Homework', 'Assignment'], ['Principal', 'Head teacher'], ['Classroom', 'Lab'], ['Notebook', 'Diary'],
    ['Eraser', 'Sharpener'], ['Scale', 'Protractor'], ['Compass', 'Divider'], ['Blackboard', 'Whiteboard'], ['Chalk', 'Marker'],
    ['Report card', 'Certificate'], ['School bus', 'Van'], ['Sports day', 'Annual day'], ['Assembly', 'Morning prayer'], ['Tuition', 'Coaching'],
    ['Maths', 'Physics'], ['Chemistry', 'Biology'], ['History', 'Geography'], ['Hindi', 'Sanskrit'], ['English', 'French'],
    ['Lecture', 'Seminar'], ['Semester', 'Term'], ['Hostel', 'Dorm'], ['Canteen', 'Mess'], ['Fest', 'Farewell'], ['Topper', 'Class monitor'],
    ['Library card', 'ID card'], ['Ragging', 'Prank'], ['Placement', 'Internship'], ['Viva', 'Presentation'], ['Bench', 'Desk'],
  ]),
  ...P('Work and money', [
    ['Salary', 'Bonus'], ['Boss', 'Manager'], ['Meeting', 'Call'], ['Email', 'Letter'], ['Resume', 'Cover letter'], ['Office', 'Factory'],
    ['Startup', 'Company'], ['Holiday', 'Weekend'], ['Promotion', 'Appraisal'], ['Interview', 'Test'], ['Credit card', 'Debit card'],
    ['Cash', 'Cheque'], ['Coin', 'Note'], ['Loan', 'EMI'], ['Shares', 'Mutual funds'], ['Gold', 'Silver'], ['Tax', 'Fine'], ['Rent', 'Bill'],
    ['Piggy bank', 'Wallet'], ['Locker', 'Safe'], ['Shop', 'Showroom'], ['Discount', 'Cashback'], ['Sale', 'Offer'], ['Receipt', 'Invoice'],
  ]),
  ...P('Getting around', [
    ['Car', 'Jeep'], ['Bike', 'Scooty'], ['Bicycle', 'Tricycle'], ['Bus', 'Tempo'], ['Auto rickshaw', 'E-rickshaw'], ['Taxi', 'Cab'],
    ['Train', 'Metro'], ['Local train', 'Express train'], ['Aeroplane', 'Helicopter'], ['Ship', 'Ferry'], ['Boat', 'Canoe'], ['Truck', 'Tractor'],
    ['Ambulance', 'Fire engine'], ['Petrol pump', 'Charging station'], ['Traffic light', 'Zebra crossing'], ['Flyover', 'Bridge'],
    ['Highway', 'Expressway'], ['Toll plaza', 'Check post'], ['Helmet', 'Seat belt'], ['Ticket', 'Boarding pass'], ['Platform', 'Bus stand'],
    ['Sleeper class', 'AC coach'], ['Window seat', 'Aisle seat'], ['Driver', 'Pilot'], ['Map', 'GPS'], ['Rocket', 'Satellite'],
  ]),
  ...P('Places in India', [
    ['Jaipur', 'Udaipur'], ['Agra', 'Mathura'], ['Varanasi', 'Haridwar'], ['Rishikesh', 'Haridwar'], ['Ooty', 'Kodaikanal'],
    ['Darjeeling', 'Gangtok'], ['Leh', 'Spiti'], ['Srinagar', 'Gulmarg'], ['Andaman', 'Lakshadweep'], ['Pondicherry', 'Goa'],
    ['Chennai', 'Bengaluru'], ['Hyderabad', 'Pune'], ['Kolkata', 'Dhaka'], ['Ahmedabad', 'Surat'], ['Chandigarh', 'Amritsar'],
    ['Lucknow', 'Kanpur'], ['Mysuru', 'Coorg'], ['Munnar', 'Wayanad'], ['Jaisalmer', 'Jodhpur'], ['Nainital', 'Mussoorie'],
    ['Taj Mahal', 'Red Fort'], ['Qutub Minar', 'Charminar'], ['India Gate', 'Gateway of India'], ['Golden Temple', 'Akshardham'],
    ['Marine Drive', 'Juhu Beach'], ['Connaught Place', 'Chandni Chowk'], ['Rann of Kutch', 'Thar Desert'], ['Kaziranga', 'Jim Corbett'],
  ]),
  ...P('Around the world', [
    ['Paris', 'London'], ['New York', 'Los Angeles'], ['Dubai', 'Singapore'], ['Tokyo', 'Seoul'], ['Bangkok', 'Bali'],
    ['Maldives', 'Mauritius'], ['Switzerland', 'Austria'], ['Australia', 'New Zealand'], ['Canada', 'USA'], ['China', 'Japan'],
    ['Egypt', 'Saudi Arabia'], ['Brazil', 'Argentina'], ['Italy', 'Spain'], ['Germany', 'France'], ['Russia', 'Ukraine'],
    ['Nepal', 'Bhutan'], ['Sri Lanka', 'Maldives'], ['Eiffel Tower', 'Leaning Tower of Pisa'], ['Pyramids', 'Great Wall of China'],
    ['Statue of Liberty', 'Christ the Redeemer'], ['Big Ben', 'London Eye'], ['Disneyland', 'Universal Studios'], ['Niagara Falls', 'Victoria Falls'],
  ]),
  ...P('Animals', [
    ['Cheetah', 'Leopard'], ['Elephant', 'Rhino'], ['Hippo', 'Rhino'], ['Zebra', 'Horse'], ['Deer', 'Antelope'], ['Bear', 'Panda'],
    ['Fox', 'Jackal'], ['Rat', 'Mouse'], ['Hamster', 'Guinea pig'], ['Pigeon', 'Dove'], ['Crow', 'Raven'], ['Sparrow', 'Robin'],
    ['Owl', 'Bat'], ['Peacock', 'Turkey'], ['Hen', 'Duck'], ['Penguin', 'Puffin'], ['Ostrich', 'Emu'], ['Flamingo', 'Crane'],
    ['Turtle', 'Tortoise'], ['Alligator', 'Crocodile'], ['Octopus', 'Squid'], ['Crab', 'Lobster'], ['Prawn', 'Fish'], ['Whale', 'Shark'],
    ['Jellyfish', 'Starfish'], ['Goldfish', 'Guppy'], ['Ant', 'Termite'], ['Spider', 'Scorpion'], ['Cockroach', 'Beetle'], ['Grasshopper', 'Cricket'],
    ['Goat', 'Sheep'], ['Pig', 'Boar'], ['Ox', 'Bull'], ['Camel', 'Llama'], ['Kangaroo', 'Wallaby'], ['Koala', 'Sloth'], ['Snail', 'Slug'],
    ['Cobra', 'Python'], ['Parrot', 'Myna'], ['Kingfisher', 'Woodpecker'], ['Vulture', 'Eagle'], ['Dinosaur', 'Dragon'], ['Unicorn', 'Pegasus'],
  ]),
  ...P('Sports and games', [
    ['Test match', 'T20'], ['Six', 'Four'], ['Bowler', 'Batter'], ['Wicketkeeper', 'Slip fielder'], ['Umpire', 'Referee'],
    ['Goalkeeper', 'Defender'], ['Penalty', 'Free kick'], ['Golf', 'Mini golf'], ['Snooker', 'Pool'], ['Bowling', 'Billiards'],
    ['Skating', 'Skateboarding'], ['Surfing', 'Rafting'], ['Skiing', 'Snowboarding'], ['Archery', 'Shooting'], ['Javelin', 'Discus'],
    ['High jump', 'Long jump'], ['Marathon', 'Sprint'], ['Yoga', 'Pilates'], ['Gym', 'Zumba'], ['Karate', 'Judo'], ['Fencing', 'Sword fighting'],
    ['Formula 1', 'MotoGP'], ['Olympics', 'Commonwealth Games'], ['World Cup', 'IPL'], ['Medal', 'Trophy'], ['Coach', 'Captain'],
    ['Monopoly', 'Business'], ['Scrabble', 'Crossword'], ['Sudoku', 'Rubik\'s cube'], ['Uno', 'Rummy'], ['Antakshari', 'Dumb charades'],
    ['Hide and seek', 'Chor police'], ['Pokemon', 'Digimon'], ['Minecraft', 'Roblox'], ['GTA', 'Need for Speed'], ['Candy Crush', 'Subway Surfers'],
    ['FIFA', 'eFootball'], ['Temple Run', 'Subway Surfers'], ['Pac-Man', 'Mario'], ['Tic-tac-toe', 'Connect Four'], ['Jenga', 'Dominoes'],
  ]),
  ...P('Jobs', [
    ['Plumber', 'Electrician'], ['Carpenter', 'Mason'], ['Painter', 'Sculptor'], ['Photographer', 'Videographer'], ['Journalist', 'News anchor'],
    ['Writer', 'Poet'], ['Dancer', 'Choreographer'], ['Director', 'Producer'], ['Scientist', 'Professor'], ['Astronaut', 'Pilot'],
    ['Soldier', 'Sailor'], ['Firefighter', 'Paramedic'], ['Cashier', 'Accountant'], ['Banker', 'Clerk'], ['Software engineer', 'Data scientist'],
    ['Designer', 'Artist'], ['Fashion designer', 'Tailor'], ['Vet', 'Doctor'], ['Pharmacist', 'Chemist'], ['Lifeguard', 'Swimming coach'],
    ['Delivery boy', 'Courier'], ['Postman', 'Courier'], ['Watchman', 'Bouncer'], ['Cook', 'Baker'], ['Priest', 'Monk'], ['Magician', 'Clown'],
    ['Comedian', 'Mimic'], ['DJ', 'RJ'], ['Cricketer', 'Footballer'], ['Model', 'Actor'], ['Politician', 'Minister'], ['Detective', 'Spy'],
  ]),
  ...P('Celebrations and life events', [
    ['Haldi', 'Mehndi'], ['Sangeet', 'Reception'], ['Baraat', 'Vidaai'], ['Mundan', 'Naamkaran'], ['Housewarming', 'Griha pravesh'],
    ['Anniversary', 'Birthday'], ['Baby shower', 'Godh bharai'], ['Graduation', 'Convocation'], ['Retirement party', 'Farewell'],
    ['Eid', 'Diwali'], ['Christmas', 'New Year'], ['Onam', 'Pongal'], ['Ganesh Chaturthi', 'Durga Puja'], ['Janmashtami', 'Ram Navami'],
    ['Karva Chauth', 'Teej'], ['Baisakhi', 'Lohri'], ['Republic Day', 'Independence Day'], ['Children\'s Day', 'Teachers\' Day'],
    ['Valentine\'s Day', 'Friendship Day'], ['Mother\'s Day', 'Father\'s Day'], ['Halloween', 'Holi'], ['Fireworks', 'Laser show'],
    ['Cake cutting', 'Candle blowing'], ['Surprise party', 'Theme party'], ['Pool party', 'DJ night'], ['Movie night', 'Game night'],
  ]),
  ...P('Movies and TV', [
    ['Dilwale Dulhania Le Jayenge', 'Kuch Kuch Hota Hai'], ['Lagaan', 'Chak De! India'], ['Dangal', 'Sultan'], ['PK', '3 Idiots'],
    ['Golmaal', 'Dhamaal'], ['Andaz Apna Apna', 'Hera Pheri'], ['Don', 'Dhoom'], ['Zindagi Na Milegi Dobara', 'Dil Chahta Hai'],
    ['RRR', 'Bahubali'], ['Pushpa', 'KGF'], ['Kabir Singh', 'Animal'], ['Stree', 'Bhool Bhulaiyaa'],
    ['Titanic', 'Avatar'], ['Frozen', 'Tangled'], ['The Lion King', 'Jungle Book'], ['Toy Story', 'Finding Nemo'], ['Shrek', 'Minions'],
    ['Star Wars', 'Star Trek'], ['Jurassic Park', 'King Kong'], ['Fast and Furious', 'Mission Impossible'], ['James Bond', 'Jason Bourne'],
    ['Thor', 'Hulk'], ['Captain America', 'Iron Man'], ['Wonder Woman', 'Black Widow'], ['Joker', 'Thanos'], ['Hulk', 'Shaktimaan'],
    ['Friends', 'How I Met Your Mother'], ['Money Heist', 'Squid Game'], ['Stranger Things', 'Wednesday'], ['Sacred Games', 'Mirzapur'],
    ['Panchayat', 'Gullak'], ['Kota Factory', 'TVF Pitchers'], ['Taarak Mehta Ka Ooltah Chashmah', 'Bhabiji Ghar Par Hain'], ['Kaun Banega Crorepati', 'Bigg Boss'],
    ['MasterChef', 'Shark Tank'], ['Roadies', 'Splitsvilla'], ['Ramayan', 'Mahabharat'], ['Tom and Jerry', 'Oggy and the Cockroaches'],
    ['Pokemon', 'Beyblade'], ['Ben 10', 'Power Rangers'], ['Scooby-Doo', 'Courage the Cowardly Dog'], ['SpongeBob', 'Phineas and Ferb'],
  ]),
  ...P('Music and dance', [
    ['Guitar', 'Ukulele'], ['Piano', 'Keyboard'], ['Violin', 'Cello'], ['Flute', 'Shehnai'], ['Drums', 'Dhol'], ['Tabla', 'Mridangam'],
    ['Sitar', 'Veena'], ['Harmonium', 'Accordion'], ['Trumpet', 'Saxophone'], ['Bhangra', 'Garba'], ['Kathak', 'Bharatanatyam'],
    ['Hip hop', 'Breakdance'], ['Salsa', 'Tango'], ['Ballet', 'Contemporary'], ['Qawwali', 'Ghazal'], ['Rap', 'Pop'], ['Rock', 'Metal'],
    ['Concert', 'Music festival'], ['Karaoke', 'Antakshari'], ['Headphones', 'Speaker'], ['Microphone', 'Loudspeaker'], ['Playlist', 'Album'],
  ]),
  ...P('Tech and internet', [
    ['Laptop', 'Desktop'], ['Mouse', 'Touchpad'], ['Keyboard', 'Typewriter'], ['Printer', 'Scanner'], ['Pen drive', 'Hard disk'],
    ['Wi-Fi', 'Mobile data'], ['Router', 'Modem'], ['Charger', 'Power bank'], ['Bluetooth', 'Wi-Fi'], ['Selfie', 'Group photo'],
    ['Reel', 'Story'], ['Post', 'Tweet'], ['Like', 'Share'], ['Follower', 'Subscriber'], ['Meme', 'GIF'], ['Emoji', 'Sticker'],
    ['Password', 'PIN'], ['Email', 'SMS'], ['Video call', 'Voice call'], ['Zoom', 'Google Meet'], ['Facebook', 'Instagram'],
    ['Twitter', 'Threads'], ['LinkedIn', 'Naukri'], ['ChatGPT', 'Google'], ['Alexa', 'Siri'], ['Android', 'iOS'], ['Windows', 'Mac'],
    ['PlayStation', 'Xbox'], ['Smart TV', 'Fire Stick'], ['Drone', 'Remote-control car'], ['Robot', 'Cyborg'], ['Hacker', 'Virus'],
    ['Paytm', 'BHIM'], ['Myntra', 'Ajio'], ['Blinkit', 'Zepto'], ['BookMyShow', 'Paytm Movies'], ['Rapido', 'Uber Moto'], ['Hotstar', 'Prime Video'],
  ]),
  ...P('Brands', [
    ['Bournvita', 'Horlicks'], ['Amul', 'Mother Dairy'], ['Haldiram\'s', 'Bikano'], ['Lay\'s', 'Kurkure'], ['Bingo', 'Uncle Chipps'],
    ['Good Day', 'Hide & Seek'], ['Oreo', 'Bourbon'], ['Monaco', 'Krackjack'], ['Maggi', 'Yippee'], ['Kissan', 'Maggi ketchup'],
    ['Colgate', 'Pepsodent'], ['Dettol', 'Savlon'], ['Lifebuoy', 'Lux'], ['Surf Excel', 'Tide'], ['Vicks', 'Zandu Balm'], ['Fevicol', 'Fevikwik'],
    ['Nike', 'Adidas'], ['Puma', 'Reebok'], ['Bata', 'Relaxo'], ['Titan', 'Fastrack'], ['Tata', 'Mahindra'], ['Royal Enfield', 'Bajaj'],
    ['Hero', 'Honda'], ['Jio', 'Airtel'], ['Starbucks', 'Café Coffee Day'], ['Subway', 'Burger King'], ['IKEA', 'Pepperfry'], ['Lenskart', 'Titan Eye'],
  ]),
  ...P('Feelings and actions', [
    ['Happy', 'Excited'], ['Sad', 'Lonely'], ['Angry', 'Annoyed'], ['Scared', 'Nervous'], ['Bored', 'Tired'], ['Shy', 'Quiet'],
    ['Jealous', 'Greedy'], ['Proud', 'Confident'], ['Laughing', 'Smiling'], ['Crying', 'Sulking'], ['Shouting', 'Singing'], ['Whispering', 'Mumbling'],
    ['Running', 'Jogging'], ['Walking', 'Hiking'], ['Sleeping', 'Napping'], ['Dancing', 'Exercising'], ['Cooking', 'Baking'], ['Reading', 'Studying'],
    ['Painting', 'Drawing'], ['Swimming', 'Floating'], ['Climbing', 'Jumping'], ['Hugging', 'Shaking hands'], ['Texting', 'Calling'], ['Shopping', 'Window shopping'],
  ]),
  ...P('Body and health', [
    ['Doctor', 'Dentist'], ['Medicine', 'Injection'], ['Fever', 'Cold'], ['Headache', 'Stomach ache'], ['Cough', 'Sneeze'], ['Bandage', 'Plaster'],
    ['X-ray', 'MRI'], ['Wheelchair', 'Crutches'], ['Glasses', 'Contact lenses'], ['Braces', 'Retainer'], ['Hair', 'Beard'], ['Eyebrow', 'Eyelash'],
    ['Elbow', 'Knee'], ['Wrist', 'Ankle'], ['Finger', 'Toe'], ['Heart', 'Lungs'], ['Brain', 'Mind'], ['Blood', 'Sweat'], ['Tooth', 'Bone'],
  ]),
  ...P('Fantasy and stories', [
    ['Ghost', 'Zombie'], ['Vampire', 'Werewolf'], ['Witch', 'Wizard'], ['Fairy', 'Angel'], ['Mermaid', 'Sea monster'], ['Genie', 'Magician'],
    ['Dragon', 'Phoenix'], ['Giant', 'Ogre'], ['Alien', 'Robot'], ['Pirate', 'Sailor'], ['King', 'Emperor'], ['Queen', 'Princess'],
    ['Knight', 'Soldier'], ['Castle', 'Palace'], ['Treasure', 'Gold coins'], ['Magic wand', 'Magic carpet'], ['Time machine', 'Spaceship'],
    ['Superhero', 'Villain'], ['Cinderella', 'Snow White'], ['Aladdin', 'Sinbad'], ['Tenali Raman', 'Birbal'], ['Panchatantra', 'Jataka tales'],
    ['Vikram', 'Betaal'], ['Sherlock Holmes', 'Byomkesh Bakshi'], ['Feluda', 'Sherlock Holmes'], ['Hogwarts', 'Narnia'], ['Gandalf', 'Dumbledore'],
  ]),
]
