// Movie Guess: each film has an emoji clue, a one-line story (which never names the film) and, for many, a famous
// line. The title is typed; `a` lists other ways people write it. l: b = Indian films, h = English-language films.
export interface Movie { t: string; a?: string[]; e: string; p: string; d?: string; y: number; l: 'b' | 'h' }

const B = (t: string, y: number, e: string, p: string, d?: string, a?: string[]): Movie => ({ t, y, e, p, ...(d ? { d } : {}), ...(a ? { a } : {}), l: 'b' })
const H = (t: string, y: number, e: string, p: string, d?: string, a?: string[]): Movie => ({ t, y, e, p, ...(d ? { d } : {}), ...(a ? { a } : {}), l: 'h' })

export const MOVIES: Movie[] = [
  // ---------- Hindi ----------
  B('Sholay', 1975, '🐎🔫👮‍♂️🤝🤝', 'A retired policeman hires two small-time crooks to catch a dacoit who destroyed his family.', 'Kitne aadmi the?'),
  B('Dilwale Dulhania Le Jayenge', 1995, '🚂🌻💑🇨🇭', 'Two young Indians fall in love on a Europe trip, and he wins over her strict father in Punjab.', 'Ja Simran ja, jee le apni zindagi.', ['DDLJ']),
  B('3 Idiots', 2009, '🎓🤓🤓🤓🚽', 'Two friends search for their old college buddy who taught them to chase excellence, not marks.', 'All is well.', ['Three Idiots']),
  B('Lagaan', 2001, '🏏☀️🌾👑', 'Villagers in 1893 bet their land tax on a cricket match against British officers.', undefined),
  B('Dangal', 2016, '🤼‍♀️👨‍👧‍👧🥇', 'A former wrestler trains his two daughters to become world-class wrestlers.', 'Mhari chhoriyan chhoron se kam hai ke?'),
  B('Kabhi Khushi Kabhie Gham', 2001, '👨‍👩‍👦‍👦🚁💔🇬🇧', 'An adopted son marries against his rich father\'s wishes and leaves home; his younger brother brings him back.', 'Keh diya na, bas keh diya.', ['K3G']),
  B('Kuch Kuch Hota Hai', 1998, '🏀👧💌👨‍👧', 'A little girl reads her late mother\'s letters and sets out to reunite her father with his college best friend.', undefined, ['KKHH']),
  B('Deewaar', 1975, '👬🚔💰⛪', 'Two brothers grow up poor; one becomes a smuggler and the other a police officer.', 'Mere paas maa hai.'),
  B('Zindagi Na Milegi Dobara', 2011, '🚗🇪🇸🤿🪂🍅', 'Three school friends take a road trip in Spain, and each faces his biggest fear.', undefined, ['ZNMD']),
  B('Dil Chahta Hai', 2001, '👬👦🏖️🍷', 'Three close friends grow apart after college as each falls in love in his own way.', undefined, ['DCH']),
  B('Andaz Apna Apna', 1994, '🤡🤡💰👰🐔', 'Two lazy dreamers compete to marry a rich heiress and end up fighting a gang of crooks.', 'Teja main hoon, mark idhar hai.'),
  B('Hera Pheri', 2000, '☎️💸👴🔫', 'A landlord and two tenants get a wrong-number call from a kidnapper and try to make money from it.', 'Utha le re baba, utha le!'),
  B('Munna Bhai MBBS', 2003, '🩺🤗😎🏥', 'A kind-hearted gangster joins a medical college to fulfil his father\'s dream.', 'Jaadu ki jhappi.'),
  B('Lage Raho Munna Bhai', 2006, '👓🕊️📻😎', 'A gangster starts seeing Mahatma Gandhi and uses his ideas to solve problems.', 'Get well soon.'),
  B('Taare Zameen Par', 2007, '⭐🎨👦🔤', 'A new art teacher realises an eight-year-old boy struggling at boarding school has dyslexia.'),
  B('Chak De India', 2007, '🏑👩‍👩‍👧‍👧🇮🇳', 'A disgraced former hockey player coaches the Indian women\'s hockey team to glory.', 'Sattar minute.', ['Chak De! India']),
  B('Swades', 2004, '🛰️🏡💡🇮🇳', 'A NASA scientist returns to his village to bring his nanny back to America, and stays to bring electricity.'),
  B('Rang De Basanti', 2006, '🎥🔥🇮🇳🎓', 'Friends acting in a film about freedom fighters start living like them after a friend dies.', undefined, ['RDB']),
  B('PK', 2014, '👽📻🙏❓', 'An alien loses the remote to his spaceship on Earth and questions everything people believe.'),
  B('Ghajini', 2008, '🧠📸✍️💪', 'A rich man who forgets everything every 15 minutes uses photos and tattoos to find the man who killed his love.'),
  B('Om Shanti Om', 2007, '🎬🔥💃👻', 'A junior artist killed in the 1970s is reborn as a star and avenges the actress he loved.', 'Ek chutki sindoor ki keemat…'),
  B('Main Hoon Na', 2004, '🎖️🏫👨‍🎓💃', 'An army officer goes undercover as a college student to protect a general\'s daughter.'),
  B('Kal Ho Naa Ho', 2003, '❤️🗽💔🎵', 'A cheerful man with a weak heart brings joy to a New York family and helps his friend marry the girl he loves.'),
  B('Jab We Met', 2007, '🚂👧🗣️🏔️', 'A sad businessman meets a talkative girl on a train, and their journey changes both their lives.', 'Main apni favourite hoon.'),
  B('Queen', 2014, '👰💔✈️🇫🇷', 'A shy girl dumped before her wedding goes on her honeymoon to Europe alone.'),
  B('Piku', 2015, '👴🚽🚗🧔', 'A daughter, her grumpy father who is obsessed with his digestion and a cab owner drive from Delhi to Kolkata.'),
  B('Bajrangi Bhaijaan', 2015, '🐒🙏👧🇵🇰', 'A devoted man takes a mute little girl who got lost in India back home across the border.'),
  B('Sultan', 2016, '🤼‍♂️💔🏆', 'A wrestler past his prime returns to the ring to win back his wife\'s respect.'),
  B('Bahubali: The Beginning', 2015, '🏞️🗡️👑🏰', 'A young man climbs a giant waterfall and learns he is heir to a great kingdom.', 'Katappa ne Bahubali ko kyun maara?', ['Baahubali', 'Bahubali', 'Baahubali The Beginning']),
  B('Gangs of Wasseypur', 2012, '🔫🏚️⛏️👨‍👦‍👦', 'A generations-long gang war over coal in a small town in Jharkhand.', 'Keh ke lunga.', ['GOW']),
  B('Golmaal', 2006, '🤪🤪🤪🤪👴👵', 'Four friends get away with lies while living in the house of a blind old couple.', undefined, ['Golmaal Fun Unlimited']),
  B('Welcome', 2007, '🏠👰🔫🤵', 'A gentle man wants to marry a girl whose brothers are dons, and his uncle wants a decent family.', 'Control Uday, control.'),
  B('Phir Hera Pheri', 2006, '💸🦆📞🔁', 'Three friends lose their money in a scheme to double it and get into bigger trouble.'),
  B('Bhool Bhulaiyaa', 2007, '🏰👻💃🧠', 'A psychiatrist solves the mystery of a haunted palace and a ghost said to live in it.'),
  B('Jodhaa Akbar', 2008, '👑💍🏰🗡️', 'A Mughal emperor marries a Rajput princess for politics, and has to win her love.'),
  B('Devdas', 2002, '🍷💔🪔💃', 'A rich young man, kept from marrying his childhood love, turns to drink and a courtesan\'s kindness.'),
  B('Hum Aapke Hain Koun', 1994, '🐕💒🎶👨‍👩‍👧‍👦', 'Two brothers marry two sisters; a family dog helps true love win after a tragedy.', undefined, ['HAHK']),
  B('Maine Pyar Kiya', 1989, '🕊️💌🏋️', 'A rich boy falls for a poor girl and must earn money to prove himself to her father.', 'Dosti ka ek usool hai.'),
  B('Baazigar', 1993, '🎭🔪🏙️', 'A man takes revenge on the businessman who ruined his family, by pretending to love his daughters.'),
  B('Darr', 1993, '📞😱💑🔪', 'A man becomes obsessed with a woman who is about to marry a naval officer.', 'I love you K-k-k-Kiran.'),
  B('Mohabbatein', 2000, '🎻🍂🏫💞', 'A violin teacher brings love to a strict boys\' school run by the father of the girl he loved.'),
  B('Rab Ne Bana Di Jodi', 2008, '🕺🥸👰🙏', 'A shy clerk disguises himself as a cool dancer to win his own wife\'s heart.'),
  B('Chennai Express', 2013, '🚂👩🔪🌴', 'A Mumbai man going to immerse his grandfather\'s ashes boards the wrong train and meets a don\'s daughter.', 'Don\'t underestimate the power of a common man.'),
  B('My Name Is Khan', 2010, '🇺🇸🧠🗣️🕌', 'A man with Asperger\'s travels across America to tell the President he is not a terrorist.', undefined, ['MNIK']),
  B('Kabir Singh', 2019, '🩺🍾💔😤', 'A brilliant surgeon with anger issues spirals out after his girlfriend is married to someone else.'),
  B('Barfi!', 2012, '🤐👂🚲❤️', 'A deaf and mute man in Darjeeling falls in love with two women.', undefined, ['Barfi']),
  B('Rockstar', 2011, '🎸💔🎤🇨🇿', 'A college boy wants heartbreak to become a great singer, and gets more than he wished for.'),
  B('Yeh Jawaani Hai Deewani', 2013, '🏔️🎒💍🌍', 'A traveller who never wants to settle down meets his college crush again at a friend\'s wedding.', undefined, ['YJHD']),
  B('Wake Up Sid', 2009, '😴📸🏙️👩', 'A lazy rich boy grows up after he moves in with a writer from Kolkata in Mumbai.'),
  B('Tanu Weds Manu', 2011, '👰🤵🍾🎉', 'A quiet doctor falls for a wild, rebellious girl from Kanpur.'),
  B('Badhaai Ho', 2018, '🤰👵👨‍👩‍👦‍👦😳', 'A grown man is embarrassed when his middle-aged mother gets pregnant.'),
  B('Andhadhun', 2018, '🎹🕶️🔪🐰', 'A piano player who pretends to be blind sees a murder.'),
  B('Drishyam', 2015, '📺🎞️🕵️‍♂️👨‍👩‍👧‍👧', 'A cable operator who loves films protects his family after his daughter kills a boy by accident.', 'Do aur teen October ko kya hua tha?'),
  B('Kahaani', 2012, '🤰🚕🔎🌆', 'A pregnant woman searches Kolkata for her missing husband during Durga Puja.'),
  B('Pink', 2016, '👩‍⚖️👧👧👧🚫', 'A retired lawyer defends three young women in a case that asks what "no" means.', 'No means no.'),
  B('Stree', 2018, '👻👗🚪🌙', 'A small town is haunted by a woman\'s ghost who takes men away at night.', 'O stree, kal aana.'),
  B('Uri: The Surgical Strike', 2019, '🎖️🪖🚁🇮🇳', 'Indian commandos cross the border to hit back after an attack on an army base.', 'How\'s the josh?', ['Uri']),
  B('Gully Boy', 2019, '🎤🏘️🎧✊', 'A young man from a Mumbai slum becomes a rapper.', 'Apna time aayega.'),
  B('Pathaan', 2023, '🕶️💥🚁🇮🇳', 'An exiled spy comes back to stop a former agent from attacking India.'),
  B('Jawan', 2023, '🦹‍♂️🚇👩‍✈️⚖️', 'A man with a team of women hijacks a metro to fight corruption.'),
  B('Animal', 2023, '🪓🩸👨‍👦🔫', 'A son\'s violent love for his distant father turns into a war with a rival gang.'),
  B('12th Fail', 2023, '📚🚌👮‍♂️💪', 'A poor boy who failed school works his way up to become an IPS officer.', 'Restart.'),
  B('RRR', 2022, '🔥💧🐅🤝', 'Two revolutionaries in the 1920s become friends and fight the British.'),
  B('Pushpa: The Rise', 2021, '🪵🧔🔥🔫', 'A labourer rises in the red sandalwood smuggling business.', 'Pushpa, Pushpa Raj, main jhukega nahi.', ['Pushpa']),
  B('KGF: Chapter 1', 2018, '⛏️👑💰🔥', 'A boy from the streets of Mumbai becomes a feared man in a gold mine.', undefined, ['KGF']),
  B('Kantara', 2022, '🌳🎭🐗🔥', 'A villager in coastal Karnataka clashes with a forest officer, and with a god\'s spirit.'),
  B('Dhoom', 2004, '🏍️💰🚔🕶️', 'A cop and a mechanic chase a gang of bike-riding robbers in Mumbai.'),
  B('Dhoom 2', 2006, '💎🎭🏍️🌴', 'A master thief who steals priceless treasures in disguise is chased by two cops.'),
  B('Don', 2006, '🕶️🔫🌍🃏', 'A look-alike of a feared gangster is planted in his gang.', 'Don ko pakadna mushkil hi nahi, namumkin hai.'),
  B('Krrish', 2006, '🦸‍♂️🎭🌳🦅', 'A boy with special powers from his father saves people in Singapore wearing a mask.'),
  B('Koi... Mil Gaya', 2003, '👽🌞📡👦', 'A slow-learning boy makes friends with an alien who gives him special powers.', 'Jadoo!', ['Koi Mil Gaya']),
  B('Kaho Naa Pyaar Hai', 2000, '🏝️🎹👯‍♂️🔫', 'A singer is killed after seeing a murder, and his look-alike helps his love find the truth.'),
  B('Jo Jeeta Wohi Sikandar', 1992, '🚲🏆🏫💪', 'A careless boy from a poor school trains for a cycle race after his brother is hurt.'),
  B('Rangeela', 1995, '💃🎬🎟️🕺', 'A girl who dreams of acting has to choose between a film star and her street-smart friend.'),
  B('Border', 1997, '🪖🏜️🇮🇳🛩️', 'A small group of Indian soldiers hold a post in the Thar desert during the 1971 war.'),
  B('Gadar: Ek Prem Katha', 2001, '🚂❤️🇮🇳🇵🇰', 'A Sikh truck driver loves a Muslim girl during Partition and crosses the border to bring her back.', 'Hindustan zindabad.', ['Gadar']),
  B('Mughal-e-Azam', 1960, '👑💃🧱⚔️', 'A prince falls in love with a court dancer, and goes to war with his own father.'),
  B('Mother India', 1957, '👩‍🌾🐂🌧️👦', 'A poor village woman raises her sons alone and stands up to a moneylender.'),
  B('Anand', 1971, '🎈🩺😄💔', 'A cheerful man dying of cancer brings joy to everyone, including his gloomy doctor.', 'Babumoshai, zindagi badi honi chahiye, lambi nahi.'),
  B('Golmaal (1979)', 1979, '🥸👨‍💼🏏🎩', 'A young man pretends to have a twin to keep his job with a strict, moustache-loving boss.', undefined, ['Golmaal']),
  B('Chupke Chupke', 1975, '🚗🗣️📚😂', 'A professor pretends to be a driver to fool his wife\'s brother-in-law, who is proud of his pure Hindi.'),
  B('Zanjeer', 1973, '🐎⛓️👮‍♂️😠', 'An angry police officer hunts the man who killed his parents when he was a child.', 'Jab tak baithne ko na kaha jaaye, khade raho.'),
  B('Agneepath', 2012, '🔥🏝️👦⚖️', 'A man takes revenge on the drug lord who hanged his father in front of the village.'),
  B('Singham', 2011, '🦁👮‍♂️👊🏘️', 'An honest village police officer takes on a powerful politician in Goa.', 'Aata majhi satakli.'),
  B('Dabangg', 2010, '🕶️👮‍♂️🥋💃', 'A tough, corrupt-but-kind cop in a small town fights his stepbrother and a politician.', 'Thappad se darr nahi lagta, sahab, pyaar se lagta hai.'),
  B('Ek Tha Tiger', 2012, '🐯🕵️‍♂️🇵🇰🇮🇳', 'An Indian spy falls in love with a Pakistani spy.'),
  B('War', 2019, '🚁🔫🧑‍🤝‍🧑💥', 'An agent is sent to hunt his own mentor, who has gone rogue.'),
  B('Kaabil', 2017, '🦯🔊💔', 'A blind man takes revenge on the men who hurt his blind wife.'),
  B('Fanaa', 2006, '❄️💣💔🦯', 'A blind girl falls in love with a charming guide who is secretly a terrorist.'),
  B('Rock On!!', 2008, '🎸🥁🎤🧔', 'Four friends who broke up their band meet again ten years later.', undefined, ['Rock On']),
  B('Tamasha', 2015, '🎭🏝️👔📖', 'A man who loves stories loses himself in a dull office job, and a girl he met in Corsica wants him back.'),
  B('Highway', 2014, '🚚👧🏔️🗺️', 'A rich girl is kidnapped before her wedding and finds freedom on the road with her kidnapper.'),
  B('Udta Punjab', 2016, '💉🎤🌾🚨', 'A pop star, a cop, a doctor and a farm worker are caught up in a state\'s drug problem.'),
  B('Raazi', 2018, '🕵️‍♀️💍🇵🇰📻', 'A young Indian woman marries into a Pakistani army family to spy during the 1971 war.'),
  B('Padmaavat', 2018, '👑🔥🏰🪞', 'A Sultan wants to see a Rajput queen whose beauty he has heard of, and lays siege to her fort.', undefined, ['Padmavati']),
  B('Bajirao Mastani', 2015, '⚔️🐎💞👑', 'A Maratha warrior marries a warrior princess, and his family refuses to accept her.'),
  B('Ram-Leela', 2013, '🎨🔫💞🏮', 'Two lovers from feuding families in Gujarat, like Romeo and Juliet.', undefined, ['Goliyon Ki Raasleela Ram-Leela', 'Ramleela']),
  B('Kick', 2014, '😈💰🎭🚔', 'A man who lives for thrills becomes a masked thief to raise money for sick children.'),
  B('Housefull', 2010, '🏠🤪🍀👰', 'An unlucky man keeps ruining his own relationships until his friends hatch a plan.'),
  B('Bhaag Milkha Bhaag', 2013, '🏃‍♂️🇮🇳🏟️💔', 'The life of an Indian sprinter who survived Partition and became a champion.'),
  B('MS Dhoni: The Untold Story', 2016, '🏏🚂🚉🏆', 'A ticket collector from Ranchi becomes captain of the Indian cricket team.', undefined, ['MS Dhoni', 'Dhoni']),
  B('83', 2021, '🏏🏆🇮🇳🏴', 'India\'s cricket team, written off by everyone, wins the World Cup.', undefined, ['Eighty Three']),
  B('Mary Kom', 2014, '🥊👩‍👦‍👦🏆', 'A woman from Manipur becomes a five-time world boxing champion.'),
  B('Sanju', 2018, '🎬💊🔫👨‍👦', 'The ups and downs of a film star with drugs, jail and a loving father.'),
  B('Dil Se', 1998, '📻🚂💣❤️', 'A radio journalist falls for a mysterious woman who is part of a group of militants.'),
  B('Roja', 1992, '🌹🏔️🔫👩', 'A village girl fights to free her husband, kidnapped by militants in Kashmir.'),
  B('Bombay', 1995, '🏙️💞🕌🛕', 'A Hindu man and a Muslim woman marry and are caught in the 1993 riots in a big city.'),
  B('Hum Dil De Chuke Sanam', 1999, '🎶🇮🇹💍💔', 'A newly married man takes his wife to Italy to find the singer she still loves.', undefined, ['HDDCS']),
  B('Hum Saath-Saath Hain', 1999, '👨‍👩‍👦‍👦🏡🤝', 'A big happy family is split when a stepmother is turned against her stepson.'),
  B('Pyaar Ka Punchnama', 2011, '👬👬💔🗣️', 'Three flatmates fall in love and suffer at the hands of their girlfriends.'),
  B('Sonu Ke Titu Ki Sweety', 2018, '👬👰🤨', 'A man is sure his best friend\'s perfect fiancée is a trap.'),
  B('Delhi Belly', 2011, '🤢💎🔫🚽', 'Three flatmates get mixed up with a gangster because of a stool sample and a parcel.'),
  B('Fukrey', 2013, '🎰🦁💸😂', 'Four losers borrow money from a dangerous woman to fund a lottery dream.'),
  B('Stree 2', 2024, '👻🪓🧔🌙', 'A small town that was saved by a ghost now faces a headless monster taking its women.'),
  B('Shershaah', 2021, '🪖🏔️❤️🇮🇳', 'The life of an army captain who gave his life in the Kargil War.', 'Yeh dil maange more.'),
  B('Kesari', 2019, '🪖🏜️🧡🪖', '21 Sikh soldiers defend an outpost against 10,000 attackers in 1897.'),
  B('Toilet: Ek Prem Katha', 2017, '🚽💍👰🏘️', 'A bride leaves her husband\'s house because it has no bathroom.', undefined, ['Toilet']),
  B('Pad Man', 2018, '🩸🧵👨‍🔧❤️', 'A man in a small town makes cheap sanitary pads for women.', undefined, ['Padman']),
  B('Airlift', 2016, '✈️🇰🇼🧳🇮🇳', 'A businessman helps evacuate 170,000 Indians from Kuwait during the 1990 invasion.'),
  B('Special 26', 2013, '🕵️‍♂️💼💰🚔', 'A gang poses as tax officers to raid rich people in the 1980s.', undefined, ['Special Chabbis']),
  B('A Wednesday', 2008, '📞💣🧔🏙️', 'An ordinary man calls the police chief to say he has hidden bombs across Mumbai.', undefined, ['A Wednesday!']),
  B('Baby', 2015, '🕵️‍♂️🇮🇳💣', 'A secret team of Indian agents hunts terrorists across the world.'),
  B('Neerja', 2016, '✈️👩‍✈️🦸‍♀️', 'A young flight attendant saves passengers from hijackers.'),
  B('Article 15', 2019, '👮‍♂️⚖️🏘️', 'A police officer investigates the disappearance of three girls and faces caste prejudice.'),
  B('Tumbbad', 2018, '🏚️🪙🌧️👹', 'A man keeps going back to a cursed god\'s womb for gold.'),
  B('Masaan', 2015, '🔥🚤⛩️💔', 'Two stories by the ghats of Varanasi, of love, loss and shame.'),
  B('Newton', 2017, '🗳️🌳👨‍💼', 'An honest clerk tries to hold a fair election in a jungle village.'),
  B('Lunchbox', 2013, '🍱💌🚆', 'A mix-up in Mumbai\'s dabba delivery starts letters between a lonely man and a housewife.', undefined, ['The Lunchbox']),
  B('English Vinglish', 2012, '🗽🍩🗣️👩', 'A housewife mocked by her family for her poor language skills takes classes in New York.'),
  B('Vicky Donor', 2012, '🧪👶💸😳', 'A young man in Delhi earns money at a fertility clinic and hides it from his wife\'s family.'),
  B('Dum Laga Ke Haisha', 2015, '🏃‍♂️👰🎵📼', 'A man who runs a cassette shop is forced to marry an overweight woman and must carry her in a race.'),
  B('Chhichhore', 2019, '🏀🏫👬💔', 'A father tells his son about his college days to show him how to handle failure.'),
  B('Super 30', 2019, '📐🧑‍🏫🚲', 'A maths teacher in Patna coaches 30 poor students for IIT.'),
  B('Kai Po Che!', 2013, '🏏🪁👬', 'Three friends in Ahmedabad start a cricket academy and are torn apart by the riots.', undefined, ['Kai Po Che']),
  B('2 States', 2014, '🍛🥘💍👪', 'A Punjabi boy and a Tamil girl try to convince their families to accept their marriage.', undefined, ['Two States']),
  B('Ae Dil Hai Mushkil', 2016, '🎤💔🇬🇧', 'A man in London falls for his best friend, who only sees him as a friend.', undefined, ['ADHM']),
  B('Dear Zindagi', 2016, '🎥🗣️🏖️', 'A young cinematographer finds help from an unusual therapist in Goa.'),
  B('Shubh Mangal Saavdhan', 2017, '💍😳🩺', 'A man finds out he has a problem in bed just before his wedding.'),
  B('Bareilly Ki Barfi', 2017, '📚💌🚲', 'A small-town girl looks for the writer of a book that seems to be about her.'),
  B('Hindi Medium', 2017, '🏫👨‍👩‍👧💸', 'A Delhi couple pretend to be poor to get their daughter into a top English school.'),
  B('Munjya', 2024, '🌳👻🧒', 'A young man is chased by the ghost of a boy who wants to get married.'),
  B('Laapataa Ladies', 2024, '👰👰🚆🔍', 'Two new brides wearing veils get swapped on a train.', undefined, ['Lapata Ladies', 'Missing Ladies']),
  B('Rocky Aur Rani Kii Prem Kahaani', 2023, '💃🕺👵👴', 'A Punjabi boy and a Bengali girl swap families for three months before their marriage.', undefined, ['Rocky Aur Rani']),
  B('Brahmastra', 2022, '🔥🧘‍♂️🗡️✨', 'A DJ finds out he is linked to the fire weapon and a secret group guarding divine weapons.', undefined, ['Brahmastra Part One']),
  B('Gangubai Kathiawadi', 2022, '👩🏻‍🦳🏙️🌹', 'A girl sold into Mumbai\'s red-light area becomes its powerful leader.', undefined, ['Gangubai']),
  B('Sooryavanshi', 2021, '👮‍♂️💣🏙️', 'An anti-terror squad chief hunts sleeper cells planning to bomb Mumbai.'),
  B('Simmba', 2018, '👮‍♂️😎💰', 'A corrupt cop changes after a girl he knows is attacked.'),
  B('Golmaal Again', 2017, '👻🤪🏚️', 'The four friends return to their orphanage and find a ghost there.'),
  B('Total Dhamaal', 2019, '💰🐯🚗', 'A group of greedy people race to find hidden cash in a zoo.'),
  B('Hungama', 2003, '🤷‍♂️😂🏠', 'A string of misunderstandings makes everyone think everyone else is in love with them.'),
  B('Bhool Bhulaiyaa 2', 2022, '🏚️👻🕺', 'A man pretends to be a psychic in a haunted house of a family in Rajasthan.'),
  B('OMG: Oh My God!', 2012, '⚡🏚️⚖️🙏', 'A shopkeeper sues God after an earthquake destroys his shop.', undefined, ['OMG', 'Oh My God']),
  B('Jolly LLB', 2013, '⚖️👨‍💼🚗', 'A small-time lawyer takes on a rich man\'s hit-and-run case.'),
  B('Mission Mangal', 2019, '🚀🔴👩‍🔬', 'Scientists at ISRO send a probe to Mars on a tight budget.'),
  B('Ta Ra Rum Pum', 2007, '🏎️👨‍👩‍👧‍👦💸', 'A race car driver loses everything after a crash and hides it from his kids.'),
  B('Wanted', 2009, '🔫😎🏙️', 'A hired gunman falls in love and turns out to be an undercover cop.', 'Ek baar jo maine commitment kar di…'),
  B('Ready', 2011, '🤵👰🎭😂', 'A man helps a girl hide from her greedy uncles, who want her property.'),
  B('Race', 2008, '🏇🚗💰🔫', 'Two brothers who own horses double-cross each other for money and love.'),
  B('Housefull 4', 2019, '🔁🏰👑', 'Three brothers about to marry three sisters discover they were all together in a past life.'),
  B('Raees', 2017, '🍾👓🏙️', 'A bootlegger builds a liquor empire in dry Gujarat.', 'Baniye ka dimaag aur Miyan bhai ki daring.'),
  B('Sairat', 2016, '💑🏃‍♂️🏘️', 'A lower-caste boy and an upper-caste girl run away together in Maharashtra.'),

  // ---------- English ----------
  H('Titanic', 1997, '🚢🧊💑🎨', 'A poor artist and a rich young woman fall in love on a ship that is about to sink.', 'I\'m the king of the world!'),
  H('Avatar', 2009, '🔵🌳🪐🐉', 'A soldier in a wheelchair lives a new life in a tall blue body on another planet.'),
  H('Jurassic Park', 1993, '🦖🏝️🧬🚙', 'An island full of dinosaurs made from old DNA goes wrong.', 'Life finds a way.'),
  H('The Lion King', 1994, '🦁👑🐗🐒', 'A cub runs away after his father\'s death and returns to rule.', 'Hakuna matata.'),
  H('Frozen', 2013, '❄️👸👸⛄', 'A princess with ice powers hides from the world, and her sister goes to find her.', 'Let it go.'),
  H('Toy Story', 1995, '🤠🚀🧸👦', 'A cowboy doll is jealous when a new space ranger toy becomes the boy\'s favourite.', 'To infinity and beyond!'),
  H('Finding Nemo', 2003, '🐠🐟🌊🔍', 'A nervous clownfish crosses the ocean to find his son.', 'Just keep swimming.'),
  H('The Dark Knight', 2008, '🦇🃏🌃', 'A masked hero faces a criminal who wants to watch the city burn.', 'Why so serious?'),
  H('Avengers: Endgame', 2019, '💎🧤⏳🦸', 'The surviving heroes travel back in time to undo the loss of half of all life.', 'I love you 3000.', ['Endgame']),
  H('Inception', 2010, '🌀😴🏙️🎡', 'A thief who steals secrets from dreams is asked to plant an idea instead.'),
  H('Interstellar', 2014, '🌽🚀🕳️⏳', 'A farmer and former pilot flies through a wormhole to find a new home for humans.'),
  H('Harry Potter and the Philosopher\'s Stone', 2001, '⚡👓🧙‍♂️🏰', 'An orphan boy learns on his eleventh birthday that he is a wizard.', 'You\'re a wizard, Harry.', ['Harry Potter', 'Harry Potter and the Sorcerer\'s Stone']),
  H('The Godfather', 1972, '🌹🐴🍝🔫', 'The ageing head of a crime family hands control to his unwilling son.', 'I\'m gonna make him an offer he can\'t refuse.'),
  H('Forrest Gump', 1994, '🏃‍♂️🍫🪶🦐', 'A kind man with a low IQ is present at many key moments of American history.', 'Life is like a box of chocolates.'),
  H('The Matrix', 1999, '💊🕶️💻🐇', 'A hacker learns the world is a computer simulation.', 'There is no spoon.'),
  H('Home Alone', 1990, '🏠👦🎄🚪', 'A boy left behind at Christmas defends his house from two burglars.'),
  H('Spider-Man', 2002, '🕷️🕸️🏙️', 'A shy student gets superpowers from a bite.', 'With great power comes great responsibility.'),
  H('Iron Man', 2008, '🤖🔥💰', 'A weapons maker builds a metal suit to escape his captors.', 'I am Iron Man.'),
  H('Black Panther', 2018, '🐆👑🌍', 'A new king returns to his hidden, advanced African nation.', 'Wakanda forever!'),
  H('Shrek', 2001, '👹🫏👸🏰', 'A grumpy green ogre goes on a quest to rescue a princess.'),
  H('Up', 2009, '🎈🏠👴👦', 'An old man ties thousands of balloons to his house to fly to South America.'),
  H('Coco', 2017, '🎸💀🌼🇲🇽', 'A boy who dreams of music ends up in the Land of the Dead.'),
  H('Inside Out', 2015, '😊😢😡😱🤢', 'Joy, Sadness and the other feelings in a girl\'s head try to help her through a move.'),
  H('The Jungle Book', 2016, '🐻🐯👦🌴', 'A boy raised by wolves is hunted by a tiger.', 'The bare necessities.'),
  H('Pirates of the Caribbean', 2003, '🏴‍☠️💀⚓🍾', 'A strange sea captain helps a blacksmith save a governor\'s daughter from a cursed crew.', undefined, ['Pirates of the Caribbean: The Curse of the Black Pearl']),
  H('Star Wars', 1977, '⭐⚔️🤖🚀', 'A farm boy joins rebels to rescue a princess from a dark lord.', 'May the Force be with you.'),
  H('Joker', 2019, '🤡🎭🪜', 'A failed comedian slowly turns into a criminal.'),
  H('Oppenheimer', 2023, '💣🎩⚛️', 'The story of the scientist behind the first atomic bomb.'),
  H('Barbie', 2023, '👱‍♀️💗🏖️👠', 'A doll leaves her perfect pink world to visit the real one.'),
  H('Fast & Furious', 2001, '🏎️💨👨‍👨‍👦', 'An undercover cop joins a gang of street racers.', 'Family.', ['The Fast and the Furious', 'Fast and Furious']),
  H('Mission: Impossible', 1996, '🕵️‍♂️💣🚁', 'A spy, framed for betrayal, must clear his name.', 'This message will self-destruct.'),
  H('The Avengers', 2012, '🦸‍♂️🦸‍♀️🌌🏙️', 'Earth\'s heroes team up to stop an alien army in New York.', undefined, ['Avengers']),
  H('Gravity', 2013, '🧑‍🚀🌍🛰️', 'Two astronauts are stranded in space after debris destroys their shuttle.'),
  H('The Martian', 2015, '🧑‍🚀🥔🔴', 'An astronaut left on Mars grows potatoes to survive.'),
  H('Cast Away', 2000, '🏝️🏐📦', 'A man stranded on an island for years makes friends with a volleyball.', 'Wilson!'),
  H('The Terminator', 1984, '🤖🕶️🔫⏳', 'A killer robot is sent back in time to kill a woman.', 'I\'ll be back.', ['Terminator']),
  H('Jaws', 1975, '🦈🏖️🚤', 'A huge shark attacks a beach town.', 'You\'re going to need a bigger boat.'),
  H('Kung Fu Panda', 2008, '🐼🥋🍜', 'A clumsy bear who loves noodles becomes a martial arts master.'),
  H('Minions', 2015, '💛👓🍌', 'Little yellow creatures look for the most evil master to serve.'),
  H('Despicable Me', 2010, '🦹‍♂️👧👧👧🌙', 'A villain plans to steal the moon, and adopts three girls.'),
  H('Ratatouille', 2007, '🐀👨‍🍳🇫🇷', 'A rat who loves cooking helps a young man in a Paris restaurant.'),
  H('Aladdin', 1992, '🧞‍♂️🪔🐒🪄', 'A street boy finds a magic lamp with a genie inside.'),
  H('Beauty and the Beast', 1991, '🌹🐻🏰📚', 'A young woman is held in a castle by a cursed prince who must learn to love.'),
  H('The Social Network', 2010, '💻👍🎓', 'The story of how a college student built a giant website.'),
  H('Slumdog Millionaire', 2008, '💰❓🏙️🇮🇳', 'A boy from Mumbai\'s slums is one question from winning a quiz show.'),
  H('Life of Pi', 2012, '🐅🛶🌊🇮🇳', 'An Indian boy is stranded at sea on a lifeboat with a Bengal tiger.'),
  H('Top Gun', 1986, '✈️🕶️🏐', 'A daring young pilot trains at an elite flying school.', 'I feel the need, the need for speed.'),
  H('Mean Girls', 2004, '👧💅📓', 'A new girl at school joins the popular clique and plans to bring it down.', 'On Wednesdays we wear pink.'),
  H('The Hangover', 2009, '🐯🦷🥂🎰', 'Friends wake up in Las Vegas with no memory of the night and a missing groom.'),
  H('Sherlock Holmes', 2009, '🔍🎩🇬🇧', 'A detective and his partner stop a man who seems to use black magic.'),
  H('Doctor Strange', 2016, '🪄🌀🩺', 'A surgeon who hurts his hands learns magic.'),
  H('Thor', 2011, '🔨⚡👑', 'A god is sent to Earth without his powers to learn humility.'),
  H('Guardians of the Galaxy', 2014, '🦝🌳🚀🎧', 'A team of misfits in space protects a powerful stone.', 'I am Groot.'),
  H('Captain America: The First Avenger', 2011, '🛡️🇺🇸💉', 'A weak young man becomes a super soldier in World War II.', undefined, ['Captain America']),
  H('Wonder Woman', 2017, '🦸‍♀️⚔️🏝️', 'An Amazon princess leaves her island to fight in World War I.'),
  H('Zootopia', 2016, '🐰🦊🚔', 'A rabbit cop and a con-artist fox solve a mystery.'),
  H('Moana', 2016, '🌊🛶🐓🏝️', 'A chief\'s daughter sails across the ocean with a demigod to save her island.'),
  H('Encanto', 2021, '🏠🦋✨🇨🇴', 'The only member of a magical family without a gift tries to save their magic.'),
  H('Madagascar', 2005, '🦁🦓🦒🦛', 'Zoo animals from New York end up on an island.', 'I like to move it, move it.'),
  H('Ice Age', 2002, '🦣🐿️🌰🧊', 'A mammoth, a sloth and a tiger return a human baby to his family.'),
  H('Spider-Man: No Way Home', 2021, '🕷️🌀🕷️🕷️', 'Three heroes from different worlds team up after a spell goes wrong.', undefined, ['No Way Home']),
  H('Dune', 2021, '🏜️🪱🗡️', 'A young duke\'s son goes to a desert planet with giant worms.'),
  H('Gladiator', 2000, '⚔️🏟️🐎', 'A betrayed Roman general becomes a slave fighter in the arena to take revenge on the emperor.', 'Are you not entertained?'),
  H('The Shawshank Redemption', 1994, '⛓️🔨🪨', 'A banker sent to prison for murder makes friends and plans his escape over 20 years.'),
  H('Avengers: Infinity War', 2018, '🧤💎💎💎🫰', 'A purple titan collects six stones to wipe out half of all life.', undefined, ['Infinity War']),
  H('Mamma Mia!', 2008, '🎶🏝️👰👨👨👨', 'A bride invites three men to her wedding, not knowing which one is her father.', undefined, ['Mamma Mia']),
  H('La La Land', 2016, '🎹💃🌆', 'A jazz pianist and an actress fall in love in Los Angeles.'),
  H('Bohemian Rhapsody', 2018, '🎤👑🦷🎸', 'The life of the lead singer of the rock band Queen.'),
  H('The Pursuit of Happyness', 2006, '👨‍👦🏃‍♂️💼', 'A homeless father and his young son struggle while he trains to be a stockbroker.', undefined, ['Pursuit of Happiness']),
  H('Catch Me If You Can', 2002, '✈️💳🕵️', 'A young con man poses as a pilot, a doctor and a lawyer, chased by the FBI.'),
  H('The Wolf of Wall Street', 2013, '💸🐺📞', 'A stockbroker gets rich through fraud and wild parties.'),
  H('Ghostbusters', 1984, '👻🚫🔫', 'Three scientists start a business catching ghosts in New York.', 'Who you gonna call?'),
  H('Back to the Future', 1985, '🚗⚡⏰', 'A teenager goes 30 years into the past in a car and must make his parents fall in love.'),
  H('E.T. the Extra-Terrestrial', 1982, '👽🚲🌕☎️', 'A boy hides a lost alien and helps him go home.', 'E.T. phone home.', ['ET']),
  H('Transformers', 2007, '🚗➡️🤖', 'A teenager gets caught in a war between giant robots that turn into cars.'),
  H('Paddington', 2014, '🐻🧥🍊🇬🇧', 'A polite bear from Peru moves to London and is taken in by a family.'),
  H('Free Guy', 2021, '👕🎮🏦', 'A bank teller finds out he is a background character in a video game.'),
  H('Top Gun: Maverick', 2022, '✈️🕶️🏔️', 'An old fighter pilot trains young pilots for a dangerous mission.'),
  H('Everything Everywhere All at Once', 2022, '🥯🌀👩‍🦳🌌', 'A laundromat owner jumps between many universes during a tax audit.'),
]
