// Prompts for Mind Meld and Most Likely To. Written for friend groups in India: plain English, everyday things.

/** Mind Meld: prompts where the group can land on the same answer. */
export const MIND_MELD: string[] = [
  'Name a fruit', 'Name a colour', 'Name an animal you would see in a zoo', 'Name a vegetable', 'Name a sweet (mithai)',
  'Name a street food', 'Name a Bollywood actor', 'Name a Bollywood actress', 'Name a cricketer', 'Name a car brand',
  'Name a phone brand', 'Name a social media app', 'Name a superhero', 'Name a cartoon character', 'Name a festival',
  'Name a city in India', 'Name a country in Europe', 'Name a sport played with a ball', 'Name something you find in a kitchen',
  'Name something in a school bag', 'Name a breakfast food', 'Name a drink that is not water', 'Name a flower',
  'Name a bird', 'Name a pet', 'Name something that is yellow', 'Name something that is cold', 'Name something that is hot',
  'Name something with wheels', 'Name something you do on a Sunday', 'Name a subject in school', 'Name a board game',
  'Name a musical instrument', 'Name a body part above the neck', 'Name a month', 'Name a day of the week',
  'Name something people are scared of', 'Name a place to go on holiday in India', 'Name a hill station',
  'Name a chocolate brand', 'Name a biscuit brand', 'Name a fast food chain', 'Name a pizza topping', 'Name a type of chai',
  'Name something you carry when it rains', 'Name a game you played as a kid', 'Name a famous monument',
  'Name a planet', 'Name a shape', 'Name a number between 1 and 10', 'Name a letter of the alphabet', 'Name an emoji',
  'Name something in a wallet', 'Name something you find on a beach', 'Name a dance form', 'Name a river in India',
  'Name a famous scientist', 'Name a Hindi movie', 'Name a Hollywood movie', 'Name a web series', 'Name a singer',
  'Name a YouTuber', 'Name a dish made with paneer', 'Name a type of bread or roti', 'Name a dal', 'Name a spice',
  'Name a dry fruit', 'Name an ice cream flavour', 'Name a cold drink', 'Name a juice', 'Name something sold at a railway station',
  'Name something you see at a wedding', 'Name a wedding dish', 'Name a word people say when they are angry (keep it clean)',
  'Name something you do when you are bored', 'Name an excuse for being late', 'Name something that makes noise',
  'Name a famous Indian brand', 'Name something you buy online', 'Name a delivery app', 'Name a payment app',
  'Name an animal that lives in water', 'Name an insect', 'Name a farm animal', 'Name something that flies',
  'Name a job', 'Name something a doctor uses', 'Name something on a cricket field', 'Name an IPL team',
  'Name a football club', 'Name an Olympic sport', 'Name a famous Indian leader', 'Name a language spoken in India',
  'Name a state in India', 'Name a famous temple', 'Name a famous fort', 'Name a mall food', 'Name something you charge',
  'Name a computer key', 'Name a programming language', 'Name a video game', 'Name a famous villain', 'Name a comedy movie',
  'Name a sad song', 'Name a party song', 'Name something you do at a sleepover', 'Name a gift for a friend',
  'Name something you see in the sky', 'Name a type of weather', 'Name something soft', 'Name something sharp',
  'Name something sticky', 'Name something round', 'Name something you can fold', 'Name something people collect',
  'Name a hobby', 'Name a famous couple', 'Name a famous duo', 'Name a reason to call your mom', 'Name a thing your parents say',
  'Name a college subject people hate', 'Name something in a hostel room', 'Name a late-night snack', 'Name a type of noodles',
  'Name a Maggi flavour', 'Name a chips brand', 'Name a sauce or chutney', 'Name a cooking oil or fat', 'Name a samosa partner',
]

/** Most Likely To: "Who is most likely to …" */
export const MOST_LIKELY: string[] = [
  'survive a zombie apocalypse', 'become a billionaire', 'become famous on Instagram', 'get lost in their own city',
  'forget a friend\'s birthday', 'cry during a movie', 'eat the last slice without asking', 'fall asleep at a party',
  'be late to their own wedding', 'win a reality show', 'become a politician', 'go viral for something silly',
  'reply "ok" to a long message', 'have 500 unread messages', 'spend all their salary in the first week',
  'order food at 3 a.m.', 'start a business', 'move abroad and never come back', 'adopt ten pets', 'cancel plans at the last minute',
  'talk their way out of a traffic challan', 'win an argument with a teacher', 'laugh at the wrong moment',
  'still be watching cartoons at 40', 'become a stand-up comedian', 'eat something off the floor', 'know all the gossip first',
  'keep a secret forever', 'tell a secret by mistake', 'take 100 selfies on a trip', 'get scammed online', 'become a YouTuber',
  'cook the best biryani', 'burn water while cooking', 'win the lottery and lose the ticket', 'be the first to get married',
  'never get married', 'have the messiest room', 'remember every song lyric', 'sing loudly in the shower', 'dance at every baraat',
  'skip the gym but post gym photos', 'become a teacher', 'bargain the hardest at a market', 'pay for everyone and forget to ask back',
  'borrow money and forget to return it', 'fall for a fake news forward', 'send good morning messages', 'become an astronaut',
  'climb Mount Everest', 'run a marathon', 'win Kaun Banega Crorepati', 'be on the news', 'get stuck in a lift', 'lose their phone',
  'lose their keys every week', 'talk to animals', 'have a secret talent', 'write a book', 'become a chef', 'open a chai stall',
  'become a cricket commentator', 'cry over a cricket match', 'stay up all night before an exam', 'top the exam without studying',
  'copy homework at the last minute', 'make friends with strangers on a train', 'sleep through an alarm', 'wake up at 5 a.m. happily',
  'have the longest phone call', 'start a fight in the family group', 'leave a WhatsApp group dramatically', 'stalk an ex online',
  'text an ex at midnight', 'get married in Las Vegas', 'have a fancy wedding', 'adopt a strict diet and quit in a day',
  'become a monk', 'go on a solo trip', 'plan a trip that never happens', 'reach the airport just in time', 'miss the train',
  'travel without a ticket', 'buy something useless at 2 a.m.', 'become a famous singer', 'become a dancer', 'become a doctor',
  'become an actor', 'become a scientist', 'build their own app', 'hack the Wi-Fi password', 'forget their own password',
  'be the best parent', 'be the strictest parent', 'spoil their kids', 'live till 100', 'eat spicy food without water',
  'faint after eating spicy food', 'scream on a roller coaster', 'believe in ghosts', 'see a ghost', 'run from a cockroach',
  'cry when they get a haircut', 'dye their hair blue', 'get a tattoo', 'say something wrong in a job interview',
  'become the boss', 'quit their job to travel', 'work on a holiday', 'win a dance battle', 'win a rap battle',
  'get the most likes on a post', 'start a podcast', 'reply to emails in seconds', 'never check their email',
  'fix anything with tape', 'break something just by looking at it', 'have a fake Instagram account', 'invent something useful',
  'become a meme', 'lie about their age', 'eat a whole pizza alone', 'win a staring contest', 'forget why they walked into a room',
]
