// Prompts for Mind Meld and Most Likely To. Written for friend groups in India: plain English, everyday things.

/** Mind Meld: prompts where the group can land on the same answer. */
export const MIND_MELD: string[] = [
  'Name a fruit', 'Name a colour', 'Name an animal you would see in a zoo', 'Name a vegetable', 'Name a sweet (mithai)',
  'Name a street food', 'Name a Bollywood actor', 'Name a Bollywood actress', 'Name a cricketer', 'Name a car brand',
  'Name a phone brand', 'Name a social media app', 'Name a superhero', 'Name a cartoon character', 'Name a festival',
  'Name a city in India', 'Name a country in Europe', 'Name a sport played with a ball', 'Name something you find in a kitchen',
  'Name something in a school bag', 'Name a breakfast food', 'Name a drink that is not water', 'Name a flower',
  'Name a bird', 'Name a pet', 'Name something that is yellow', 'Name something that is cold', 'Name something that is hot',
  'Name something with wheels', 'Name something you do on a Sunday', 'Name a subject in school', 'Name a board game',
  'Name a musical instrument', 'Name a body part above the neck', 'Name a month', 'Name a day of the week',
  'Name something people are scared of', 'Name a place to go on holiday in India', 'Name a hill station',
  'Name a chocolate brand', 'Name a biscuit brand', 'Name a fast food chain', 'Name a pizza topping', 'Name a type of chai',
  'Name something you carry when it rains', 'Name a game you played as a kid', 'Name a famous monument',
  'Name a planet', 'Name a shape', 'Name a number between 1 and 10', 'Name a letter of the alphabet', 'Name an emoji',
  'Name something in a wallet', 'Name something you find on a beach', 'Name a dance form', 'Name a river in India',
  'Name a famous scientist', 'Name a Hindi movie', 'Name a Hollywood movie', 'Name a web series', 'Name a singer',
  'Name a YouTuber', 'Name a dish made with paneer', 'Name a type of bread or roti', 'Name a dal', 'Name a spice',
  'Name a dry fruit', 'Name an ice cream flavour', 'Name a cold drink', 'Name a juice', 'Name something sold at a railway station',
  'Name something you see at a wedding', 'Name a wedding dish', 'Name a word people say when they are angry (keep it clean)',
  'Name something you do when you are bored', 'Name an excuse for being late', 'Name something that makes noise',
  'Name a famous Indian brand', 'Name something you buy online', 'Name a delivery app', 'Name a payment app',
  'Name an animal that lives in water', 'Name an insect', 'Name a farm animal', 'Name something that flies',
  'Name a job', 'Name something a doctor uses', 'Name something on a cricket field', 'Name an IPL team',
  'Name a football club', 'Name an Olympic sport', 'Name a famous Indian leader', 'Name a language spoken in India',
  'Name a state in India', 'Name a famous temple', 'Name a famous fort', 'Name a mall food', 'Name something you charge',
  'Name a computer key', 'Name a programming language', 'Name a video game', 'Name a famous villain', 'Name a comedy movie',
  'Name a sad song', 'Name a party song', 'Name something you do at a sleepover', 'Name a gift for a friend',
  'Name something you see in the sky', 'Name a type of weather', 'Name something soft', 'Name something sharp',
  'Name something sticky', 'Name something round', 'Name something you can fold', 'Name something people collect',
  'Name a hobby', 'Name a famous couple', 'Name a famous duo', 'Name a reason to call your mom', 'Name a thing your parents say',
  'Name a college subject people hate', 'Name something in a hostel room', 'Name a late-night snack', 'Name a type of noodles',
  'Name a Maggi flavour', 'Name a chips brand', 'Name a sauce or chutney', 'Name a cooking oil or fat', 'Name a samosa partner',
  // Food and drink
  'Name a type of pakoda', 'Name something you put on toast', 'Name a type of rice dish', 'Name a South Indian dish',
  'Name a Punjabi dish', 'Name a Bengali sweet', 'Name a Gujarati snack', 'Name a dish from Maharashtra', 'Name a Chinese dish you get in India',
  'Name a sandwich filling', 'Name a pickle (achaar)', 'Name a summer fruit', 'Name a winter food', 'Name a food that is green',
  'Name a food that is red', 'Name a food that is white', 'Name something you eat with a spoon', 'Name something you eat with your hands',
  'Name a food you dip', 'Name a food that is crunchy', 'Name a food that is sour', 'Name a food that is bitter', 'Name something sweet that is not a mithai',
  'Name a cake flavour', 'Name a milkshake flavour', 'Name a type of egg dish', 'Name a chicken dish', 'Name a fish dish',
  'Name a soup', 'Name something you eat at the movies', 'Name a food sold on a cart', 'Name a food you eat in the rain',
  'Name a Diwali sweet', 'Name a Holi drink or snack', 'Name something in a lunch box', 'Name a food kids hate', 'Name a food everyone loves',
  'Name a famous food from Delhi', 'Name a famous food from Mumbai', 'Name a famous food from Kolkata', 'Name a famous food from Hyderabad',
  'Name a famous food from Lucknow', 'Name a famous food from Indore', 'Name a dish made with potato', 'Name a dish made with besan',
  'Name a dish made with rice', 'Name a dish made with milk', 'Name a dish made with maida', 'Name a dish made with curd',
  'Name a vegetable that grows under the ground', 'Name a leafy vegetable', 'Name something you add to chai', 'Name a coffee drink',
  'Name a hot drink', 'Name a packaged snack', 'Name a namkeen', 'Name a toffee or candy', 'Name a gum or mint', 'Name a jam or spread',
  'Name a breakfast cereal', 'Name something you eat on a train journey', 'Name a food at a birthday party', 'Name a sabzi',
  'Name a fried food', 'Name a baked food', 'Name a fruit with seeds inside', 'Name a fruit you peel', 'Name a citrus fruit',
  'Name a berry', 'Name a nut', 'Name a food you eat at a dhaba', 'Name a food at a mela', 'Name a raita', 'Name a paratha filling',
  'Name a dosa type', 'Name a lassi flavour', 'Name a kulfi flavour', 'Name a golgappa water flavour', 'Name a momo type',
  'Name a pizza place', 'Name a burger place', 'Name a coffee shop chain', 'Name an ice cream brand', 'Name a dairy brand',
  'Name a tea brand', 'Name a noodle brand', 'Name a ketchup or sauce brand', 'Name a juice brand', 'Name a water bottle brand',
  // Home and everyday life
  'Name something in a bathroom', 'Name something in a bedroom', 'Name something in a living room', 'Name something on a dining table',
  'Name something in a fridge', 'Name something in a first aid box', 'Name something in a pooja room', 'Name something on a balcony',
  'Name something in a dressing table drawer', 'Name something you find under a bed', 'Name something you plug in', 'Name a home appliance',
  'Name something with a remote', 'Name something with buttons', 'Name something with a screen', 'Name something with a handle',
  'Name something with a lid', 'Name something that has keys', 'Name something with a zip', 'Name something made of glass',
  'Name something made of wood', 'Name something made of plastic', 'Name something made of steel', 'Name something made of paper',
  'Name something made of cloth', 'Name something made of rubber', 'Name something made of gold', 'Name something you fill with water',
  'Name something you hang on a wall', 'Name something on a fridge door', 'Name a cleaning item', 'Name a kitchen utensil',
  'Name something you sweep', 'Name a household chore', 'Name a chore everyone avoids', 'Name something you lock',
  'Name something you open every day', 'Name something you switch off at night', 'Name something you do before sleeping',
  'Name something you do right after waking up', 'Name something people forget at home', 'Name something you lose often',
  'Name something you borrow from neighbours', 'Name something the doodhwala brings', 'Name something the kabadiwala buys',
  'Name something on a key chain', 'Name something you keep in your car', 'Name something in a handbag', 'Name something in a pencil box',
  'Name something in a toolbox', 'Name something in a sewing kit', 'Name something in a medicine box', 'Name something you pack for a trip',
  'Name something you forget to pack', 'Name something in a hotel room', 'Name something you buy at a chemist', 'Name something sold at a kirana store',
  'Name something you buy every week', 'Name something you buy once a year', 'Name something you wear on your feet', 'Name something you wear on your head',
  'Name something you wear in winter', 'Name something you wear in summer', 'Name something you wear to a wedding', 'Name a piece of jewellery',
  'Name a type of shoe', 'Name a type of bag', 'Name something with stripes', 'Name something with spots', 'Name an animal with a long tail',
  'Name something that has legs but is not alive', 'Name something that has a face', 'Name something that has teeth', 'Name something that has wings',
  // School, college and work
  'Name something you see in a classroom', 'Name something on a teacher\'s desk', 'Name a thing in a science lab', 'Name a school event',
  'Name something you do in a free period', 'Name a game played in a school ground', 'Name a reason to bunk class', 'Name an excuse for not doing homework',
  'Name a famous exam', 'Name something students carry to an exam', 'Name a type of degree', 'Name an engineering branch', 'Name a famous college',
  'Name an IIT', 'Name something in a canteen', 'Name something you do in a long lecture', 'Name a thing that happens on the last day of school',
  'Name something you write with', 'Name a geometry box item', 'Name a school uniform item', 'Name a word teachers say a lot',
  'Name a thing you do at a job interview', 'Name an office item', 'Name a thing people do in a boring meeting', 'Name a reason to take leave',
  'Name a job that needs a uniform', 'Name a job you can do from home', 'Name a job kids dream of', 'Name a job that starts early in the morning',
  'Name a job that works at night', 'Name a job with a lot of money', 'Name a job with a lot of travel', 'Name a tech company',
  'Name an app on every phone', 'Name a messaging app', 'Name a video app', 'Name a music app', 'Name a shopping app', 'Name a cab app',
  'Name a game on the phone', 'Name a website everyone uses', 'Name something you search on Google', 'Name a word you type every day',
  'Name a laptop brand', 'Name a TV brand', 'Name a shoe brand', 'Name a clothing brand', 'Name a bike brand', 'Name a watch brand',
  'Name a bank in India', 'Name a newspaper', 'Name a news channel', 'Name a TV channel',
  // Entertainment
  'Name a Shah Rukh Khan movie', 'Name a Salman Khan movie', 'Name an Aamir Khan movie', 'Name an Amitabh Bachchan movie', 'Name an Akshay Kumar movie',
  'Name a Ranbir Kapoor movie', 'Name a Deepika Padukone movie', 'Name a horror movie', 'Name a love story movie', 'Name a cricket movie',
  'Name a movie with songs everyone knows', 'Name a South Indian movie', 'Name a South Indian actor', 'Name a Disney movie', 'Name a Marvel movie',
  'Name an animated movie', 'Name a movie villain', 'Name a TV serial', 'Name a reality show',
  'Name a cartoon from your childhood', 'Name a kids\' TV channel', 'Name a cartoon dog', 'Name a cartoon cat', 'Name a Disney princess',
  'Name a Harry Potter character', 'Name a superhero\'s power', 'Name a comic book', 'Name a famous magician or wizard', 'Name a famous detective',
  'Name a song you dance to at weddings', 'Name a Holi song', 'Name a famous music composer', 'Name a playback singer', 'Name a rapper',
  'Name an international pop star', 'Name a band', 'Name a song everyone knows the words to', 'Name a lullaby', 'Name a nursery rhyme',
  'Name a famous comedian', 'Name a game show', 'Name a card game', 'Name an outdoor game',
  'Name a game played at a birthday party', 'Name a video game character', 'Name a toy', 'Name something at a fun fair',
  'Name an amusement park ride', 'Name a circus act', 'Name a thing in a museum', 'Name a famous painter',
  // Sport
  'Name a cricket shot', 'Name a way to get out in cricket', 'Name a fast bowler', 'Name a spin bowler', 'Name a cricket captain',
  'Name a cricket team (country)', 'Name a famous cricket ground', 'Name a football player', 'Name a tennis player', 'Name a badminton player',
  'Name an Indian Olympic medal winner', 'Name a sport played on water', 'Name a sport played on ice', 'Name a sport with a racket',
  'Name a sport with a net', 'Name a sport you can play alone', 'Name a team sport', 'Name a sport with a stick', 'Name a martial art',
  'Name something in a gym', 'Name an exercise', 'Name a yoga pose', 'Name a thing you need to play cricket', 'Name a position in football',
  'Name a famous race', 'Name a Formula 1 driver', 'Name a famous wrestler', 'Name a famous boxer', 'Name a chess player', 'Name a famous athlete',
  // Places and travel
  'Name a country in Asia', 'Name a country in Africa', 'Name a country in South America', 'Name a big city in the world', 'Name a country people move to',
  'Name a country with a lot of snow', 'Name a beach in India', 'Name a place in Goa', 'Name a place in Kerala', 'Name a place in Rajasthan',
  'Name a place in the Himalayas', 'Name a famous lake', 'Name a famous waterfall', 'Name a desert', 'Name a famous mountain', 'Name an ocean or sea',
  'Name a capital city', 'Name a state capital in India', 'Name a famous palace', 'Name a famous mosque', 'Name a famous church', 'Name a wonder of the world',
  'Name a famous market in India', 'Name a famous street in India', 'Name a famous railway station', 'Name an airport in India', 'Name an airline',
  'Name a famous train', 'Name a type of vehicle', 'Name something you see on a highway', 'Name a thing you see on a road trip', 'Name a hill station in the south',
  'Name a place to go on a honeymoon', 'Name a theme park', 'Name a famous bridge', 'Name a famous tower', 'Name a national park',
  'Name something you do at a beach', 'Name something you do in the mountains', 'Name something you see at an airport', 'Name something you see at a bus stand',
  // People and life
  'Name a relative', 'Name something your grandparents say', 'Name a thing aunties ask at weddings', 'Name a thing uncles talk about',
  'Name something people do at a family function', 'Name a wedding ritual', 'Name a thing you see at a baraat', 'Name a gift people give at weddings',
  'Name a thing people do on Diwali', 'Name a thing people do on Holi', 'Name a festival in winter',
  'Name a festival in the south', 'Name a Christmas thing', 'Name a New Year resolution', 'Name a birthday party item', 'Name a thing at a picnic',
  'Name something you do on a holiday', 'Name a reason to be happy', 'Name a reason to cry', 'Name something that makes you sleepy',
  'Name something that wakes you up', 'Name a thing people are proud of', 'Name a thing people are jealous of', 'Name something you do when nervous',
  'Name a feeling', 'Name a word that means happy', 'Name a word that means big', 'Name a word that means small', 'Name a word that means fast',
  'Name a compliment', 'Name a nickname', 'Name a common Indian surname', 'Name a common first name for a boy', 'Name a common first name for a girl',
  'Name a famous Indian sportsperson', 'Name a famous businessperson', 'Name a famous Indian scientist', 'Name a freedom fighter', 'Name a Prime Minister of India',
  'Name a famous king or queen', 'Name a famous writer', 'Name a god or goddess', 'Name a character from the Ramayana', 'Name a character from the Mahabharata',
  // Nature and science
  'Name a wild animal', 'Name an animal with stripes', 'Name an animal with a long neck', 'Name an animal that is black and white', 'Name a big cat',
  'Name an animal that jumps', 'Name an animal that is slow', 'Name an animal that is fast', 'Name an animal that lives in a cold place', 'Name an animal in the desert',
  'Name an animal that eats grass', 'Name an animal with horns', 'Name a baby animal name', 'Name an animal sound', 'Name a sea creature',
  'Name a reptile', 'Name a bird that cannot fly', 'Name a colourful bird', 'Name a tree', 'Name a plant you keep at home', 'Name a type of grain',
  'Name a season', 'Name something that melts', 'Name something that floats', 'Name something that glows', 'Name something you see at night',
  'Name a natural disaster', 'Name a thing in space', 'Name a body organ', 'Name a body part below the waist', 'Name a bone', 'Name something with a smell',
  'Name a bad smell', 'Name a good smell', 'Name a sound you hear in the morning', 'Name something that is loud', 'Name something that is quiet',
  'Name something that is heavy', 'Name something that is light', 'Name something that is tall', 'Name something that is tiny', 'Name something that is fast',
  'Name something that is slow', 'Name something that is old', 'Name something that bounces', 'Name something that spins', 'Name something that rings',
  'Name something pink', 'Name something blue', 'Name something orange', 'Name something black', 'Name something white', 'Name something purple',
  'Name something green that is not a plant', 'Name something brown', 'Name something gold in colour', 'Name a metal', 'Name a gemstone',
  'Name a chemical element', 'Name a unit of measurement', 'Name a shape with corners', 'Name a number people think is lucky', 'Name a number people think is unlucky',
  'Name an even number under 20', 'Name a number between 1 and 100', 'Name a famous number', 'Name a sign of the zodiac', 'Name a Roman numeral',
  'Name a vowel', 'Name a word that starts with Z', 'Name a five-letter word', 'Name a word that rhymes with cat', 'Name a word that rhymes with day',
  'Name a four-letter animal', 'Name a three-letter word', 'Name a word with double letters', 'Name a long word', 'Name a Hindi word everyone in India knows',
  // Just for fun
  'Name something that is always late', 'Name something you can never find when you need it', 'Name something that is overrated', 'Name something that is underrated',
  'Name a thing that is better in the rain', 'Name a smell that reminds you of home', 'Name something you would take to a desert island', 'Name a superpower you would want',
  'Name a thing you would buy with a crore', 'Name a thing that gets lost in the wash', 'Name something people do in a traffic jam', 'Name a thing people do in a lift',
  'Name a reason people honk', 'Name something you shout at a cricket match', 'Name a thing you see in a WhatsApp family group', 'Name a type of forward message',
  'Name something you say on a phone call', 'Name a word you say when you are surprised', 'Name a thing people say when someone sneezes', 'Name a sound a car makes',
  'Name something you can play', 'Name something you can break', 'Name something you can catch', 'Name something you can throw', 'Name something you can climb',
  'Name something you can ride', 'Name something you can blow', 'Name something you can pop', 'Name something you can cut', 'Name something you can count',
  'Name something you can share', 'Name something you should never share', 'Name something that comes in pairs', 'Name something that comes in a packet', 'Name something that comes in a box',
  'Name something you do with your hands', 'Name something you do with your feet', 'Name something you do every Monday', 'Name something you do on your birthday',
  'Name a thing kids collect', 'Name a thing people queue for', 'Name a thing people fight over', 'Name a thing that goes up and down', 'Name a thing you wait for',
]

/** Most Likely To: "Who is most likely to …" */
export const MOST_LIKELY: string[] = [
  'survive a zombie apocalypse', 'become a billionaire', 'become famous on Instagram', 'get lost in their own city',
  'forget a friend\'s birthday', 'cry during a movie', 'eat the last slice without asking', 'fall asleep at a party',
  'be late to their own wedding', 'win a reality show', 'become a politician', 'go viral for something silly',
  'reply "ok" to a long message', 'have 500 unread messages', 'spend all their salary in the first week',
  'order food at 3 a.m.', 'start a business', 'move abroad and never come back', 'adopt ten pets', 'cancel plans at the last minute',
  'talk their way out of a traffic challan', 'win an argument with a teacher', 'laugh at the wrong moment',
  'still be watching cartoons at 40', 'become a stand-up comedian', 'eat something off the floor', 'know all the gossip first',
  'keep a secret forever', 'tell a secret by mistake', 'take 100 selfies on a trip', 'get scammed online', 'become a YouTuber',
  'cook the best biryani', 'burn water while cooking', 'win the lottery and lose the ticket', 'be the first to get married',
  'never get married', 'have the messiest room', 'remember every song lyric', 'sing loudly in the shower', 'dance at every baraat',
  'skip the gym but post gym photos', 'become a teacher', 'bargain the hardest at a market', 'pay for everyone and forget to ask back',
  'borrow money and forget to return it', 'fall for a fake news forward', 'send good morning messages', 'become an astronaut',
  'climb Mount Everest', 'run a marathon', 'win Kaun Banega Crorepati', 'be on the news', 'get stuck in a lift', 'lose their phone',
  'lose their keys every week', 'talk to animals', 'have a secret talent', 'write a book', 'become a chef', 'open a chai stall',
  'become a cricket commentator', 'cry over a cricket match', 'stay up all night before an exam', 'top the exam without studying',
  'copy homework at the last minute', 'make friends with strangers on a train', 'sleep through an alarm', 'wake up at 5 a.m. happily',
  'have the longest phone call', 'start a fight in the family group', 'leave a WhatsApp group dramatically', 'stalk an ex online',
  'text an ex at midnight', 'get married in Las Vegas', 'have a fancy wedding', 'adopt a strict diet and quit in a day',
  'become a monk', 'go on a solo trip', 'plan a trip that never happens', 'reach the airport just in time', 'miss the train',
  'travel without a ticket', 'buy something useless at 2 a.m.', 'become a famous singer', 'become a dancer', 'become a doctor',
  'become an actor', 'become a scientist', 'build their own app', 'hack the Wi-Fi password', 'forget their own password',
  'be the best parent', 'be the strictest parent', 'spoil their kids', 'live till 100', 'eat spicy food without water',
  'faint after eating spicy food', 'scream on a roller coaster', 'believe in ghosts', 'see a ghost', 'run from a cockroach',
  'cry when they get a haircut', 'dye their hair blue', 'get a tattoo', 'say something wrong in a job interview',
  'become the boss', 'quit their job to travel', 'work on a holiday', 'win a dance battle', 'win a rap battle',
  'get the most likes on a post', 'start a podcast', 'reply to emails in seconds', 'never check their email',
  'fix anything with tape', 'break something just by looking at it', 'have a fake Instagram account', 'invent something useful',
  'become a meme', 'lie about their age', 'eat a whole pizza alone', 'win a staring contest', 'forget why they walked into a room',
  // Phones and the internet
  'reply to a message after three days', 'send a voice note instead of typing', 'type "hahaha" with a straight face', 'have 5,000 photos in their gallery',
  'run out of phone storage', 'keep their phone at 1% battery', 'use the same password for everything', 'leave someone on "seen"',
  'post a story every hour', 'change their profile picture every week', 'comment on a celebrity\'s post', 'get into an argument in the comments',
  'watch reels until 4 a.m.', 'start a meme page', 'go viral on LinkedIn', 'click every link in a forward', 'forward a message without reading it',
  'mute the family WhatsApp group', 'add everyone to a new group for no reason', 'send a message to the wrong group', 'use ten emojis in one message',
  'reply with only a thumbs up', 'be online at 3 a.m.', 'binge a full web series in one night', 'cry at an ad', 'spend an hour choosing what to watch',
  'buy something just because of an ad', 'fill their cart and never check out', 'return everything they order online',
  'track their delivery every five minutes', 'leave a one-star review out of anger', 'write a long review for a pen', 'win an online quiz',
  'steal the neighbour\'s Wi-Fi', 'break their phone screen in the first week', 'take a photo of their food before eating',
  'take a mirror selfie in the gym', 'post a gym check-in but not go in', 'do an Instagram live that nobody watches', 'start a vlog and stop after one video',
  'become a gaming streamer', 'rage quit a game', 'play the same mobile game for years', 'top the leaderboard in a game',
  // Money and shopping
  'save every rupee', 'spend money they do not have', 'bargain even in a mall', 'order the most expensive thing on the menu',
  'split the bill to the last rupee', 'always say "I will pay next time"', 'find a sale on everything', 'buy ten of the same T-shirt',
  'buy shoes they never wear', 'lose money in the share market', 'get rich from crypto', 'invest in something strange', 'win a free trip',
  'get a free dessert by talking nicely', 'tip too much', 'forget their wallet at home', 'pay with coins', 'count change at the shop for ten minutes',
  'have the most cards in their wallet', 'keep money in a book and forget it', 'find money in old jeans', 'go shopping for one thing and come back with ten',
  'open their own restaurant', 'run a successful startup', 'become a shark on a business show', 'sell anything to anyone', 'become an influencer',
  // Food
  'eat Maggi for dinner every night', 'put ketchup on everything', 'finish a whole box of mithai', 'eat the most golgappe', 'ask for extra cheese on everything',
  'try every new restaurant in town', 'eat at the same place every day', 'eat dessert before dinner', 'cook a full meal for twenty people',
  'start a food blog', 'eat street food and never fall sick', 'fall sick after eating street food', 'steal food from a friend\'s tiffin',
  'hide snacks in their room', 'eat chocolate at midnight', 'drink ten cups of chai a day', 'forget to drink water all day', 'go on a diet every Monday',
  'order the same dish every time', 'judge every biryani they eat', 'win a pani puri eating contest',
  'add extra chilli to everything', 'cry while cutting onions', 'burn the toast', 'forget the cooker whistle', 'keep leftovers for a week',
  'eat cake straight from the box', 'say "I am not hungry" and then eat everyone\'s fries', 'take home food from a wedding',
  // School, college and work
  'sit on the first bench', 'sleep on the last bench', 'become the class monitor', 'get caught passing notes', 'bunk class to watch a movie',
  'ask the teacher a question just before the bell', 'remind the teacher about homework', 'copy in an exam and get caught', 'top the class in maths',
  'fail in the easiest subject', 'study only the night before', 'make the best notes and lend them to no one', 'lose their ID card',
  'become a professor', 'become the college president', 'win the college fest', 'get a placement on day one', 'switch jobs every year',
  'stay in the same job for 30 years', 'become the CEO', 'fall asleep in a meeting', 'unmute themselves at the wrong moment',
  'forget to turn the camera off', 'join a call from bed', 'send a work email at 2 a.m.', 'take the most leaves', 'never take a leave',
  'reply-all to the whole company', 'become the boss\'s favourite', 'complain about Monday every Monday', 'work from a beach',
  'start their own company and hire their friends', 'make a resume full of lies', 'quit a job on the first day',
  // Travel
  'pack a day before the trip', 'pack a week before the trip', 'overpack for a two-day trip', 'forget their passport', 'get lost in a new country',
  'make friends with the locals', 'try every street food on a trip', 'fall asleep in every car ride', 'get motion sickness', 'insist on driving',
  'sing the whole road trip', 'take the window seat every time', 'carry home food on every trip', 'buy fridge magnets from every city',
  'plan every minute of a trip', 'travel without any plan', 'book the cheapest hotel', 'stay in a five-star hotel', 'go to Goa every year',
  'visit every state in India', 'live in the mountains', 'live on a beach', 'travel the world on a bike', 'go skydiving', 'go bungee jumping',
  'go scuba diving', 'climb a mountain in chappals', 'get stuck at an airport for a day', 'miss a flight', 'reach the station two hours early',
  'talk to the person next to them on a flight', 'bring a pillow on every trip', 'lose their luggage', 'get a sunburn', 'run out of money on a trip',
  // Family, friends and love
  'call their mom every day', 'still ask their parents for pocket money', 'be the favourite child', 'be the family photographer',
  'arrange the family get-together', 'fight with siblings over the TV remote', 'babysit for the whole family', 'remember every relative\'s name',
  'forget a cousin\'s name at a wedding', 'dance with every aunty at a wedding', 'get the most wedding invitations', 'plan a surprise party',
  'ruin a surprise party', 'give the best gifts', 'give gifts that are re-gifted', 'remember everyone\'s birthday', 'make a scrapbook for a friend',
  'fall in love at first sight', 'fall in love on a holiday', 'propose in public', 'say "I love you" first', 'write love letters',
  'marry their school crush', 'have a long-distance relationship', 'go on the worst date', 'set up two friends', 'give the best advice',
  'give the worst advice', 'keep a friend\'s secret for years', 'be the peacemaker in a fight', 'start a group fight by mistake', 'make the group plan and then cancel',
  'always be the one who waits', 'reach exactly on time', 'say "five minutes" and come after an hour', 'call instead of texting', 'remember inside jokes from years ago',
  'cry at a friend\'s wedding', 'give a speech at a wedding', 'dance like nobody is watching', 'be the last to leave a party', 'be the first to leave a party',
  // Everyday habits
  'snooze the alarm ten times', 'wake up without an alarm', 'sleep for 12 hours', 'nap anywhere', 'talk in their sleep', 'walk in their sleep',
  'make their bed every morning', 'never make their bed', 'keep everything very neat', 'lose things in their own room', 'wear the same clothes for days',
  'iron clothes perfectly', 'have the biggest shoe collection', 'spend an hour getting ready', 'get ready in two minutes', 'have the best handwriting',
  'have the worst handwriting', 'clean the house only when guests come', 'water the plants every day', 'kill every plant they get', 'talk to their plants',
  'keep a diary', 'read 50 books a year', 'start a book and never finish it', 'watch the same movie 20 times', 'know every dialogue of a movie',
  'sing every song with the wrong words', 'hum all day', 'whistle all the time', 'talk to themselves', 'laugh at their own jokes', 'make bad puns',
  'tell the same story again and again', 'exaggerate every story', 'remember every small detail', 'forget what they said a minute ago', 'ask "what?" after every sentence',
  'give directions using landmarks', 'get lost even with Google Maps', 'take the longest route', 'walk everywhere', 'never walk anywhere',
  // Silly and dramatic
  'become a superhero', 'play the villain in a movie', 'survive on a desert island', 'befriend a wild animal', 'adopt a stray dog',
  'be scared of a lizard', 'scream at a small spider', 'catch a snake with bare hands', 'lose a dance-off to a kid', 'win at cards every time',
  'lose at Ludo and get angry', 'cheat at Monopoly', 'flip the board when losing', 'take board games too seriously', 'win an argument by shouting',
  'say sorry first', 'never say sorry', 'cry while laughing', 'faint at the sight of blood',
  'volunteer for everything', 'run away from every responsibility', 'appear on a cooking show', 'win a talent show',
  'become a magician', 'learn ten languages', 'speak in an accent after one trip abroad', 'pretend to know a song', 'pretend to have watched a movie',
  'pretend to be busy', 'pretend to be sick to skip something', 'say yes to everything', 'say no to everything', 'change their mind every five minutes',
  'take an hour to order food', 'ask the waiter for suggestions and then order dal', 'call customer care and win', 'argue with an auto driver and win',
  'make friends with the security guard', 'know everyone in the colony', 'be the colony gossip', 'read the newspaper from start to end', 'shout at the TV during the news',
  'predict the cricket score correctly', 'become a cricket umpire', 'play gully cricket at 50', 'break a window playing cricket', 'hit a six on the first ball',
  'be a superfan of a TV show', 'meet a celebrity and freeze', 'get a selfie with a celebrity', 'get into a movie as an extra', 'go to every concert in town',
  'have a secret YouTube channel', 'write poetry', 'write a love song', 'paint a masterpiece', 'build a robot', 'fix the TV by hitting it',
  'believe every horoscope', 'carry a lucky charm', 'touch wood every few minutes', 'have a weird phobia', 'collect something strange',
  'keep every box their gadgets came in', 'save every plastic bag', 'reuse gift wrap', 'hoard ketchup packets',
  'own the most hoodies', 'wear sunglasses indoors', 'dress up for a video call', 'wear pyjamas to the market', 'match their outfit to their phone cover',
  'have a different hairstyle every month', 'cut their own hair', 'grow a long beard', 'shave their head for fun', 'wear a lungi to a party',
  'eat a green chilli in one bite', 'drink a whole bottle of cold drink at once', 'win a burping contest', 'hiccup for an hour',
  'laugh so hard they cry', 'sneeze ten times in a row', 'yawn and make everyone yawn', 'trip on flat ground', 'walk into a glass door',
  'start a fan club', 'start a protest for a small reason', 'write a complaint letter', 'become a lawyer', 'win a debate competition',
  // Seasons, festivals and weather
  'burst the loudest crackers on Diwali', 'hide inside the house on Holi', 'throw colour on everyone on Holi', 'win every kite fight on Sankranti',
  'eat the most sweets during Diwali', 'clean the whole house before Diwali', 'dance all night at garba', 'fast for a festival and cheat by noon',
  'get drenched in the first rain on purpose', 'carry an umbrella and still get wet', 'complain about the heat every summer', 'sit in front of the cooler all day',
  'wear a sweater in May', 'love winter more than anyone', 'make chai for everyone when it rains', 'go out for pakode when it rains',
  'get a cold every time the season changes', 'sleep under three blankets', 'switch on the AC at 16 degrees', 'go to a hill station every summer',
  // Gadgets and home
  'have twenty chargers and none that work', 'keep the TV on while sleeping', 'fight over the AC remote', 'buy every new gadget the day it comes out',
  'use a phone until it falls apart', 'fix the Wi-Fi by switching it off and on', 'set up the new TV for the whole family', 'teach parents how to use a phone',
  'read the whole manual before using anything', 'never read the instructions', 'press every button on the lift', 'take the stairs to avoid people',
  'talk to Alexa like a friend', 'shout at the laptop when it hangs', 'keep 50 tabs open', 'lose their earphones in a week',
  // Out and about
  'start a dance circle at a party', 'request a song from the DJ ten times', 'win a game of antakshari', 'know the words to every old Hindi song',
  'take the front seat in every car', 'fall asleep in the cinema', 'talk loudly during a movie', 'clap when the plane lands',
  'make friends in a queue', 'cut the queue', 'get the best seat everywhere', 'find parking right at the door', 'get a challan for the smallest thing',
  'ask for directions five times', 'walk into the wrong wedding', 'eat at a wedding they were not invited to', 'win the lucky draw',
]
