// Writes src/content/make24.ts: every hand of four numbers from 1 to 13 that can make 24 with + − × ÷, with one
// answer and a difficulty. Run once: node scripts/build-24.mjs
import { writeFileSync } from 'node:fs'

const gcd = (a, b) => (b ? gcd(b, a % b) : Math.abs(a))
const fr = (n, d = 1) => { if (d < 0) { n = -n; d = -d } const g = gcd(n, d) || 1; return [n / g, d / g] }
const OPS = {
  '+': (a, b) => fr(a[0] * b[1] + b[0] * a[1], a[1] * b[1]),
  '-': (a, b) => fr(a[0] * b[1] - b[0] * a[1], a[1] * b[1]),
  '×': (a, b) => fr(a[0] * b[0], a[1] * b[1]),
  '÷': (a, b) => (b[0] === 0 ? null : fr(a[0] * b[1], a[1] * b[0])),
}

/** Every way to reach 24, as expression strings; and whether some way avoids fractions. */
function solve(nums) {
  const found = new Set()
  let clean = false
  const go = (items, frac) => {
    if (items.length === 1) {
      const [v, e] = items[0]
      if (v[0] === 24 && v[1] === 1) { found.add(e); if (!frac) clean = true }
      return
    }
    for (let i = 0; i < items.length; i++) for (let j = 0; j < items.length; j++) {
      if (i === j) continue
      const rest = items.filter((_, k) => k !== i && k !== j)
      for (const [op, f] of Object.entries(OPS)) {
        if ((op === '+' || op === '×') && i > j) continue
        const v = f(items[i][0], items[j][0])
        if (!v) continue
        const wrap = x => (x.includes(' ') ? `(${x})` : x)
        go([...rest, [v, `${wrap(items[i][1])} ${op} ${wrap(items[j][1])}`]], frac || v[1] !== 1)
      }
    }
  }
  go(nums.map(n => [[n, 1], String(n)]), false)
  return { ways: found.size, clean, one: [...found].sort((a, b) => a.length - b.length)[0] }
}

const hands = []
for (let a = 1; a <= 13; a++) for (let b = a; b <= 13; b++) for (let c = b; c <= 13; c++) for (let d = c; d <= 13; d++) {
  const r = solve([a, b, c, d])
  if (r.ways) hands.push({ n: [a, b, c, d], ways: r.ways, clean: r.clean, one: r.one })
}
// Hard: only through a fraction, or very few ways. Easy: many ways.
const sorted = hands.map(h => h.ways).sort((x, y) => x - y)
const lo = sorted[Math.floor(sorted.length / 3)], hi = sorted[Math.floor((sorted.length * 2) / 3)]
const level = h => (!h.clean || h.ways <= Math.min(lo, 4) ? 3 : h.ways >= hi ? 1 : 2)
const rows = hands.map(h => `  [${h.n.join(', ')}, ${level(h)}, ${JSON.stringify(h.one)}],`)
writeFileSync('src/content/make24.ts', `// Generated by scripts/build-24.mjs. Every hand of four numbers from 1 to 13 that makes 24, with its difficulty
// (1 easy, 2 medium, 3 hard: only through a fraction, or very few ways) and one answer.
export type Hand = [number, number, number, number, 1 | 2 | 3, string]
export const HANDS: Hand[] = [
${rows.join('\n')}
]
`)
const by = [1, 2, 3].map(l => hands.filter(h => level(h) === l).length)
console.log(`${hands.length} solvable hands of 1820 · easy ${by[0]} · medium ${by[1]} · hard ${by[2]}`)
