// Writes the files generated from src/catalog.ts:
//   public/catalog.js           the game list for the page
//   public/games/<id>.html      a guide page per game, for search engines and for people deciding what to play
//   public/games.html           the index of every game
//   public/sitemap.xml
//   the top bar, footer and head of the hand-written pages (public/*.html), so every page has the same ones
// Runs before every deploy (npm run deploy).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { CATALOG } from '../src/catalog.ts'
import { iconSvg as icon, KINDS } from '../src/icons.ts'

const SITE = 'https://games.amittal.dev'
const TODAY = new Date().toISOString().slice(0, 10)
const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c])

const iconSvg = id => icon(id, CATALOG.find(m => m.id === id).cat)
const KIND_ORDER = Object.keys(KINDS)
writeFileSync('public/catalog.js', `// Generated by scripts/build-site.mjs from src/catalog.ts. Do not edit.\nexport const KINDS = ${JSON.stringify(Object.fromEntries(KIND_ORDER.map(k => [k, [KINDS[k].bg, KINDS[k].ink]])))}\nexport const CATALOG = ${JSON.stringify(CATALOG.map(m => ({ ...m, icon: iconSvg(m.id) })))}\n`)

const players = m => (m.min === m.max ? `${m.min}` : `${m.min} to ${m.max}`)
const minutes = m => Math.round(m.minutes[0] + m.minutes[1] * Math.max(4, m.min))
const DNA = [['skill', 'Skill'], ['luck', 'Luck'], ['social', 'Social'], ['brain', 'Brain power'], ['chaos', 'Chaos'], ['replay', 'Replay value']]
const MOOD = { think: 'thinking', chaos: 'chaos', competitive: 'competitive', deception: 'deception', creative: 'creative', fast: 'fast', social: 'social', strategic: 'strategy' }

// The light/dark switch shows the mode it switches to: a moon in light mode, a sun in dark mode.
const THEME_BTN = `<button class="theme-btn" type="button" onclick="toggleTheme()" aria-label="Switch between light and dark mode" title="Light or dark"><svg class="moon" viewBox="0 0 24 24" aria-hidden="true"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/></svg><svg class="sun" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M4.93 19.07l1.41-1.41M17.66 6.34l1.41-1.41"/></svg></button>`
const nav = current => `<header class="site-nav"><div class="sn">
  <a class="brand" href="/"><span class="mark" aria-hidden="true"><i></i><i></i></span>Game Night</a>
  <nav aria-label="Main"><a href="/games"${current === 'games' ? ' aria-current="page"' : ''}>All games</a>${THEME_BTN}</nav>
</div></header>`
const foot = `<footer class="foot"><div class="foot-in">
  <nav class="foot-games" aria-label="Games">${CATALOG.map(m => `<a href="/games/${m.id}">${esc(m.name)}</a>`).join('')}</nav>
  <p>Game Night is an independent site by <a href="https://www.amittal.dev/">Armaan Mittal</a>. It is not affiliated with the makers of Wordle, Codenames, Uno, Pictionary, Boggle or any other game named here. Trivia questions from the <a href="https://opentdb.com/">Open Trivia Database</a> (CC BY-SA 4.0).</p>
  <nav class="foot-links" aria-label="Guides"><a href="/how-to-play">Word Race rules</a><a href="/game-modes">Game modes</a><a href="/wordle-tips">Wordle starting words</a><a href="/wordle-unlimited">Wordle practice</a><a href="/privacy">Privacy</a></nav>
</div></footer>`
// Light or dark: the saved choice, else the system setting. Runs before the page draws.
const THEME_SCRIPT = `<script>/* Light or dark: the saved choice, else the system setting. Runs before the page draws. */(function(){var d=document.documentElement;function set(t){d.dataset.theme=t;var m=document.querySelector('meta[name="theme-color"]');if(m)m.content=t==='light'?'#eef0f3':'#121318'}var t;try{t=localStorage.getItem('gn.theme')}catch(e){}set(t||(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'));window.toggleTheme=function(){var n=d.dataset.theme==='light'?'dark':'light';set(n);try{localStorage.setItem('gn.theme',n)}catch(e){}}})()</script>`
const FONTS = `<link rel="preload" href="/fonts/onest-latin.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="/fonts/unbounded-latin.woff2" as="font" type="font/woff2" crossorigin>`
const head = ({ title, description, path, type = 'website', ld }) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${SITE}${path}">
<meta name="theme-color" content="#121318">
${THEME_SCRIPT}
<meta property="og:type" content="${type}">
<meta property="og:site_name" content="Game Night">
<meta property="og:url" content="${SITE}${path}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:image" content="${SITE}/og.png">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/manifest.webmanifest">
${FONTS}
<link rel="stylesheet" href="/style.css">
<script type="application/ld+json">
${JSON.stringify(ld, null, 1)}
</script>
</head>`

/** A game as a card that links to its guide page: its icon, name and line, and with `facts` how many play and for how long. */
const gameLink = (m, facts = false) => `<li><a class="gl" href="/games/${m.id}"><span class="gicon">${iconSvg(m.id)}</span><span class="gl-text"><b>${esc(m.name)}</b><span>${esc(m.blurb)}</span>${facts ? `<span class="gl-facts">${players(m)} players · about ${minutes(m)} min</span>` : ''}</span></a></li>`
/** A setting's values as chips, the default one marked. */
function settingChips(o) {
  const unit = o.unit === 's' ? ' seconds' : o.unit ? ' ' + o.unit : ''
  if (o.kind === 'choice') return o.choices.map(([v, l]) => v === o.def ? `<i class="on">${esc(l)}<span class="vh"> (default)</span></i>` : `<i>${esc(l)}</i>`).join('')
  return `<i>${o.min} to ${o.max}${unit}</i><i class="on">${o.def}${unit}<span class="vh"> (default)</span></i>`
}

mkdirSync('public/games', { recursive: true })
for (const m of CATALOG) {
  const path = `/games/${m.id}`
  const ld = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebApplication', name: `${m.name} (Game Night)`, url: SITE + path, description: m.seo.description,
        applicationCategory: 'EntertainmentApplication', operatingSystem: 'Any',
        isAccessibleForFree: true, offers: { '@type': 'Offer', price: '0', priceCurrency: 'INR' }, image: `${SITE}/og.png`, inLanguage: 'en',
        author: { '@type': 'Person', name: 'Armaan Mittal', url: 'https://www.amittal.dev/' },
      },
      {
        '@type': 'HowTo', name: `How to play ${m.name}`, totalTime: `PT${minutes(m)}M`,
        step: [
          { '@type': 'HowToStep', position: 1, name: 'Make a room', text: 'Open games.amittal.dev, type your name and tap Create a room. Share the code or link with your friends.' },
          ...m.rules.map((r, i) => ({ '@type': 'HowToStep', position: i + 2, name: r.split(/[.:]/)[0].slice(0, 80), text: r })),
        ],
      },
      { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Game Night', item: SITE + '/' }, { '@type': 'ListItem', position: 2, name: 'Games', item: SITE + '/games' }, { '@type': 'ListItem', position: 3, name: m.name, item: SITE + path }] },
    ],
  }
  const others = CATALOG.filter(o => o.id !== m.id && (o.cat === m.cat || o.moods.some(x => m.moods.includes(x)))).slice(0, 4)
  const html = `${head({ title: `${m.seo.title} | Game Night`, description: m.seo.description, path, type: 'article', ld })}
<body>
${nav('game')}
<main class="doc">
  <p class="crumbs"><a href="/">Game Night</a> › <a href="/games">Games</a> › ${esc(m.name)}</p>
  <div class="doc-title"><span class="gicon big">${iconSvg(m.id)}</span><h1>${esc(m.seo.title)}</h1></div>
  <p class="lead">${esc(m.name)} is ${esc(m.seo.about)} you can play free in your browser. ${esc(m.blurb)}</p>
  <p class="cta"><a class="button" href="/?play=${m.id}">Play ${esc(m.name)} now</a> <a class="button alt" href="/">Plan a whole game night</a></p>
  <ul class="facts">
    <li><b>${players(m)}</b><span>players</span></li>
    <li><b>~${minutes(m)} min</b><span>per game</span></li>
    <li><b>${esc(m.cat)}</b><span>kind of game</span></li>
    <li><b>Free</b><span>no sign-up</span></li>
  </ul>

  <section>
    <h2>How to play ${esc(m.name)}</h2>
    <ol class="steps">
      <li><b>Make a room.</b> Type your name, tap Create a room and send the five-character code (or the link) to your friends. Phones and laptops can share a room.</li>
      ${m.rules.map(r => `<li>${esc(r)}</li>`).join('\n      ')}
    </ol>
  </section>

  ${m.options.length ? `<section>
    <h2>Settings</h2>
    <p>The host can change these in the room before starting. The default is marked.</p>
    <div class="settings">${m.options.map(o => `<div><b>${esc(o.label)}</b><span>${settingChips(o)}</span></div>`).join('')}</div>
  </section>` : ''}

  <section>
    <h2>Is it a good fit for your group?</h2>
    <p>Best when you want something ${m.moods.map(x => MOOD[x]).join(', ')}. Every game on the site has a Game DNA score from 1 to 5:</p>
    <div class="dna-doc">${DNA.map(([k, l]) => `<div><span>${l}</span><span class="dots" aria-hidden="true">${[1, 2, 3, 4, 5].map(i => `<i class="${i <= m.dna[k] ? 'on' : ''}"></i>`).join('')}</span><b>${m.dna[k]}/5</b></div>`).join('')}</div>
    <p>Playing with a bigger group or short on time? Start a <b>game night</b> instead: pick Quick, Standard, Chaos, Tournament or Endless and the mood you are in, and the site lines up games that fit your group, with one room table across all of them.</p>
  </section>

  <section>
    <h2>More games like this</h2>
    <ul class="glist">${others.map(o => gameLink(o)).join('')}</ul>
  </section>
  <p class="cta"><a class="button" href="/?play=${m.id}">Play ${esc(m.name)}</a></p>
</main>
${foot}
<script type="module" src="/js/view.js"></script>
</body>
</html>
`
  writeFileSync(`public/games/${m.id}.html`, html)
}

// The index of every game.
{
  const ld = {
    '@context': 'https://schema.org',
    '@graph': [
      { '@type': 'ItemList', name: 'Games on Game Night', itemListElement: CATALOG.map((m, i) => ({ '@type': 'ListItem', position: i + 1, name: m.name, url: `${SITE}/games/${m.id}` })) },
      { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Game Night', item: SITE + '/' }, { '@type': 'ListItem', position: 2, name: 'Games', item: SITE + '/games' }] },
    ],
  }
  const cats = KIND_ORDER.filter(k => CATALOG.some(m => m.cat === k))
  writeFileSync('public/games.html', `${head({ title: `All ${CATALOG.length} Multiplayer Party Games | Game Night`, description: `Every game on Game Night: drawing, word, party, deception, trivia, card and reflex games for 2 to 30 friends. Free in the browser, no sign-up.`, path: '/games', ld })}
<body>
${nav('games')}
<main class="doc wide-doc">
  <p class="crumbs"><a href="/">Game Night</a> › Games</p>
  <h1>All ${CATALOG.length} games</h1>
  <p class="lead">Free multiplayer games for friends, in the browser. Make one room and switch between games all night; the room keeps score across every game.</p>
  ${cats.map(c => `<section><h2 class="kind" style="--k:${KINDS[c].bg}">${esc(c)}</h2><ul class="glist">${CATALOG.filter(m => m.cat === c).map(m => gameLink(m, true)).join('')}</ul></section>`).join('\n  ')}
  <p class="cta"><a class="button" href="/">Make a room</a></p>
</main>
${foot}
<script type="module" src="/js/view.js"></script>
</body>
</html>
`)
}

const urls = [
  ['/', '1.0', 'weekly'], ['/games', '0.9', 'weekly'],
  ...CATALOG.map(m => [`/games/${m.id}`, '0.8', 'monthly']),
  ['/how-to-play', '0.6', 'monthly'], ['/game-modes', '0.6', 'monthly'], ['/wordle-tips', '0.7', 'monthly'], ['/wordle-unlimited', '0.7', 'monthly'],
  ['/privacy', '0.2', 'yearly'],
]
writeFileSync('public/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(([p, pr, f]) => `  <url><loc>${SITE}${p}</loc><lastmod>${TODAY}</lastmod><changefreq>${f}</changefreq><priority>${pr}</priority></url>`).join('\n')}
</urlset>
`)
console.log(`catalog.js, ${CATALOG.length} game pages, games.html, sitemap.xml (${urls.length} URLs)`)

// The home page's welcome, as the page draws it once it has loaded, so nothing jumps when it does.
const kcard = (id, cls) => { const m = CATALOG.find(x => x.id === id), k = KINDS[m.cat]; return `<div class="kcard ${cls}" style="--k:${k.bg};--ink:${k.ink}"><small>${m.cat}</small><span class="gicon">${iconSvg(id)}</span><b>${esc(m.name)}</b></div>` }
const HERO = `<section class="hero"><div class="hero-text"><h1>Play together, each on your own phone</h1>
      <div class="hero-card start"><div class="start-head"><h2>Start playing</h2><p>Type your name and make a room. You get a code to send your friends.</p></div><label class="name-row" for="name"><span>Your name</span><input id="name" maxlength="16" autocomplete="nickname" placeholder="e.g. Armaan"></label><button class="primary big" type="button">Create a room</button><div class="or" role="separator"><span>Got a code from a friend?</span></div><div class="join-row"><input class="code-in" placeholder="Room code or link" aria-label="Room code, or paste the room link" autocomplete="off"><button class="tint" type="button">Join</button></div><ul class="start-facts"><li>Free</li><li>No sign-up</li><li>No app needed</li></ul></div></div>
      <div class="hero-art" aria-hidden="true">${kcard('wordle', 'c1')}${kcard('mindmeld', 'c2')}${kcard('draw', 'c3')}</div></section>`

// The hand-written pages get the same top bar, footer, colours and fonts as the generated ones.
for (const file of ['index', 'how-to-play', 'game-modes', 'wordle-tips', 'wordle-unlimited', 'privacy', '404']) {
  const path = `public/${file}.html`
  let page = readFileSync(path, 'utf8')
  page = page.replace(/<meta name="theme-color" content="[^"]*">/, '<meta name="theme-color" content="#121318">')
  page = page.replace(/<script>\/\* Light or dark:[^\n]*<\/script>/, () => THEME_SCRIPT)
  if (!page.includes('/fonts/onest-latin.woff2')) page = page.replace('<link rel="stylesheet" href="/style.css">', `${FONTS}\n<link rel="stylesheet" href="/style.css">`)
  page = page.replace(/<header class="site-nav">[\s\S]*?<\/header>/, () => nav(file === 'games' ? 'games' : ''))
  page = page.replace(/<footer class="foot">[\s\S]*?<\/footer>/, () => foot)
  if (file === 'index') page = page.replace(/<section class="hero">[\s\S]*?<\/section>/, () => HERO)
  writeFileSync(path, page)
}
