// Builds the GeoGuess map from Natural Earth's 1:10m countries as India sees them (ne_10m_admin_0_countries_ind,
// public domain), so India's borders are drawn as India draws them.
//   node scripts/build-geo.mjs <path to ne_10m_admin_0_countries_ind.geojson>
// Writes public/geo/world.json (every country's outline, for drawing) and src/content/geo-shapes.ts (coarser outlines
// of the countries the game asks about, for scoring). Coordinates are in tenths of a degree: x = (lon + 180) × 10,
// y = (90 − lat) × 10, a plain equirectangular map.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

const src = JSON.parse(readFileSync(process.argv[2], 'utf8'))
const P = ([lon, lat]) => [Math.round((lon + 180) * 10), Math.round((90 - lat) * 10)]

/** Douglas–Peucker on a closed ring: split at the point farthest from the first, simplify each half. */
function simplifyRing(ring, tol) {
  const pts = ring[0][0] === ring[ring.length - 1][0] && ring[0][1] === ring[ring.length - 1][1] ? ring.slice(0, -1) : ring
  if (pts.length < 4) return pts
  let far = 0, at = 0
  pts.forEach((p, i) => { const d = Math.hypot(p[0] - pts[0][0], p[1] - pts[0][1]); if (d > far) { far = d; at = i } })
  return [...simplify(pts.slice(0, at + 1), tol).slice(0, -1), ...simplify([...pts.slice(at), pts[0]], tol).slice(0, -1)]
}

/** Douglas–Peucker on an open line. */
function simplify(pts, tol) {
  if (pts.length < 4) return pts
  const keep = new Uint8Array(pts.length)
  keep[0] = keep[pts.length - 1] = 1
  const stack = [[0, pts.length - 1]]
  while (stack.length) {
    const [a, b] = stack.pop()
    const [ax, ay] = pts[a], [bx, by] = pts[b]
    const dx = bx - ax, dy = by - ay, len = Math.hypot(dx, dy) || 1
    let best = -1, far = 0
    for (let i = a + 1; i < b; i++) {
      const d = Math.abs(dy * pts[i][0] - dx * pts[i][1] + bx * ay - by * ax) / len
      if (d > far) { far = d; best = i }
    }
    if (far > tol) { keep[best] = 1; stack.push([a, best], [best, b]) }
  }
  return pts.filter((_, i) => keep[i])
}
const area = r => Math.abs(r.reduce((a, p, i) => { const q = r[(i + 1) % r.length]; return a + p[0] * q[1] - q[0] * p[1] }, 0) / 2)
const dedupe = r => r.filter((p, i) => i === 0 || p[0] !== r[i - 1][0] || p[1] !== r[i - 1][1])

function rings(f, tol, minArea) {
  const g = f.geometry
  const polys = g.type === 'Polygon' ? [g.coordinates] : g.coordinates
  let out = polys.map(poly => dedupe(simplifyRing(poly[0].map(P), tol))).filter(r => r.length >= 3)
  const biggest = Math.max(...out.map(area))
  // Small islands are dropped, but never a country's largest piece (tiny countries stay on the map).
  out = out.filter(r => area(r) >= minArea || area(r) === biggest)
  return out
}

// The countries the game asks about. Natural Earth files Palestine under Israel; it is asked about on its own.
const ALSO = new Set(['Palestine'])
const SKIP = new Set(['Antarctica', 'Taiwan', 'Bir Tawil', 'Brazilian Island', 'Wake Island', 'Scarborough Shoal'])
const name = f => f.properties.NAME_EN
// A country governs itself: its own sovereign (Natural Earth's ADMIN equals SOVEREIGNT), and not a dependency.
const isCountry = f => !SKIP.has(name(f)) && (ALSO.has(name(f)) || (f.properties.ADMIN === f.properties.SOVEREIGNT && f.properties.TYPE !== 'Dependency'))

const draw = [], shapes = []
for (const f of src.features) {
  if (name(f) === 'Antarctica') continue
  const d = rings(f, 1.2, 8).map(r => 'M' + r.map(p => p.join(' ')).join('L') + 'Z').join('')
  draw.push({ n: name(f), d })
  if (isCountry(f)) {
    // Tiny countries vanish when outlines are simplified: they keep a finer outline instead.
    let r = rings(f, 1.5, 6)
    if (!r.length) r = rings(f, 0.2, 0)
    shapes.push({ n: name(f), lat: +f.properties.LABEL_Y.toFixed(2), lon: +f.properties.LABEL_X.toFixed(2), r: r.map(x => x.flat()) })
  }
}
mkdirSync('public/geo', { recursive: true })
writeFileSync('public/geo/world.json', JSON.stringify(draw))
writeFileSync('src/content/geo-shapes.ts', `// Generated by scripts/build-geo.mjs from Natural Earth (public domain), as India sees borders. Each country's
// outline in tenths of a degree (x = (lon + 180) × 10, y = (90 − lat) × 10), flat [x, y, x, y, …] per ring, and a
// point inside it for the label.
export interface Shape { n: string; lat: number; lon: number; r: number[][] }
export const SHAPES: Shape[] = ${JSON.stringify(shapes)}
`)
const kb = f => Math.round(readFileSync(f).length / 1024)
console.log(`${draw.length} outlines drawn (${kb('public/geo/world.json')} KB), ${shapes.length} countries to ask (${kb('src/content/geo-shapes.ts')} KB)`)
