// Writes the files generated from src/catalog.ts:
//   public/catalog.js           the game list for the page
//   public/games/<id>.html      a guide page per game, for search engines and for people deciding what to play
//   public/games.html           the index of every game
//   public/sitemap.xml
//   the list of games on public/index.html
// Runs before every deploy (npm run deploy).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { CATALOG } from '../src/catalog.ts'
import { iconSvg } from '../src/icons.ts'

const SITE = 'https://games.amittal.dev'
const TODAY = new Date().toISOString().slice(0, 10)
const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c])

writeFileSync('public/catalog.js', `// Generated by scripts/build-site.mjs from src/catalog.ts. Do not edit.\nexport const CATALOG = ${JSON.stringify(CATALOG.map(m => ({ ...m, icon: iconSvg(m.id) })))}\n`)

const players = m => (m.min === m.max ? `${m.min}` : `${m.min} to ${m.max}`)
const minutes = m => Math.round(m.minutes[0] + m.minutes[1] * Math.max(4, m.min))
const DNA = [['skill', 'Skill'], ['luck', 'Luck'], ['social', 'Social'], ['brain', 'Brain power'], ['chaos', 'Chaos'], ['replay', 'Replay value']]
const MOOD = { think: 'thinking', chaos: 'chaos', competitive: 'competitive', deception: 'deception', creative: 'creative', fast: 'fast', social: 'social', strategic: 'strategy' }

const nav = current => `<header class="site-nav">
  <a class="brand" href="/">🎲 Game Night</a>
  <nav aria-label="Main"><a href="/games"${current === 'games' ? ' aria-current="page"' : ''}>All games</a><a href="/how-to-play">Word Race rules</a><a class="play" href="/">Play</a><button class="theme-btn" type="button" onclick="toggleTheme()" aria-label="Switch between light and dark mode" title="Light or dark"></button></nav>
</header>`
const foot = `<footer class="foot">
  <nav aria-label="Games">${CATALOG.map(m => `<a href="/games/${m.id}">${esc(m.name)}</a>`).join('')}</nav>
  <p>Game Night is an independent site by <a href="https://www.amittal.dev/">Armaan Mittal</a>. It is not affiliated with the makers of Wordle, Codenames, Uno, Pictionary, Boggle or any other game named here. Trivia questions from the <a href="https://opentdb.com/">Open Trivia Database</a> (CC BY-SA 4.0).</p>
</footer>`
const head = ({ title, description, path, type = 'website', ld }) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}">
<link rel="canonical" href="${SITE}${path}">
<meta name="theme-color" content="#121213">
<script>/* Light or dark: the saved choice, else the system setting. Runs before the page draws. */(function(){var d=document.documentElement;function set(t){d.dataset.theme=t;var m=document.querySelector('meta[name="theme-color"]');if(m)m.content=t==='light'?'#f6f6f4':'#121213'}var t;try{t=localStorage.getItem('gn.theme')}catch(e){}set(t||(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'));window.toggleTheme=function(){var n=d.dataset.theme==='light'?'dark':'light';set(n);try{localStorage.setItem('gn.theme',n)}catch(e){}}})()</script>
<meta property="og:type" content="${type}">
<meta property="og:site_name" content="Game Night">
<meta property="og:url" content="${SITE}${path}">
<meta property="og:title" content="${esc(title)}">
<meta property="og:description" content="${esc(description)}">
<meta property="og:image" content="${SITE}/og.png">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<link rel="manifest" href="/manifest.webmanifest">
<link rel="stylesheet" href="/style.css">
<script type="application/ld+json">
${JSON.stringify(ld, null, 1)}
</script>
</head>`

mkdirSync('public/games', { recursive: true })
for (const m of CATALOG) {
  const path = `/games/${m.id}`
  const ld = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': ['VideoGame', 'WebApplication'], name: `${m.name} (Game Night)`, url: SITE + path, description: m.seo.description,
        genre: [m.cat, 'Party game'], gamePlatform: ['Web browser', 'Android', 'iOS', 'Desktop'], playMode: m.min === 1 ? ['MultiPlayer', 'SinglePlayer'] : ['MultiPlayer'],
        numberOfPlayers: { '@type': 'QuantitativeValue', minValue: m.min, maxValue: m.max }, applicationCategory: 'GameApplication', operatingSystem: 'Any',
        isAccessibleForFree: true, offers: { '@type': 'Offer', price: '0', priceCurrency: 'INR' }, image: `${SITE}/og.png`, inLanguage: 'en',
        author: { '@type': 'Person', name: 'Armaan Mittal', url: 'https://www.amittal.dev/' },
      },
      {
        '@type': 'HowTo', name: `How to play ${m.name}`, totalTime: `PT${minutes(m)}M`,
        step: [
          { '@type': 'HowToStep', position: 1, name: 'Make a room', text: 'Open games.amittal.dev, type your name and tap Create a room. Share the code or link with your friends.' },
          ...m.rules.map((r, i) => ({ '@type': 'HowToStep', position: i + 2, name: r.split(/[.:]/)[0].slice(0, 80), text: r })),
        ],
      },
      { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Game Night', item: SITE + '/' }, { '@type': 'ListItem', position: 2, name: 'Games', item: SITE + '/games' }, { '@type': 'ListItem', position: 3, name: m.name, item: SITE + path }] },
    ],
  }
  const others = CATALOG.filter(o => o.id !== m.id && (o.cat === m.cat || o.moods.some(x => m.moods.includes(x)))).slice(0, 4)
  const html = `${head({ title: `${m.seo.title} | Game Night`, description: m.seo.description, path, type: 'article', ld })}
<body>
${nav('game')}
<main class="doc">
  <p class="crumbs"><a href="/">Game Night</a> › <a href="/games">Games</a> › ${esc(m.name)}</p>
  <h1 class="with-icon"><span class="gicon big">${iconSvg(m.id)}</span>${esc(m.seo.title)}</h1>
  <p class="lead">${esc(m.name)} is ${esc(m.seo.about)} you can play free in your browser. ${esc(m.blurb)}</p>
  <p class="cta"><a class="button" href="/?play=${m.id}">Play ${esc(m.name)} now</a> <a class="button alt" href="/">Plan a whole game night</a></p>
  <div class="facts">
    <div><b>${players(m)}</b><span>players</span></div>
    <div><b>~${minutes(m)} min</b><span>per game</span></div>
    <div><b>${esc(m.cat)}</b><span>category</span></div>
    <div><b>Free</b><span>no sign-up</span></div>
  </div>

  <section>
    <h2>How to play ${esc(m.name)}</h2>
    <ol class="steps">
      <li><b>Make a room.</b> Type your name, tap Create a room and send the five-character code (or the link) to your friends. Phones and laptops can share a room.</li>
      ${m.rules.map(r => `<li>${esc(r)}</li>`).join('\n      ')}
    </ol>
  </section>

  ${m.options.length ? `<section>
    <h2>Settings</h2>
    <p>The host can change these in the room before starting:</p>
    <ul>${m.options.map(o => `<li><b>${esc(o.label)}:</b> ${o.kind === 'choice' ? o.choices.map(c => esc(c[1])).join(', ') : `${o.min} to ${o.max}${o.unit === 's' ? ' seconds' : o.unit ? ' ' + o.unit : ''}`} (default ${esc(o.kind === 'choice' ? o.choices.find(c => c[0] === o.def)?.[1] : o.def)}${o.kind === 'num' && o.unit === 's' ? ' seconds' : ''}).</li>`).join('')}</ul>
  </section>` : ''}

  <section>
    <h2>Is it a good fit for your group?</h2>
    <p>Best when you want something ${m.moods.map(x => MOOD[x]).join(', ')}. Every game on the site has a "Game DNA" score from 1 to 5:</p>
    <div class="dna-doc">${DNA.map(([k, l]) => `<div><span>${l}</span><span class="dots">${[1, 2, 3, 4, 5].map(i => `<i class="${i <= m.dna[k] ? 'on' : ''}"></i>`).join('')}</span><b>${m.dna[k]}/5</b></div>`).join('')}</div>
    <p>Playing with a bigger group or short on time? Start a <b>game night</b> instead: pick Quick, Standard, Chaos, Tournament or Endless and the mood you are in, and the site lines up games that fit your group, with one leaderboard across all of them.</p>
  </section>

  <section>
    <h2>More games like this</h2>
    <div class="cards">${others.map(o => `<a class="card gl" href="/games/${o.id}"><h3 class="with-icon"><span class="gicon">${iconSvg(o.id)}</span>${esc(o.name)}</h3><p>${esc(o.blurb)}</p></a>`).join('')}</div>
  </section>
  <p class="cta"><a class="button" href="/?play=${m.id}">Play ${esc(m.name)}</a></p>
</main>
${foot}
<script type="module" src="/js/view.js"></script>
</body>
</html>
`
  writeFileSync(`public/games/${m.id}.html`, html)
}

// The index of every game.
{
  const ld = {
    '@context': 'https://schema.org',
    '@graph': [
      { '@type': 'ItemList', name: 'Games on Game Night', itemListElement: CATALOG.map((m, i) => ({ '@type': 'ListItem', position: i + 1, name: m.name, url: `${SITE}/games/${m.id}` })) },
      { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Game Night', item: SITE + '/' }, { '@type': 'ListItem', position: 2, name: 'Games', item: SITE + '/games' }] },
    ],
  }
  const cats = [...new Set(CATALOG.map(m => m.cat))]
  writeFileSync('public/games.html', `${head({ title: `All ${CATALOG.length} Multiplayer Party Games | Game Night`, description: `Every game on Game Night: drawing, word, party, deception, trivia, card and reflex games for 2 to 30 friends. Free in the browser, no sign-up.`, path: '/games', ld })}
<body>
${nav('games')}
<main class="doc">
  <p class="crumbs"><a href="/">Game Night</a> › Games</p>
  <h1>All ${CATALOG.length} games</h1>
  <p class="lead">Free multiplayer games for friends, in the browser. Make one room and switch between games all night; the room keeps score across every game.</p>
  ${cats.map(c => `<section><h2>${esc(c)}</h2><div class="cards">${CATALOG.filter(m => m.cat === c).map(m => `<a class="card gl" href="/games/${m.id}"><h3 class="with-icon"><span class="gicon">${iconSvg(m.id)}</span>${esc(m.name)}</h3><p>${esc(m.blurb)}</p><p class="dim small">${players(m)} players · about ${minutes(m)} min</p></a>`).join('')}</div></section>`).join('\n  ')}
  <p class="cta"><a class="button" href="/">Make a room</a></p>
</main>
${foot}
<script type="module" src="/js/view.js"></script>
</body>
</html>
`)
}

const urls = [
  ['/', '1.0', 'weekly'], ['/games', '0.9', 'weekly'],
  ...CATALOG.map(m => [`/games/${m.id}`, '0.8', 'monthly']),
  ['/how-to-play', '0.6', 'monthly'], ['/game-modes', '0.6', 'monthly'], ['/wordle-tips', '0.7', 'monthly'], ['/wordle-unlimited', '0.7', 'monthly'],
]
writeFileSync('public/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(([p, pr, f]) => `  <url><loc>${SITE}${p}</loc><lastmod>${TODAY}</lastmod><changefreq>${f}</changefreq><priority>${pr}</priority></url>`).join('\n')}
</urlset>
`)
console.log(`catalog.js, ${CATALOG.length} game pages, games.html, sitemap.xml (${urls.length} URLs)`)

// The home page's list of games (what search engines and visitors without JavaScript see), from the catalog.
{
  const home = readFileSync('public/index.html', 'utf8')
  const open = '<!-- games: written by scripts/build-site.mjs from src/catalog.ts -->'
  const i = home.indexOf(open) + open.length, j = home.indexOf('</div>', i)
  const nl = home.includes('\r\n') ? '\r\n' : '\n'
  const cards = CATALOG.map(m => `      <a class="card gl" href="/games/${m.id}"><h3 class="with-icon"><span class="gicon">${iconSvg(m.id)}</span>${esc(m.name)}</h3><p>${esc(m.blurb)}</p></a>`).join(nl)
  writeFileSync('public/index.html', home.slice(0, i) + nl + cards + nl + '    ' + home.slice(j))
}
