// Removes Most Likely To prompts that appear twice (in the original list in src/content/party.ts or in another file
// under src/content/likely), keeping the first. Run after adding prompts: node scripts/dedupe-likely.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'

const norm = s => s.toLowerCase().replace(/[^a-z0-9 ]+/g, ' ').replace(/\s+/g, ' ').trim()
const party = readFileSync('src/content/party.ts', 'utf8')
const old = party.slice(party.indexOf('export const MOST_LIKELY'))
const seen = new Set([...old.slice(0, old.indexOf('\n]')).matchAll(/'((?:[^'\\]|\\.)*)'/g)].map(m => norm(m[1].replace(/\\'/g, "'"))))
let removed = 0
// Clean files first, so a prompt in both packs stays in the clean one (where everyone can get it).
const files = readdirSync('src/content/likely').filter(f => f !== 'index.ts').sort((a, b) => (a.startsWith('clean') ? 0 : 1) - (b.startsWith('clean') ? 0 : 1) || a.localeCompare(b))
for (const f of files) {
  const path = `src/content/likely/${f}`
  const text = readFileSync(path, 'utf8')
  const head = text.slice(0, text.indexOf('export default ['))
  const items = [...text.slice(text.indexOf('export default [')).matchAll(/"([^"]+)"/g)].map(m => m[1])
  const keep = items.filter(t => { const k = norm(t); if (seen.has(k)) { removed++; console.log(`removed from ${f}: ${t}`); return false } seen.add(k); return true })
  if (keep.length === items.length) continue
  const lines = []
  for (let i = 0; i < keep.length; i += 5) lines.push('  ' + keep.slice(i, i + 5).map(t => JSON.stringify(t)).join(', ') + ',')
  writeFileSync(path, `${head}export default [\n${lines.join('\n')}\n]\n`)
}
console.log(`${removed} removed, ${seen.size} prompts in all`)

// The index that puts the files together into the two packs.
const id = f => f.replace('.ts', '').replace(/-(\w)/g, (_, c) => c.toUpperCase())
const all = readdirSync('src/content/likely').filter(f => f.endsWith('.ts') && f !== 'index.ts').sort()
const pack = p => all.filter(f => f.startsWith(p)).map(f => '...' + id(f)).join(', ')
writeFileSync('src/content/likely/index.ts', `// Generated by scripts/dedupe-likely.mjs. Most Likely To packs: Clean is fine for any group (it includes the original
// prompts in ../party.ts); Spicy is dating, exes, parties and roasts. Add prompts to the files here, then run the script.
import { MOST_LIKELY } from '../party'
${all.map(f => `import ${id(f)} from './${f.replace('.ts', '')}'`).join('\n')}

export const CLEAN: string[] = [...MOST_LIKELY, ${pack('clean')}]
export const SPICY: string[] = [${pack('spicy')}]
`)
